Repository redhat-appstudio/infra-deployments, pull requests merged in 2021-11, with the labels that each got.

#3 rename to redhat-appstudio
  argo-cd-apps/base/gitops.yaml
Labels: lgtm

#6 fix: add OperatorGroup & CatalogSource to README
  README.md
Labels: needs-ok-to-test

#8 syntax fix in yaml for ClusterRoleBinding
  components/build/build-templates/2-read-pipelines-binding.yaml
Labels: lgtm

#9 Add "view" in relevant namespaces to build and gitops members
  argo-cd-apps/base/authentication.yaml
  argo-cd-apps/base/kustomization.yaml
  components/authentication/kustomization.yaml
  components/authentication/view-build-service.yaml
  components/authentication/view-gitops-service.yaml
Labels: lgtm

#13 Add Hybrid Application Service component
  argo-cd-apps/base/has.yaml
  argo-cd-apps/base/kustomization.yaml
  components/has/catalogsource.yaml
  components/has/kustomization.yaml
  components/has/operatorgroup.yaml
  components/has/subscription.yaml
Labels: lgtm

#15 Add role for viewing application-service namespace
  components/authentication/kustomization.yaml
  components/authentication/view-has.yaml
Labels: lgtm

#16 development mode scripts
  README.md
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  hack/development-mode.sh
  hack/upstream-mode.sh
  hack/util-set-development-repos.sh
  hack/util-update-app-of-apps.sh
Labels: documentation, enhancement, lgtm

#17 added CRC tips
  README.md
Labels: lgtm, needs-ok-to-test

#19 Pipelines scripts
  components/build/README.md
  components/build/build-templates/nodejs-builder.yaml
  components/build/experimental-pipelines/app-studio-build-pipeline.yaml
  components/build/experimental-pipelines/kustomization.yaml
  components/build/experimental-pipelines/pvc.yaml
  components/build/hack/build.sh
  components/build/hack/default-build.yaml
  components/build/hack/install-pipelines.sh
  components/build/hack/test-known-build.sh
  components/build/kustomization.yaml
Labels: documentation, enhancement, lgtm

#25 Restructure staging builds installation directory
  components/build/README.md
  components/build/build-templates/docker-build.yaml
  components/build/build-templates/kustomization.yaml
  components/build/build-templates/pvc.yaml
  components/build/experimental-pipelines/kustomization.yaml
  components/build/hack/build.sh
  components/build/kustomization.yaml
  hack/build/build.sh
  hack/build/default-build.yaml
  hack/build/install-pipelines.sh
  hack/build/test-known-build.sh
Labels: documentation, enhancement, lgtm

#26 CRC step by step
  README.md
  documentation/images/argo-cd-login.png
Labels: lgtm

#30 Fixed variable exposure
  hack/util-update-app-of-apps.sh
Labels: lgtm

#31 Build updates
  README.md
  components/build/build-templates/docker-build.yaml
  components/build/build-templates/java-builder.yaml
  components/build/build-templates/kustomization.yaml
  components/build/build-templates/nodejs-builder.yaml
  components/build/build-templates/noop.yaml
  hack/build/build.sh
  hack/build/check-repo.sh
  hack/build/cleanup-pvc.sh
  hack/build/default-build.yaml
  hack/build/install-pipelines.sh
  hack/build/install-secrets.sh
  hack/build/install-single-pipeline.sh
  hack/build/ls-all-my-repos.sh
  hack/build/prune-pipelines
  hack/build/quick-noop-build.sh
  hack/build/repo-to-pipeline.sh
  hack/build/test-known-build.sh
Labels: documentation, enhancement, lgtm
