Repository redhat-appstudio/infra-deployments, pull requests merged in 2021-12, with the labels that each got.

#34 Add johnmcollier to has-ci role
  components/authentication/has-ci.yaml
Labels: lgtm

#33 Update version pinning of tasks and new scripts
  components/build/build-templates/docker-build.yaml
  components/build/build-templates/java-builder.yaml
  components/build/build-templates/nodejs-builder.yaml
  components/build/build-templates/noop.yaml
  hack/build/build.sh
  hack/build/cleanup-pvc.sh
  hack/build/deploy.sh
  hack/build/maintainance-loop.sh
  hack/build/package-bundle.sh
  hack/build/poll-build.sh
  hack/build/test-known-build.sh
Labels: bug, enhancement, lgtm

#35 Update sha for app service catalog
  components/has/catalogsource.yaml
Labels: lgtm

#37 Add verb for deleting secrets to user-ci-maintainer role
  components/authentication/user-ci-maintainer.yaml
Labels: lgtm

#39 Consistently uses ./hack
  README.md
Labels: lgtm

#43 Add e2e binary to Openshift CI test container
  .ci/openshift-ci/Dockerfile
Labels: lgtm

#40 Use new pipeline definitions
  components/build/build-templates/bundle-config.yaml
Labels: enhancement, lgtm

#41 cleanup moved to be an AppStudioutils cluster task
  components/build/clustertasks/analyze-devfile.yaml
  components/build/clustertasks/appstudio-utils.yaml
  components/build/clustertasks/cleanup-build-directories.yaml
  components/build/clustertasks/image-exists.yaml
  components/build/clustertasks/kustomization.yaml
  hack/build/utils/cleanup-pvc.sh
Labels: enhancement, lgtm

#32 HAS: Manage image refs in this repo & controller manifests from source repo
  components/authentication/argocd-permissions.yaml
  components/authentication/kustomization.yaml
  components/has/catalogsource.yaml
  components/has/kustomization.yaml
  components/has/operatorgroup.yaml
  components/has/subscription.yaml
Labels: lgtm
