Repository redhat-appstudio/infra-deployments, pull requests merged in 2022-07, with the labels that each got.

#470 Update integration service
  components/integration/kustomization.yaml
Labels: lgtm, approved

#471 fix: Remove old task param from ec demo
  hack/chains/release-pipeline-with-ec-demo.sh
Labels: lgtm, approved

#481 PLNSRVCE-452: allow for override of cache,sidecar,reqprocessor images of jvm-build-service
  components/build/jvm-build-service/kustomization.yaml
  hack/preview.sh
Labels: lgtm, approved

#488 Give my github identity rights to my SSO-named user namespace
  components/authentication/tenants/rbean.yaml
Labels: lgtm, approved

#490 Spi update 0.6.8
  components/spi/kustomization.yaml
Labels: lgtm, approved

#494 Add admin role for shebert namespace
  components/authentication/tenants/shebert.yaml
Labels: lgtm, approved

#496 Adding shebert as an owner
  OWNERS
Labels: lgtm, approved

#495 Adding Integration and Release teams for view of integration
  components/authentication/view-integration.yaml
Labels: lgtm, approved

#497 setting up managed workspace for shebert for demo
  components/authentication/tenants/managed-shebert-namespace.yaml
  components/authentication/tenants/shebert.yaml
Labels: lgtm, approved

#498 Add managed-shebert-namespace to kustomization
  components/authentication/tenants/kustomization.yaml
Labels: lgtm, approved

#499 add release team to be able to get cosign pub key
  components/authentication/view-build-service.yaml
Labels: lgtm, approved

#500 Add roleBindings for ReleaseLinks in shebert
  components/authentication/tenants/shebert.yaml
Labels: lgtm, approved

#501 add applicationsnapshots to ClusterRole
  components/authentication/tenants/shbose.yaml
Labels: lgtm, approved

#425 Allow to override Integration operator references
  hack/preview-template.env
  hack/preview.sh
Labels: approved

#505 add sabhardw.yaml to kustomization
  components/authentication/tenants/kustomization.yaml
Labels: needs-ok-to-test

#509 fix: ci: create shared secret
  .ci/oci-e2e-deployment.sh
  components/build/kustomization.yaml
  hack/build/templates/default-build-bundle.yaml
Labels: lgtm, approved

#506 PLNSRVCE-455: Add image as env var on operator
  components/build/jvm-build-service/kustomization.yaml
  components/build/jvm-build-service/operator-images.yaml
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm, approved

#516 PLNSRVCE-452: fix jvm side car image override in preview.sh
  hack/preview.sh
Labels: approved

#519 PipelinesAsCode update to v0.11.0
  components/build/pipelines-as-code/kustomization.yaml
Labels: approved

#526 Allow the override of the default build bundle when running preview
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm, approved

#525 Remove uneeded ClusterTasks
  components/build/jvm-build-service/kustomization.yaml
Labels: approved

#479 RHDP-442 Update script to also send PR number for webhook
  .ci/oci-e2e-deployment.sh
Labels: lgtm

#533 Allow John to prune old HAS OLM resources
  components/authentication/kustomization.yaml
  components/authentication/prune-olm-has.yaml
Labels: lgtm, approved

#535 Fix typo in APIGroup for has-olm-pruner role
  components/authentication/prune-olm-has.yaml
Labels: lgtm, approved

#534 Allow Chains to use the SharedSecret resource
  README.md
  components/build/tekton-chains/kustomization.yaml
  components/build/tekton-chains/tekton-chains-controller-shared-secret.yaml
  components/build/tekton-chains/tekton-chains-controller-shared-secrets-rolebinding.yaml
Labels: lgtm, approved

#542 Fix crc bootstrap guide for chains/ec development
  hack/chains/README.md
Labels: approved

#543 Updating chains deployment with rebased fork
  components/build/tekton-chains/chains-controller-deployment.yaml
Labels: lgtm

#518 Preview optimalization - sync all applications and wait for them
  .ci/oci-e2e-deployment.sh
  argo-cd-apps/overlays/development/delete-applications.yaml
  components/build/tekton-chains/chains-secrets-config.yaml
  hack/bootstrap-cluster.sh
  hack/preview-template.env
  hack/preview.sh
  hack/util-set-spi-api-server.sh
Labels: approved

#539 Fix destruction of cluster
  hack/destroy-cluster.sh
Labels: approved

#545 Add defaults values for REPO_OWNER/REPO_NAME/PULL_NUMBER envs to fix periodic jobs
  .ci/oci-e2e-deployment.sh
Labels: approved

#547 fix: ignore 'context deadline exceeded' issue
  hack/preview.sh
Labels: approved

#524 Update gitops component
  components/gitops/staging/kustomization.yaml
Labels: approved

#551 GitOpsService update to 1b42854146c71359724dd402f72f0172f56c5443
  components/gitops/staging/kustomization.yaml
Labels: approved
