Repository redhat-appstudio/infra-deployments, pull requests merged in 2022-12, with the labels that each got.

#979 Extend view to jvmbuildservice and managed-gitops groups
  components/authentication/everyone-can-view.yaml
Labels: approved

#964 Move monitoring setup in its own README
  README.md
  components/monitoring/README.md
Labels: approved

#991 Return shared secret which is used by hacbs-service-core bundle
  components/shared-resources/kustomization.yaml
  components/shared-resources/redhat-appstudio-staginguser-secret.yaml
  components/shared-resources/shared-resources-components.yaml
Labels: approved

#988 fix: deploy jvm-build-service custom images
  components/jvm-build-service/kustomization.yaml
  components/jvm-build-service/operator_env_patch.yaml
  hack/preview-template.env
  hack/preview.sh
Labels: approved

#995 chore: Add quality dashboard PaC Repository
  components/tekton-ci/repository.yaml
Labels: approved

#999 Fix monitoring deployment with ArgoCD
  components/monitoring/base/configure-prometheus.yaml
  components/monitoring/base/grafana-app.yaml
Labels: lgtm, approved

#1005 Remove monitoring from hack in favour of setup through ArgoCD
  hack/monitoring-template.env
  hack/monitoring/configure_grafana.yaml
  hack/monitoring/configure_prometheus.yaml
  hack/monitoring/grafanadashboard_sandbox_usage.yaml
  hack/monitoring/grafanadatasource_prometheus.yaml
  hack/monitoring/install_grafana.yaml
  hack/monitoring/install_prometheus.yaml
  hack/monitoring/prometheus_servicemonitors.yaml
  hack/setup_observability.sh
Labels: lgtm, approved

#1002 Correct versions of these tools
  README.md
  hack/setup/macos-based.sh
Labels: approved

#1006 preview: Do not allow empty MY_GITHUB_ORG
  hack/preview.sh
Labels: lgtm, approved

#1018 Auth-view: add PaC repositories, update jvm-build-service
  components/authentication/everyone-can-view.yaml
Labels: lgtm, approved

#1016 Add SA, Role and RoleBindings for Internal Services Controller
  argo-cd-apps/base/internal-services.yaml
  argo-cd-apps/base/kustomization.yaml
  components/authentication/internal-services.yaml
  components/authentication/kustomization.yaml
  components/internal-services/OWNERS
  components/internal-services/README.md
  components/internal-services/internal_service_request_role.yaml
  components/internal-services/internal_service_request_role_binding.yaml
  components/internal-services/internal_service_request_service_account.yaml
  components/internal-services/internal_service_service_account_token.yaml
  components/internal-services/kustomization.yaml
Labels: lgtm, approved

#1033 chore: delete unused jvm-build-service env vars
  hack/preview.sh
Labels: lgtm, approved

#996 Remove pvc-cleaner
  components/authentication/build.yaml
  components/pipeline-service/kustomization.yaml
  components/pipeline-service/pvc-cleaner/kustomization.yaml
  components/pipeline-service/pvc-cleaner/namespace.yaml
  components/tekton-ci/repository.yaml
Labels: ok-to-test, approved

#1035 Add ConfigMap for latest EC task
  components/enterprise-contract/kustomization.yaml
Labels: lgtm, approved

#1038 Allow Pipeline Service members to manage tekton resources
  components/authentication/kustomization.yaml
  components/authentication/pipeline-service-sre.yaml
Labels: lgtm, approved

#1008 RHDP-420 install keycloak&toolchain in dev env
  README.md
  argo-cd-apps/overlays/development/dev-sso.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  components/dev-sso/keycloak-realm.yaml
  components/dev-sso/keycloak.yaml
  components/dev-sso/kustomization.yaml
  components/dev-sso/operatorgroup.yaml
  components/dev-sso/subscription.yaml
  hack/bootstrap-cluster.sh
  hack/preview.sh
Labels: lgtm, approved

#1041 Add InternalRequest CRD
  components/internal-services/kustomization.yaml
Labels: lgtm, approved

#1046 Allow Release team to create InternalRequest CRs
  components/authentication/internal-services.yaml
Labels: lgtm, approved

#1047 Add the internal-services repo to tekton-ci
  components/tekton-ci/repository.yaml
Labels: approved

#1030 Added fluent bit logging setup for appstudio-stage
  components/monitoring/logging/base/fluent-bit-cluster-info-cm.yaml
  components/monitoring/logging/base/fluent-bit-sa-config.yaml
  components/monitoring/logging/base/fluent-bit-setup.yaml
  components/monitoring/logging/base/fluent-bit-state-pvc.yaml
  components/monitoring/logging/base/kustomization.yaml
Labels: lgtm, approved

#1054 Update release team access
  components/authentication/kustomization.yaml
  components/authentication/release-team.yaml
Labels: lgtm, approved

#1053 PLNSRVCE-939: skip tekton-pruning on tekton-ci namespace
  components/tekton-ci/kustomization.yaml
  components/tekton-ci/namespace.yaml
Labels: approved

#1051 Update instruction to set PaC for appstudio components
  README.md
Labels: approved

#1057 fix wait for reg. service in preview.sh
  hack/preview.sh
Labels: approved

#1060 Updated GitOps deployments for monitoring with new file structure
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/base/monitoring-workload-grafana.yaml
  argo-cd-apps/base/monitoring-workload-logging.yaml
  argo-cd-apps/base/monitoring-workload-prometheus.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
Labels: lgtm, approved

#1066 Allow multiple Repository CRs to reference the same repository
  components/pipeline-service/pipelines-as-code/disable-pipelines-as-code-webhook.yaml
  components/pipeline-service/pipelines-as-code/kustomization.yaml
Labels: approved

#1069 Revert "Allow multiple Repository CRs to reference the same repository"
  components/pipeline-service/pipelines-as-code/disable-pipelines-as-code-webhook.yaml
  components/pipeline-service/pipelines-as-code/kustomization.yaml
Labels: approved

#1070 STONE-249 Enable direct access grants in dev keycloak realm
  components/dev-sso/keycloak-realm.yaml
Labels: lgtm, approved

#1071 Allow multiple Repository CRs to reference the same repository (PLNSRVCE-946) (#1066)
  components/pipeline-service/pipelines-as-code/disable-pipelines-as-code-webhook.yaml
  components/pipeline-service/pipelines-as-code/kustomization.yaml
Labels: approved

#1077 Updated authentication org and team for grafana
  components/monitoring/grafana/base/grafana-app.yaml
Labels: lgtm, approved

#1076 Update verify ec-task reference
  components/enterprise-contract/kustomization.yaml
Labels: lgtm, approved

#1078 application-service update - with e2e-tests pairing
  components/has/kustomization.yaml
Labels: approved

#1039 build-service: Pipeline selection
  components/build-service/build-pipeline-selector.yaml
  components/build-service/kustomization.yaml
  components/jvm-build-service/kustomization.yaml
Labels: approved

#1075 Create entry for the ec-policy source in the ec-defaults configmap
  components/enterprise-contract/kustomization.yaml
Labels: approved
