Repository redhat-appstudio/infra-deployments, pull requests merged in 2022-11, with the labels that each got.

#884 fix: SPI init script default URL
  .ci/oci-e2e-deployment.sh
  hack/preview.sh
Labels: lgtm

#849 Add prometheus CR to deploy prometheus pod and rules
  README.md
  components/monitoring/base/configure-prometheus.yaml
  components/monitoring/base/install-prometheus.yaml
  components/monitoring/base/kustomization.yaml
Labels: lgtm, approved

#889 create a user workspace of the given type
  hack/create-user-workspace.sh
Labels: lgtm, approved

#895 Update application-api component to c9e003808d1fcc557a0a93ab96ace6caa…
  components/application-api/base/kustomization.yaml
Labels: lgtm, approved

#896 Use upstream version of Tekton Chains - 0.13.0
  components/build/tekton-chains/chains-controller-deployment.yaml
  components/build/tekton-chains/kustomization.yaml
Labels: lgtm, approved

#897 Enable PaC for application-api
  components/has/.tekton/kustomization.yaml
  components/has/.tekton/pipelines-as-code-application-api.yaml
Labels: approved

#899 Update the integration image with some rbac issues fixed
  components/integration/kustomization.yaml
  components/integration/manager_resources_patch.yaml
Labels: lgtm, approved

#907 Build-service secrets creation roles
  components/authorization/kcp/appstudio/build-service-secrets.yaml
  components/authorization/kcp/appstudio/kustomization.yaml
Labels: lgtm, approved

#904 preview: generate missing APIExports
  components/application-api/overlays/dev/apiexport.yaml
  components/spi/overlays/dev/apiexport.yaml
  hack/preview.sh
Labels: approved

#910 Removed interval from snitchHeartBeat
  components/monitoring/base/configure-prometheus.yaml
Labels: lgtm, approved

#912 increase the memory limit of the operator to overcome the operational problems on the staging cluster.
  components/spi/kustomization.yaml
  components/spi/operator-limits-patch.json
Labels: lgtm, approved

#911 add owners file for SPI
  components/spi/OWNERS
Labels: approved

#928 main -> kcp
  .ci/Readme.md
  .github/workflows/auto-update.yml
  README.md
  argo-cd-apps/app-of-apps/all-applications.yaml
  argo-cd-apps/base/application-api.yaml
  argo-cd-apps/base/application-service.yaml
  argo-cd-apps/base/authorization-in-cluster.yaml
  argo-cd-apps/base/authorization-in-kcp.yaml
  argo-cd-apps/base/build-service.yaml
  argo-cd-apps/base/build-templates.yaml
  argo-cd-apps/base/clusterworkspacetypes.yaml
  argo-cd-apps/base/enterprise-contract.yaml
  argo-cd-apps/base/gitops-appstudio-service.yaml
  argo-cd-apps/base/gitops-core-service.yaml
  argo-cd-apps/base/integration-service.yaml
  argo-cd-apps/base/jvm-build-service.yaml
  argo-cd-apps/base/kcp-syncer.yaml
  argo-cd-apps/base/monitoring-workload-in-cluster.yaml
  argo-cd-apps/base/release-service.yaml
  argo-cd-apps/base/spi.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  hack/preview.sh
  hack/util-set-development-repos.sh
  hack/util-update-app-of-apps.sh
Labels: approved

#932 Disable pack-broker on development environments
  argo-cd-apps/overlays/development/delete-applications.yaml
Labels: approved

#935 Add application-api component
  argo-cd-apps/base/application-api.yaml
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/application-api/OWNERS
  components/application-api/kustomization.yaml
Labels: approved

#940 fix: add missing files in application-api application
  components/application-api/allow-argocd-to-manage.yaml
  components/application-api/argocd-permissions.yaml
Labels: approved

#944 fix: preview.sh is pointing to spi-e2e-setup.sh from main branch by default
  hack/preview.sh
Labels: approved

#939 Added prometheus configs to ArgoCD
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/base/monitoring-workload-in-cluster.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  components/monitoring/base/configure-prometheus.yaml
  components/monitoring/base/install-prometheus.yaml
  components/monitoring/base/kustomization.yaml
  components/monitoring/base/prometheus-view.yaml
Labels: lgtm, approved

#946 fix: use correct URL in SPI configmap when deployed on CRC.
  hack/util-patch-spi-config.sh
Labels: lgtm, approved

#949 Update HAS Pruner role to include listing of Snapshots/Bindings
  components/authentication/prune-has.yaml
Labels: approved

#925 Disable rekor integration
  components/build/tekton-chains/chains-config.yaml
Labels: lgtm, approved

#950 Allow listing of environments in HAS pruner role
  components/authentication/prune-has.yaml
Labels: approved

#951 Bump HAS to a852feca3998db496d08ba012ba0cc588af5a6a3
  components/has/kustomization.yaml
Labels: approved

#883 add script to create secrets for Prometheus and Grafana
  README.md
  components/monitoring/base/configure-prometheus.yaml
  hack/setup-monitoring.sh
Labels: lgtm, ok-to-test, approved

#954 Update Openshift pipelines to v1.8
  components/pipeline-service/openshift-pipelines/subscription.yaml
Labels: lgtm, approved

#956 drop unnecessary admin permissions
  components/authentication/build.yaml
  components/authentication/cluster-registration-ci.yaml
  components/authentication/cluster-registration-maintainer.yaml
  components/authentication/component-maintainer.yaml
  components/authentication/e2e-tests.yaml
  components/authentication/everyone-can-view.yaml
  components/authentication/gitops.yaml
  components/authentication/group-sync/group-sync-ci.yaml
  components/authentication/group-sync/group-sync.yaml
  components/authentication/group-sync/kustomization.yaml
  components/authentication/has-debug.yaml
  components/authentication/has.yaml
  components/authentication/integration.yaml
  components/authentication/kustomization.yaml
  components/authentication/prune-has.yaml
  components/authentication/prune-olm-has.yaml
  components/authentication/release.yaml
  components/authentication/spi-ci.yaml
  components/authentication/spi.yaml
  components/authentication/tenants/gazarenkov.yaml
  components/authentication/tenants/kustomization.yaml
  components/authentication/tenants/managed-rbean-namespace.yaml
  components/authentication/tenants/managed-shebert-namespace.yaml
  components/authentication/tenants/mshaposh.yaml
  components/authentication/tenants/mvalarh.yaml
  components/authentication/tenants/pdave.yaml
  components/authentication/tenants/rbean.yaml
  components/authentication/tenants/redhat-namespace.yaml
  components/authentication/tenants/sabhardw.yaml
  components/authentication/tenants/shbose.yaml
  components/authentication/tenants/shebert.yaml
  components/authentication/tenants/skabashn.yaml
  components/authentication/tenants/sm43.yaml
  components/authentication/test-team-ci.yaml
  components/authentication/test-team.yaml
  components/authentication/view-build-service.yaml
  components/authentication/view-cluster-registration.yaml
  components/authentication/view-e2e-tests.yaml
  components/authentication/view-enterprise-contract.yaml
  components/authentication/view-gitops-service.yaml
  components/authentication/view-has.yaml
  components/authentication/view-integration.yaml
  components/authentication/view-quality-dashboard.yaml
  components/authentication/view-release.yaml
Labels: lgtm, approved

#969 grant cluster view to only stage members from redhat-appstudio-sre
  components/authentication/everyone-can-view.yaml
  components/authentication/group-sync/github-redhat-appstudio-sre.yaml
  components/authentication/group-sync/kustomization.yaml
Labels: lgtm, approved

#958 Enable pprof in HAS on staging
  components/has/kustomization.yaml
  components/has/pprof_patch.yaml
Labels: lgtm, approved

#966 preview.sh improvements
  argo-cd-apps/overlays/development/repo-overlay.yaml
  hack/bootstrap-cluster.sh
  hack/build/setup-pac-integration.sh
  hack/preview.sh
  hack/util-set-development-repos.sh
  hack/util-set-quality-dashboard-backend-route.sh
  hack/util-update-app-of-apps.sh
Labels: approved

#967 Bump PaC version to v0.14.0
  components/pipeline-service/pipelines-as-code/kustomization.yaml
Labels: lgtm, approved

#859 feat: deploy Grafana using operator
  components/monitoring/base/dashboards/example.json
  components/monitoring/base/grafana-app.yaml
  components/monitoring/base/grafana.ini
  components/monitoring/base/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#973 Fix components path
  hack/preview.sh
Labels: lgtm, approved

#976 fix: update sed cmd for compatibility with mac os
  hack/preview.sh
Labels: approved

#978 Fixed incorrect vault route url
  components/spi/overlays/staging/config-patch.json
Labels: approved

#972 chore: AD-35 move quality-dashboard deployment files to quality-dashboard repo
  components/quality-dashboard/backend/deployment.yaml
  components/quality-dashboard/backend/kustomization.yaml
  components/quality-dashboard/backend/route.yaml
  components/quality-dashboard/backend/service.yaml
  components/quality-dashboard/frontend/deployment.yaml
  components/quality-dashboard/frontend/kustomization.yaml
  components/quality-dashboard/frontend/route.yaml
  components/quality-dashboard/frontend/service-account.yaml
  components/quality-dashboard/frontend/service.yaml
Labels: approved

#983 Necessary permission for the component maintainers to trigger deployment restart
  components/authentication/component-maintainer.yaml
Labels: approved
