Repository redhat-appstudio/infra-deployments, pull requests merged in 2022-05, with the labels that each got.

#326 Let Github:Serena see her appstudio namespace
  components/authentication/tenants/kustomization.yaml
  components/authentication/tenants/serena.yaml
Labels: lgtm

#325 Update pipeline-as-code to version 0.7.0
  components/build/pipelines-as-code/kustomization.yaml
Labels: lgtm

#331 new cluster registration version - 0.0.0-20220504-13-23-32
  components/cluster-registration/kustomization.yaml
Labels: ok-to-test

#324 Update application and build operators image references
  components/build/build-service/kustomization.yaml
  components/gitops/staging/argo-cd.yaml
  hack/build/build-via-appstudio.sh
Labels: lgtm

#337 allow overriding build-service config
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm

#339 Bundle selection enablement
  components/build/build-service/kustomization.yaml
  components/has/kustomization.yaml
Labels: lgtm

#342 demo: Support local rekor instance
  hack/chains/release-pipeline-with-ec-demo.sh
Labels: ok-to-test

#347 Wait for the pipeline service account in e2e demo
  hack/chains/end-to-end-demo.sh
Labels: lgtm

#286 Create install pre-requisites scripts for the chains demos
  hack/chains/README.md
  hack/chains/setup/debian-based.sh
  hack/chains/setup/install-demo-pre-req.sh
  hack/chains/setup/macos-based.sh
  hack/chains/setup/redhat-based.sh
Labels: ok-to-test

#350 PLNSRVCE-255 - Create sharedSecret for infra-deployments-update task
  components/build/shared-resources/infra-deployments-pr-creator.yaml
  components/build/shared-resources/kustomization.yaml
  components/build/shared-resources/shared-resources-components.yaml
Labels: lgtm

#351 update spi operator
  components/spi/kustomization.yaml
Labels: lgtm

#341 EnterpriseContractPolicy CRD
  argo-cd-apps/base/enterprise-contract.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/enterprise-contract/kustomization.yaml
Labels: ok-to-test

#357 update ci to go 1.17
  .ci/openshift-ci/Dockerfile
Labels: lgtm

#358 CSI-SCC: Sync with pipelines-scc
  components/build/shared-resources/scc.yaml
Labels: lgtm

#349 PLNSRVCE-248: create shared secret redhat-appstudio-user-workload
  components/build/shared-resources/add-user-workload-shared-secret-scc-clusterrole.yaml
  components/build/shared-resources/kustomization.yaml
  components/build/shared-resources/redhat-appstudio-user-workload-sharedsecret.yaml
Labels: lgtm

#366 Add PaC for e2e-tests
  components/build/shared-resources/shared-resources-components.yaml
  components/e2e-tests/.tekton/kustomization.yaml
  components/e2e-tests/.tekton/pipelines-as-code.yaml
Labels: lgtm

#372 View access for CI related namespaces to EC team
  components/authentication/view-build-service.yaml
Labels: lgtm

#373 fix: enable HAS to override kustomize config
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm

#380 Update pipelines-as-code version in infra-deployments to 0.8.0
  components/build/pipelines-as-code/kustomization.yaml
Labels: lgtm

#383 chore: Auto Rebase PR's that are approved
  .github/workflows/auto-update.yml
Labels: lgtm

#388 Use custom version of chains to attest pr
  components/build/tekton-chains/chains-config.yaml
  components/build/tekton-chains/chains-controller-deployment.yaml
  hack/chains/config.sh
Labels: lgtm

#378 docs: point to e2e-tests repo
  README.md
Labels: lgtm, needs-ok-to-test

#389 Use official repo instead of jgwest fork
  components/gitops/staging/kustomization.yaml
Labels: lgtm

#364 Add pipelines-as-code for enterprise contract
  argo-cd-apps/base/enterprise-contract.yaml
  components/build/shared-resources/shared-resources-components.yaml
  components/enterprise-contract/.tekton/kustomization.yaml
  components/enterprise-contract/.tekton/pipelines-as-code.yaml
  components/enterprise-contract/.tekton/pvc.yaml
  components/enterprise-contract/kustomization.yaml
Labels: lgtm

#395 Allow to view enterprise-contract-service namespace
  components/authentication/kustomization.yaml
  components/authentication/view-enterprise-contract.yaml
Labels: lgtm

#394 Allow jvm-build-service to access shared secrets
  components/build/shared-resources/shared-resources-components.yaml
Labels: lgtm

#392 SPI OAuth service update v0.5.5
  components/spi/kustomization.yaml
Labels: lgtm

#400 Add openshift ci custom user
  .ci/oci-e2e-deployment.sh
Labels: lgtm

#402 fix: add SPI setup to openshift-ci e2e
  .ci/oci-e2e-deployment.sh
Labels: lgtm

#404 jvm-build-service: extent PVC, localstack on quay
  components/build/jvm-build-service/.tekton/pvc.yaml
  components/build/jvm-build-service/localstack.yaml
Labels: lgtm

#407 Update HAS May 27 2022
  components/has/kustomization.yaml
Labels: lgtm
