Repository redhat-appstudio/infra-deployments, pull requests merged in 2022-02, with the labels that each got.

#80 Add bash scripts to demo chains signed taskrun verification
  hack/chains/check-pipelinerun.sh
  hack/chains/check-taskrun.sh
Labels: lgtm, needs-ok-to-test

#82 HAS: Deploy integration with Builds
  components/has/kustomization.yaml
Labels: do-not-merge/hold

#84 update README with component testing instructions
  README.md
Labels: lgtm, needs-ok-to-test

#89 Add HAS User for View
  components/authentication/view-has.yaml
Labels: lgtm

#90 Increase memory and CPU limits for HAS
  components/has/kustomization.yaml
  components/has/manager_resources_patch.yaml
Labels: lgtm

#92 Add HAS Pruner role to kustomization.yaml
  components/authentication/kustomization.yaml
Labels: lgtm

#93 Add patch verb to HAS Pruner role
  components/authentication/prune-has.yaml
Labels: lgtm

#97 Added cluster monitoring config for crc setup and updated SPI config
  README.md
Labels: lgtm, needs-ok-to-test

#94 Use the kubeadmin user when bootstrapping the cluster/Wait for Argo CD route to be up
  hack/bootstrap-cluster.sh
Labels: lgtm, needs-ok-to-test

#101 Assign PVC by onetime job
  components/gitops/.tekton/pvc.yaml
  components/has/.tekton/pvc.yaml
Labels: lgtm

#96 Configure tekton PipelineRuns pruner
  components/build/openshift-pipelines/kustomization.yaml
  components/build/openshift-pipelines/patch-tekton-config-rb.yaml
  components/build/openshift-pipelines/patch-tekton-config-role.yaml
  components/build/openshift-pipelines/patch-tekton-config-sa.yaml
  components/build/openshift-pipelines/pruner-configuration-job.yaml
Labels: lgtm

#106 Fix typo in preview.env readme instructions
  README.md
Labels: needs-ok-to-test

#102 Deployment of SPI's simple demo UI
  components/spi/cluster-rb-patch.json
  components/spi/kustomization.yaml
  components/spi/scm_route.yaml
Labels: lgtm

#107 Make hack/bootstrap-cluster.sh wait more calmly
  hack/bootstrap-cluster.sh
Labels: ok-to-test

#110 Refresh HAS in staging
  components/has/kustomization.yaml
Labels: lgtm

#114 Add back argocd-permissions.yaml for HAS
  components/has/kustomization.yaml
Labels: lgtm

#113 Update triggers.tekton.dev API version from v1alpha1 to v1beta1
  components/gitops/.tekton/event-listener.yaml
  components/gitops/.tekton/trigger-template.yaml
  components/has/.tekton/event-listener.yaml
  components/has/.tekton/trigger-template.yaml
Labels: lgtm, ok-to-test

#115 Infra for PR checks / Add Pipelines As Code for internal use
  components/authentication/build-ci.yaml
  components/authentication/kustomization.yaml
  components/authentication/view-build-service.yaml
  components/build/kustomization.yaml
  components/build/openshift-pipelines/allow-argocd-create-sa.yaml
  components/build/openshift-pipelines/kustomization.yaml
  components/build/pipelines-as-code/allow-argocd.yaml
  components/build/pipelines-as-code/kustomization.yaml
  components/gitops/kustomization.yaml
  components/has/.tekton/kustomization.yaml
  components/has/.tekton/pipelines-as-code.yaml
Labels: lgtm

#109 Allow to select mode during bootstrap, allow to select application for deployment
  README.md
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  hack/bootstrap-cluster.sh
  hack/destroy-cluster.sh
  hack/preview-template.env
  hack/util-set-development-repos.sh
Labels: lgtm

#121 Install yq go binaries instead of python bins
  .ci/openshift-ci/Dockerfile
Labels: lgtm

#122 SVPI-61 - vault admin rolebinding
  components/spi/kustomization.yaml
  components/spi/vault_rolebinding.yaml
Labels: lgtm

#128 Add logic to execute latest e2e tests version against appstudio
  .ci/oci-e2e-deployment.sh
  hack/preview.sh
Labels: lgtm

#56 Build: Automate build of build-templates-bundle and appstudio-utils
  components/build/.tekton/event-listener.yaml
  components/build/.tekton/kustomization.yaml
  components/build/.tekton/pvc.yaml
  components/build/.tekton/serviceaccount.yaml
  components/build/.tekton/trigger-template.yaml
  components/build/.tekton/webhook-route.yaml
  components/build/kustomization.yaml
Labels: lgtm

#119 A few updates to bootstrap script.
  hack/bootstrap-cluster.sh
Labels: lgtm, needs-ok-to-test
