Repository redhat-appstudio/infra-deployments, pull requests merged in 2022-09, with the labels that each got.

#682 fir: drop missing usage of dev mode script
  hack/bootstrap.sh
Labels: lgtm, approved

#685 fix: dev mode uses the right overlay
  hack/bootstrap.sh
  hack/util-set-development-repos.sh
  hack/util-update-app-of-apps.sh
Labels: lgtm, approved

#686 fix source.path for dev overlay
  hack/util-update-app-of-apps.sh
Labels: lgtm, approved

#676 hard apps refresh when new kcp is configured
  hack/configure-kcp.sh
Labels: lgtm, approved

#683 Update quality dashboard backend and frontend versions
  components/quality-dashboard/backend/deployment.yaml
  components/quality-dashboard/frontend/deployment.yaml
  hack/bootstrap-cluster.sh
Labels: lgtm

#688 Fix quality dashboard backend binary deployment
  components/quality-dashboard/backend/deployment.yaml
Labels: lgtm, approved

#689 Fix quality dashboard backend memory limits
  components/quality-dashboard/backend/deployment.yaml
Labels: approved

#691 Update new quality dashboard frontend version
  components/quality-dashboard/frontend/deployment.yaml
Labels: lgtm, approved

#690 delete ApplicationSet and use right element name
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
Labels: lgtm, approved

#687 improve workspace name handling & README
  README.md
  hack/configure-kcp.sh
  hack/destroy.sh
Labels: lgtm, approved

#692 [demo] manage gitops in sdoyle
  components/authentication/tenants/shbose.yaml
Labels: approved

#699 fix: Upgrade Dashboard to Latest
  components/quality-dashboard/frontend/deployment.yaml
  components/quality-dashboard/frontend/service-account.yaml
Labels: lgtm, approved

#701 fix: Dashboard proxy error
  components/quality-dashboard/frontend/deployment.yaml
Labels: approved

#681 Add tags for gradle versions in the builder images
  components/build/jvm-build-service/system-config.yaml
Labels: lgtm

#705 use pre-kcp branch
  README.md
  argo-cd-apps/app-of-apps/all-applications-staging.yaml
  argo-cd-apps/base/authentication.yaml
  argo-cd-apps/base/build.yaml
  argo-cd-apps/base/cluster-registration.yaml
  argo-cd-apps/base/e2e-tests.yaml
  argo-cd-apps/base/enterprise-contract.yaml
  argo-cd-apps/base/gitops.yaml
  argo-cd-apps/base/has.yaml
  argo-cd-apps/base/integration.yaml
  argo-cd-apps/base/quality-dashboard.yaml
  argo-cd-apps/base/release.yaml
  argo-cd-apps/base/spi.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/build/README.md
  hack/preview.sh
  hack/util-set-development-repos.sh
  hack/util-update-app-of-apps.sh
Labels: lgtm, approved

#706 merge main into kcp
  hack/setup/prepare-crc.sh
Labels: lgtm, approved

#708 set all targetRevision occurrences to main
  argo-cd-apps/app-of-apps/all-applications.yaml
  argo-cd-apps/base/authorization-in-cluster.yaml
  argo-cd-apps/base/authorization-in-kcp.yaml
  argo-cd-apps/base/has.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
Labels: lgtm, approved

#704 Added deployment dependencies for AppStudio
  README.md
  hack/setup/debian-based.sh
  hack/setup/macos-based.sh
  hack/setup/redhat-based.sh
Labels: approved

#716 CI: PaC cover jvm-build-service-builder-images
  components/build/jvm-build-service/.tekton/pipelines-as-code.yaml
Labels: lgtm, approved

#713 Grant rbean rights to view in root:redhat-appstudio
  components/authorization/kcp/members-view-everything.yaml
Labels: lgtm

#709 Initial implementation of preview-ckcp and preview-cps
  README.md
  components/ckcp/cert-manager.yaml
  components/ckcp/certs.yaml
  components/ckcp/deployment.yaml
  components/ckcp/kustomization.yaml
  components/ckcp/namespace.yaml
  components/ckcp/pvc.yaml
  components/ckcp/route.yaml
  components/ckcp/service.yaml
  hack/bootstrap.sh
  hack/configure-kcp.sh
  hack/flags.sh
  hack/install-ckcp.sh
  hack/preview-template.env
  hack/preview.sh
  hack/util-set-github-org
Labels: lgtm, approved

#717 fix: add missing --kubeconfig flag when creating bind RBAC
  hack/configure-kcp.sh
Labels: lgtm, approved

#719 preview: force usage of CLUSTER_KUBECONFIG
  hack/preview.sh
Labels: lgtm, approved

#722 make install-ckcp.sh independent of preview vars
  hack/bootstrap.sh
  hack/install-ckcp.sh
Labels: lgtm, approved

#714 Accomodate for the changes to SPI config introduced in PR 232
  README.md
  components/spi/config-patch.json
  components/spi/config.yaml
  components/spi/insecuretls-patch.json
  components/spi/kustomization.yaml
  components/spi/oauth-service-config-patch.json
  components/spi/oauth-service-deployment-patch.json
  hack/preview.sh
  hack/util-patch-spi-config.sh
  hack/util-set-spi-vault-host.sh
Labels: lgtm, approved

#726 use one kcp kubeconfig
  README.md
  hack/bootstrap.sh
  hack/flags.sh
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm, approved

#725 Unify code to use one preview mode
  README.md
  hack/bootstrap.sh
  hack/configure-kcp.sh
  hack/flags.sh
  hack/install-ckcp.sh
  hack/preview-template.env
Labels: lgtm, approved

#730 Show message when invalid bootstrap mode is used
  README.md
  hack/bootstrap.sh
Labels: lgtm, approved

#733 Copy quicklab scripts from pre-kcp branch
  hack/quicklab/README.md
  hack/quicklab/setup-nfs-quicklab.sh
  hack/quicklab/templates/deployment.yaml
  hack/quicklab/templates/rbac.yaml
  hack/quicklab/templates/storageClass.yaml
  hack/quicklab/templates/test-pvc.yaml
Labels: lgtm, approved

#731 ignore could not parse version error
  hack/flags.sh
Labels: lgtm, approved

#735 Update to golang 1.18 dockerfile tests
  .ci/openshift-ci/Dockerfile
Labels: lgtm

#715 SPI on KCP/CPS
  .gitignore
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/base/spi.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/spi/apibinding_spi.yaml
  components/spi/config-patch.json
  components/spi/config.yaml
  components/spi/kustomization.yaml
  components/spi/oauth-service-config-patch.json
  components/spi/vault/kustomization.yaml
  hack/destroy.sh
  hack/preview.sh
  hack/util-patch-spi-config.sh
Labels: lgtm, approved

#737 Rename occurences of has to application-service
  README.md
  argo-cd-apps/base/application-service.yaml
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/application-service/OWNERS
  components/application-service/kustomization.yaml
  components/application-service/manager_resources_patch.yaml
  components/authorization/kcp/application-service-secrets.yaml
  components/authorization/kcp/kustomization.yaml
  hack/preview.sh
  hack/util-set-github-org
Labels: lgtm, approved

#732 sync replace after configuring kcp
  hack/configure-kcp.sh
Labels: lgtm, approved

#738 Update PipelinesAsCode to v0.12
  components/build/pipelines-as-code/kustomization.yaml
Labels: lgtm, approved

#744 Fix perf issue on Chains controller
  components/build/tekton-chains/chains-controller-deployment.yaml
Labels: lgtm, approved

#742 preview: always work in ${ROOT_WORKSPACE}:redhat-appstudio
  hack/preview-template.env
  hack/preview.sh
Labels: approved

#729 add support for HACBS service provider workspace
  README.md
  argo-cd-apps/base/authorization-in-kcp.yaml
  components/authorization/kcp/appstudio/application-service-secrets.yaml
  components/authorization/kcp/appstudio/kustomization.yaml
  components/authorization/kcp/appstudio/spi-secrets.yaml
  components/authorization/kcp/base/kustomization.yaml
  components/authorization/kcp/base/members-view-everything.yaml
  components/authorization/kcp/base/view-everything.yaml
  components/authorization/kcp/hacbs/kustomization.yaml
  hack/configure-kcp.sh
  hack/destroy.sh
Labels: approved

#746 Fix: workspace switch
  hack/preview.sh
Labels: approved

#749 fix: hardcode cluster name in argocd
  hack/configure-kcp.sh
Labels: approved

#754 resources-finalizer is not valid for ApplicationSets
  argo-cd-apps/overlays/development/repo-overlay.yaml
Labels: approved

#751 allow everyone bind all APIExports
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/authorization/kcp/base/bind-apiexports.yaml
  components/authorization/kcp/base/everyone-bind-apiexports.yaml
  components/authorization/kcp/base/kustomization.yaml
Labels: approved

#745 Add script for install Pipeline Service
  README.md
  hack/install-pipeline-service.sh
Labels: approved

#759 Specify yq version in readme
  README.md
Labels: approved

#756 Split SPI to overlays
  .gitignore
  argo-cd-apps/base/spi.yaml
  components/spi/base/apibinding_spi.yaml
  components/spi/base/config.yaml
  components/spi/base/delete-shared-configuration-file.yaml
  components/spi/base/kustomization.yaml
  components/spi/base/oauth-service-config-patch.json
  components/spi/overlays/dev/config-patch.json
  components/spi/overlays/dev/kustomization.yaml
  components/spi/overlays/kcp-stable/config-patch.json
  components/spi/overlays/kcp-stable/kustomization.yaml
  components/spi/overlays/kcp-unstable/config-patch.json
  components/spi/overlays/kcp-unstable/kustomization.yaml
  hack/preview.sh
  hack/util-patch-spi-config.sh
Labels: approved

#753 add script for creating user AppStudio workspace
  README.md
  apibindings/appstudio/application-api.yaml
  apibindings/appstudio/application-service.yaml
  apibindings/appstudio/kustomization.yaml
  apibindings/appstudio/spi.yaml
  apibindings/hacbs/kustomization.yaml
  components/spi/base/kustomization.yaml
  hack/create-user-workspace.sh
Labels: approved

#752 EC binding with owners list
  argo-cd-apps/base/enterprise-contract.yaml
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/enterprise-contract/OWNERS
  components/enterprise-contract/kustomization.yaml
Labels: approved

#762 Add mkovarik(Michkov) permission to view kcp cluster
  components/authorization/kcp/base/members-view-everything.yaml
Labels: approved

#761 preview: set user workspaces with bindings
  hack/preview.sh
Labels: approved

#766 use --short to get workspace path
  hack/configure-kcp.sh
  hack/create-user-workspace.sh
  hack/install-pipeline-service.sh
Labels: lgtm, approved

#765 automatically accept all permission claims in APIBindings
  apibindings/appstudio/application-api.yaml
  apibindings/appstudio/application-service.yaml
  apibindings/appstudio/kustomization.yaml
  apibindings/appstudio/spi.yaml
  apibindings/hacbs/kustomization.yaml
  hack/create-user-workspace.sh
Labels: approved

#768 Update spi components with latest changes
  components/spi/base/kustomization.yaml
  hack/preview.sh
Labels: lgtm, approved

#769 Remove sharedSecret from SPI config
  components/spi/base/config.yaml
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm, approved

#763 IdentityHashes for APIExports
  apibindings/appstudio/application-service.yaml
  argo-cd-apps/base/enterprise-contract.yaml
  components/application-api/overlays/dev/apiexport.yaml
  components/application-service/base/manager_resources_patch.yaml
  components/application-service/overlays/dev/apiexport.yaml
  components/application-service/overlays/dev/kustomization.yaml
  components/application-service/overlays/kcp-stable/apiexport.yaml
  components/application-service/overlays/kcp-stable/kustomization.yaml
  components/application-service/overlays/kcp-unstable/apiexport.yaml
  components/application-service/overlays/kcp-unstable/kustomization.yaml
  components/hacbs/enterprise-contract/OWNERS
  components/hacbs/enterprise-contract/kustomization.yaml
  components/spi/overlays/dev/apiexport.yaml
  hack/build/build-via-appstudio.sh
  hack/build/templates/application.yaml
  hack/build/templates/component.yaml
  hack/preview.sh
Labels: approved

#771 give Ann Marie permission to view KCP cluster
  components/authorization/kcp/base/members-view-everything.yaml
Labels: approved

#770 Increase resources of ckcp, keep unresolved IdentityHash
  components/ckcp/deployment.yaml
  components/ckcp/pvc.yaml
  hack/preview.sh
Labels: approved

#772 Preview - add pipeline service integration
  apibindings/appstudio/kustomization.yaml
  apibindings/appstudio/pipeline-service.yaml
  hack/create-user-workspace.sh
  hack/preview-template.env
  hack/preview.sh
Labels: approved

#776 Fixed some wording, grouped access info together
  README.md
Labels: lgtm, approved

#718 CRC: Updating rebranding and links
  README.md
Labels: lgtm, needs-ok-to-test, approved

#775 Add build-service
  apibindings/appstudio/build-service.yaml
  apibindings/appstudio/kustomization.yaml
  argo-cd-apps/base/build-service.yaml
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/build-service/OWNERS
  components/build-service/base/kustomization.yaml
  components/build-service/overlays/dev/apiexport.yaml
  components/build-service/overlays/dev/kustomization.yaml
  components/build-service/overlays/kcp-stable/apiexport.yaml
  components/build-service/overlays/kcp-stable/kustomization.yaml
  components/build-service/overlays/kcp-unstable/apiexport.yaml
  components/build-service/overlays/kcp-unstable/kustomization.yaml
  hack/build/build-via-appstudio.sh
Labels: approved

#779 Give Gal Ben Haim permissions to view resources
  components/authorization/kcp/base/members-view-everything.yaml
Labels: needs-ok-to-test, approved

#777 Check kubectl version to be 1.24.x or higher
  hack/flags.sh
Labels: approved

#773 Convert ROOT_WORKSPACE='~' to full path in flags.sh
  hack/configure-kcp.sh
  hack/create-user-workspace.sh
  hack/flags.sh
  hack/install-pipeline-service.sh
  hack/preview.sh
Labels: approved

#781 Allow to install pipeline-service automatically
  hack/create-user-workspace.sh
  hack/install-pipeline-service.sh
  hack/preview-template.env
  hack/preview.sh
Labels: approved
