Repository redhat-appstudio/infra-deployments, pull requests merged in 2022-10, with the labels that each got.

#785 Fix variable quoting in preview.sh for APIExports
  hack/preview.sh
Labels: approved

#758 PLNSRVCE-658: readd kcp'ed jvm-build-service but leverages a bunch of simplifications over pre-kcp integration
  apibindings/hacbs/jvm-build-service.yaml
  apibindings/hacbs/kustomization.yaml
  argo-cd-apps/base/jvm-build-service.yaml
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/hacbs/jvm-build-service/OWNERS
  components/hacbs/jvm-build-service/base/kustomization.yaml
  components/hacbs/jvm-build-service/overlays/dev/apiexport.yaml
  components/hacbs/jvm-build-service/overlays/dev/kustomization.yaml
  components/hacbs/jvm-build-service/overlays/kcp-stable/apiexport.yaml
  components/hacbs/jvm-build-service/overlays/kcp-stable/kustomization.yaml
  components/hacbs/jvm-build-service/overlays/kcp-unstable/apiexport.yaml
  components/hacbs/jvm-build-service/overlays/kcp-unstable/kustomization.yaml
Labels: approved

#783 Script for resolving identityHashes
  README.md
  components/build-service/base/kustomization.yaml
  components/build-service/overlays/dev/apiexport.yaml
  components/build-service/overlays/dev/kustomization.yaml
  components/build-service/overlays/kcp-stable/apiexport.yaml
  components/build-service/overlays/kcp-stable/kustomization.yaml
  components/build-service/overlays/kcp-unstable/apiexport.yaml
  components/build-service/overlays/kcp-unstable/kustomization.yaml
  hack/generate-apiexport-overlays.sh
  identityhashes/kcp-stable/application-api
  identityhashes/kcp-stable/pipeline-service
  identityhashes/kcp-stable/spi
  identityhashes/kcp-unstable/application-api
  identityhashes/kcp-unstable/spi
Labels: approved

#774 preview - Update of identityhash code
  hack/preview.sh
Labels: needs-rebase, approved

#797 Allow Michkov to view spi namespace
  components/authentication/view-spi.yaml
Labels: approved

#794 preview fix: filter hacbs by folder components/hacbs
  hack/preview.sh
Labels: approved

#790 Update application-service to use apiexport from repo
  components/application-service/overlays/dev/apiexport.yaml
  components/application-service/overlays/dev/kustomization.yaml
  components/application-service/overlays/kcp-stable/apiexport.yaml
  components/application-service/overlays/kcp-stable/kustomization.yaml
  components/application-service/overlays/kcp-unstable/apiexport.yaml
  components/application-service/overlays/kcp-unstable/kustomization.yaml
Labels: approved

#801 Add bkundu to everything viewer for kcp
  components/authorization/kcp/base/members-view-everything.yaml
Labels: lgtm, approved

#802 Add '--destroy' param to install-ckcp.sh
  README.md
  hack/install-ckcp.sh
Labels: lgtm, approved

#806 Bind syncer to kcp version
  hack/configure-kcp.sh
Labels: lgtm, approved

#813 Added domain address for sso login
  components/authorization/kcp/base/members-view-everything.yaml
Labels: approved

#814 Set TEKTON_RESULTS creds for pipeline-service
  hack/install-pipeline-service.sh
  hack/preview-template.env
Labels: lgtm, approved

#811 Template API Version update
  hack/monitoring/configure_grafana.yaml
  hack/monitoring/configure_prometheus.yaml
  hack/monitoring/prometheus_servicemonitors.yaml
  hack/setup_observability.sh
Labels: lgtm, approved

#810 build-via-appstudio.sh: do not create pipeline SA
  hack/build/build-via-appstudio.sh
Labels: approved

#815 add hacbs release-service apiexport
  apibindings/hacbs/kustomization.yaml
  apibindings/hacbs/release-service.yaml
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/base/release-service.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/hacbs/release-service/OWNERS
  components/hacbs/release-service/base/kustomization.yaml
  components/hacbs/release-service/overlays/dev/apiexport.yaml
  components/hacbs/release-service/overlays/dev/kustomization.yaml
  components/hacbs/release-service/overlays/kcp-stable/apiexport.yaml
  components/hacbs/release-service/overlays/kcp-stable/kustomization.yaml
  components/hacbs/release-service/overlays/kcp-unstable/apiexport.yaml
  components/hacbs/release-service/overlays/kcp-unstable/kustomization.yaml
Labels: approved

#823 Fix: generate-apiexport-overlays.sh and regenerate
  components/application-service/overlays/kcp-unstable/apiexport.yaml
  components/build-service/overlays/kcp-unstable/apiexport.yaml
  components/hacbs/jvm-build-service/overlays/kcp-unstable/apiexport.yaml
  components/hacbs/release-service/overlays/dev/apiexport.yaml
  components/hacbs/release-service/overlays/kcp-stable/apiexport.yaml
  components/hacbs/release-service/overlays/kcp-unstable/apiexport.yaml
  hack/generate-apiexport-overlays.sh
Labels: approved

#825 Connect Syncer to Local CKCP via internal service
  components/ckcp/certs.yaml
  hack/configure-kcp.sh
  hack/flags.sh
  hack/preview-template.env
  hack/util-validate-preview-env.sh
Labels: lgtm, approved

#828 Grant Alexey Kazakov view permissions in kcp
  components/authorization/kcp/base/members-view-everything.yaml
Labels: approved

#821 Add hacbs integration-service apiexport to support kcp
  apibindings/hacbs/integration-service.yaml
  apibindings/hacbs/kustomization.yaml
  argo-cd-apps/base/integration-service.yaml
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/hacbs/integration-service/OWNERS
  components/hacbs/integration-service/base/kustomization.yaml
  components/hacbs/integration-service/overlays/dev/apiexport.yaml
  components/hacbs/integration-service/overlays/dev/kustomization.yaml
  components/hacbs/integration-service/overlays/kcp-stable/apiexport.yaml
  components/hacbs/integration-service/overlays/kcp-stable/kustomization.yaml
  components/hacbs/integration-service/overlays/kcp-unstable/apiexport.yaml
  components/hacbs/integration-service/overlays/kcp-unstable/kustomization.yaml
Labels: approved

#808 Add initial support for running GitOps Service on KCP
  argo-cd-apps/base/gitops-appstudio-service.yaml
  argo-cd-apps/base/gitops-core-service.yaml
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/gitops-appstudio-service/base/kustomization.yaml
  components/gitops-appstudio-service/overlays/dev/apiexport.yaml
  components/gitops-appstudio-service/overlays/dev/kustomization.yaml
  components/gitops-appstudio-service/overlays/kcp-stable/apiexport.yaml
  components/gitops-appstudio-service/overlays/kcp-stable/kustomization.yaml
  components/gitops-appstudio-service/overlays/kcp-unstable/apiexport.yaml
  components/gitops-appstudio-service/overlays/kcp-unstable/kustomization.yaml
  components/gitops-core-service/base/kustomization.yaml
  components/gitops-core-service/overlays/dev/apiexport.yaml
  components/gitops-core-service/overlays/dev/kustomization.yaml
  components/gitops-core-service/overlays/kcp-stable/apiexport.yaml
  components/gitops-core-service/overlays/kcp-stable/kustomization.yaml
  components/gitops-core-service/overlays/kcp-unstable/apiexport.yaml
  components/gitops-core-service/overlays/kcp-unstable/kustomization.yaml
  hack/configure-kcp.sh
  hack/preview.sh
  identityhashes/kcp-stable/gitops-api
  identityhashes/kcp-unstable/gitops-api
Labels: approved

#832 Gitops identityhashes
  components/gitops-appstudio-service/overlays/kcp-stable/apiexport.yaml
  components/gitops-appstudio-service/overlays/kcp-unstable/apiexport.yaml
  identityhashes/kcp-stable/gitops-api
  identityhashes/kcp-stable/gitopsrvc-appstudio-shared
  identityhashes/kcp-unstable/gitops-api
  identityhashes/kcp-unstable/gitopsrvc-appstudio-shared
Labels: approved

#833 add GitOps APIBindings
  apibindings/appstudio/gitops-appstudio-service.yaml
  apibindings/appstudio/gitops-core-service.yaml
  apibindings/appstudio/kustomization.yaml
Labels: approved

#830 match syncer version
  hack/configure-kcp.sh
  hack/flags.sh
Labels: approved

#835 Update SPI to the latest version
  components/spi/base/kustomization.yaml
  components/spi/vault/kustomization.yaml
  hack/preview.sh
Labels: lgtm, approved

#838 add hacbs release-service manager
  components/hacbs/release-service/base/kustomization.yaml
  components/hacbs/release-service/base/manager_resources_patch.yaml
Labels: approved

#836 Use background pruning
  argo-cd-apps/app-of-apps/all-applications.yaml
  argo-cd-apps/base/application-api.yaml
  argo-cd-apps/base/application-service.yaml
  argo-cd-apps/base/authorization-in-cluster.yaml
  argo-cd-apps/base/authorization-in-kcp.yaml
  argo-cd-apps/base/build-service.yaml
  argo-cd-apps/base/enterprise-contract.yaml
  argo-cd-apps/base/gitops-appstudio-service.yaml
  argo-cd-apps/base/gitops-core-service.yaml
  argo-cd-apps/base/integration-service.yaml
  argo-cd-apps/base/jvm-build-service.yaml
  argo-cd-apps/base/release-service.yaml
  argo-cd-apps/base/spi.yaml
Labels: approved

#840 add Syncer manifests
  argo-cd-apps/base/kcp-syncer.yaml
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  components/authorization/cluster/stable-syncer-namespace-edit.yaml
  components/authorization/cluster/unstable-syncer-namespace-edit.yaml
  components/kcp-syncer/kcp-stable/appstudio-internal-syncer.yaml
  components/kcp-syncer/kcp-stable/kustomization.yaml
  components/kcp-syncer/kcp-unstable/appstudio-internal-syncer.yaml
  components/kcp-syncer/kcp-unstable/kustomization.yaml
  hack/configure-kcp.sh
Labels: approved

#844 Add description of WORKSPACE env vars
  hack/preview-template.env
Labels: approved

#843 Set build-templates component
  argo-cd-apps/base/build-templates.yaml
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/build-templates/kustomization.yaml
  components/build-templates/namespace.yaml
  components/build-templates/role.yaml
  components/build-templates/rolebinding.yaml
Labels: approved

#851 Use variable for sync manifest
  hack/configure-kcp.sh
Labels: approved

#848 Improve scripts to end when subcommand fails
  hack/bootstrap.sh
  hack/flags.sh
  hack/install-ckcp.sh
  hack/preview.sh
  hack/util-patch-spi-config.sh
  hack/util-set-development-repos.sh
  hack/util-set-github-org
Labels: approved

#852 Quicklab: fix directory removal
  hack/quicklab/templates/storageClass.yaml
Labels: approved

#846 Update util-validate-preview-env.sh to be more compact
  hack/flags.sh
  hack/preview-template.env
  hack/preview.sh
  hack/util-validate-preview-env.sh
Labels: approved

#827 PLNSRVCE-762: add IMAGE_TAG,IMAGE_REPO env vars to jvm bld svc
  components/hacbs/jvm-build-service/base/kustomization.yaml
  components/hacbs/jvm-build-service/overlays/dev/kustomization.yaml
Labels: approved

#853 Add timeout for SPI OAUTH route creation
  hack/preview.sh
Labels: approved

#855 docs: update readme with note about sed, openssl (on Mac OS)
  README.md
Labels: approved

#863 Use the v0.8.0 tag for pipeline-service
  hack/install-pipeline-service.sh
Labels: lgtm

#723 Add pact broker.
  argo-cd-apps/base/hac-pact-broker.yaml
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/authentication/pact-broker.yaml
  components/hac-pact-broker/imagestream.yaml
  components/hac-pact-broker/kustomization.yaml
  components/hac-pact-broker/pactbroker.yaml
  components/hac-pact-broker/postgre.yaml
  components/hac-pact-broker/postgrepvc.yaml
  components/hac-pact-broker/postgreservice.yaml
  components/hac-pact-broker/route.yaml
  components/hac-pact-broker/service.yaml
Labels: lgtm, ok-to-test, approved

#867 Fix pact broker
  argo-cd-apps/base/hac-pact-broker.yaml
Labels: lgtm, ok-to-test, approved

#868 rm jvm-bld-srvc apibinding entries (allow populate from repo)
  components/hacbs/jvm-build-service/base/self-binding.yaml
Labels: approved

#870 Fix permissions
  components/authentication/kustomization.yaml
  components/authentication/pact-broker.yaml
Labels: approved

#876 revert workspace type to `root:universal`
  hack/create-user-workspace.sh
Labels: needs-ok-to-test, approved
