Repository redhat-appstudio/infra-deployments, pull requests merged in 2022-04, with the labels that each got.

#195 Add script for testing building via AppStudio
  README.md
  hack/build/build-via-appstudio.sh
  hack/build/templates/application.yaml
  hack/build/templates/component.yaml
Labels: lgtm

#228 updates to scripts to support devfiles
  hack/build/analyze-devfile.sh
  hack/build/build-deploy.sh
  hack/build/build-quay.sh
  hack/build/build.sh
  hack/build/m2-builds.sh
  hack/build/repo-to-pipeline.sh
  hack/build/templates/default-build-bundle.yaml
  hack/build/utils/install-secrets.sh
Labels: lgtm

#229 setup release RBACs
  components/authentication/kustomization.yaml
  components/authentication/release-ci.yaml
  components/authentication/view-release.yaml
Labels: lgtm

#230 fix broken release rbac
  components/authentication/release-ci.yaml
Labels: lgtm

#227 Move build definitions CI to Pipelines as Code
  components/build/.tekton/event-listener.yaml
  components/build/.tekton/kustomization.yaml
  components/build/.tekton/pipelines-as-code.yaml
  components/build/.tekton/trigger-template.yaml
  components/build/.tekton/webhook-route.yaml
Labels: needs-ok-to-test

#225 Add cluster registration component
  .gitignore
  README.md
  argo-cd-apps/base/cluster-registration.yaml
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/cluster-registration/kustomization.yaml
Labels: needs-ok-to-test

#211 Update chains readme
  hack/chains/README.md
Labels: needs-ok-to-test

#242 fix: use yq for replacing github org in has tmpl
  hack/util-set-github-org
Labels: ok-to-test

#246 Add ability to view cluster-registration pods
  components/authentication/kustomization.yaml
  components/authentication/view-cluster-registration.yaml
Labels: lgtm, ok-to-test

#248 Disable authorization on tekton-results-api
  components/build/tekton-results/kustomization.yaml
  components/build/tekton-results/patch-tekton-results-api-no-auth.yaml
  hack/build/set-tkn-results.sh
Labels: lgtm

#243 Move has CI to apllication-service repo
  components/has/.tekton/event-listener.yaml
  components/has/.tekton/kustomization.yaml
  components/has/.tekton/trigger-template.yaml
  components/has/.tekton/webhook-route.yaml
Labels: lgtm

#240 Move SPI CI to SPI-operator repository
  components/spi/.tekton/event-listener.yaml
  components/spi/.tekton/kustomization.yaml
  components/spi/.tekton/trigger-template.yaml
  components/spi/.tekton/webhook-route.yaml
Labels: lgtm

#231 Tekton - enable tekton-scope-when-expressions-to-task
  components/build/openshift-pipelines/openshift-pipelines-feature-flags.yaml
Labels: lgtm

#251 PipelineAsCode for PVC-Cleaner
  components/build/kustomization.yaml
  components/build/pvc-cleaner/.tekton/kustomization.yaml
  components/build/pvc-cleaner/.tekton/pipelines-as-code.yaml
  components/build/pvc-cleaner/.tekton/pvc.yaml
  components/build/pvc-cleaner/.tekton/serviceaccount.yaml
  components/build/pvc-cleaner/kustomization.yaml
  components/build/pvc-cleaner/namespace.yaml
Labels: lgtm

#254 Add permission to manage pvc-cleaner namespace
  components/authentication/build-ci.yaml
  components/authentication/view-build-service.yaml
Labels: lgtm

#257 Add QE triona doyle & Pavel Sturc: build-templates
  components/authentication/view-build-service.yaml
Labels: ok-to-test

#252 Use forked Tekton Chains image
  components/build/tekton-chains/chains-controller-deployment.yaml
  components/build/tekton-chains/kustomization.yaml
Labels: ok-to-test

#255 Update HAS to 75a4c79e49ab5c1a4c15d844256d1e4419da63e3
  components/has/kustomization.yaml
  components/has/manager_resources_patch.yaml
Labels: lgtm

#213 HACBS 45 - Add YAML lint documentation
  hack/chains/.yamllint
  hack/chains/README.md
  hack/chains/check-yaml.sh
  hack/chains/pipeline-quay-demo.yaml
Labels: ok-to-test

#253 add cluster reg ability to create secrets on stage and production App…
  components/authentication/cluster-registration-ci.yaml
  components/authentication/kustomization.yaml
  components/cluster-registration/kustomization.yaml
Labels: lgtm, needs-ok-to-test

#260 Update PipelinesAsCode to 0.6.0
  components/build/pipelines-as-code/kustomization.yaml
Labels: lgtm

#258 Add build-service deployment configuration
  components/build/build-service/allow-argocd-to-manage.yaml
  components/build/build-service/kustomization.yaml
  components/build/kustomization.yaml
Labels: lgtm

#265 Enable github groups sync
  components/authentication/group-sync/github-redhat-appstudio.yaml
  components/authentication/group-sync/group-sync-ci.yaml
  components/authentication/group-sync/kustomization.yaml
  components/authentication/group-sync/namespaces.yaml
  components/authentication/group-sync/subscription.yaml
  components/authentication/group-sync/view-group-sync.yaml
  components/authentication/kustomization.yaml
  components/authentication/view-build-service.yaml
Labels: lgtm

#241 Enable all-namespaces mode for pvc-cleaner.
  components/build/pvc-cleaner/gitops/kustomization.yaml
  components/build/pvc-cleaner/has/kustomization.yaml
  components/build/pvc-cleaner/kustomization.yaml
  components/build/pvc-cleaner/pipeline-applications/kustomization.yaml
Labels: lgtm, do-not-merge/work-in-progress

#276 Add gitops ci maintainer
  components/authentication/gitops-ci.yaml
Labels: lgtm

#264 fix: Fix the SPI OAuth service deployment
  components/spi/kustomization.yaml
  components/spi/oauth-service-deployment-patch.json
  hack/development-mode.sh
  hack/preview-template.env
  hack/preview.sh
  hack/upstream-mode.sh
  hack/util-set-spi-api-server.sh
Labels: lgtm

#269 update to 0.0.0-20220418-12-39-25
  components/cluster-registration/kustomization.yaml
Labels: lgtm, ok-to-test

#273 Cluster reg create
  components/authentication/cluster-registration-maintainer.yaml
  components/authentication/kustomization.yaml
Labels: lgtm, ok-to-test

#275 Add section about authentication setting on stage
  README.md
Labels: lgtm

#274 Build definitions update
  components/build/kustomization.yaml
  components/e2e-tests/.tekton/trigger-template.yaml
  hack/build/templates/default-build-bundle.yaml
Labels: lgtm

#271 Prefer using Groups for view roles
  components/authentication/view-build-service.yaml
  components/authentication/view-e2e-tests.yaml
  components/authentication/view-gitops-service.yaml
  components/authentication/view-has.yaml
  components/authentication/view-spi.yaml
Labels: lgtm

#280 Cluster reg create2
  components/authentication/cluster-registration-maintainer.yaml
Labels: lgtm, needs-ok-to-test

#282 Update HAS to 6ae1a3ff557d6d01fbc6a00db655b1babf3df786
  components/has/kustomization.yaml
Labels: lgtm

#281 Cluster reg 20220421 17 46 47
  components/cluster-registration/kustomization.yaml
Labels: needs-ok-to-test

#288 Allow to override RELEASE operator references
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm

#293 Add demo of enforcing EC in a pipeline
  hack/chains/release-pipeline-with-ec-demo.sh
Labels: lgtm, needs-ok-to-test

#294 Use upstream patched version of chains
  components/build/tekton-chains/chains-controller-deployment.yaml
Labels: needs-ok-to-test

#296 Update HAS to 27318cfaa0c82c3e48a76c5d139fdacb8205a801
  components/has/kustomization.yaml
Labels: lgtm

#283 Add pipelines-as-code for release-service
  components/release/.tekton/kustomization.yaml
  components/release/.tekton/pipelines-as-code.yaml
  components/release/.tekton/pvc.yaml
  components/release/.tekton/serviceaccount.yaml
  components/release/kustomization.yaml
Labels: lgtm

#297 Define image for build-service
  components/build/build-service/kustomization.yaml
Labels: lgtm

#304 Use cosign to copy the public key
  hack/chains/copy-public-sig-key.sh
Labels: lgtm, needs-ok-to-test

#303 Update HAS to 45c4a52d9b6c567983ec72c3a6b776a95b99ba26
  components/has/kustomization.yaml
Labels: lgtm

#298 fix: update openshift-ci script
  .ci/oci-e2e-deployment.sh
Labels: lgtm

#302 update cluster registration to 0.0.0-20220426-15-32-36
  components/cluster-registration/kustomization.yaml
Labels: needs-ok-to-test

#309 Add build-templates-e2e namespace for test execution
  components/authentication/view-build-service.yaml
  components/build/build-templates/e2e/kustomization.yaml
  components/build/build-templates/e2e/namespace.yaml
  components/build/build-templates/e2e/role.yaml
  components/build/build-templates/e2e/rolebinding.yaml
  components/build/build-templates/kustomization.yaml
Labels: lgtm

#314 Show non-json log lines from Chains
  hack/chains/nice-logs.sh
Labels: ok-to-test

#310 End to end demo script for enterprise contract
  hack/chains/end-to-end-demo.sh
  hack/chains/release-pipeline-with-ec-demo.sh
Labels: needs-ok-to-test

#312 Add namespace and pvc-claim arguments to show-pvc.sh
  hack/build/utils/show-pvc.sh
Labels: lgtm

#315 Add pipeline-maintainers for build-templates-e2e
  components/authentication/build-ci.yaml
Labels: lgtm

#319 Update pvc-cleaner for AppStudio components
  components/build/pvc-cleaner/kustomization.yaml
Labels: lgtm
