Repository redhat-appstudio/infra-deployments, pull requests merged in 2022-08, with the labels that each got.

#552 Update GitOps Service resources to latest from main branch
  components/gitops/staging/argo-cd.yaml
  components/gitops/staging/kustomization.yaml
Labels: approved

#477 Appstudio Pipelines-as-code integration
  components/build/build-service/kustomization.yaml
  components/gitops/staging/argo-cd.yaml
  hack/build/setup-pac-app.sh
  hack/build/templates/component.yaml
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm, approved

#537 PLNSRVCE-428 Add JVM build service system config
  components/build/jvm-build-service/kustomization.yaml
  components/build/jvm-build-service/system-config.yaml
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm, approved

#555 Remove accidental double up
  hack/preview.sh
Labels: lgtm

#559 Print yaml of failed application when conditions are empty, do not fail on Progressing
  hack/preview.sh
Labels: approved

#557 Scripts cleanup and documentation update
  README.md
  components/authentication/view-build-service.yaml
  components/build/README.md
  components/build/clustertasks/0-permissions.yaml
  components/build/infra-deployments-ci/kustomization.yaml
  components/build/infra-deployments-ci/namespace.yaml
  components/build/infra-deployments-ci/pipelines-as-code.yaml
  components/build/infra-deployments-ci/pvc.yaml
  components/build/kustomization.yaml
  components/gitops/README.md
  hack/bootstrap-cluster.sh
  hack/build/analyze-devfile.sh
  hack/build/build-deploy.sh
  hack/build/build-quay.sh
  hack/build/build-via-appstudio.sh
  hack/build/build.sh
  hack/build/deploy-this-build.sh
  hack/build/deploy.sh
  hack/build/ls-build.sh
  hack/build/ls-builds.sh
  hack/build/m2-builds.sh
  hack/build/package-bundle.sh
  hack/build/poll-build.sh
  hack/build/prune-builds-loop.sh
  hack/build/prune-builds.sh
  hack/build/quick-noop-build.sh
  hack/build/repo-to-pipeline.sh
  hack/build/templates/component.yaml
  hack/build/templates/default-build-bundle.yaml
  hack/build/test-known-build.sh
  hack/build/utils/check-repo.sh
  hack/build/utils/cleanup-pvc.sh
  hack/build/utils/install-pipelines.sh
  hack/build/utils/install-pvc.sh
  hack/build/utils/install-sa.sh
  hack/build/utils/install-secrets.sh
  hack/build/utils/ls-all-my-repos.sh
  hack/build/utils/show-pvc.sh
  hack/development-mode.sh
  hack/preview-template.env
  hack/setup/prepare-has.sh
  hack/upstream-mode.sh
  hack/util-set-development-repos.sh
Labels: approved

#553 update SPI
  components/spi/config-patch.json
  components/spi/insecuretls-patch.json
  components/spi/kustomization.yaml
  components/spi/oauth-service-deployment-patch.json
  components/spi/vault/kustomization.yaml
  components/spi/vault/vault_role.yaml
  components/spi/vault/vault_rolebinding.yaml
  hack/preview.sh
  hack/util-set-spi-vault-host.sh
Labels: lgtm, approved

#575 Spi update 0.7.2
  components/spi/kustomization.yaml
  components/spi/vault/kustomization.yaml
Labels: lgtm, approved

#586 added part-of label on spi-oauth-route
  components/spi/oauth_route.yaml
Labels: lgtm, approved

#587 Update PipelinesAsCode to v0.11.1
  components/build/pipelines-as-code/kustomization.yaml
Labels: lgtm, approved

#588 Grant Enterprise Contract to view e2e namespace
  components/authentication/view-e2e-tests.yaml
Labels: lgtm, approved

#589 Un-skip Enterprise Contract e2e tests
  .ci/oci-e2e-deployment.sh
Labels: lgtm, approved

#590 Add PaC webhook support
  components/build/README.md
  hack/build/build-via-appstudio.sh
  hack/build/setup-pac-app.sh
  hack/build/setup-pac-integration.sh
  hack/preview-template.env
  hack/preview.sh
Labels: approved

#568 gitops: remove unused dbschema-config-map
  components/gitops/staging/dbschema-config-map.yaml
Labels: approved

#579 remove cache instance in jvm-build-service namespace
  components/build/jvm-build-service/kustomization.yaml
Labels: lgtm, approved

#601 chore: Add authentication to the Quality Dashboard
  components/quality-dashboard/OWNERS
  components/quality-dashboard/backend/deployment.yaml
  components/quality-dashboard/backend/route.yaml
  components/quality-dashboard/backend/service.yaml
  components/quality-dashboard/frontend/deployment.yaml
  components/quality-dashboard/frontend/kustomization.yaml
  components/quality-dashboard/frontend/route.yaml
  components/quality-dashboard/frontend/service-account.yaml
  components/quality-dashboard/frontend/service.yaml
  hack/util-set-quality-dashboard-backend-route.sh
Labels: lgtm, approved

#619 fix: Labels for frontend deployment
  components/quality-dashboard/frontend/deployment.yaml
  components/quality-dashboard/frontend/service.yaml
Labels: lgtm, approved

#625 fix: Quality Dashboard frontend Labels
  components/quality-dashboard/frontend/deployment.yaml
Labels: lgtm, approved

#627 update SPI
  components/spi/kustomization.yaml
  components/spi/vault/kustomization.yaml
Labels: lgtm, approved

#616 fix end-to-end-demo.sh to use verify-enterprise-contract-v2
  hack/chains/end-to-end-demo.sh
Labels: lgtm, approved

#629 Add builder image tags to config
  components/build/jvm-build-service/system-config.yaml
Labels: lgtm, approved

#563 Add observability stack configuration for appstudio
  .gitignore
  README.md
  hack/monitoring-template.env
  hack/monitoring/configure_grafana.yaml
  hack/monitoring/configure_prometheus.yaml
  hack/monitoring/grafanadashboard_sandbox_usage.yaml
  hack/monitoring/grafanadatasource_prometheus.yaml
  hack/monitoring/install_grafana.yaml
  hack/monitoring/install_prometheus.yaml
  hack/monitoring/prometheus_servicemonitors.yaml
  hack/setup_observability.sh
Labels: lgtm, approved

#634 Downgrade PaC to v1.10.2
  components/build/pipelines-as-code/kustomization.yaml
Labels: approved

#636 Force sync of chains-ca-cert secret
  components/build/tekton-chains/chains-secrets-config.yaml
Labels: lgtm, approved

#605 Add Tekton Result build configuration for HACBS
  components/build/tekton-results/.tekton/kustomization.yaml
  components/build/tekton-results/.tekton/pipelines-as-code.yaml
  components/build/tekton-results/.tekton/pvc.yaml
  components/build/tekton-results/kustomization.yaml
Labels: ok-to-test, approved

#653 add quotes around $CRCBINARY
  hack/setup/prepare-crc.sh
Labels: lgtm, approved

#639 Introduced SPI operator ServiceMonitor
  components/spi/kustomization.yaml
  components/spi/vault/kustomization.yaml
  hack/monitoring/prometheus_servicemonitors.yaml
Labels: lgtm, approved

#661 Allow access tekton-pipelines to shared secret
  components/authentication/build-ci.yaml
  components/build/shared-resources/shared-resources-components.yaml
  components/build/tekton-results/.tekton/kustomization.yaml
  components/build/tekton-results/.tekton/serviceaccount.yaml
Labels: lgtm, approved

#648 integration-service and release-service update
  components/integration/kustomization.yaml
  components/release/kustomization.yaml
Labels: lgtm, approved

#650 PLNSRVCE-624: set hacbs tekton bundle key
  components/build/README.md
  components/build/build-service/kustomization.yaml
  components/build/kustomization.yaml
  components/has/kustomization.yaml
Labels: lgtm, approved

#667 update rbac for refactor of release links
  components/authentication/tenants/shbose.yaml
Labels: approved

#669 Add rbac for Environments
  components/authentication/tenants/shbose.yaml
Labels: lgtm, approved

#668 Grant rbean tekton-triggers-admin
  components/authentication/tenants/rbean.yaml
Labels: lgtm, approved

#670 auth: Fix link to files
  components/authorization/cluster/kustomization.yaml
  components/authorization/kcp/kustomization.yaml
Labels: lgtm, approved

#671 fix: path to components/authorization/cluster
  argo-cd-apps/base/authorization-in-cluster.yaml
Labels: lgtm, approved

#672 fix: authentication -> authorization
  argo-cd-apps/base/authorization-in-cluster.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
Labels: lgtm, approved

#674 fix: naming of CRs & CRBs
  components/authorization/cluster/everyone-view.yaml
  components/authorization/cluster/kustomization.yaml
  components/authorization/kcp/kustomization.yaml
  components/authorization/kcp/members-view-everything.yaml
  components/authorization/kcp/view-everything.yaml
Labels: lgtm, approved

#673 drop obsolete development-mode.sh script
  hack/development-mode.sh
Labels: lgtm, approved

#678 Update members-view-everything.yaml
  components/authorization/kcp/members-view-everything.yaml
Labels: lgtm, needs-ok-to-test
