Repository redhat-appstudio/infra-deployments, pull requests merged in 2022-03, with the labels that each got.

#134 Remove kustomize command dependency
  README.md
  hack/destroy-cluster.sh
Labels: lgtm

#130 Tekton ci for service provider integration operator repo
  components/spi/.tekton/event-listener.yaml
  components/spi/.tekton/kustomization.yaml
  components/spi/.tekton/pipelines-as-code.yaml
  components/spi/.tekton/pvc.yaml
  components/spi/.tekton/serviceaccount.yaml
  components/spi/.tekton/trigger-template.yaml
  components/spi/.tekton/webhook-route.yaml
  components/spi/kustomization.yaml
Labels: lgtm

#140 HAS: App labels, build pv subpath, build resources in gitops repo
  components/has/kustomization.yaml
Labels: lgtm

#142 Update directory in README
  README.md
Labels: lgtm

#145 Refresh HAS in staging to pull in GitOps repo visibility changes
  components/has/kustomization.yaml
Labels: lgtm

#147 Fix: Create missing namespace for tekton-resutls
  components/build/tekton-results/kustomization.yaml
  components/build/tekton-results/tekton-pipelines-namespace.yaml
Labels: lgtm

#139 Avoid installation of multiple openshift-gitops for new clusters
  openshift-gitops/subscription-openshift-gitops.yaml
Labels: lgtm

#154 change PaC to latest version
  components/build/pipelines-as-code/kustomization.yaml
Labels: lgtm

#146 Preview mode: fix HAS secret creation, use it by ci
  .ci/oci-e2e-deployment.sh
  hack/util-set-github-org
Labels: lgtm

#152 dynamic support for openssl.cnf location
  hack/bootstrap-cluster.sh
Labels: lgtm, needs-ok-to-test

#156 Switch to 5864c77a3d1701618d358fd8fd0b53f38226bd49
  components/has/kustomization.yaml
Labels: lgtm

#159 Fix: Add e2e-tests to app-of-apps.
  argo-cd-apps/base/e2e-tests.yaml
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
Labels: lgtm

#160 Fix: Add missing route for e2e-tests event listener.
  components/e2e-tests/.tekton/kustomization.yaml
  components/e2e-tests/.tekton/webhook-route.yaml
Labels: lgtm

#158 Allow argoCD manage tekton-pipelines namespace
  components/build/tekton-results/allow-argocd-to-manage.yaml
  components/build/tekton-results/kustomization.yaml
Labels: lgtm

#162 Update HAS to f9bd765925c2cc968701f236ab13892ef17a7e58
  components/has/kustomization.yaml
Labels: lgtm

#166 Preview mode: set docker.io globally
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm

#163 Add release component
  argo-cd-apps/base/kustomization.yaml
  argo-cd-apps/base/release.yaml
  argo-cd-apps/overlays/development/repo-overlay.yaml
  components/release/allow-argocd-to-manage.yaml
  components/release/argocd-permissions.yaml
  components/release/kustomization.yaml
  components/release/manager_resources_patch.yaml
Labels: lgtm

#167 Update HAS to include CDQ w/Alizer
  components/has/kustomization.yaml
Labels: lgtm

#164 Tekton chains support and related scripts
  .gitignore
  README.md
  components/authentication/build-ci.yaml
  components/build/README.md
  components/build/kustomization.yaml
  components/build/tekton-chains/chains-certs.yaml
  components/build/tekton-chains/chains-config.yaml
  components/build/tekton-chains/chains-controller-cert.yaml
  components/build/tekton-chains/kustomization.yaml
  components/build/tekton-chains/security-context-fix.yaml
  hack/chains/README.md
  hack/chains/_helpers.sh
  hack/chains/check-pipelinerun.sh
  hack/chains/check-taskrun.sh
  hack/chains/config.sh
  hack/chains/cosign-verify-image.sh
  hack/chains/create-signing-secret.sh
  hack/chains/default-pipelines-demo.sh
  hack/chains/gitops-sync.sh
  hack/chains/inspect-pipeline-run.sh
  hack/chains/kaniko-cosign-verify.sh
  hack/chains/kaniko-demo.sh
  hack/chains/pipeline-quay-demo.sh
  hack/chains/pipeline-quay-demo.yaml
  hack/chains/rekor-verify-taskrun.sh
  hack/chains/simple-demo.sh
  hack/chains/trust-local-cert.sh
  hack/destroy-cluster.sh
Labels: lgtm, ok-to-test

#176 Update HAS to ebf7fed9ab85eae3ce2736f089886594d5765a39
  components/has/kustomization.yaml
Labels: lgtm

#177 Contract team view permission for tekton-chains
  components/authentication/view-build-service.yaml
Labels: ok-to-test

#175 Add brunoapimentel to view HAS
  components/authentication/view-has.yaml
Labels: ok-to-test

#183 Signature verification for in-toto via verify-blob
  hack/chains/check-taskrun.sh
Labels: lgtm, ok-to-test

#182 Add service CA to the chains-ca-cert ConfigMap
  components/build/tekton-chains/chains-certs.yaml
Labels: lgtm, ok-to-test

#184 Build definitions update
  components/build/.tekton/trigger-template.yaml
  components/build/kustomization.yaml
  components/e2e-tests/.tekton/trigger-template.yaml
  components/gitops/.tekton/trigger-template.yaml
  components/has/.tekton/trigger-template.yaml
  components/spi/.tekton/trigger-template.yaml
  hack/build/templates/default-build-bundle.yaml
  hack/chains/default-pipelines-demo.sh
Labels: lgtm

#188 Misc small chains improvements
  hack/chains/README.md
  hack/chains/config.sh
  hack/chains/create-signing-secret.sh
  hack/chains/default-pipelines-demo.sh
  hack/chains/kaniko-cosign-verify.sh
  hack/chains/kaniko-demo.sh
  hack/chains/nice-logs.sh
  hack/chains/rekor-image-lookup.sh
  hack/chains/rekor-verify-taskrun.sh
Labels: ok-to-test

#192 HACBS-60 - Add support for local cluster rekor
  hack/chains/README.md
  hack/chains/config.sh
  hack/chains/deploy-local-rekor.sh
  hack/chains/deploy-local-rekor.tpl
Labels: ok-to-test

#196 Support custom rekor-server in image lookup
  hack/chains/rekor-image-lookup.sh
  hack/chains/rekor-verify-taskrun.sh
Labels: lgtm, needs-ok-to-test

#210 Fix: ci stuck on waiting for completion of hook batch/Job/tekton-chai…
  components/build/tekton-chains/chains-secrets-config.yaml
Labels: lgtm

#203 Fix script to work on Mac without realpath tool
  hack/bootstrap-cluster.sh
Labels: needs-ok-to-test

#127 Added automated pre-requisite installation for fedora and ubuntu
  hack/setup/debian-based.sh
  hack/setup/install-pre-req.sh
  hack/setup/macos-based.sh
  hack/setup/prepare-crc.sh
  hack/setup/prepare-has.sh
  hack/setup/redhat-based.sh
Labels: lgtm, needs-ok-to-test

#205 Add view ClusterRole for QE team to e2e-tests namespace.
  components/authentication/kustomization.yaml
  components/authentication/view-e2e-tests.yaml
Labels: lgtm

#216 update SPI to increase memory limit
  components/spi/kustomization.yaml
Labels: lgtm

#219 Cleanup bootstrap
  README.md
  hack/reduce-gitops-cpu-requests.sh
  hack/setup/install-pre-req.sh
Labels: lgtm

#220 update SPI operator image to 0.4.1
  components/spi/kustomization.yaml
Labels: lgtm

#221 revert spi to 0.4.0
  components/spi/kustomization.yaml
Labels: lgtm

#222 update SPI operator to 0.4.2
  components/spi/kustomization.yaml
Labels: lgtm

#135 Add pvc-cleaner commonent.
  components/build/kustomization.yaml
  components/build/pvc-cleaner/gitops/kustomization.yaml
  components/build/pvc-cleaner/has/kustomization.yaml
  components/build/pvc-cleaner/pipeline-applications/kustomization.yaml
  hack/build/utils/show-pvc.sh
Labels: lgtm

#197 Demo script for running in-cluster cosign tasks
  hack/chains/kaniko-cosign-verify.sh
Labels: needs-ok-to-test, do-not-merge/work-in-progress
