Repository redhat-appstudio/infra-deployments, pull requests merged in 2023-11, with the labels that each got.

#2668 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#2669 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#2662 feat(STONEINTG-536): add 2 panels for SLO 6
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#2665 Update Pipeline Service in production
  components/pipeline-service/production/base/kustomization.yaml
Labels: lgtm, approved

#2674 feat(STONEINTG-535): adding one SLI panel
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#2676 Remove quality dashboard
  argo-cd-apps/base/quality-dashboard/kustomization.yaml
  argo-cd-apps/base/quality-dashboard/quality-dashboard.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/staging/kustomization.yaml
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
  components/quality-dashboard/OWNERS
  components/quality-dashboard/base/backend/kustomization.yaml
  components/quality-dashboard/base/frontend/kustomization.yaml
  components/quality-dashboard/base/kustomization.yaml
  components/quality-dashboard/base/rbac/kustomization.yaml
  components/quality-dashboard/base/rbac/quality-dashboard.yaml
  components/quality-dashboard/development/kustomization.yaml
  components/quality-dashboard/staging/external-secrets/kustomization.yaml
  components/quality-dashboard/staging/external-secrets/quality-dashboard-auth.yaml
  components/quality-dashboard/staging/external-secrets/quality-dashboard-secrets.yaml
  components/quality-dashboard/staging/kustomization.yaml
  docs/_data/navigation.yml
  docs/misc/quality-dashboard.md
  hack/bootstrap-host-cluster.sh
  hack/destroy-cluster.sh
  hack/secret-creator/create-quality-dashboard-secrets.sh
Labels: approved

#2677 doc(RHTAPWATCH-554): troubleshooting missing metrics and labels
  components/monitoring/prometheus/README.md
Labels: approved

#2678 fix(RHTAPWATCH-561): remove servicemonitor namespace limitations
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#2681 RHTAPBUGS-937 explictly use the image SPI
  components/jvm-build-service/base/operator_env_patch.yaml
Labels: lgtm, approved

#2683 managed-gitops: Cherry pick #2653 to staging, update components/gitops/staging/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#2692 feat(RHTAPREL-675): ignore differences in releaseplans (#2684)
  argo-cd-apps/base/tenants-config/tenants-config.yaml
Labels: lgtm, approved

#2693 Bump vm size for ephemeral arm multi-platform builds
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#2695 tell ArgoCD to respect the ignoreDifferences
  argo-cd-apps/base/tenants-config/tenants-config.yaml
Labels: lgtm, approved

#2704 Promote release-service from development to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#2703 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#2689 [Managed-Gitops] Add metrics.
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#2708 Add Grafana dashboard for remote secret metrics
  components/monitoring/grafana/base/dashboards/spi/dashboard.yaml
  components/monitoring/grafana/base/dashboards/spi/kustomization.yaml
Labels: lgtm, approved

#2714 Fix RemoteSecret Grafana dashboard datasources variable
  components/monitoring/grafana/base/dashboards/spi/kustomization.yaml
Labels: lgtm, approved

#2715 Promote release-service from development to production and staging
  components/release/production/kustomization.yaml
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#2717 Remove auto-update. Tide will take care of updating pr with main in tests
  .github/workflows/auto-update.yml
Labels: lgtm, approved

#2710 add rbac to allow monitoring of cluster health
  components/pipeline-service/base/rbac/cluster-role/pipeline-service-sre.yaml
Labels: lgtm, approved

#2691 Adding manifests for backing up RHTAP in staging environments through…
  argo-cd-apps/base/member/infra-deployments/backup/backup.yaml
  argo-cd-apps/base/member/infra-deployments/backup/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/production/delete-applications.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
  components/backup/base/external-secret.yaml
  components/backup/base/kustomization.yaml
  components/backup/staging/stone-stg-m01/backup-stone-stg-m01.yaml
  components/backup/staging/stone-stg-m01/kustomization.yaml
  components/backup/staging/stone-stg-rh01/backup-stone-stg-rh01.yaml
  components/backup/staging/stone-stg-rh01/kustomization.yaml
  components/cluster-secret-store/base/appsre-vault-secret-store.yml
Labels: lgtm, ok-to-test, approved

#2723 Fix backup application path
  argo-cd-apps/base/member/infra-deployments/backup/backup.yaml
Labels: lgtm, approved

#2729 Formatting s3-bucket-credentials secret through ExternalSecret/s3-buc…
  components/backup/base/external-secret.yaml
Labels: lgtm, needs-ok-to-test, approved

#2732 turn on metrics exporter trace in dev/stage
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/development/metrics-exporter-trace.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/metrics-exporter-trace.yaml
Labels: lgtm, approved

#2699 Improve development documentation
  README.md
  docs/development/deployment.md
  hack/preview-template.env
Labels: lgtm, approved

#2709 Update BuildPipelineSelector to new syntax
  components/build-service/base/build-pipeline-selectors/build-pipeline-selector.yaml
Labels: lgtm, approved

#2728 Adding namespace definition for backup component
  components/backup/base/kustomization.yaml
  components/backup/base/namespace.yaml
Labels: lgtm, ok-to-test, approved

#2751 bump prod pipeline service level to what we have in staging
  components/pipeline-service/production/base/kustomization.yaml
Labels: lgtm, approved

#2707 STONEBLD-1869 Deploy the OTP service in production
  components/multi-platform-controller/base/kustomization.yaml
  components/multi-platform-controller/staging/kustomization.yaml
Labels: lgtm, approved

#2744 Set Image Controller quay token refresh interval to 15 minutes
  components/image-controller/base/external-secrets/quaytoken.yaml
Labels: lgtm, approved

#2760 Adding S3 buckets definitions for production environment backup
  argo-cd-apps/overlays/production/delete-applications.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
  components/backup/production/stone-prd-m01/backup-stone-prd-m01.yaml
  components/backup/production/stone-prd-m01/kustomization.yaml
  components/backup/production/stone-prd-rh01/backup-stone-prd-rh01.yaml
  components/backup/production/stone-prd-rh01/kustomization.yaml
Labels: lgtm, approved

#2753 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#2766 Set tekton-ci quay token refresh interval to 15 minutes
  components/tekton-ci/base/external-secrets/quay-push-secret.yaml
Labels: lgtm, approved

#2762 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#2774 Fix remote-secret image name
  hack/preview.sh
Labels: lgtm, approved

#2770 managed-gitops: cherry pick #2686 to staging, update components/gitops/staging/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#2783 Promote SPI/RemoteSecret from staging to prod
  components/remote-secret-controller/overlays/production/base/kustomization.yaml
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#2784 chore(integration-svc): update grafana dashboard
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#2765 feat(STONEINTG-682): add base/overlay files for integration
  argo-cd-apps/base/member/infra-deployments/integration/integration.yaml
  argo-cd-apps/base/member/infra-deployments/integration/kustomization.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
  components/integration/base/allow-argocd-to-manage.yaml
  components/integration/base/argocd-permissions.yaml
  components/integration/base/integration.yaml
  components/integration/base/kustomization.yaml
  components/integration/development/kustomization.yaml
  components/integration/k-components/manager-resources-patch/kustomization.yaml
  components/integration/k-components/manager-resources-patch/manager_resources_patch.yaml
  components/integration/production/kustomization.yaml
  components/integration/staging/kustomization.yaml
  hack/preview.sh
Labels: lgtm, approved

#2790 Add Build Team representatives into global OWNERS
  OWNERS
Labels: lgtm, approved

#2793 Simplify backup ApplicationSet generators
  argo-cd-apps/base/member/infra-deployments/backup/backup.yaml
  argo-cd-apps/base/member/infra-deployments/backup/kustomization.yaml
Labels: lgtm, approved

#2797 Revert "Simplify backup ApplicationSet generators"
  argo-cd-apps/base/member/infra-deployments/backup/backup.yaml
  argo-cd-apps/base/member/infra-deployments/backup/kustomization.yaml
Labels: lgtm, approved

#2383 pipeline service gating promotion to staging poc
  .tekton/hack/check-pr-label.py
  .tekton/hack/get-component-name.py
  .tekton/hack/get-git-token.py
  .tekton/hack/merge-pr.py
  .tekton/hack/remove-pr-label.py
  .tekton/hack/update-argocd-app-revision.sh
  .tekton/pipeline/rhtap-staging-e2e.yaml
  .tekton/rhtap-staging-e2e-ci.yaml
  .tekton/tasks/check-pr-label.yaml
  .tekton/tasks/check-pr-rebase-label.yaml
  .tekton/tasks/component-app-name.yaml
  .tekton/tasks/get-git-token.yaml
  .tekton/tasks/get-pr-modified-files.yaml
  .tekton/tasks/merge-pr.yaml
  .tekton/tasks/rebase-pr.yaml
  .tekton/tasks/remove-pr-label.yaml
  .tekton/tasks/replace-revision.yaml
  .tekton/tasks/revert-replace-revision.yaml
  .tekton/tasks/verify-smoke-e2e.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/stone-prd-m01/resources/tekton-results-s3-secret-path.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/kustomization.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/tekton-results-s3-secret-path.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/kustomization.yaml
  components/pipeline-service/staging/stone-stg-m01/resources/kustomization.yaml
  components/pipeline-service/staging/stone-stg-m01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/staging/stone-stg-m01/resources/tekton-results-s3-secret-path.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/kustomization.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/kustomization.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/tekton-results-s3-secret-path.yaml
  staging-app.yaml
Labels: lgtm, approved

#2799 Promote integration-service from staging to production
  components/integration/production/kustomization.yaml
Labels: lgtm, approved

#2800 Add quay-push-secret to build-templates-e2e namespace in stage and prod
  components/build-templates/production/e2e-quay-push-secret.yaml
  components/build-templates/production/kustomization.yaml
  components/build-templates/staging/e2e-quay-push-secret.yaml
  components/build-templates/staging/kustomization.yaml
Labels: lgtm, approved

#2802 feat: Added more graphs to perf dashboard and organized it to rows
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, approved

#2807 enable mfrancisc to view spacebindingrequests
  components/sandbox/base/rbac/view-spacebindingrequests.yaml
Labels: lgtm, approved

#2810 Add admins for build-templates-e2e namespace
  components/build-templates/base/e2e/role.yaml
  components/build-templates/base/e2e/rolebinding.yaml
Labels: lgtm, approved

#2795 SVPI-683 - Set Explicit TOKENSTORAGE Configuration to 'vault' in E2E Tests and SVPI-690 - Set Explicit TOKENSTORAGE Configuration to 'aws' for stage/prod
  components/spi/overlays/development/config-patch.json
  components/spi/overlays/production/base/config-patch.json
  components/spi/overlays/staging/base/config-patch.json
Labels: lgtm, approved

#2813 Link quay push secret to the SA in build-templates-e2e namespace
  components/build-templates/base/e2e/kustomization.yaml
  components/build-templates/base/e2e/rolebinding.yaml
  components/build-templates/base/e2e/serviceaccount.yaml
Labels: lgtm, approved

#2819 Promote SPI/RemoteSecret from staging to prod
  components/remote-secret-controller/overlays/production/base/kustomization.yaml
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#2821 Remove SA resource from base
  components/build-templates/base/e2e/kustomization.yaml
  components/build-templates/production/kustomization.yaml
  components/build-templates/production/serviceaccount.yaml
  components/build-templates/staging/kustomization.yaml
  components/build-templates/staging/serviceaccount.yaml
Labels: lgtm, approved

#2824 Add internalrequests to view-appstudio
  components/authentication/base/everyone-can-view.yaml
Labels: lgtm, approved

#2816 Add podAntiAffinity rules
  components/has/k-components/replicas-patch/replicas_patch.yaml
Labels: lgtm, approved

#2808 Install oadp operator in stg-rh01 cluster
  components/backup/base/oadp/dpa.yaml
  components/backup/base/oadp/install-oadp.yaml
  components/backup/base/oadp/kustomization.yaml
  components/backup/staging/stone-stg-rh01/dpa-bucket-patch.yaml
  components/backup/staging/stone-stg-rh01/dpa-kmskeyid-patch.yaml
  components/backup/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#2823 Promote integration-service from staging to production
  components/integration/production/kustomization.yaml
Labels: lgtm, approved

#2832 chore(integration): update to the latest grafana dashboard
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#2831 Fix installation order of backup components
  components/backup/base/external-secret.yaml
  components/backup/base/oadp/install-oadp.yaml
Labels: lgtm, approved

#2840 Promote SPI/RemoteSecret from staging to prod
  components/remote-secret-controller/overlays/production/base/kustomization.yaml
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#2727 fix(STONEINTG-608): create secret for pac used by integration-service
  components/integration/base/external-secrets/kustomization.yaml
  components/integration/base/external-secrets/pipelines-as-code-secret.yaml
  components/integration/staging/kustomization.yaml
  hack/build/setup-pac-integration.sh
Labels: lgtm, approved

#2836 build-templates-e2e: set service account namespace
  components/build-templates/production/e2e-serviceaccount.yaml
  components/build-templates/production/kustomization.yaml
  components/build-templates/staging/e2e-serviceaccount.yaml
  components/build-templates/staging/kustomization.yaml
  components/build-templates/staging/serviceaccount.yaml
Labels: lgtm, approved

#2842 Promote integration-service from staging to production
  components/integration/production/kustomization.yaml
Labels: lgtm, approved

#2847 chore(RHTAPWATCH-580): deploy prometheus exporter from o11y
  components/monitoring/grafana/base/kustomization.yaml
Labels: lgtm, approved

#2849 PLNSRVCE-1537: add new combined/filtered pipeline service alert metrics to app sre in-cluster prometheus list
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved, jira/valid-reference
