Repository redhat-appstudio/infra-deployments, pull requests merged in 2023-04, with the labels that each got.

#1608 chore(RHTAP-687): Don't prune local cluster secret
  argo-cd-apps/base/local-cluster-secret/host-on-local-cluster/kustomization.yaml
Labels: approved

#1610 chore(RHTAP-687): Remove local cluster secret from stage
  argo-cd-apps/overlays/staging/kustomization.yaml
Labels: approved

#1612 chore(RHTAP-687): Disable autosync on staging
  argo-cd-apps/k-components/disable-auto-sync/disable-auto-sync.yaml
  argo-cd-apps/k-components/disable-auto-sync/kustomization.yaml
  argo-cd-apps/overlays/staging/kustomization.yaml
Labels: approved

#1617 chore(RHTAP-687): Enable autosync on staging
  argo-cd-apps/overlays/staging/kustomization.yaml
Labels: approved

#1618 chore(RHTAP-687): Disable autosync on production
  argo-cd-apps/overlays/production/kustomization.yaml
Labels: approved

#1621 chore(RHTAP-687): Remove local cluster secret from prod
  argo-cd-apps/overlays/production/kustomization.yaml
Labels: approved

#1615 update quality dashboard
  components/quality-dashboard/base/backend/kustomization.yaml
  components/quality-dashboard/base/frontend/kustomization.yaml
Labels: approved

#1622 chore(RHTAP-687): Enable autosync on production
  argo-cd-apps/overlays/production/kustomization.yaml
Labels: approved

#1623 Remove ArgoCD finalizer from app-of-appsets
  argo-cd-apps/app-of-app-sets/base/all-application-sets.yaml
Labels: approved

#1583 chore(STONEO11Y-83): add template service monitor
  components/monitoring/README.md
  components/monitoring/prometheus/development/dummy-service-service-monitor.yaml
  components/monitoring/prometheus/development/dummy-service.yaml
  components/monitoring/prometheus/development/kustomization.yaml
Labels: lgtm, approved

#1619 pipeline-service: add approvers from different TZ
  components/pipeline-service/OWNERS
Labels: lgtm, approved

#1592 Bump pipeline-service version
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: approved

#1624 update quality dashboard
  components/quality-dashboard/base/backend/kustomization.yaml
  components/quality-dashboard/base/frontend/kustomization.yaml
Labels: approved

#1611 Add scheme to endpoint value of s3 secret
  components/pipeline-service/base/external-secrets/tekton-results/tekton-results-s3.yaml
Labels: approved

#1629 Revert "Bump pipeline-service version"
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#1640 prepare spi prod with aws secrets manager credentials secrets
  components/spi/overlays/production/base/kustomization.yaml
  components/spi/overlays/production/base/spi-aws-credentials-external-secret.yaml
  components/spi/overlays/production/stone-prd-m01/kustomization.yaml
  components/spi/overlays/production/stone-prd-m01/spi-aws-credentials-path-patch.yaml
  components/spi/overlays/production/stone-prd-rh01/kustomization.yaml
  components/spi/overlays/production/stone-prd-rh01/spi-aws-credentials-path-patch.yaml
Labels: lgtm, approved

#1644 feat: Changes related to openshift-ci onboarding
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm, approved

#1655 managed-gitops update: staging and dev
  components/gitops/development/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#1658 Update the servicemonitor file for pipeline-service
  components/monitoring/prometheus/base/servicemonitors/pipeline-service.yaml
Labels: lgtm, approved

#1670 Update pipeline-service component - dev & staging
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#1672 plnsvc: update path of vault credentials for s3 in staging
  components/pipeline-service/staging/stone-stg-m01/tekton-results-s3-secret-path.yaml
  components/pipeline-service/staging/stone-stg-rh01/tekton-results-s3-secret-path.yaml
Labels: lgtm, approved

#1643 Configure Grafana with OpenShift login
  components/monitoring/grafana/README.md
  components/monitoring/grafana/base/grafana-app.yaml
Labels: lgtm, approved

#1676 RHTAP-825: fix grafana deployment
  components/monitoring/grafana/base/kustomization.yaml
Labels: lgtm, approved, jira/valid-reference

#1678 feat(STONEO11Y-163): Grafana dashboards
  argo-cd-apps/overlays/development/kustomization.yaml
  components/monitoring/grafana/base/build-service/dashboard.yaml
  components/monitoring/grafana/base/build-service/kustomization.yaml
  components/monitoring/grafana/base/dora-metrics/dashboard.yaml
  components/monitoring/grafana/base/dora-metrics/kustomization.yaml
  components/monitoring/grafana/base/has/dashboard.yaml
  components/monitoring/grafana/base/has/kustomization.yaml
  components/monitoring/grafana/base/jvm-build-service/dashboard.yaml
  components/monitoring/grafana/base/jvm-build-service/kustomization.yaml
  components/monitoring/grafana/base/managed-gitops/dashboard.yaml
  components/monitoring/grafana/base/managed-gitops/kustomization.yaml
  components/monitoring/grafana/base/release-service/dashboard.yaml
  components/monitoring/grafana/base/release-service/kustomization.yaml
  components/monitoring/grafana/base/spi/dashboard.yaml
  components/monitoring/grafana/base/spi/kustomization.yaml
Labels: approved

#1679 Enable staging to use a different OpenShift GitOps version than prod/dev
  components/gitops/development/kustomization.yaml
  components/gitops/openshift-gitops/base/cluster-rbac/argocd-application-controller-clusterrole.yaml
  components/gitops/openshift-gitops/base/cluster-rbac/argocd-application-controller-clusterrolebinding.yaml
  components/gitops/openshift-gitops/base/cluster-rbac/argocd-server-clusterrole.yaml
  components/gitops/openshift-gitops/base/cluster-rbac/argocd-server-clusterrolebinding.yaml
  components/gitops/openshift-gitops/base/cluster-rbac/kustomization.yaml
  components/gitops/openshift-gitops/base/kustomization.yaml
  components/gitops/openshift-gitops/overlays/production-and-dev/kustomization.yaml
  components/gitops/openshift-gitops/overlays/production-and-dev/subscription-openshift-gitops.yaml
  components/gitops/openshift-gitops/overlays/staging/kustomization.yaml
  components/gitops/openshift-gitops/overlays/staging/subscription-openshift-gitops.yaml
  components/gitops/production/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
  hack/deploy-argocd.sh
  hack/destroy-cluster.sh
Labels: approved

#1689 Allow GitOps maintainers to upgrade OpenShift GitOps operator via InstallPlans
  components/authentication/base/gitops-component-maintainer.yaml
Labels: approved

#1686 Pin Grafana oauth image
  components/monitoring/grafana/base/grafana-app.yaml
Labels: approved

#1698 Deploy external-secrets operator in a dedicated ns
  components/external-secrets-operator/kustomization.yaml
  components/external-secrets-operator/operator-config.yaml
  components/external-secrets-operator/subscription.yaml
Labels: approved

#1700 chore(STONE-895): Deploy ESO on the host cluster
  argo-cd-apps/base/all-clusters/infra-deployments/external-secrets-operator/external-secrets-operator.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/external-secrets-operator/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
  components/external-secrets-operator/base/kustomization.yaml
  components/external-secrets-operator/base/operator-config.yaml
  components/external-secrets-operator/base/subscription.yaml
  components/external-secrets-operator/production/kustomization.yaml
  components/external-secrets-operator/staging/kustomization.yaml
Labels: approved

#1702 chore(STONE-895): Deploy secret store to the host clusters
  argo-cd-apps/base/all-clusters/infra-deployments/cluster-secret-store/cluster-secret-store.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/cluster-secret-store/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
Labels: approved

#1691 fix: use proper variable names
  hack/preview-template.env
  hack/preview.sh
Labels: approved

#1706 Deploy Grafana to the host cluster
  argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-grafana/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-grafana/monitoring-workload-grafana.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
Labels: approved

#1666 PLNSRVCE-1281: Update sprayproxy component for staging kustomize overlay
  components/sprayproxy/base/kustomization.yaml
  components/sprayproxy/production/kustomization.yaml
  components/sprayproxy/staging/kustomization.yaml
Labels: lgtm, approved, jira/valid-reference

#1709 Managed-gitops: apply PR #1693 latest to staging, only
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#1710 GitOps: Upgrade OpenShift GitOps up to gitops-1.8 channel
  components/gitops/openshift-gitops/overlays/production-and-dev/subscription-openshift-gitops.yaml
Labels: approved

#1708 Add a dashboard for the Migration team
  components/monitoring/grafana/base/cm-dashboard.yaml
  components/monitoring/grafana/base/kustomization.yaml
  components/monitoring/grafana/base/migration/dashboard.yaml
  components/monitoring/grafana/base/migration/kustomization.yaml
  components/monitoring/grafana/base/migration/migration-team-dashboard.json
Labels: approved

#1712 Update Migration Dashboard
  components/monitoring/grafana/base/migration/migration-team-dashboard.json
Labels: approved

#1699 Expose GH webhook secret to sprayproxy
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
  components/sprayproxy/production/kustomization.yaml
  components/sprayproxy/production/pipelines-as-code-secret.yaml
  components/sprayproxy/staging/kustomization.yaml
  components/sprayproxy/staging/pipelines-as-code-secret.yaml
Labels: approved

#1713 chore(STONEO11Y-84): Configure logging on the host clusters
  argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-logging/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
Labels: approved

#1714 chore(STONEO11Y-84): Remove openshift-operators-redhat namespace
  components/monitoring/logging/base/install-logging-operator.yaml
Labels: approved

#1715 chore(STONEO11Y-84): Don't create openshift-operators
  components/monitoring/logging/base/install-logging-operator.yaml
Labels: approved

#1668 fix: Remove unknown field retention_in_days field from ClusterLogForwarder
  components/monitoring/logging/base/configure-logging/configure-logforwarder.yaml
Labels: approved

#1718 Removing tekton-chains public key
  components/pipeline-service/public/README.md
  components/pipeline-service/public/tekton-chains-signing-secret.pub
Labels: lgtm, approved

#1719 update spi prod
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#1721 Add webhook secret to sprayproxy deployment
  components/sprayproxy/production/add-webhook-secret.yaml
  components/sprayproxy/production/kustomization.yaml
  components/sprayproxy/staging/add-webhook-secret.yaml
  components/sprayproxy/staging/kustomization.yaml
Labels: lgtm, approved

#1724 [DEVHAS-259] Increase number of replicas for HAS
  components/has/production/kustomization.yaml
  components/has/staging/kustomization.yaml
Labels: lgtm, approved

#1732 [DEHVAS-259 Redux] Use patch files to set replicas for HAS
  components/has/production/kustomization.yaml
  components/has/production/replicas_patch.yaml
  components/has/staging/kustomization.yaml
  components/has/staging/replicas_patch.yaml
Labels: lgtm, approved

#1736 [DEVHAS-272] Add HAS Service Monitor
  components/has/base/kustomization.yaml
Labels: lgtm, approved

#1743 [DEVHAS-259] Fix replicas patch for HAS in production
  components/has/production/kustomization.yaml
  components/has/staging/kustomization.yaml
Labels: lgtm, approved

#1730 Add README for integration-service
  components/integration/README.md
Labels: lgtm, approved

#1669 Fix label selector for release service service monitor
  components/monitoring/prometheus/base/servicemonitors/release-service.yaml
Labels: lgtm, approved

#1744 Add role for bouncing HAS pods after token rotation
  components/authentication/base/has-admin.yaml
  components/authentication/base/kustomization.yaml
Labels: lgtm, approved

#1745 Fixing mismatched file names in kustomize reference
  components/tekton-ci/production/kustomization.yaml
Labels: lgtm, approved

#1747 add inspect pods manifests
  components/authentication/base/inspect-pods.yaml
  components/authentication/base/kustomization.yaml
Labels: lgtm, approved
