Repository redhat-appstudio/infra-deployments, pull requests merged in 2023-08, with the labels that each got.

#2186 Fix: rename tekton-ci secret
  components/tekton-ci/base/serviceaccount.yaml
Labels: lgtm, approved

#2179 managed-gitops update
  components/gitops/production/base/kustomization.yaml
Labels: approved

#2191 fix: reinstate the o11y repo in tekton-ci
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#2189 PLNSRVCE-1350: move to openshift-pipelines 1.11 in prod (porting changes used for staging)
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/base/pipelines-as-code-namespace.yaml
  components/pipeline-service/production/base/pipelines-as-code-secret.yaml
  components/sprayproxy/production/add-backends.yml
Labels: lgtm, do-not-merge/hold, approved, jira/valid-reference

#2202 fix: pipeline-as-code namespcae to set pac app
  components/pipeline-service/production/base/kustomization.yaml
Labels: lgtm, approved

#2204 Update image-controller image
  components/image-controller/base/kustomization.yaml
Labels: lgtm, approved

#2198 chore: update release-service owners
  components/internal-services/OWNERS
  components/release/OWNERS
Labels: lgtm, approved

#2114 chore(RHTAPWATCH-376): segment-bridge member-cluster component
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/segment-bridge/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/segment-bridge/segment-bridge.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
  components/segment-bridge/OWNERS
  components/segment-bridge/README.md
  components/segment-bridge/base/kustomization.yaml
  components/segment-bridge/base/serviceaccount.yaml
  components/segment-bridge/development/kustomization.yaml
  components/segment-bridge/production/kustomization.yaml
  components/segment-bridge/staging/kustomization.yaml
Labels: lgtm, approved

#2201 Update sprayproxy prod
  components/sprayproxy/production/kustomization.yaml
Labels: lgtm, approved

#2215 Use new namespace for Tekton Chains public key
  components/enterprise-contract/ecp.yaml
Labels: lgtm, approved

#2054 chore(RHTAPWATCH-351): segment-bridge component deployment
  argo-cd-apps/base/host/kustomization.yaml
  argo-cd-apps/base/host/segment-bridge/kustomization.yaml
  argo-cd-apps/base/host/segment-bridge/segment-bridge-host.yaml
  argo-cd-apps/base/member/infra-deployments/segment-bridge/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/segment-bridge/segment-bridge-member.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  components/authentication/base/segment-bridge.yaml
  components/segment-bridge/README.md
  components/segment-bridge/base/kustomization.yaml
  components/segment-bridge/base/serviceaccount.yaml
Labels: lgtm, approved

#2223 added steps to add a new service in RHTAP
  docs/deployment/extending-the-service.md
Labels: lgtm, ok-to-test, approved

#2226 fix: gitops has been removed from authentication
  components/authentication/base/kustomization.yaml
Labels: lgtm, approved

#2227 chore: segment-bridge on authentication component
  components/authentication/base/kustomization.yaml
Labels: lgtm, approved

#2214 SVPI-567: refactor vault-init to keep keys in a specific file
  hack/spi/vault-init.sh
Labels: lgtm, approved, jira/valid-reference

#2197 feat: add kube-linter CI check
  .github/workflows/kube-linter.yaml
Labels: lgtm, approved

#2238 chore: segment-bridge has the right usersignup access
  components/authentication/base/segment-bridge.yaml
Labels: lgtm, approved

#2239 update dora metrics dashboard
  components/monitoring/grafana/base/dashboards/dora-metrics/kustomization.yaml
Labels: lgtm, approved

#2225 Update release CRs in servicerelease tenant
  ci/teams/rhtap-gitops/release.yaml
  ci/teams/rhtap-servicerelease/ec-policy.yaml
  ci/teams/rhtap-servicerelease/kustomization.yaml
  ci/teams/rhtap-servicerelease/persistent-volume-claim.yaml
  ci/teams/rhtap-servicerelease/release-pipeline-sa.yaml
  ci/teams/rhtap-servicerelease/release-service-account-build-rb.yaml
  ci/teams/rhtap-servicerelease/release-service-account-external-secrets-rb.yaml
  ci/teams/rhtap-servicerelease/release-strategy.yaml
Labels: lgtm, approved

#2207 Support Pac in ephemeral cluster to work with QE SprayProxy
  hack/build/setup-pac-integration.sh
  hack/preview-template.env
Labels: lgtm, approved

#2243 Specify namespace for ECP resource
  ci/teams/rhtap-servicerelease/ec-policy.yaml
Labels: lgtm, approved

#2244 managed-gitops: update cluster role to allow cluster maintenance of SnapshotEnvironmentBindings
  components/gitops/base/authentication/gitops-clusterroles.yaml
Labels: approved

#2237 Initial prototype of Multi Arch Controller
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/multi-arch-controller/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/multi-arch-controller/multi-arch-controller.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/production/delete-applications.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
  components/authentication/base/build.yaml
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
  components/multi-arch-controller/OWNERS
  components/multi-arch-controller/base/allow-argocd-to-manage.yaml
  components/multi-arch-controller/base/external-secrets/awskeys.yaml
  components/multi-arch-controller/base/external-secrets/kustomization.yaml
  components/multi-arch-controller/base/host-config.yaml
  components/multi-arch-controller/base/kustomization.yaml
  components/multi-arch-controller/development/kustomization.yaml
  components/multi-arch-controller/development/logs-in-console-format-cmd-arg-patch.yaml
  components/multi-arch-controller/staging/kustomization.yaml
  hack/preview.sh
Labels: lgtm, approved

#2152 stage(sandbox components): add sandbox component and edit-secrets permissions for host and member operator namespaces
  argo-cd-apps/base/host/kustomization.yaml
  argo-cd-apps/base/host/toolchain-host-operator/kustomization.yaml
  argo-cd-apps/base/host/toolchain-host-operator/toolchain-host-operator.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/toolchain-member-operator/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/toolchain-member-operator/toolchain-member-operator.yaml
  components/sandbox/OWNERS
  components/sandbox/base/kustomization.yaml
  components/sandbox/base/rbac/edit-secrets.yaml
  components/sandbox/toolchain-host-operator/staging/kustomization.yaml
  components/sandbox/toolchain-member-operator/staging/kustomization.yaml
Labels: lgtm, approved

#2257 Update multi arch controller
  components/multi-arch-controller/base/kustomization.yaml
Labels: lgtm, approved

#2263 prod(sandbox components): add edit-secrets permissions for host and member operator namespaces
  argo-cd-apps/overlays/production/kustomization.yaml
  components/sandbox/toolchain-host-operator/production/kustomization.yaml
  components/sandbox/toolchain-member-operator/production/kustomization.yaml
Labels: lgtm, approved

#2269 grant SpaceBindingRequest permissions to sandbox-sre admins
  components/authentication/base/sandbox-sre-admins.yaml
Labels: lgtm, approved

#2268 Update multi arch controller
  components/multi-arch-controller/base/kustomization.yaml
Labels: lgtm, approved

#2272 Use rhtap-service-push release pipeline
  ci/teams/rhtap-servicerelease/external-secrets/infra-deployments-pr-creator.yaml
  ci/teams/rhtap-servicerelease/external-secrets/kustomization.yaml
  ci/teams/rhtap-servicerelease/external-secrets/slack-webhook-notification-secret.yaml
  ci/teams/rhtap-servicerelease/release-build.yaml
  ci/teams/rhtap-servicerelease/release-external-secrets.yaml
  ci/teams/rhtap-servicerelease/release-strategy.yaml
Labels: lgtm, approved

#2161 Update gitops version to 1.9 in prod and dev
  components/gitops/openshift-gitops/overlays/production-and-dev/subscription-openshift-gitops.yaml
Labels: do-not-merge/hold, approved

#2280 Update PaC config staging
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/pac-config.yaml
  components/pipeline-service/staging/base/update-tekton-config-pac.yaml
Labels: lgtm, approved

#2273 Fix RBAC on prod for HAS team
  components/has/production/kustomization.yaml
Labels: lgtm, approved

#2275 fix missing external-secrets definition
  ci/teams/rhtap-servicerelease/kustomization.yaml
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: approved

#2290 Fix pullspec typo in releasestrategy
  ci/teams/rhtap-servicerelease/release-strategy.yaml
Labels: lgtm, approved

#2297 Update image-controller component
  ci/teams/rhtap-servicerelease/release-build.yaml
  components/image-controller/base/kustomization.yaml
Labels: lgtm, approved

#2258 Add jvm-build-service monitoring owners
  components/monitoring/grafana/base/dashboards/jvm-build-service/OWNERS
Labels: lgtm, approved

#2292 Fix links to RHTAP console from the PR
  components/pipeline-service/staging/base/update-tekton-config-pac.yaml
Labels: lgtm, approved

#2304 use external-secrets for pyxis
  ci/teams/rhtap-servicerelease/external-secrets/kustomization.yaml
  ci/teams/rhtap-servicerelease/external-secrets/pyxis-secret.yaml
  ci/teams/rhtap-servicerelease/release-strategy.yaml
Labels: lgtm, approved

#2285 Add PR creator secret to rhtap-build-tenant
  ci/teams/rhtap-build/external-secrets/infra-deployments-pr-creator.yaml
  ci/teams/rhtap-build/external-secrets/kustomization.yaml
  ci/teams/rhtap-build/kustomization.yaml
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: lgtm, approved

#2287 feat: openshift-ci onboarding for remotesecrets and spi
  hack/preview-template.env
  hack/preview.sh
Labels: approved

#2309 move cluster role and role bindings for Build-Service && jvm-build-se…
  components/authentication/base/build.yaml
  components/build-service/base/kustomization.yaml
  components/build-service/base/rbac/build-maintainer.yaml
  components/build-service/base/rbac/kustomization.yaml
  components/jvm-build-service/base/kustomization.yaml
  components/jvm-build-service/base/rbac/jvm-build-maintainer.yaml
  components/jvm-build-service/base/rbac/kustomization.yaml
Labels: lgtm, approved

#2313 fix: authentication is not having sandbox-sre-admins.yaml
  components/authentication/base/kustomization.yaml
Labels: approved

#2314 add support for RHEL to pre-reqs script
  hack/setup/install-pre-req.sh
Labels: needs-ok-to-test

#2279 Allow GitOps team members to access jgwest-tenant namespace where it is available
  components/gitops/production/stone-prd-m01/gitops-team-member-namespaces.yaml
  components/gitops/production/stone-prd-m01/kustomization.yaml
  components/gitops/staging/stone-stg-m01/gitops-team-member-namespaces.yaml
  components/gitops/staging/stone-stg-m01/kustomization.yaml
Labels: approved

#2312 RHTAP-1495: AppSet for RH users configurations
  argo-cd-apps/base/tenants-config/kustomization.yaml
  argo-cd-apps/base/tenants-config/tenants-config.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
Labels: lgtm, approved, jira/valid-reference

#2317 RHTAP-1495: correct typo in tenants-config
  argo-cd-apps/base/tenants-config/tenants-config.yaml
Labels: lgtm, approved, jira/valid-reference

#2321 Add RBAC to fix orphaned SpaceRequests on staging
  components/gitops/base/authentication/gitops-clusterroles.yaml
Labels: approved

#2325 Add hugares to the OWNERS file
  OWNERS
Labels: lgtm, ok-to-test, approved

#2327 Added spartidarh OWNERS
  OWNERS
Labels: lgtm, ok-to-test, approved

#2332 fix(RHTAPWATCH-456): Resolve kubelinter warnings for monitoring component
  components/monitoring/prometheus/development/dummy-service.yaml
Labels: lgtm, approved

#2333 RHTAP-1201: Add RH cluster secrets stores
  argo-cd-apps/base/cluster-secret-store-rh/cluster-secret-store-rh.yaml
  argo-cd-apps/base/cluster-secret-store-rh/kustomization.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
  components/cluster-secret-store-rh/base/appsre-stonesoup-vault-rh-secret-store.yaml
  components/cluster-secret-store-rh/base/kustomization.yaml
  components/cluster-secret-store-rh/base/rh-artifacts-bucket-writer-secret-store.yml
  components/cluster-secret-store-rh/production/approle-id-patch.yaml
  components/cluster-secret-store-rh/production/kustomization.yaml
Labels: lgtm, approved, jira/valid-reference

#2341 FRHTAP-1201: RH - Fix secret store version
  components/cluster-secret-store-rh/base/rh-artifacts-bucket-writer-secret-store.yml
Labels: approved
