Repository redhat-appstudio/infra-deployments, pull requests merged in 2023-01, with the labels that each got.

#1093 Upgrade PAC to v0.15.0
  components/pipeline-service/pipelines-as-code/kustomization.yaml
Labels: ok-to-test, approved

#1097 build-definitions - Skip checks pairing with e2e-tests
  components/build-service/build-pipeline-selector.yaml
  components/build-service/kustomization.yaml
  components/build-templates/kustomization.yaml
Labels: lgtm, approved

#1052 Add onboarding to monitoring
  components/monitoring/README.md
Labels: lgtm, approved

#1101 PLNSRVCE-885: build-selector - add FBC pipeline
  components/build-service/build-pipeline-selector.yaml
Labels: approved

#1103 Update Tekton Chains to 0.14.0
  components/pipeline-service/tekton-chains/kustomization.yaml
Labels: lgtm, approved

#1111 Use pull secret as imagePullSecret in tekton-ci
  components/tekton-ci/serviceaccount.yaml
Labels: lgtm, approved

#1113 Updated README to make it explicit and grafana oauth token non expiring
  components/monitoring/grafana/README.md
Labels: lgtm, approved

#1110 Refactor the documentation
  .ci/Readme.md
  README.md
  _config.yml
  components/build-service/README.md
  components/gitops/README.md
  components/internal-services/README.md
  components/monitoring/grafana/README.md
  components/monitoring/prometheus/README.md
  docs/_data/navigation.yml
  docs/_data/variables.yml
  docs/deployment/extending-the-service.md
  docs/deployment/observability.md
  docs/deployment/stage.md
  docs/development/argo-cd-login.png
  docs/development/deployment.md
  docs/development/pre.md
  docs/development/sandbox.md
  docs/development/spi.md
  docs/introduction/about.md
  docs/misc/faq.md
  docs/misc/quality-dashboard.md
  docs/testing/e2e-tests.md
  hack/quicklab/README.md
  index.html
Labels: lgtm, approved

#1104 Add the latest data and policy source to the ec-defaults configMap
  components/enterprise-contract/kustomization.yaml
Labels: lgtm, approved

#1112 ignore diff in imagePullSecrets in tekton-ci
  argo-cd-apps/base/tekton-ci.yaml
Labels: lgtm, approved

#1123 Add Pipeline Service team permissions
  components/authentication/build.yaml
  components/authentication/pipeline-service-sre.yaml
Labels: approved

#1116 Added metrics reader access to prometheus
  components/monitoring/prometheus/base/configure-prometheus.yaml
  components/monitoring/prometheus/base/prometheus-servicemonitors.yaml
Labels: lgtm, approved

#1115 Update ose-cli to v4.11
  components/pipeline-service/tekton-chains/chains-secrets-config.yaml
  components/pipeline-service/tekton-results/ingress-annotation-job.yaml
Labels: approved

#1125 Add tekton-chains public signing key
  components/pipeline-service/public/README.md
  components/pipeline-service/public/tekton-chains-signing-secret.pub
Labels: approved

#1126 Profiling performance-related metrics based on controller-runtime
  components/monitoring/grafana/base/dashboards/controller-runtime-controllers-detail_rev1.json
  components/monitoring/grafana/base/kustomization.yaml
Labels: lgtm, approved

#1132 Align SPI's scrape interval with other ServiceMonitors
  components/monitoring/prometheus/base/prometheus-servicemonitors.yaml
Labels: lgtm, approved

#1133 Grafana dashboard: Go Prometheus client library
  components/monitoring/grafana/base/dashboards/go-processes_rev1.json
  components/monitoring/grafana/base/kustomization.yaml
Labels: lgtm, approved

#1134 fix: buildpipelineselectors roles, rolebindings
  components/authentication/everyone-can-view.yaml
  components/build-templates/e2e/role.yaml
  components/build-templates/e2e/rolebinding.yaml
Labels: approved

#1140 Revert "Update keycloak-realm.yaml"
  components/dev-sso/keycloak-realm.yaml
Labels: approved

#1141 Increase the dev sso tokens to 2h.
  components/dev-sso/keycloak-realm.yaml
Labels: approved

#1143 Update quality dashboard images with codecov v2 api
  components/quality-dashboard/backend/kustomization.yaml
  components/quality-dashboard/frontend/kustomization.yaml
Labels: approved

#1144 Provision SPI's grafana dashboard
  components/monitoring/grafana/base/grafana-app.yaml
  components/monitoring/grafana/base/kustomization.yaml
Labels: lgtm, approved

#1137 Build services Prometheus monitor
  components/monitoring/prometheus/base/prometheus-servicemonitors.yaml
Labels: lgtm, approved

#1147 Fixes issue: mount path should be unique
  components/monitoring/grafana/base/grafana-app.yaml
Labels: approved

#1154 build-service update
  components/build-service/kustomization.yaml
Labels: lgtm, approved

#1155 Add Pipeline Service leads
  OWNERS
Labels: lgtm, approved

#1139 managed-gitops: Update gitops component to use new kustomize-based manifest organization
  components/gitops/staging/argo-cd.yaml
  components/gitops/staging/kustomization.yaml
Labels: approved

#1158 Add ServiceMonitor configuration for integration service
  components/monitoring/prometheus/base/prometheus-servicemonitors.yaml
Labels: lgtm, approved

#1149 [DEVHAS-217] create an empty gitops-repo-pruner component
  components/gitops-repo-pruner/OWNERS
  components/gitops-repo-pruner/kustomization.yaml
Labels: lgtm, approved

#1171 hotfix: Return shared snyk secret used by infra-update
  components/shared-resources/globally-shared-secrets-clusterrole.yaml
  components/shared-resources/snyk-shared-secret.yaml
Labels: approved

#1176 Add sprayproxy to tekton-ci
  components/tekton-ci/repository.yaml
Labels: approved

#1173 update components/build-service/kustomization.yaml
  components/build-service/kustomization.yaml
Labels: approved

#982 Use pipeline-service components from pipeline-service repo
  components/pipeline-service/kustomization.yaml
  components/pipeline-service/openshift-pipelines/allow-argocd-create-sa.yaml
  components/pipeline-service/openshift-pipelines/config.yaml
  components/pipeline-service/openshift-pipelines/kustomization.yaml
  components/pipeline-service/openshift-pipelines/subscription.yaml
  components/pipeline-service/pipelines-as-code/allow-argocd.yaml
  components/pipeline-service/pipelines-as-code/disable-pipelines-as-code-webhook.yaml
  components/pipeline-service/pipelines-as-code/kustomization.yaml
  components/pipeline-service/tekton-chains-controller-deployment.yaml
  components/pipeline-service/tekton-chains-controller-shared-secret.yaml
  components/pipeline-service/tekton-chains-controller-shared-secrets-rolebinding.yaml
  components/pipeline-service/tekton-chains/allow-argocd-to-manage.yaml
  components/pipeline-service/tekton-chains/chains-config.yaml
  components/pipeline-service/tekton-chains/chains-controller-deployment.yaml
  components/pipeline-service/tekton-chains/chains-secrets-config.yaml
  components/pipeline-service/tekton-chains/kustomization.yaml
  components/pipeline-service/tekton-chains/security-context-fix.yaml
  components/pipeline-service/tekton-results/allow-argocd-to-manage.yaml
  components/pipeline-service/tekton-results/allow-http2.yaml
  components/pipeline-service/tekton-results/db-execution-configmap.yaml
  components/pipeline-service/tekton-results/ingress-annotation-job.yaml
  components/pipeline-service/tekton-results/ingress-annotation-rb.yaml
  components/pipeline-service/tekton-results/ingress-annotation-role.yaml
  components/pipeline-service/tekton-results/ingress-annotation-sa.yaml
  components/pipeline-service/tekton-results/kustomization.yaml
  components/pipeline-service/tekton-results/patch-postgres-redhat-statefulset.yaml
  components/pipeline-service/tekton-results/patch-tekton-results-api-no-auth.yaml
  components/pipeline-service/tekton-results/route.yaml
  components/pipeline-service/tekton-results/tekton-pipelines-namespace.yaml
  hack/bootstrap-cluster.sh
  hack/preview.sh
Labels: approved

#1182 Remove unused tekton scripts
  components/authentication/build.yaml
  components/build-service/README.md
  hack/build/set-tkn-results.sh
Labels: approved

#1177 [DEVHAS-121] add service monitor for HAS
  components/monitoring/prometheus/base/prometheus-servicemonitors.yaml
Labels: lgtm, approved

#1186 prometheus-servicemonitors.yaml: fix typo caused by manual rebase
  components/monitoring/prometheus/base/prometheus-servicemonitors.yaml
Labels: approved

#1183 Add OWNERS to pipeline-service component
  components/pipeline-service/OWNERS
Labels: lgtm, approved

#1187 Update dora-metrics image
  components/dora-metrics/kustomization.yaml
Labels: approved

#1201 Fix tekton-chains resource limits and set a new signing-secret
  components/pipeline-service/kustomization.yaml
  components/pipeline-service/public/tekton-chains-signing-secret.pub
Labels: approved

#1193 Add default ECP resource
  components/enterprise-contract/default-ecp.yaml
  components/enterprise-contract/kustomization.yaml
Labels: lgtm, approved

#1205 Mention Enterprise Contract in the new docs
  components/enterprise-contract/README.md
  docs/_data/navigation.yml
Labels: lgtm, approved

#1160 HACBS-1606 - Dashboard for Release Service
  components/monitoring/grafana/base/grafana-app.yaml
  components/monitoring/grafana/base/kustomization.yaml
Labels: lgtm, approved

#1198 update components/build-service/kustomization.yaml
  components/build-service/kustomization.yaml
Labels: approved

#1181 Restructured servicemonitors for easy onboard
  components/monitoring/README.md
  components/monitoring/prometheus/base/configure-prometheus.yaml
  components/monitoring/prometheus/base/kustomization.yaml
  components/monitoring/prometheus/base/prometheus-servicemonitors.yaml
  components/monitoring/prometheus/base/servicemonitors/build-service.yaml
  components/monitoring/prometheus/base/servicemonitors/dora-service.yaml
  components/monitoring/prometheus/base/servicemonitors/integration-service.yaml
  components/monitoring/prometheus/base/servicemonitors/jvm-build-service.yaml
  components/monitoring/prometheus/base/servicemonitors/kustomization.yaml
  components/monitoring/prometheus/base/servicemonitors/prometheus.yaml
  components/monitoring/prometheus/base/servicemonitors/release-service.yaml
  components/monitoring/prometheus/base/servicemonitors/sandbox-host-operator.yaml
  components/monitoring/prometheus/base/servicemonitors/sandbox-member-operator.yaml
  components/monitoring/prometheus/base/servicemonitors/spi-operator.yaml
Labels: lgtm, approved

#1220 Add lcarva as EC owner and reviewer
  components/enterprise-contract/OWNERS
Labels: lgtm, approved

#1221 Add GitOps Service' Prometheus ServiceMonitors/ClusteRoleBindings
  components/monitoring/prometheus/base/servicemonitors/gitops-service.yaml
  components/monitoring/prometheus/base/servicemonitors/kustomization.yaml
Labels: approved

#1224 GitOps Service: Add Grafana dashboard JSON
  components/monitoring/grafana/base/kustomization.yaml
Labels: approved

#1216 Update pipeline-service
  components/pipeline-service/kustomization.yaml
Labels: lgtm, approved

#1248 fix: build-via-appstudio.sh - link secret
  hack/build/build-via-appstudio.sh
Labels: lgtm, approved

#1180 Added token expiration duration to readme
  components/monitoring/grafana/README.md
Labels: lgtm, approved
