Repository redhat-appstudio/infra-deployments, pull requests merged in 2023-05, with the labels that each got.

#1751 chore(RHTAPSRE-4): Deploy GSO on the host clusters
  argo-cd-apps/base/all-clusters/infra-deployments/authentication/authentication.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/authentication/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
Labels: approved

#1752 Add missing group/version in auth app
  components/authentication/base/inspect-pods.yaml
Labels: approved

#1755 [HAS] Move prometheus to staging and production overlays
  components/has/base/kustomization.yaml
  components/has/production/kustomization.yaml
  components/has/staging/kustomization.yaml
Labels: lgtm, approved

#1756 GitOps Service: staging only, update components/gitops/staging/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#1764 all permissions over secrets and SA tokens for sandbox-sre admins
  components/authentication/base/sandbox-sre-admins.yaml
Labels: lgtm, approved

#1770 add user to HAS auth role
  components/authentication/base/has.yaml
Labels: lgtm, approved

#1769 Update pipeline-service
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  hack/secret-creator/create-plnsvc-secrets.sh
Labels: lgtm, approved

#1717 chore(STONEO11Y-169): limit login to grafana
  components/monitoring/grafana/base/grafana-app.yaml
Labels: lgtm, approved

#1775 Promote pipeline-service
  components/pipeline-service/production/base/kustomization.yaml
Labels: lgtm, approved

#1766 [DEVHAS-272] Add new HAS rate limiting dashboard
  components/monitoring/grafana/base/has/dashboard.yaml
Labels: lgtm, approved

#1778 AD-82 Update Quality Dashboard backend image
  components/quality-dashboard/base/backend/kustomization.yaml
Labels: lgtm, approved

#1649 Disable CSV Copy for all the operators from OLM
  argo-cd-apps/base/all-clusters/infra-deployments/disable-csvcopy-for-all-cluster/disable-csvcopy.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/disable-csvcopy-for-all-cluster/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
  configs/disable-csvcopy-for-all-cluster/cluster.yaml
  configs/disable-csvcopy-for-all-cluster/kustomization.yaml
Labels: lgtm, approved

#1782 fix(RHTAPBUGS-212): increase integration service memory limit
  components/integration/manager_resources_patch.yaml
Labels: approved

#1683 chore: update owners for Integration service
  components/integration/OWNERS
Labels: lgtm, approved

#1787 Pod latency migration dashboard
  components/monitoring/grafana/base/migration/OWNERS
  components/monitoring/grafana/base/migration/migration-team-dashboard.json
Labels: lgtm, approved

#1677 STONEO11Y-153: Add a ClusterLogForwarder for Splunk for Staging env
  components/monitoring/logging/staging/configure-logforwarder-patch.yaml
  components/monitoring/logging/staging/kustomization.yaml
  components/monitoring/logging/staging/monitoring-logging-splunk-log-forwarder-external-secret.yaml
Labels: lgtm, approved

#1788 give pipeline-service team view access to the sprayproxy namespace for support
  components/sprayproxy/base/kustomization.yaml
  components/sprayproxy/base/team-support-rbac.yaml
Labels: lgtm, approved

#1797 create snyk-shared-secret since
  components/tekton-ci/base/external-secrets/snyk-shared-token.yaml
Labels: lgtm, approved

#1791 Enable remote secrets on development environment
  components/spi/overlays/development/config-patch.json
Labels: lgtm, approved

#1796 STONEO11Y-158: Add a ClusterLogForwarder for Splunk for Staging env
  components/monitoring/logging/staging/configure-logging/cluster-log-forwarder-patch.yaml
  components/monitoring/logging/staging/configure-logging/kustomization.yaml
  components/monitoring/logging/staging/external-secrets/kustomization.yaml
  components/monitoring/logging/staging/external-secrets/monitoring-logging-splunk-log-forwarder.yaml
  components/monitoring/logging/staging/kustomization.yaml
Labels: lgtm, approved

#1811 Upgrade Pipeline-Service
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#1815 GitOps: Staging only version of PR #1810, update components/gitops/staging/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#1817 GitOps: apply #1816 to staging only, update components/gitops/staging/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#1800 chore(STONEO11Y-228): Add o11y dashboard
  components/monitoring/grafana/base/kustomization.yaml
  components/monitoring/grafana/base/o11y/kustomization.yaml
Labels: lgtm, approved

#1804 update quality dashboard
  components/quality-dashboard/base/backend/kustomization.yaml
  components/quality-dashboard/base/frontend/kustomization.yaml
Labels: approved

#1801 chore(STONEO11Y-232): Dashborad editor access for development env
  components/monitoring/grafana/development/auto-assign-role-patch.yaml
  components/monitoring/grafana/development/kustomization.yaml
Labels: lgtm, approved

#1808 Add script for setup namespace for appstudio execution
  hack/build/build-via-appstudio.sh
  hack/build/setup-namespace.sh
Labels: approved

#1819 fix: remove release-service grafana dashboard
  components/monitoring/grafana/base/kustomization.yaml
  components/monitoring/grafana/base/release-service/dashboard.yaml
  components/monitoring/grafana/base/release-service/kustomization.yaml
Labels: lgtm

#1798 fix pipeline service team rbac for sprayproxy namespace
  components/sprayproxy/base/kustomization.yaml
  components/sprayproxy/production/kustomization.yaml
  components/sprayproxy/production/team-support-rbac.yaml
  components/sprayproxy/staging/kustomization.yaml
  components/sprayproxy/staging/team-support-rbac.yaml
Labels: lgtm, approved

#1825 Update integration service for STONEINTG-419
  components/integration/kustomization.yaml
Labels: lgtm, approved

#1822 Update sprayproxy version prod
  components/sprayproxy/production/kustomization.yaml
Labels: lgtm, approved

#1824 Update pipeline-service in development/staging
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#1829 Update pipeline-service in production
  components/pipeline-service/production/base/kustomization.yaml
Labels: lgtm, approved

#1833 Use appstudio-pipeline sa for internal CI
  components/tekton-ci/base/appstudio-pipelines-runner-rolebinding.yaml
  components/tekton-ci/base/kustomization.yaml
  components/tekton-ci/base/serviceaccount.yaml
Labels: lgtm, approved

#1826 PLNSRVCE-1318: scale down pipeline-metrics-exporter until we fix scaling/perf issues
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/development/scale-down-exporter.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/base/scale-down-exporter.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/scale-down-exporter.yaml
Labels: lgtm, approved, jira/valid-reference

#1834 RHTAP-872: tekton-ci: fix SA update - ignore native secret
  argo-cd-apps/base/tekton-ci/tekton-ci.yaml
Labels: approved, jira/valid-reference

#1835 RHTAP-872: Update name of serviceaccount
  argo-cd-apps/base/tekton-ci/tekton-ci.yaml
Labels: lgtm, approved, jira/valid-reference

#1843 add yangcao77 as has-admin
  components/authentication/base/has-admin.yaml
Labels: lgtm, approved

#1841 Add thepetk as has-admin
  components/authentication/base/has-admin.yaml
  components/authentication/base/has.yaml
Labels: lgtm, needs-ok-to-test, approved

#1845 add mike-hoang as has-admin
  components/authentication/base/has-admin.yaml
  components/authentication/base/has.yaml
Labels: lgtm, approved

#1844 feat: add release dashboard
  components/monitoring/grafana/base/kustomization.yaml
  components/monitoring/grafana/base/release/kustomization.yaml
Labels: lgtm, approved

#1850 Offboarding mmhedhbi(Mo3men) and bnallapeta
  components/pipeline-service/OWNERS
Labels: lgtm, approved

#1840 Adjust codeowners
  components/authentication/base/spi-vault-admin.yaml
  components/spi/OWNERS
Labels: lgtm, approved

#1842 fix(STONEINTG-430): fix integration service preview env vars
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm, approved

#1860 pipeline-service update dev/staging through mv back pac back to upstream
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#1864 docs: add image-controller to navigation
  docs/_data/navigation.yml
Labels: approved

#1827 update quality dashboard
  components/quality-dashboard/base/backend/kustomization.yaml
  components/quality-dashboard/base/frontend/kustomization.yaml
Labels: lgtm, approved

#1876 chore(RHTAPWATCH-242): rename Grafana datasource
  components/monitoring/grafana/base/grafana-app.yaml
Labels: lgtm, approved

#1836 STONEBLD-867: remove sharedResources
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/shared-resources/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/shared-resources/shared-resources.yaml
  components/build-service/README.md
  components/build-templates/base/external-secrets/kustomization.yaml
  components/build-templates/base/external-secrets/redhat-appstudio-user-workload.yaml
  components/build-templates/production/kustomization.yaml
  components/build-templates/production/redhat-appstudio-user-workload.yaml
  components/build-templates/staging/kustomization.yaml
  components/pipeline-service/components/tekton-chains/kustomization.yaml
  components/pipeline-service/components/tekton-chains/tekton-chains-controller-deployment.yaml
  components/pipeline-service/components/tekton-chains/tekton-chains-controller-shared-secret.yaml
  components/pipeline-service/components/tekton-chains/tekton-chains-controller-shared-secrets-rolebinding.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/shared-resources/globally-shared-secrets-clusterrole.yaml
  components/shared-resources/kustomization.yaml
  components/shared-resources/redhat-appstudio-user-workload-sharedsecret.yaml
  components/shared-resources/scc.yaml
  hack/preview-template.env
  hack/preview.sh
Labels: approved, jira/valid-reference

#1831 Docs: Use the production robot account
  docs/deployment/extending-the-service.md
Labels: approved

#1883 PLNSRVCE-1325: patch tektonconfig so performance setting are reverted to upstream defaults
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/development/update-tekton-config-performance.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/update-tekton-config-performance.yaml
Labels: lgtm, approved, jira/valid-reference
