Repository redhat-appstudio/infra-deployments, pull requests merged in 2023-03, with the labels that each got.

#1414 Added external secrets for stone-prod-prometheus
  components/monitoring/prometheus/production/base/kustomization.yaml
  components/monitoring/prometheus/production/stone-prd-m01/kustomization.yaml
  components/monitoring/prometheus/production/stone-prd-m01/monitoring-prometheus-oauth-config-path.yaml
  components/monitoring/prometheus/production/stone-prd-rh01/kustomization.yaml
  components/monitoring/prometheus/production/stone-prd-rh01/monitoring-prometheus-oauth-config-path.yaml
Labels: approved

#1426 pipeline-service: Update secrets path for RDS and S3
  components/pipeline-service/base/external-secrets/tekton-results/kustomization.yaml
  components/pipeline-service/base/external-secrets/tekton-results/tekton-results-s3.yaml
  components/pipeline-service/production/stone-prd-m01/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/stone-prd-m01/tekton-results-s3-secret-path.yaml
  components/pipeline-service/production/stone-prd-rh01/kustomization.yaml
  components/pipeline-service/production/stone-prd-rh01/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/stone-prd-rh01/tekton-results-s3-secret-path.yaml
  components/pipeline-service/staging/stone-stg-m01/kustomization.yaml
  components/pipeline-service/staging/stone-stg-m01/tekton-results-s3-secret-path.yaml
  components/pipeline-service/staging/stone-stg-rh01/kustomization.yaml
  components/pipeline-service/staging/stone-stg-rh01/tekton-results-s3-secret-path.yaml
Labels: approved

#1428 GitOps: Update references to prod RDS vault secrets
  components/gitops/production/stone-prd-m01/gitops-service-postgres-rds-config-path.yaml
  components/gitops/production/stone-prd-rh01/gitops-service-postgres-rds-config-path.yaml
Labels: approved

#1430 monitoring: Add path to cluster overlays
  argo-cd-apps/base/member/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
  argo-cd-apps/base/member/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml
Labels: approved

#1435 Update OWNERS
  OWNERS
Labels: approved

#1391 Add scope for a client.
  components/dev-sso/keycloak-realm.yaml
Labels: approved

#1429 Fixing staging overlay for monitoring
  components/monitoring/logging/stagging/base/kustomization.yaml
  components/monitoring/logging/stagging/stone-stg-m01/monitoring-logging-cloudwatch-forwarder-path.yaml
  components/monitoring/logging/stagging/stone-stg-rh01/kustomization.yaml
  components/monitoring/logging/stagging/stone-stg-rh01/monitoring-logging-cloudwatch-forwarder-path.yaml
  components/monitoring/logging/staging/kustomization.yaml
  components/monitoring/logging/staging/monitoring-logging-cloudwatch-forwarder-path.yaml
  components/monitoring/prometheus/staging/base/kustomization.yaml
  components/monitoring/prometheus/staging/stone-stg-m01/kustomization.yaml
  components/monitoring/prometheus/staging/stone-stg-m01/monitoring-prometheus-oauth-config-path.yaml
  components/monitoring/prometheus/staging/stone-stg-rh01/kustomization.yaml
  components/monitoring/prometheus/staging/stone-stg-rh01/monitoring-prometheus-oauth-config-path.yaml
Labels: lgtm, approved

#1446 Remove hacks/chains
  hack/chains/.yamllint
  hack/chains/README.md
  hack/chains/_helpers.sh
  hack/chains/check-pipelinerun.sh
  hack/chains/check-taskrun.sh
  hack/chains/check-yaml.sh
  hack/chains/config.sh
  hack/chains/copy-public-sig-key.sh
  hack/chains/cosign-verify-image.sh
  hack/chains/create-signing-secret.sh
  hack/chains/default-pipelines-demo.sh
  hack/chains/deploy-local-rekor.sh
  hack/chains/deploy-local-rekor.tpl
  hack/chains/end-to-end-demo.sh
  hack/chains/gitops-sync.sh
  hack/chains/inspect-pipeline-run.sh
  hack/chains/kaniko-cosign-verify.sh
  hack/chains/kaniko-demo.sh
  hack/chains/nice-logs.sh
  hack/chains/pipeline-quay-demo.sh
  hack/chains/pipeline-quay-demo.yaml
  hack/chains/rekor-image-lookup.sh
  hack/chains/rekor-verify-taskrun.sh
  hack/chains/release-pipeline-with-ec-demo.sh
  hack/chains/setup/debian-based.sh
  hack/chains/setup/install-demo-pre-req.sh
  hack/chains/setup/macos-based.sh
  hack/chains/setup/redhat-based.sh
  hack/chains/simple-demo.sh
  hack/chains/trust-local-cert.sh
Labels: lgtm, approved

#1409 feat(HACBS-1592): Enable deployment from integration-service PRs
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm

#1439 Add other ECP resources
  components/enterprise-contract/default-ecp.yaml
  components/enterprise-contract/ecp.yaml
  components/enterprise-contract/kustomization.yaml
Labels: lgtm, approved

#1449 staging: Configure sprayproxy backends
  components/sprayproxy/staging/add-backends.yml
Labels: approved

#1452 Sync external secrets first
  components/authentication/base/group-sync/external-secrets/github-redhat-appstudio-sre.yaml
  components/authentication/base/group-sync/external-secrets/github-redhat-appstudio.yaml
  components/build-service/base/external-secrets/pipelines-as-code-secret.yaml
  components/build-templates/base/external-secrets/redhat-appstudio-user-workload.yaml
  components/dora-metrics/base/external-secrets/exporters-secrets.yaml
  components/gitops/base/external-secrets/gitops-service-postgres-rds-config.yaml
  components/has/base/external-secrets/has-github-token.yaml
  components/image-controller/base/external-secrets/quaytoken.yaml
  components/monitoring/logging/base/external-secrets/monitoring-logging-cloudwatch-forwarder.yaml
  components/monitoring/prometheus/base/external-secrets/monitoring-prometheus-oauth-config.yaml
  components/pipeline-service/base/external-secrets/pipelines-as-code/pipelines-as-code-secret.yaml
  components/pipeline-service/base/external-secrets/tekton-results/tekton-results-database.yaml
  components/pipeline-service/base/external-secrets/tekton-results/tekton-results-s3.yaml
  components/quality-dashboard/staging/external-secrets/quality-dashboard-secrets.yaml
  components/spi/base/external-secrets/spi-shared-configuration-file.yaml
  components/spi/base/external-secrets/spi-vault-approle-spi-oauth.yaml
  components/spi/base/external-secrets/spi-vault-approle-spi-operator.yaml
  components/tekton-ci/base/external-secrets/infra-deployments-pr-creator.yaml
  components/tekton-ci/base/external-secrets/tekton-ci-push-secret.yaml
Labels: approved

#1447 Add fluentd authentication for prod
  components/monitoring/logging/production/kustomization.yaml
  components/monitoring/logging/production/monitoring-logging-cloudwatch-forwarder-path.yaml
Labels: lgtm, approved

#1458 Fix logging deployment to the clusters
  argo-cd-apps/base/member/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
Labels: lgtm, approved

#1338 move to 4.12 version of sharead resources, including official images; add reminders for moves to OCP 4.13, 4.14
  components/shared-resources/globally-shared-secrets-clusterrole.yaml
  components/shared-resources/kustomization.yaml
  components/shared-resources/scc.yaml
Labels: lgtm, approved

#1460 Add OpenShift-logging namespace to secret store
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: approved

#1456 Add testing NS for pipeline-service
  components/pipeline-service/base/testing/kustomization.yaml
  components/pipeline-service/base/testing/rbac.yaml
Labels: approved

#1467 chore: Removing the .ci directory files which are not needed anymore
  .ci/Readme.md
  .ci/oci-e2e-deployment.sh
  .ci/openshift-ci/Dockerfile
Labels: lgtm, approved

#1471 Skip step_image_registries in the minimal ECP
  components/enterprise-contract/ecp.yaml
Labels: lgtm, approved

#1473 fix issue that update resources of plnsvc development layer
  hack/preview.sh
Labels: lgtm, approved

#1475 let sandbox-sre admins impersonate groups and users
  components/authentication/base/kustomization.yaml
  components/authentication/sandbox-sre-admins.yaml
Labels: lgtm, approved

#1477 Remove repeated operator group installation
  components/monitoring/logging/base/install-logging-operator.yaml
Labels: approved

#1479 fix: move sandbox-sre-admins to base
  components/authentication/base/sandbox-sre-admins.yaml
Labels: lgtm, approved

#1474 chore: Removing the reference from readme which is no longer valid
  docs/testing/e2e-tests.md
Labels: lgtm, approved

#1481 STONE-524 - Add script for installing ephemeral HAC & wiring
  hack/hac/installHac.sh
Labels: lgtm, approved

#1489 enable fmuntean to manage spacerequest in own namespace
  components/authentication/base/kustomization.yaml
  components/authentication/base/sandbox-dev.yaml
Labels: lgtm, approved

#1485 add log retention for new log groups
  components/monitoring/logging/base/configure-logging/configure-logforwarder.yaml
Labels: lgtm, approved

#1437 chore(STONEO11Y-28): o11y component deployment
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/o11y/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/o11y/o11y.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
  components/o11y/README.md
  components/o11y/base/kustomization.yaml
  components/o11y/production/kustomization.yaml
  components/o11y/staging/kustomization.yaml
Labels: lgtm, approved

#1492 Added grafana oauth2-proxy secret from vault
  components/monitoring/grafana/base/external-secrets/kustomization.yaml
  components/monitoring/grafana/base/external-secrets/monitoring-grafana-oauth-config.yaml
  components/monitoring/grafana/production/kustomization.yaml
  components/monitoring/grafana/production/monitoring-grafana-oauth-config-path.yaml
  components/monitoring/grafana/staging/kustomization.yaml
  components/monitoring/grafana/staging/monitoring-grafana-oauth-config-path.yaml
Labels: lgtm, approved

#1499 grant admin permission to pipeline service team on pipeline-service namespaces
  components/authentication/base/pipeline-service-sre.yaml
Labels: lgtm, approved

#1501 Add whole keycloak realm setup.
  components/dev-sso/keycloak-realm.yaml
Labels: lgtm, approved

#1511 feat: view permissions for EC configmap
  components/enterprise-contract/ecp.yaml
  components/enterprise-contract/kustomization.yaml
  components/enterprise-contract/role.yaml
  components/enterprise-contract/rolebinding.yaml
Labels: lgtm, approved

#1514 Removed ArgoCD pointers for appstudio custom prometheus
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
Labels: approved

#1515 Added one loop to make sure application spi-in-cluster-local is created
  hack/preview.sh
Labels: lgtm, approved

#1521 Update image registry link
  hack/quicklab/templates/deployment.yaml
Labels: approved

#1528 Fix wrong ec-release-policy digests
  components/enterprise-contract/ecp.yaml
Labels: lgtm, approved

#1523 fix: quality dashboard auth secret on stage
  components/quality-dashboard/staging/external-secrets/kustomization.yaml
  components/quality-dashboard/staging/external-secrets/quality-dashboard-auth.yaml
  hack/secret-creator/create-quality-dashboard-secrets.sh
Labels: lgtm

#1532 fix: backendroute in the config map
  components/quality-dashboard/base/frontend/kustomization.yaml
Labels: lgtm, approved

#1535 update quality dashboard
  components/quality-dashboard/base/backend/kustomization.yaml
  components/quality-dashboard/base/frontend/kustomization.yaml
Labels: lgtm, approved

#1534 Fix image path for image-controller
  hack/preview.sh
Labels: lgtm, approved

#1527 add json parsing, remove infrastructure and audit logs
  components/monitoring/logging/base/configure-logging/configure-logforwarder.yaml
Labels: lgtm, approved

#1541 Add jannfis as maintainer for GitOps
  components/authentication/base/gitops.yaml
Labels: approved

#1546 add spi instance id config
  components/spi/overlays/development/config-patch.json
  components/spi/overlays/production/stone-prd-m01/config-patch.json
  components/spi/overlays/production/stone-prd-rh01/config-patch.json
  components/spi/overlays/staging/stone-stg-m01/config-patch.json
  components/spi/overlays/staging/stone-stg-rh01/config-patch.json
Labels: lgtm, approved

#1547 [STONE-774] Use redhat-appstudio-appdata-staging on staging
  components/has/production/gitops-org-patch.yaml
  components/has/production/kustomization.yaml
  components/has/staging/gitops-org-patch.yaml
  components/has/staging/kustomization.yaml
Labels: lgtm, approved

#1562 [STONEBUGS-89] Set GITHUB_ORG for HAS via Config Map
  components/has/production/gitops-org-patch.yaml
  components/has/production/kustomization.yaml
  components/has/staging/gitops-org-patch.yaml
  components/has/staging/kustomization.yaml
Labels: lgtm, approved

#1544 Set application name for PaC
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/base/pac-app-name.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/pac-app-name.yaml
Labels: lgtm, approved

#1555 Make Pact Broker deplyoment optional in dev mode.
  argo-cd-apps/base/host/optional/infra-deployments/hac-pact-broker/hac-pact-broker.yaml
  argo-cd-apps/base/host/optional/infra-deployments/hac-pact-broker/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/hac-pact-broker/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  hack/bootstrap-cluster.sh
  hack/bootstrap-host-cluster.sh
  hack/preview-template.env
  hack/preview.sh
  hack/secret-creator/create-pact-broker-secret.sh
Labels: lgtm, approved

#1573 prepare SPI for AWS tokenstorage
  components/spi/base/kustomization.yaml
  components/spi/overlays/development/delete-shared-configuration-file.yaml
  components/spi/overlays/development/kustomization.yaml
  components/spi/overlays/development/operator-limits-patch.json
  components/spi/overlays/production/base/delete-shared-configuration-file.yaml
  components/spi/overlays/production/base/kustomization.yaml
  components/spi/overlays/production/base/operator-limits-patch.json
  components/spi/overlays/staging/base/delete-shared-configuration-file.yaml
  components/spi/overlays/staging/base/kustomization.yaml
  components/spi/overlays/staging/base/operator-limits-patch.json
  components/spi/overlays/staging/stone-stg-m01/kustomization.yaml
  components/spi/overlays/staging/stone-stg-m01/spi-aws-credentials-external-secret.yaml
  hack/preview.sh
Labels: lgtm, approved

#1580 STONEBLD-937: image-controller secrets description
  components/image-controller/README.md
Labels: lgtm, approved, jira/valid-reference

#1584 fix aws credentials secret format for spi
  components/spi/overlays/staging/base/kustomization.yaml
  components/spi/overlays/staging/base/spi-aws-credentials-external-secret.yaml
  components/spi/overlays/staging/stone-stg-m01/kustomization.yaml
  components/spi/overlays/staging/stone-stg-m01/spi-aws-credentials-external-secret.yaml
  components/spi/overlays/staging/stone-stg-m01/spi-aws-credentials-path-patch.yaml
  components/spi/overlays/staging/stone-stg-rh01/kustomization.yaml
  components/spi/overlays/staging/stone-stg-rh01/spi-aws-credentials-path-patch.yaml
Labels: lgtm, approved

#1588 Remove unused imagestream
  components/hac-pact-broker/imagestream.yaml
Labels: lgtm, approved

#1589 fix: remove dead references in monitoring overlays
  components/monitoring/prometheus/production/base/kustomization.yaml
  components/monitoring/prometheus/staging/base/kustomization.yaml
Labels: approved

#1590 chore(STONEO11Y-86): create dev overlay for o11y
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  components/o11y/development/kustomization.yaml
Labels: approved

#1606 add neccessary SpaceRequst permissions to sandbox-sre admins
  components/authentication/base/sandbox-sre-admins.yaml
Labels: lgtm, approved

#1605 contract: Use new collection format in default ECP
  components/enterprise-contract/ecp.yaml
Labels: lgtm, approved
