Repository redhat-appstudio/infra-deployments, pull requests merged in 2023-06, with the labels that each got.

#1884 feat(STONEINTG-185): add integration service grafana dashboard
  components/monitoring/grafana/base/integration/kustomization.yaml
  components/monitoring/grafana/base/kustomization.yaml
Labels: lgtm, approved

#1885 Remove pods/exec from component maintainer role
  components/authentication/base/component-maintainer.yaml
Labels: approved

#1556 Enable maintainer to manually approve..
  components/authentication/base/component-maintainer.yaml
  components/authentication/base/pipeline-service-sre.yaml
Labels: lgtm, approved

#1832 feat: support quickcluster as we do quicklab
  hack/quickcluster/README.md
  hack/quickcluster/setup-nfs-quickcluster.sh
  hack/quickcluster/templates/deployment.yaml
  hack/quickcluster/templates/rbac.yaml
  hack/quickcluster/templates/storageClass.yaml
  hack/quickcluster/templates/test-pvc.yaml
Labels: approved

#1886 RHTAPWATCH-281: Reconfigure Splunk ClusterLogForwarders for Staging environment
  components/monitoring/logging/staging/configure-logging/cluster-log-forwarder-patch.yaml
  components/monitoring/logging/staging/external-secrets/kustomization.yaml
  components/monitoring/logging/staging/external-secrets/monitoring-logging-splunk-log-forwarder.yaml
  components/monitoring/logging/staging/external-secrets/splunk-log-forwarders-external-secrets.yaml
Labels: lgtm, approved, jira/valid-reference

#1889 Move to QuickCluster
  docs/development/pre.md
  hack/quicklab/README.md
  hack/quicklab/setup-nfs-quicklab.sh
  hack/quicklab/templates/deployment.yaml
  hack/quicklab/templates/rbac.yaml
  hack/quicklab/templates/storageClass.yaml
  hack/quicklab/templates/test-pvc.yaml
Labels: approved

#1893 Add michael-valdron as has-admin
  components/authentication/base/has-admin.yaml
  components/authentication/base/has.yaml
Labels: lgtm, approved

#1892 Update pipeline-service in production
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/base/update-tekton-config-performance.yaml
Labels: lgtm, approved

#1880 updated performance/dashboard.yaml to rename kubernetes-cluster-moni…
  components/monitoring/grafana/base/performance/dashboard.yaml
Labels: lgtm, approved

#1620 Add Results ServiceMonitor to pipeline-service
  components/pipeline-service/base/servicemonitors/kustomization.yaml
  components/pipeline-service/base/servicemonitors/tekton-results-service-monitor.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#1902 Promote SPI stage to prod
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#1897 Pipeline Service Dashboard
  components/monitoring/grafana/base/kustomization.yaml
  components/monitoring/grafana/base/pipeline-service/kustomization.yaml
Labels: lgtm, approved

#1878 managed-gitops: staging only for #1855, update components/gitops/staging/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#1901 RHTAPWATCH-244: Configure ClusterLogForwarder to Splunk for Production env
  components/monitoring/logging/base/configure-logging/configure-logforwarder.yaml
  components/monitoring/logging/base/external-secrets/kustomization.yaml
  components/monitoring/logging/base/external-secrets/splunk-log-forwarder-external-secrets.yaml
  components/monitoring/logging/development/kustomization.yaml
  components/monitoring/logging/production/kustomization.yaml
  components/monitoring/logging/staging/configure-logging/cluster-log-forwarder-patch.yaml
  components/monitoring/logging/staging/external-secrets/kustomization.yaml
  components/monitoring/logging/staging/kustomization.yaml
Labels: lgtm, approved, jira/valid-reference

#1919 chore(grafana): update integration-service grafana
  components/monitoring/grafana/base/integration/kustomization.yaml
Labels: lgtm, approved

#1916 Enable remote-secret feature for staging
  components/spi/overlays/staging/base/config-patch.json
  components/spi/overlays/staging/base/kustomization.yaml
Labels: lgtm, approved

#1900 chore(RHTAPWATCH-262): Federate from UWM Prometheus
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
  components/monitoring/prometheus/development/monitoringstack/kustomization.yaml
  components/monitoring/prometheus/production/monitoringstack/kustomization.yaml
  components/monitoring/prometheus/staging/monitoringstack/kustomization.yaml
Labels: lgtm, approved

#1924 feat(STONEINTG-362): adding PAC to hacbs-test repo
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#1922 fix(RHTAPWATCH-295): Fix bug in the Staging ExternalSecrets configuration
  components/monitoring/logging/staging/kustomization.yaml
Labels: lgtm, approved

#1911 Update Pipeline Service in Staging
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#1923 STONEBLD-29: add slack notification secret for tekton-ci
  components/tekton-ci/base/external-secrets/kustomization.yaml
  components/tekton-ci/base/external-secrets/slack-webhook-notification-secret.yaml
Labels: approved, jira/valid-reference

#1927 chore(grafana): update integration-service grafana
  components/monitoring/grafana/base/integration/kustomization.yaml
Labels: lgtm, approved

#1933 PLNSRVCE-1310: reenable in dev/stage, but keeping disable patch around for now, pipeline service metrics exporter
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved, jira/valid-reference

#1947 Fix Tekton Results servicemonitors scheme
  components/pipeline-service/base/servicemonitors/tekton-results-service-monitor.yaml
Labels: lgtm, approved

#1890 [DEVHAS-377] separate stage and prod deployments
  components/has/base/argocd-roles/allow-argocd-to-manage.yaml
  components/has/base/argocd-roles/argocd-permissions.yaml
  components/has/base/argocd-roles/kustomization.yaml
  components/has/base/kustomization.yaml
  components/has/development/kustomization.yaml
  components/has/k-components/enable-profiling/kustomization.yaml
  components/has/k-components/enable-profiling/pprof_patch.yaml
  components/has/k-components/manager-resources/kustomization.yaml
  components/has/k-components/manager-resources/manager_resources_patch.yaml
  components/has/k-components/replicas-patch/kustomization.yaml
  components/has/k-components/replicas-patch/replicas_patch.yaml
  components/has/production/kustomization.yaml
  components/has/staging/kustomization.yaml
  components/has/staging/replicas_patch.yaml
Labels: lgtm, approved

#1949 PLNSRVCE-1310: bump pipeline service prod to vetted staging version
  components/pipeline-service/production/base/kustomization.yaml
Labels: lgtm, approved, jira/valid-reference

#1944 chore(RHTAPWATCH-241): Increase UWM prometheus retention duration and size
  components/monitoring/prometheus/README.md
  components/monitoring/prometheus/base/uwm-config/uwm-config.yaml
Labels: lgtm, approved

#1942 chore(integration): remove service monitor
  components/monitoring/prometheus/base/servicemonitors/integration-service.yaml
  components/monitoring/prometheus/base/servicemonitors/kustomization.yaml
Labels: lgtm, approved

#1963 Fix JVM Build Service in repo tests
  hack/preview.sh
Labels: lgtm, approved

#1971 Correctly set production overlay for remote-secret operator
  argo-cd-apps/overlays/production/kustomization.yaml
Labels: lgtm, approved

#1970 RHTAPWATCH-322: Fluentd collectors are incompatible with Splunk ClusterLogForwarder configuration
  components/monitoring/logging/base/configure-logging/configure-log-collectors.yaml
Labels: lgtm, approved, jira/valid-reference

#1974 Make PaC webhook SSL check configurable
  components/build-service/development/kustomization.yaml
  components/build-service/development/pac-webhook-insecure-ssl-patch.yaml
Labels: approved

#1852 feat(RHTAP-965): Add dashboard to track PipelineRuns and TaskRuns
  components/monitoring/grafana/base/performance/dashboard.yaml
  components/monitoring/grafana/base/performance/dashboards/kubernetes-cluster-monitoring.json
  components/monitoring/grafana/base/performance/dashboards/kubernetes-persistent-volumes.json
  components/monitoring/grafana/base/performance/kustomization.yaml
Labels: approved

#1983 feat(HACBS-2310): add clusterrole for release pipelines
  components/release/kustomization.yaml
  components/release/release-pipeline-resources-clusterrole.yaml
Labels: lgtm, approved

#1991 PLNSRVCE-1326: switch tekton pipeline controller to larger scale settings in dev/stage
  components/pipeline-service/development/update-tekton-config-performance.yaml
  components/pipeline-service/staging/base/update-tekton-config-performance.yaml
Labels: lgtm, approved, jira/valid-reference

#1986 fix: remove unneeded metrics from federation
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#1997 PLNSRVCE-1326: switch tekton pipeline controller to larger scale settings in prod
  components/pipeline-service/production/base/update-tekton-config-performance.yaml
Labels: lgtm, approved, jira/valid-reference

#2008 Briefly add role to allow exec into HAS on stage
  components/authentication/staging/has-exec.yaml
  components/authentication/staging/kustomization.yaml
Labels: lgtm, approved

#2012 PLNSRVCE-1124-Move CI to StoneSoup Prod MVP
  components/tekton-ci/base/repository.yaml
  components/tekton-ci/production/kustomization.yaml
  components/tekton-ci/production/plnsvc-ci-secret.yaml
Labels: lgtm, approved

#1937 chore(RHTAPWATCH-110): Add "label_app_kubernetes_io_managed_by" label to the monitoringstack
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#2014 PLNSRVCE-1069: remove servicemonitor definition that is not currently being processed
  components/monitoring/prometheus/base/servicemonitors/pipeline-service.yaml
Labels: lgtm, approved, jira/valid-reference

#2015 bump pipeline service in dev/staging
  components/monitoring/grafana/base/pipeline-service/kustomization.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#1995 Do not create image repository for component in build test script
  components/build-service/README.md
  hack/build/build-via-appstudio.sh
  hack/build/templates/component.yaml
Labels: approved

#1989 Fix timeout for remote-secret-controller-in-cluster-local
  hack/preview.sh
Labels: lgtm, approved

#2021 Promote SPI staging to prod
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#2023 bump pipeline service in prod
  components/pipeline-service/production/base/kustomization.yaml
Labels: lgtm, approved

#2024 bump pipeline service in dev/stage
  components/monitoring/grafana/base/pipeline-service/kustomization.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#2026 Add enarha as reviewer for sprayproxy and pipeline-service
  components/pipeline-service/OWNERS
  components/sprayproxy/OWNERS
Labels: lgtm, approved

#2033 bump pipeline service version
  components/monitoring/grafana/base/pipeline-service/kustomization.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#2022 feat(HACBS-2290): add snapshots to release pipeline clusterrole
  components/release/release-pipeline-resources-clusterrole.yaml
Labels: lgtm, approved

#2025 Add new profile to Keycloak
  components/dev-sso/keycloak-realm.yaml
Labels: lgtm, approved

#2040 update dora metrics
  components/dora-metrics/staging/kustomization.yaml
  components/monitoring/grafana/base/dora-metrics/kustomization.yaml
  hack/secret-creator/create-dora-metrics-exporter-secrets.sh
Labels: lgtm

#2044 remove CI config for external-secrets
  components/tekton-ci/base/repository.yaml
Labels: approved

#2046 Update GitOps Service ServiceMonitors and move to 'gitops' component folder
  components/gitops/base/monitoring/kustomization.yaml
  components/gitops/base/monitoring/monitoring-agent.yaml
  components/gitops/base/monitoring/monitoring-all.yaml
  components/gitops/base/monitoring/monitoring-appstudio.yaml
  components/gitops/base/monitoring/monitoring-core.yaml
  components/gitops/production/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
  components/monitoring/prometheus/base/servicemonitors/gitops-service.yaml
  components/monitoring/prometheus/base/servicemonitors/kustomization.yaml
Labels: approved

#2048 Remove generatorOptions from dashboard configmap gen
  components/monitoring/grafana/base/managed-gitops/kustomization.yaml
Labels: approved

#2049 Remove unused ec configmap keys
  components/enterprise-contract/kustomization.yaml
Labels: lgtm, approved
