Repository redhat-appstudio/infra-deployments, pull requests merged in 2023-10, with the labels that each got.

#2435 chore(STONEINTG-542): update licence info
  LICENSE
Labels: lgtm, approved

#2489 Grant read access of clusterversions to all developers
  components/authentication/base/everyone-can-view.yaml
Labels: lgtm, approved

#2495 Remove quality dashboard from tekton-ci. Quality dashboard is onboarded in RHTAP, so no need this config
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#2481 Fix subscription namaspace
  configs/enable-dvo-for-all-cluster/install-dvo.yaml
Labels: lgtm, approved

#2490 feat(STONEINTG-532): grafana panel release creation latency
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#2473 Add a cron job to send notification about cluster/dedicated-admins
  components/authentication/base/admin-checker/admin-checker-sa.yaml
  components/authentication/base/admin-checker/cronjob.yaml
  components/authentication/base/admin-checker/external-secrets/kustomization.yaml
  components/authentication/base/admin-checker/external-secrets/rhtap-infra-secrets.yaml
  components/authentication/base/admin-checker/kustomization.yaml
  components/authentication/base/admin-checker/namespace.yaml
  components/authentication/base/kustomization.yaml
  components/authentication/production/kustomization.yaml
  components/authentication/production/rhtap-infra-secrets-patch.yaml
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: lgtm, approved

#2508 PLNSRVCE-1328: allow access to clusterresourcequota for SOP for per namespace secrets quota
  components/pipeline-service/base/rbac/cluster-role/pipeline-service-sre.yaml
Labels: lgtm, approved, jira/valid-reference

#2503 chore(build-definitions): update owners
  components/build-service/base/build-pipeline-selectors/OWNERS
  components/build-service/base/build-pipeline-selectors/build-pipeline-selector.yaml
  components/build-service/base/kustomization.yaml
Labels: lgtm, approved

#2483 Fix olm-restart kube-linter issues
  components/sandbox/base/olm-restart/cronjob.yaml
Labels: lgtm, approved

#2520 Update application-api to 8b646f622222d641fe4b05e7d62845037a88cada
  components/application-api/kustomization.yaml
Labels: lgtm, approved

#2424 feat: Add service account for perf team to read from Prometheus
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/perf-team-prometheus-reader/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/perf-team-prometheus-reader/perf-team-prometheus-reader.yaml
  components/perf-team-prometheus-reader/OWNERS
  components/perf-team-prometheus-reader/README.md
  components/perf-team-prometheus-reader/base/kustomization.yaml
  components/perf-team-prometheus-reader/base/serviceaccount.yaml
  components/perf-team-prometheus-reader/development/kustomization.yaml
  components/perf-team-prometheus-reader/staging/kustomization.yaml
Labels: lgtm, approved

#2524 Remove rights for rhtap-admin on internalrequests
  components/authentication/base/rhtap-admins.yaml
Labels: lgtm, approved

#2526 Do not run admin checker cron on weekends
  components/authentication/base/admin-checker/cronjob.yaml
Labels: lgtm, approved

#2527 bump pipeline-service prod to same level as stage
  components/pipeline-service/production/base/kustomization.yaml
Labels: lgtm, approved

#2528 Fix admin-checker cron on empty list of users
  components/authentication/base/admin-checker/cronjob.yaml
Labels: lgtm, approved

#2519 managed-gitops: temporarily all component maintainer to modify WebhookConfiguration
  components/gitops/base/authentication/gitops-clusterroles.yaml
Labels: approved

#2539 managed-gitops: cherrypick #2529 to staging update components/gitops/staging/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#2537 Remove unneeded secret for perf-team-prometheus-reader
  components/perf-team-prometheus-reader/base/serviceaccount.yaml
Labels: lgtm, approved

#2540 fix(RHTAPWATCH-542): Add status label to the spi metric on app-sre
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#2549 Update pipeline-service in production
  components/pipeline-service/production/base/kustomization.yaml
Labels: lgtm, approved

#2552 ClusterLogging instance is constantly on OutOfSync status in Argo
  components/monitoring/logging/base/configure-logging/configure-log-collectors.yaml
Labels: lgtm, approved

#2546 managed-gitops update: Enable Environment webhook on staging only
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#2553 managed-gitops: disable temporary Environment webhook on staging
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#2550 Remove cluster-registration-operator from production
  argo-cd-apps/base/member/infra-deployments/cluster-registration/cluster-registration.yaml
  argo-cd-apps/base/member/infra-deployments/cluster-registration/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/staging/delete-applications.yaml
  argo-cd-apps/overlays/staging/kustomization.yaml
  components/cluster-registration/cluster-registration-maintainer.yaml
  components/cluster-registration/kustomization.yaml
Labels: lgtm, approved

#2554 [PROD] Update pipeline-service
  components/pipeline-service/production/base/kustomization.yaml
Labels: lgtm, approved

#2556 Update sprayproxy production
  components/sprayproxy/production/kustomization.yaml
Labels: lgtm, approved

#2515 fix(STONEINTG-532): fix grafana panel display err
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#2567 bump pipeilne-service prod to same level as stage
  components/pipeline-service/production/base/kustomization.yaml
Labels: lgtm, approved

#2560 managed-gitops update: cherry pick #2557 to staging only, update components/gitops/staging/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#2570 managed-gitops: Revert #2560 from staging, "update components/gitops/staging/base/kustomization.yaml (#2560)"
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#2574 managed-gitops: cherry pick #2557 to staging only, update components/gitops/staging/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#2576 Revert push to staging on #2574 "update components/gitops/staging/base/kustomization.yaml (#2574)"
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#2578 chore(RHTAPREL-647): releaseserviceconfig rbac
  components/authentication/base/everyone-can-view.yaml
  components/authentication/base/rhtap-admins.yaml
  components/release/kustomization.yaml
  components/release/release-service-configurator-role.yaml
  components/release/release-team.yaml
Labels: lgtm, approved

#2581 chore(RHTAPREL-435): remove internal-services PaC repo
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#2589 Added permissions for the following apiGroups
  components/authentication/base/rhtap-admins.yaml
Labels: lgtm, approved

#2573 chore(RHTAPREL-645): add release overlays
  argo-cd-apps/base/member/infra-deployments/release/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/release/release.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
  components/release/base/allow-argocd-to-manage.yaml
  components/release/base/argocd-permissions.yaml
  components/release/base/kustomization.yaml
  components/release/base/release-pipeline-resources-clusterrole.yaml
  components/release/base/release-service-configurator-role.yaml
  components/release/base/release-team.yaml
  components/release/development/kustomization.yaml
  components/release/k-components/manager-resources-patch/kustomization.yaml
  components/release/k-components/manager-resources-patch/manager_resources_patch.yaml
  components/release/kustomization.yaml
  components/release/production/kustomization.yaml
  components/release/staging/kustomization.yaml
  hack/preview.sh
Labels: lgtm, approved

#2591 chore(RHTAPREL-645): fix production overlay
  argo-cd-apps/overlays/production/kustomization.yaml
Labels: lgtm, approved

#2585 Update OWNERS - remove Michkov
  OWNERS
Labels: lgtm, ok-to-test, approved

#2597 Promote SPI/RemoteSecret from staging to prod
  components/remote-secret-controller/overlays/production/base/kustomization.yaml
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#2596 managed-gitops: cherrypick #2557 to staging only, update components/gitops/staging/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#2328 Fix staging sprayproxy duplicated GH_APP_WEBHOOK_SECRET
  components/sprayproxy/staging/add-backends.yml
  components/sprayproxy/staging/add-webhook-secret.yaml
  components/sprayproxy/staging/change-backends.yaml
  components/sprayproxy/staging/change-webhook-secret.yaml
  components/sprayproxy/staging/kustomization.yaml
Labels: lgtm, approved

#2610 Update sprayproxy prod
  components/sprayproxy/production/kustomization.yaml
Labels: lgtm, approved

#2613 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#2611 Fix prd sprayproxy duplicated GH_APP_WEBHOOK_SECRET
  components/sprayproxy/production/add-backends.yml
  components/sprayproxy/production/add-webhook-secret.yaml
  components/sprayproxy/production/change-backends.yaml
  components/sprayproxy/production/change-webhook-secret.yaml
  components/sprayproxy/production/kustomization.yaml
Labels: lgtm, approved

#2618 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#2625 bump pipeline-service prod to current stage level
  components/pipeline-service/production/base/kustomization.yaml
Labels: lgtm, approved

#2616 feat(STONEINTG-533): Latency release creation slo panels
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#2577 add serviceMonitor for proxy metrics
  components/sandbox/base/kustomization.yaml
  components/sandbox/base/monitoring/sandbox-registration-service-proxy.yaml
Labels: lgtm, ok-to-test, approved

#2628 managed-gitops: Cherry pick #2620 to staging, update components/gitops/staging/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#2633 PLNSRVCE-1470: add the metrics/labels pipeline service wants scraped by app sre grafana
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved, jira/valid-reference

#2630 add network policy for proxy-metrics
  components/sandbox/base/kustomization.yaml
  components/sandbox/base/monitoring/prometheus-network-policy.yaml
Labels: lgtm, ok-to-test, approved

#2636 feat: Adding perf team that maintains perf-team-prometheus-reader NS
  components/perf-team-prometheus-reader/base/kustomization.yaml
  components/perf-team-prometheus-reader/base/perf-team.yaml
Labels: lgtm, approved

#2642 PLNSRVCE-1470: minor fix to add the metrics/labels pipeline service wants scraped by app sre
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved, jira/valid-reference

#2640 Stoneintg 533 fix parsing error
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#2646 Revert "add network policy for proxy-metrics"
  components/sandbox/base/kustomization.yaml
  components/sandbox/base/monitoring/prometheus-network-policy.yaml
Labels: lgtm, approved

#2649 sandbox: enable prune during sync
  argo-cd-apps/base/host/toolchain-host-operator/toolchain-host-operator.yaml
  argo-cd-apps/base/member/infra-deployments/toolchain-member-operator/toolchain-member-operator.yaml
Labels: lgtm, approved

#2656 add support for stg-rh01 cluster
  argo-cd-apps/base/rh-managed-workspaces-config/rh-managed-workspaces-config.yaml
Labels: approved

#2657 Revert "add support for stg-rh01 cluster"
  argo-cd-apps/base/rh-managed-workspaces-config/rh-managed-workspaces-config.yaml
Labels: approved

#2619 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved
