Repository redhat-appstudio/infra-deployments, pull requests merged in 2023-07, with the labels that each got.

#2035 chore(RHTAPWATCH-331): Add namespace to dummy service monitor example
  components/monitoring/prometheus/development/dummy-service-namespace.yaml
  components/monitoring/prometheus/development/dummy-service-service-monitor.yaml
  components/monitoring/prometheus/development/dummy-service.yaml
  components/monitoring/prometheus/development/kustomization.yaml
Labels: lgtm, approved

#2053 bump pipeline service version
  components/monitoring/grafana/base/pipeline-service/kustomization.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#2051 fix(RHTAPWATCH-356): obo conflicts when using OSD on AWS
  components/monitoring/prometheus/README.md
  components/monitoring/prometheus/development/kustomization.yaml
  hack/bootstrap-cluster.sh
  hack/preview.sh
Labels: lgtm, approved

#2052 Fix components kustomization files
  components/image-controller/base/kustomization.yaml
  components/integration/kustomization.yaml
  components/release/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#2060 update quality dashboard
  components/quality-dashboard/base/backend/kustomization.yaml
  components/quality-dashboard/base/frontend/kustomization.yaml
Labels: approved

#2066 Change pipeline pruner behavior in Staging
  components/pipeline-service/staging/base/greedy-pruner.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: approved

#2067 Keep PipelineRuns for 24h in tekton-ci
  components/tekton-ci/base/namespace.yaml
Labels: approved

#2075 Update sprayproxy prod
  components/sprayproxy/production/kustomization.yaml
Labels: lgtm, approved

#2045 do not run image-controller pipelines in tekton-ci ns
  components/tekton-ci/base/repository.yaml
Labels: do-not-merge/hold, approved

#2078 chore(RHTAPSRE-45): Upgrade ESO on stage
  components/external-secrets-operator/staging/kustomization.yaml
  components/external-secrets-operator/staging/starting-csv-patch.yaml
Labels: approved

#2079 chore(RHTAPSRE-45): Upgrade ESO on stage to 0.9.1
  components/external-secrets-operator/staging/starting-csv-patch.yaml
Labels: approved

#2087 GitOps Service: deploy to staging only, update components/gitops/staging/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#2059 SVPI-518: split vault-init into vault-init, spi-init, and remote-secret-init scripts
  hack/preview.sh
  hack/spi/remote-secret-init.sh
  hack/spi/spi-init.sh
  hack/spi/utils.sh
  hack/spi/vault-init.sh
Labels: approved, jira/valid-reference

#2096 workaround for SRVKP-3245 operator tektonconfig update bug
  hack/preview.sh
Labels: approved

#2094 fix the rollout of 'pipelines-as-code-secret' in staging
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/pipelines-as-code-namespace.yaml
  components/pipeline-service/staging/base/pipelines-as-code-secret.yaml
Labels: approved

#2102 Allow access vault-secret store from openshift-pipelines
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: approved

#2092 application-api update
  components/application-api/kustomization.yaml
Labels: lgtm, approved

#2105 Update Pipeline Service
  components/pipeline-service/base/servicemonitors/kustomization.yaml
  components/pipeline-service/base/servicemonitors/tekton-results-service-monitor.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#2108 Update sprayproxy backends after OSP 1.11 upgrade
  components/sprayproxy/staging/add-backends.yml
Labels: approved

#2097 Enable generic Grafana dashboards
  components/monitoring/grafana/base/generic-dashboards/controller-runtime-controllers-detail_rev1.json
  components/monitoring/grafana/base/generic-dashboards/dashboard.yaml
  components/monitoring/grafana/base/generic-dashboards/example.json
  components/monitoring/grafana/base/generic-dashboards/go-processes_rev1.json
  components/monitoring/grafana/base/generic-dashboards/kustomization.yaml
  components/monitoring/grafana/base/grafana-app.yaml
  components/monitoring/grafana/base/kustomization.yaml
Labels: lgtm, approved

#2061 Use RHTAP to build image-controller and external-secrets
  argo-cd-apps/base/ci-workspaces/ci-workspaces.yaml
  argo-cd-apps/base/ci-workspaces/kustomization.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
  ci/teams/rhtap-build/kustomization.yaml
  ci/teams/rhtap-build/release.yaml
  ci/teams/rhtap-gitops/kustomization.yaml
  ci/teams/rhtap-gitops/release.yaml
  ci/teams/rhtap-servicerelease/kustomization.yaml
  ci/teams/rhtap-servicerelease/release-build.yaml
  ci/teams/rhtap-servicerelease/release-external-secrets.yaml
Labels: approved

#2084 chore(RHTAPWATCH-365): Remove o11y dashboard deployment from infra-deployments
  components/monitoring/grafana/base/kustomization.yaml
  components/monitoring/grafana/base/o11y/kustomization.yaml
Labels: lgtm, approved

#2119 Update instructions regarding setting Quay organization
  hack/preview-template.env
Labels: approved

#2125 tekton-ci: github-read-only-token from ExternalSecrets
  components/tekton-ci/base/external-secrets/github-secret.yaml
  components/tekton-ci/base/external-secrets/kustomization.yaml
Labels: lgtm, approved

#1940 GitOps Service team RBAC changes for staging/production (#604)
  components/authentication/base/gitops-component-maintainer.yaml
  components/authentication/base/gitops.yaml
  components/gitops/base/authentication/gitops-clusterrolebindings.yaml
  components/gitops/base/authentication/gitops-clusterroles.yaml
  components/gitops/base/authentication/kustomization.yaml
  components/gitops/production/base/authentication/gitops-rolebindings.yaml
  components/gitops/production/base/authentication/kustomization.yaml
  components/gitops/production/base/kustomization.yaml
  components/gitops/staging/base/authentication/gitops-rolebindings.yaml
  components/gitops/staging/base/authentication/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#2134 feat(STONE-485): add integration github token secret from vault
  components/tekton-ci/base/external-secrets/integration-github-token.yaml
  components/tekton-ci/base/external-secrets/kustomization.yaml
Labels: approved

#2133 chore(HACBS-2290): manual release-service update
  components/monitoring/grafana/base/release/kustomization.yaml
  components/release/kustomization.yaml
Labels: lgtm, approved

#2001 Use the default snyk token name
  components/tekton-ci/base/external-secrets/snyk-shared-token.yaml
Labels: approved

#2121 Update image-controller
  components/image-controller/base/kustomization.yaml
Labels: approved

#2129 gitops: cherry pick to staging #2135 to staging - update components/gitops/staging/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#2103 Add remote secret monitor deployment
  components/remote-secret-controller/overlays/production/base/kustomization.yaml
  components/remote-secret-controller/overlays/staging/base/kustomization.yaml
Labels: lgtm, approved

#2140 Update gitops version
  components/gitops/openshift-gitops/overlays/staging/subscription-openshift-gitops.yaml
Labels: approved

#2149 monitoring: Add GitOps Service's Argo CD Dashboard
  components/monitoring/grafana/base/managed-gitops/gitops-service-argocd-dashboard.yaml
  components/monitoring/grafana/base/managed-gitops/kustomization.yaml
Labels: approved

#2157 PLNSRVCE-1381: prototype adding cluster-wide results viewing to some pipeline-service team members
  components/authentication/staging/kustomization.yaml
  components/authentication/staging/results-cluster-viewer.yaml
Labels: lgtm, approved, jira/valid-reference

#2124 RHTAPBUGS-499: Fix bonfire version + fix tests execution.
  hack/hac/installHac.sh
Labels: approved, jira/valid-reference

#2156 Fix(RHTAPWATCH-332): Remove the o11y component from infra-deployments
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/o11y/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/o11y/o11y.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
  components/monitoring/README.md
  components/o11y/OWNERS
  components/o11y/README.md
  components/o11y/base/kustomization.yaml
  components/o11y/development/kustomization.yaml
  components/o11y/production/kustomization.yaml
  components/o11y/staging/kustomization.yaml
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#2158 Fix(RHTAPWATCH-8): Upgrade to Grafana Operator v5
  components/monitoring/README.md
  components/monitoring/grafana/base/build-service/dashboard.yaml
  components/monitoring/grafana/base/dora-metrics/dashboard.yaml
  components/monitoring/grafana/base/generic-dashboards/controller-runtime-controllers-detail_rev1.json
  components/monitoring/grafana/base/generic-dashboards/dashboard.yaml
  components/monitoring/grafana/base/generic-dashboards/go-processes_rev1.json
  components/monitoring/grafana/base/grafana-app.yaml
  components/monitoring/grafana/base/grafana-operator.yaml
  components/monitoring/grafana/base/has/dashboard.yaml
  components/monitoring/grafana/base/jvm-build-service/dashboard.yaml
  components/monitoring/grafana/base/kustomization.yaml
  components/monitoring/grafana/base/managed-gitops/dashboard.yaml
  components/monitoring/grafana/base/migration/dashboard.yaml
  components/monitoring/grafana/base/spi/dashboard.yaml
Labels: lgtm, do-not-merge/hold, approved

#2166 replace grafan subscription
  components/monitoring/grafana/base/grafana-operator.yaml
Labels: approved

#2167 add syncwave to grafana
  components/monitoring/grafana/base/grafana-operator.yaml
Labels: approved

#2169 Reorder the Grafana component
  components/monitoring/grafana/base/dashboards/build-service/dashboard.yaml
  components/monitoring/grafana/base/dashboards/build-service/kustomization.yaml
  components/monitoring/grafana/base/dashboards/cm-dashboard.yaml
  components/monitoring/grafana/base/dashboards/dora-metrics/dashboard.yaml
  components/monitoring/grafana/base/dashboards/dora-metrics/kustomization.yaml
  components/monitoring/grafana/base/dashboards/generic-dashboards/controller-runtime-controllers-detail_rev1.json
  components/monitoring/grafana/base/dashboards/generic-dashboards/dashboard.yaml
  components/monitoring/grafana/base/dashboards/generic-dashboards/example.json
  components/monitoring/grafana/base/dashboards/generic-dashboards/go-processes_rev1.json
  components/monitoring/grafana/base/dashboards/generic-dashboards/kustomization.yaml
  components/monitoring/grafana/base/dashboards/has/OWNERS
  components/monitoring/grafana/base/dashboards/has/dashboard.yaml
  components/monitoring/grafana/base/dashboards/has/kustomization.yaml
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
  components/monitoring/grafana/base/dashboards/jvm-build-service/dashboard.yaml
  components/monitoring/grafana/base/dashboards/jvm-build-service/kustomization.yaml
  components/monitoring/grafana/base/dashboards/kustomization.yaml
  components/monitoring/grafana/base/dashboards/managed-gitops/dashboard.yaml
  components/monitoring/grafana/base/dashboards/managed-gitops/gitops-service-argocd-dashboard.yaml
  components/monitoring/grafana/base/dashboards/managed-gitops/kustomization.yaml
  components/monitoring/grafana/base/dashboards/migration/OWNERS
  components/monitoring/grafana/base/dashboards/migration/dashboard.yaml
  components/monitoring/grafana/base/dashboards/migration/kustomization.yaml
  components/monitoring/grafana/base/dashboards/migration/migration-team-dashboard.json
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
  components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
  components/monitoring/grafana/base/dashboards/release/kustomization.yaml
  components/monitoring/grafana/base/dashboards/spi/dashboard.yaml
  components/monitoring/grafana/base/dashboards/spi/kustomization.yaml
  components/monitoring/grafana/base/external-secrets/kustomization.yaml
  components/monitoring/grafana/base/grafana-app.yaml
  components/monitoring/grafana/base/kustomization.yaml
Labels: approved

#2170 Remove ext secrets from Grafana
  components/monitoring/grafana/base/external-secrets/kustomization.yaml
  components/monitoring/grafana/base/external-secrets/monitoring-grafana-oauth-config.yaml
  components/monitoring/grafana/base/kustomization.yaml
Labels: approved

#2171 Add missing annotation to the Grafana CR
  components/monitoring/grafana/base/grafana-app.yaml
Labels: approved

#2173 Deploy Grafana's operator group first
  components/monitoring/grafana/base/grafana-operator.yaml
Labels: lgtm, approved

#2174 fix(RHTAPWATCH-8): Update gitops-service-argocd-dashboard CRD
  components/monitoring/grafana/base/dashboards/managed-gitops/gitops-service-argocd-dashboard.yaml
Labels: lgtm, approved
