Repository redhat-appstudio/infra-deployments, pull requests merged in 2023-12, with the labels that each got.

#2852 feat(STONEINTG-608): add integration ns to vault
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
  components/integration/base/external-secrets/pipelines-as-code-secret.yaml
Labels: lgtm, approved

#2853 Link the registry secret as a mountable secret
  components/build-templates/production/e2e-serviceaccount.yaml
Labels: lgtm, approved

#2850 Upgrade OADP operator to channel 1.3
  components/backup/base/oadp/install-oadp.yaml
Labels: lgtm, approved

#2822 feat: More graphs
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, approved

#2848 Add backup schedule for tenants namespaces
  components/backup/base/external-secret.yaml
  components/backup/base/oadp/backup-tenants-schedule.yaml
  components/backup/base/oadp/dpa.yaml
  components/backup/base/oadp/kustomization.yaml
Labels: lgtm, approved

#2861 Remove status section from backup schedule
  components/backup/base/oadp/backup-tenants-schedule.yaml
Labels: lgtm, approved

#2863 add resolution.tekton.dev to pipeline service sre permissions
  components/pipeline-service/base/rbac/cluster-role/pipeline-service-sre.yaml
Labels: lgtm, approved

#2865 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#2866 Promote release-service from development to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#2864 Add owner references to backup created by schedule
  components/backup/base/oadp/backup-tenants-schedule.yaml
Labels: lgtm, approved

#2862 Promote integration-service from staging to production
  components/integration/production/kustomization.yaml
Labels: lgtm, approved

#2870 chore(integration): update to the latest grafana dashboard
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#2881 RHTAPWATCH-619: Create RBAC configuration for a logging-admin
  components/monitoring/logging/base/kustomization.yaml
  components/monitoring/logging/base/rbac/kustomization.yaml
  components/monitoring/logging/base/rbac/logging-admin.yaml
Labels: lgtm, approved, jira/valid-reference

#2886 Promote release-service from development to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#2882 Remove PaC config for ec-cli repo
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#2885 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#2841 update hac-proxy for hac-e2e
  hack/hac/installHac.sh
Labels: lgtm, ok-to-test, approved

#2893 feat: Adding dashboard showing per pipeline pods consumed resources
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, approved

#2897 Fix typo in appliedclusterresourcequotas
  components/authentication/base/rhtap-admins.yaml
Labels: lgtm, approved

#2902 Promote SPI/RemoteSecret from staging to prod
  components/remote-secret-controller/overlays/production/base/kustomization.yaml
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#2894 Promote integration-service from staging to production
  components/integration/production/kustomization.yaml
Labels: lgtm, approved

#2909 fix: Fix omission in kustomize config and typo in dahboard name
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, approved

#2889 feat(STONEINTG-696): remove integration from tekton-ci
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#2908 fix(STONEINTG-694): tekton-ci - clair-in-ci-db token
  components/tekton-ci/base/external-secrets/clair-in-ci-db-github-token.yaml
Labels: lgtm, approved

#2907 Reorganize backup component to allow backing up host clusters
  components/backup/base/all-clusters/external-secret.yaml
  components/backup/base/all-clusters/kustomization.yaml
  components/backup/base/all-clusters/namespace.yaml
  components/backup/base/all-clusters/oadp/dpa.yaml
  components/backup/base/all-clusters/oadp/install-oadp.yaml
  components/backup/base/all-clusters/oadp/kustomization.yaml
  components/backup/base/host/kustomization.yaml
  components/backup/base/member/backup-tenants-schedule.yaml
  components/backup/base/member/kustomization.yaml
  components/backup/production/stone-prd-host1/kustomization.yaml
  components/backup/production/stone-prd-m01/kustomization.yaml
  components/backup/production/stone-prd-rh01/kustomization.yaml
  components/backup/staging/stone-stg-host/kustomization.yaml
  components/backup/staging/stone-stg-m01/kustomization.yaml
  components/backup/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#2915 Install OADP operator on stone-stg-host cluster
  components/backup/staging/stone-stg-host/dpa-bucket-patch.yaml
  components/backup/staging/stone-stg-host/dpa-kmskeyid-patch.yaml
  components/backup/staging/stone-stg-host/kustomization.yaml
Labels: lgtm, approved

#2920 fix(STONEINTG-694): fix broken kustomize for tekton-ci
  components/tekton-ci/base/external-secrets/kustomization.yaml
Labels: lgtm, approved

#2922 fix: segment-bridge production host configurations
  argo-cd-apps/base/host/segment-bridge/segment-bridge-host.yaml
  components/segment-bridge/production/stone-prd-host1/kustomization.yaml
Labels: lgtm, approved

#2924 Allow RHTAP admins to patch PipelineRun
  components/authentication/base/rhtap-admins.yaml
Labels: lgtm, approved

#2786 Configure RHTAP stage promotion testing setup
  .tekton/pipeline/rhtap-staging-e2e.yaml
  argo-cd-apps/base/promotion/kustomization.yaml
  argo-cd-apps/base/promotion/promotion.yaml
  argo-cd-apps/overlays/staging/kustomization.yaml
  components/promotion/base/appstudio-gitops-service-argocd-argocd-application-controller-clusterrolebinding.yaml
  components/promotion/base/appstudio-pipelines-runner-rolebinding.yaml
  components/promotion/base/external-secrets/infra-deployments-pr-creator.yaml
  components/promotion/base/external-secrets/kustomization.yaml
  components/promotion/base/external-secrets/stage-test-e2e.yaml
  components/promotion/base/kustomization.yaml
  components/promotion/base/namespace.yaml
  components/promotion/base/promotion-maintainers-rb.yaml
  components/promotion/base/repository.yaml
  components/promotion/base/serviceaccount.yaml
  components/promotion/staging/stone-stg-rh01/infra-deployments-pr-creator.yaml
  components/promotion/staging/stone-stg-rh01/kustomization.yaml
  components/promotion/staging/stone-stg-rh01/stage-test-e2e.yaml
Labels: lgtm, approved

#2925 Deploy promotion application only on stg-rh01
  argo-cd-apps/base/promotion/promotion.yaml
Labels: lgtm, approved

#2926 Grant access to secret store from rhtap-promotion-staging namespace
  components/cluster-secret-store/staging/kustomization.yaml
  components/cluster-secret-store/staging/rhtap-promotion-staging-patch.yaml
Labels: lgtm, approved

#2752 GITOPSRVCE-750: Add metric
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: approved, jira/valid-reference

#2923 Apply prd overlay patch to both segment-bridge applications
  argo-cd-apps/overlays/production/kustomization.yaml
Labels: lgtm, approved

#2932 Fix prd cluster names for segment-bridge
  argo-cd-apps/base/member/infra-deployments/segment-bridge/segment-bridge-member.yaml
Labels: lgtm, approved

#2890 fix(STONEINTG-654): remove SnapshotinvalidTotal metric
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#2934 fix prd cluster kustomization for segment-bridge
  components/segment-bridge/production/base/kustomization.yaml
Labels: lgtm, approved

#2918 Deploy backup component on prd member clusters
  components/backup/production/stone-prd-m01/dpa-bucket-patch.yaml
  components/backup/production/stone-prd-m01/dpa-kmskeyid-patch.yaml
  components/backup/production/stone-prd-m01/kustomization.yaml
  components/backup/production/stone-prd-rh01/dpa-bucket-patch.yaml
  components/backup/production/stone-prd-rh01/dpa-kmskeyid-patch.yaml
  components/backup/production/stone-prd-rh01/kustomization.yaml
Labels: lgtm, approved

#2935 Backup user registration information
  components/backup/base/host/backup-toolchain-host-schedule.yaml
  components/backup/base/host/kustomization.yaml
  components/backup/base/member/backup-toolchain-member-schedule.yaml
  components/backup/base/member/kustomization.yaml
Labels: lgtm, approved

#2936 Deploy oadp to production host cluster
  components/backup/production/stone-prd-host1/dpa-bucket-patch.yaml
  components/backup/production/stone-prd-host1/dpa-kmskeyid-patch.yaml
  components/backup/production/stone-prd-host1/kustomization.yaml
Labels: lgtm, approved

#2879 fix: PaC request annotation name
  hack/build/build-via-appstudio.sh
Labels: lgtm, approved

#2942 RHTAPSRE-279: Manifests for downstream deployment
  argo-cd-apps/app-of-app-sets/staging-downstream/change-source-path.yaml
  argo-cd-apps/app-of-app-sets/staging-downstream/change-target-namespace.yaml
  argo-cd-apps/app-of-app-sets/staging-downstream/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml
  argo-cd-apps/base/member/infra-deployments/gitops/gitops.yaml
  argo-cd-apps/base/member/infra-deployments/pipeline-service/pipeline-service.yaml
  argo-cd-apps/base/member/infra-deployments/remote-secret-controller/remote-secret-controller.yaml
  argo-cd-apps/base/member/infra-deployments/spi/spi.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/kustomization.yaml
  components/gitops/staging/stone-stage-p01/gitops-service-postgres-rds-config-path.yaml
  components/gitops/staging/stone-stage-p01/kustomization.yaml
  components/monitoring/prometheus/staging/stone-stage-p01/cluster-id-label.yaml
  components/monitoring/prometheus/staging/stone-stage-p01/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/tekton-results-s3-secret-path.yaml
  components/remote-secret-controller/overlays/staging/stone-stg-p01/aws-credentials-path-patch.yaml
  components/remote-secret-controller/overlays/staging/stone-stg-p01/config-patch.json
  components/remote-secret-controller/overlays/staging/stone-stg-p01/kustomization.yaml
  components/spi/overlays/staging/stone-stage-p01/config-patch.json
  components/spi/overlays/staging/stone-stage-p01/kustomization.yaml
  components/spi/overlays/staging/stone-stage-p01/oauth-service-config-patch.json
  components/spi/overlays/staging/stone-stage-p01/spi-aws-credentials-path-patch.yaml
  components/spi/overlays/staging/stone-stage-p01/spi-shared-configuration-file-config-path.yaml
Labels: lgtm, approved, jira/valid-reference

#2883 Add ec CLI downloads to OpenShift Console
  components/enterprise-contract/download-service.yaml
  components/enterprise-contract/kustomization.yaml
Labels: lgtm, approved

#2950 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#2951 Promote release-service from development to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#2952 Fix mismatch namespace error
  .tekton/pipeline/rhtap-staging-e2e.yaml
  .tekton/rhtap-staging-e2e-ci.yaml
  .tekton/tasks/check-pr-label.yaml
  .tekton/tasks/check-pr-rebase-label.yaml
  .tekton/tasks/component-app-name.yaml
  .tekton/tasks/get-git-token.yaml
  .tekton/tasks/get-pr-modified-files.yaml
  .tekton/tasks/merge-pr.yaml
  .tekton/tasks/rebase-pr.yaml
  .tekton/tasks/remove-pr-label.yaml
  .tekton/tasks/replace-revision.yaml
  .tekton/tasks/revert-replace-revision.yaml
  .tekton/tasks/verify-smoke-e2e.yaml
Labels: lgtm, approved

#2956 Fix staging get github token
  .tekton/tasks/get-git-token.yaml
Labels: lgtm, approved

#2954 Use PaC secret from pipeline service vault
  components/build-service/README.md
  components/build-service/base/external-secrets/pipelines-as-code-secret.yaml
  components/build-service/production/pipelines-as-code-secret-patch.yaml
Labels: lgtm, approved

#2958 feat(RHTAPWATCH-760): Smee client on DS cluster
  argo-cd-apps/base/smee-client/kustomization.yaml
  argo-cd-apps/base/smee-client/smee-client.yaml
  argo-cd-apps/overlays/staging-downstream/kustomization.yaml
  components/smee-client/deployment.yaml
  components/smee-client/kustomization.yaml
Labels: lgtm, approved

#2959 fix: update release role
  components/release/base/release-pipeline-resources-clusterrole.yaml
Labels: lgtm, approved

#2957 upgrade Pipeline Service in Prod
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
Labels: lgtm, approved

#2953 wait for Tekton CRDs to be ready
  hack/preview.sh
Labels: lgtm, approved

#2960 Deploy backup component to stone-stg-m01
  components/backup/base/all-clusters/kustomization.yaml
  components/backup/base/host/kustomization.yaml
  components/backup/base/member/kustomization.yaml
  components/backup/staging/stone-stg-m01/dpa-bucket-patch.yaml
  components/backup/staging/stone-stg-m01/dpa-kmskeyid-patch.yaml
  components/backup/staging/stone-stg-m01/kustomization.yaml
Labels: lgtm, approved

#2917 STONEBLD-1999: use new registry.redhat.io secret for e2e-tests
  components/build-templates/production/e2e-registry-redhat-io-pull-secret.yaml
  components/build-templates/production/e2e-serviceaccount.yaml
  components/build-templates/production/kustomization.yaml
  components/build-templates/staging/e2e-serviceaccount.yaml
Labels: lgtm, approved, jira/valid-reference

#2963 chore(RHTAPWATCH-670): smee-client: OWNERS&README
  components/smee-client/OWNERS
  components/smee-client/README.md
Labels: lgtm, approved

#2965 Disable Results API configuration DB SSL staging
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#2966 Disable Results API configuration DB SSL prod
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
Labels: lgtm, approved

#2968 Update build-service dashboard owners
  components/build-service/OWNERS
  components/monitoring/grafana/base/dashboards/build-service/OWNERS
Labels: lgtm, approved

#2964 RHTAPSRE-279: Update secrets paths and SPI ids
  components/gitops/staging/stone-stage-p01/gitops-service-postgres-rds-config-path.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/tekton-results-s3-secret-path.yaml
  components/remote-secret-controller/overlays/staging/stone-stg-p01/aws-credentials-path-patch.yaml
  components/remote-secret-controller/overlays/staging/stone-stg-p01/config-patch.json
  components/spi/overlays/staging/stone-stage-p01/config-patch.json
  components/spi/overlays/staging/stone-stage-p01/spi-aws-credentials-path-patch.yaml
Labels: approved, jira/valid-reference

#2971 RHTAPSRE-279: Fix the downstream cluster name for spi
  argo-cd-apps/base/member/infra-deployments/remote-secret-controller/remote-secret-controller.yaml
  argo-cd-apps/base/member/infra-deployments/spi/spi.yaml
Labels: approved, jira/valid-reference

#2972 RHTAPSRE-279: Fix overlay name for remote-secrets
  components/remote-secret-controller/overlays/staging/stone-stage-p01/aws-credentials-path-patch.yaml
  components/remote-secret-controller/overlays/staging/stone-stage-p01/config-patch.json
  components/remote-secret-controller/overlays/staging/stone-stage-p01/kustomization.yaml
Labels: approved, jira/valid-reference

#2973 Remove Ingress app from ds deployment
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
Labels: lgtm, approved

#2794 chore(RHTAPWATCH-579): Remove o11y repository from infra-deployments
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#2979 RHTAPSRE-292: Add Github app for the internal cluster
  argo-cd-apps/base/member/infra-deployments/build-service/build-service.yaml
  components/build-service/staging/base/kustomization.yaml
  components/build-service/staging/stone-stage-p01/kustomization.yaml
  components/build-service/staging/stone-stage-p01/pipelines-as-code-secret-path.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/pipelines-as-code-secret-path.yaml
Labels: approved, jira/valid-reference

#2981 RHTAPSRE-281: UI Deployment
  argo-cd-apps/base/ui/kustomization.yaml
  argo-cd-apps/base/ui/ui.yaml
  argo-cd-apps/overlays/staging-downstream/kustomization.yaml
  components/ui/README.md
  components/ui/base/chrome/chrome-frontend.yaml
  components/ui/base/chrome/kustomization.yaml
  components/ui/base/hac/hac-core-frontend.yaml
  components/ui/base/hac/hac-dev.yaml
  components/ui/base/hac/kustomization.yaml
  components/ui/base/kustomization.yaml
  components/ui/base/ns.yaml
  components/ui/base/proxy/kustomization.yaml
  components/ui/base/proxy/nginx.conf
  components/ui/base/proxy/proxy.yaml
  components/ui/staging/fed-modules.json
  components/ui/staging/kustomization.yaml
  components/ui/staging/set-hostname.yaml
  docs/_data/navigation.yml
Labels: approved, jira/valid-reference

#2982 RHTAPSRE-281: Fix source path for the UI app
  argo-cd-apps/base/ui/ui.yaml
Labels: approved, jira/valid-reference

#2984 RHTAPSRE-281: Mount empty dirs to the ui proxy
  components/ui/base/proxy/proxy.yaml
Labels: approved, jira/valid-reference

#2985 RHTAPSRE-281: Mount nginx logs volume
  components/ui/base/proxy/proxy.yaml
Labels: jira/valid-reference
