Repository redhat-appstudio/infra-deployments, pull requests merged in 2023-02, with the labels that each got.

#1259 Add build-service grafana dashboards
  components/monitoring/grafana/base/grafana-app.yaml
  components/monitoring/grafana/base/kustomization.yaml
Labels: approved

#1260 updated quality-dashboard
  components/quality-dashboard/backend/kustomization.yaml
  components/quality-dashboard/frontend/kustomization.yaml
Labels: approved

#1271 Update HAS to pull in fix for DEVHAS-228
  components/has/kustomization.yaml
Labels: lgtm, approved

#1273 grafana: move component code to subfolders
  components/monitoring/grafana/base/build-service/kustomization.yaml
  components/monitoring/grafana/base/dora-metrics/kustomization.yaml
  components/monitoring/grafana/base/kustomization.yaml
  components/monitoring/grafana/base/managed-gitops/kustomization.yaml
  components/monitoring/grafana/base/release-service/kustomization.yaml
  components/monitoring/grafana/base/spi/kustomization.yaml
Labels: lgtm, approved

#1276 Rollout keycloak dev before restarting cluster-registration
  hack/preview.sh
Labels: approved

#1282 Update quality dashboard image to latest one
  components/quality-dashboard/backend/kustomization.yaml
  components/quality-dashboard/frontend/kustomization.yaml
Labels: approved

#1285 updated quality-dashboard
  components/quality-dashboard/backend/kustomization.yaml
  components/quality-dashboard/frontend/kustomization.yaml
Labels: approved

#1270 Improve support for overriding SPI images
  hack/preview-template.env
  hack/preview.sh
Labels: approved

#1281 Enable PaC with the new annotation
  hack/build/build-via-appstudio.sh
  hack/build/templates/component.yaml
Labels: approved

#1291 Add maintainer for integration service in tektion ci namespace
  components/authentication/tekton-ci.yaml
Labels: approved

#1290 PLNSRVCE-1022: add kube-rbac-proxy related rback for sprayproxy; add sprayproxy servicemonitor; bump sprayproxy git/image sha
  components/sprayproxy/kustomization.yaml
  components/sprayproxy/servicemonitor-rbacproxy/auth-proxy-clusterrolebinding.yaml
  components/sprayproxy/servicemonitor-rbacproxy/kustomization.yaml
  components/sprayproxy/servicemonitor-rbacproxy/servicemonitor.yaml
Labels: approved, jira/valid-reference

#1293 make sprayproxy namespace name consistent across relevant repositories
  argo-cd-apps/base/host/sprayproxy/sprayproxy.yaml
  components/sprayproxy/kustomization.yaml
Labels: lgtm, approved

#1287 Configure a cut-back set of EC rules by default
  components/enterprise-contract/default-ecp.yaml
Labels: lgtm, approved

#1302 Update pipeline-service component to work on the new staging environment
  components/authentication/pipeline-service-sre.yaml
  components/pipeline-service/kustomization.yaml
Labels: approved

#1257 add SLI dashboard for HAS
  components/monitoring/grafana/base/grafana-app.yaml
  components/monitoring/grafana/base/has/kustomization.yaml
  components/monitoring/grafana/base/kustomization.yaml
Labels: lgtm, approved

#1235 doc: how to add a new grafana dashboard
  components/monitoring/README.md
Labels: lgtm, approved

#1305 Update GitOps Maintainers and maintainer role: fix duplicate role names in kustomize.yaml
  components/authentication/gitops.yaml
  components/authentication/kustomization.yaml
Labels: approved

#1308 Update gitops roles feb 2023
  components/authentication/gitops-component-maintainer.yaml
  components/authentication/gitops.yaml
  components/authentication/kustomization.yaml
Labels: approved

#1309 Update GitOps Component Maintainer Role YAML: fix quotes
  components/authentication/gitops-component-maintainer.yaml
Labels: approved

#1310 GitOps Service: Update to latest dashboard contents on managed-gitops repository
  components/monitoring/grafana/base/managed-gitops/kustomization.yaml
Labels: approved

#1312 GitOps Service: Update to latest dashboard contents on managed-gitops repository
  components/monitoring/grafana/base/managed-gitops/kustomization.yaml
Labels: approved

#1313 Add GitOps Service Dashboard references to Grafana Deployment/ConfigMap
  components/monitoring/grafana/base/grafana-app.yaml
Labels: approved

#1272 STONEBLD-27: continue cleaning up the rest related to removed build-pipelines-defaults configmap
  components/build-service/README.md
  components/build-templates/1-read-cm.yaml
  components/build-templates/2-read-cm-binding.yaml
  components/build-templates/kustomization.yaml
  hack/preview.sh
Labels: jira/valid-reference

#1304 Added ServiceMonitor for pipeline-service
  components/monitoring/prometheus/base/servicemonitors/kustomization.yaml
  components/monitoring/prometheus/base/servicemonitors/pipeline-service.yaml
Labels: lgtm, approved

#1316 GitOps: multi-cluster - Move to GitOps' Stonesoup member cluster kustomize overlay
  components/authentication/gitops.yaml
  components/gitops/staging/kustomization.yaml
Labels: approved

#1318 GitOps: update dashboard URL
  components/monitoring/grafana/base/managed-gitops/kustomization.yaml
Labels: approved

#1319 Update Application service
  components/has/kustomization.yaml
  components/monitoring/grafana/base/has/kustomization.yaml
Labels: lgtm, approved

#1321 Update pipeline service to have the custom exporter changes
  components/pipeline-service/kustomization.yaml
Labels: lgtm, approved

#1315 Fix typo in keycloak config
  hack/preview.sh
Labels: ok-to-test

#1323 Add external secret for spi
  cluster-config/staging/member-base/namespaces/kustomization.yaml
  cluster-config/staging/member-base/namespaces/spi-system/kustomization.yaml
  cluster-config/staging/member-base/namespaces/spi-system/spi-shared-configuration-file.yaml
  cluster-config/staging/member-base/namespaces/spi-system/spi-vault-approle-spi-oauth.yaml
  cluster-config/staging/member-base/namespaces/spi-system/spi-vault-approle-spi-operator.yaml
  cluster-config/staging/stone-stg-m01/kustomization.yaml
  cluster-config/staging/stone-stg-m01/spi-shared-configuration-file-config-path.yaml
  cluster-config/staging/stone-stg-m01/spi-vault-approle-spi-oauth-config-path.yaml
  cluster-config/staging/stone-stg-m01/spi-vault-approle-spi-operator-config-path.yaml
  cluster-config/staging/stone-stg-rh01/kustomization.yaml
  cluster-config/staging/stone-stg-rh01/spi-shared-configuration-file-config-path.yaml
  cluster-config/staging/stone-stg-rh01/spi-vault-approle-spi-oauth-config-path.yaml
  cluster-config/staging/stone-stg-rh01/spi-vault-approle-spi-operator-config-path.yaml
Labels: approved

#1295 chore: updates CRD for InternalRequests
  components/internal-services/kustomization.yaml
Labels: lgtm, approved

#1327 update pipeline service to use latest metrics image
  components/pipeline-service/kustomization.yaml
Labels: lgtm, approved

#1324 STONE-445 - Fix handling of toolchain and keycloak parameters
  hack/bootstrap-cluster.sh
  hack/preview.sh
Labels: approved

#1344 update quality dashboard
  components/quality-dashboard/backend/kustomization.yaml
  components/quality-dashboard/frontend/kustomization.yaml
Labels: approved

#1347 add image-controller to main CI
  components/tekton-ci/repository.yaml
Labels: approved

#1350 feat(ASC-262): Deploy applications from main
  argo-cd-apps/base/host/sprayproxy/kustomization.yaml
  argo-cd-apps/base/host/sprayproxy/sprayproxy.yaml
  argo-cd-apps/k-components/inject-infra-deployments-repo-details/application-patch.yaml
  argo-cd-apps/k-components/inject-infra-deployments-repo-details/application-set-patch.yaml
Labels: lgtm, approved

#1351 Use shared public key in default ECP
  components/enterprise-contract/default-ecp.yaml
Labels: lgtm, approved

#1361 Add external secrets for dora-metrics and quality dashboard
  argo-cd-apps/base/all-clusters/infra-deployments/dora-metrics/dora-metrics.yaml
  argo-cd-apps/base/local-cluster-secret/all-in-one/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/quality-dashboard/kustomization.yaml
  argo-cd-apps/base/quality-dashboard/quality-dashboard.yaml
  argo-cd-apps/k-components/deploy-to-all-clusters/all-clusters-label-selector.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/staging/kustomization.yaml
  components/dora-metrics/base/kustomization.yaml
  components/dora-metrics/development/kustomization.yaml
  components/dora-metrics/staging/external-secrets/exporters-secrets.yaml
  components/dora-metrics/staging/external-secrets/kustomization.yaml
  components/dora-metrics/staging/kustomization.yaml
  components/quality-dashboard/base/backend/kustomization.yaml
  components/quality-dashboard/base/frontend/kustomization.yaml
  components/quality-dashboard/base/kustomization.yaml
  components/quality-dashboard/development/kustomization.yaml
  components/quality-dashboard/staging/external-secrets/kustomization.yaml
  components/quality-dashboard/staging/external-secrets/quality-dashboard-secrets.yaml
  components/quality-dashboard/staging/kustomization.yaml
Labels: lgtm

#1358 Move tekton-ci rb to the component's dir
  components/authentication/staging/kustomization.yaml
  components/tekton-ci/kustomization.yaml
  components/tekton-ci/tekton-ci-maintainers-rb.yaml
Labels: lgtm, approved

#1368 docs: fixed wrong url for development config
  docs/development/deployment.md
Labels: lgtm, approved

#1369 Fix source path for quality-dashboard
  argo-cd-apps/base/quality-dashboard/quality-dashboard.yaml
Labels: approved

#1356 Added external secret for prometheus
  components/monitoring/prometheus/base/external-secrets/kustomization.yaml
  components/monitoring/prometheus/base/external-secrets/monitoring-prometheus-oauth-config.yaml
  components/monitoring/prometheus/stagging/base/kustomization.yaml
  components/monitoring/prometheus/stagging/stone-stg-m01/kustomization.yaml
  components/monitoring/prometheus/stagging/stone-stg-m01/monitoring-prometheus-oauth-config-path.yaml
  components/monitoring/prometheus/stagging/stone-stg-rh01/kustomization.yaml
  components/monitoring/prometheus/stagging/stone-stg-rh01/monitoring-prometheus-oauth-config-path.yaml
Labels: lgtm, approved

#1385 Support overlays in the Prometheus app
  argo-cd-apps/base/member/infra-deployments/monitoring-workload-prometheus/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
Labels: lgtm, approved

#1389 Fix source path for sprayproxy
  argo-cd-apps/base/host/sprayproxy/sprayproxy.yaml
Labels: approved

#1390 Move tekton-ci from stage to prod
  argo-cd-apps/overlays/production/kustomization.yaml
  argo-cd-apps/overlays/staging/kustomization.yaml
Labels: approved

#1382 Update keycloak user
  components/dev-sso/keycloak-realm.yaml
Labels: approved

#1375 feat: Enable deployment from release-service PRs
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm

#1392 STONEBLD-777: tekton-ci - define External-secrets
  argo-cd-apps/base/tekton-ci/tekton-ci.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
  components/tekton-ci/base/external-secrets/infra-deployments-pr-creator.yaml
  components/tekton-ci/base/external-secrets/kustomization.yaml
  components/tekton-ci/base/external-secrets/tekton-ci-push-secret.yaml
  components/tekton-ci/base/kustomization.yaml
  components/tekton-ci/base/namespace.yaml
  components/tekton-ci/base/pvc.yaml
  components/tekton-ci/base/repository.yaml
  components/tekton-ci/base/serviceaccount.yaml
  components/tekton-ci/base/tekton-ci-maintainers-rb.yaml
  components/tekton-ci/production/infra-deployments-pr-creator.yaml
  components/tekton-ci/production/kustomization.yaml
  components/tekton-ci/production/tekton-ci-push-secret.yaml
  components/tekton-ci/serviceaccount.yaml
  components/tekton-ci/staging/kustomization.yaml
Labels: approved, jira/valid-reference

#1393 tekton-ci: limit cluster where to deploy and remove PVC
  argo-cd-apps/base/tekton-ci/tekton-ci.yaml
  components/tekton-ci/base/kustomization.yaml
  components/tekton-ci/base/pvc.yaml
Labels: approved

#1394 tekton-ci: fix generator to deploy only to labeled cluster
  argo-cd-apps/base/tekton-ci/tekton-ci.yaml
Labels: approved

#1396 Allow use external-secrets in tekton-ci namespace
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: approved

#1395 Update group-sync configurations
  components/authentication/production/github-redhat-appstudio-secret-patch.yaml
  components/authentication/production/github-redhat-appstudio-sre-secret-patch.yaml
  components/authentication/production/kustomization.yaml
Labels: approved

#1387 fix: Dashboard Secret error
  components/quality-dashboard/base/backend/kustomization.yaml
  components/quality-dashboard/base/frontend/kustomization.yaml
Labels: lgtm, approved

#1378 deploy pipeline-service customized SHA
  hack/preview.sh
Labels: lgtm, approved

#1404 Remove unused shared secrets
  components/shared-resources/globally-shared-secrets-clusterrole.yaml
  components/shared-resources/infra-deployments-pr-creator.yaml
  components/shared-resources/kustomization.yaml
  components/shared-resources/redhat-appstudio-staginguser-secret.yaml
  components/shared-resources/shared-resources-components.yaml
  components/shared-resources/snyk-shared-secret.yaml
Labels: approved

#1407 Skip on missing
  components/authentication/base/group-sync/github-redhat-appstudio-sre.yaml
  components/authentication/base/group-sync/github-redhat-appstudio.yaml
  components/gitops/production/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#1353 STONEBLD-40 Add JVM Build Service Dashboard
  components/monitoring/grafana/base/grafana-app.yaml
  components/monitoring/grafana/base/jvm-build-service/kustomization.yaml
  components/monitoring/grafana/base/kustomization.yaml
Labels: approved

#1411 [prd-m01] Setup SPI configuration for prod
  components/spi/overlays/production/stone-prd-m01/config-patch.json
  components/spi/overlays/production/stone-prd-m01/oauth-service-config-patch.json
  components/spi/overlays/production/stone-prd-m01/spi-shared-configuration-file-config-path.yaml
  components/spi/overlays/production/stone-prd-m01/spi-vault-approle-spi-oauth-config-path.yaml
  components/spi/overlays/production/stone-prd-m01/spi-vault-approle-spi-operator-config-path.yaml
Labels: approved

#1412 Remove test-team authentication
  components/authentication/base/kustomization.yaml
  components/authentication/base/test-team.yaml
  components/build-service/README.md
Labels: approved

#1417 Setup SPI configuration for prod/rh01
  components/spi/overlays/production/stone-prd-rh01/config-patch.json
  components/spi/overlays/production/stone-prd-rh01/oauth-service-config-patch.json
  components/spi/overlays/production/stone-prd-rh01/spi-shared-configuration-file-config-path.yaml
  components/spi/overlays/production/stone-prd-rh01/spi-vault-approle-spi-oauth-config-path.yaml
  components/spi/overlays/production/stone-prd-rh01/spi-vault-approle-spi-operator-config-path.yaml
Labels: approved

#1314 Add image controller
  argo-cd-apps/base/member/infra-deployments/image-controller/image-controller.yaml
  argo-cd-apps/base/member/infra-deployments/image-controller/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
  components/image-controller/base/OWNERS
  components/image-controller/base/allow-argocd-to-manage.yaml
  components/image-controller/base/kustomization.yaml
  components/image-controller/base/manager_resources_patch.yaml
  components/image-controller/development/kustomization.yaml
  components/image-controller/production/kustomization.yaml
  components/image-controller/production/quaytoken.yaml
  components/image-controller/staging/kustomization.yaml
  hack/bootstrap-member-cluster.sh
  hack/build/build-via-appstudio.sh
  hack/preview-template.env
  hack/preview.sh
  hack/secret-creator/create-image-controller-secret.sh
Labels: approved

#1419 fix: image controller - add external-secrets
  components/image-controller/base/external-secrets/kustomization.yaml
  components/image-controller/base/external-secrets/quaytoken.yaml
  components/image-controller/production/kustomization.yaml
Labels: approved

#1422 STONEO11Y-27: Add CI for o11y
  components/tekton-ci/base/repository.yaml
Labels: approved
