Repository redhat-appstudio/infra-deployments, pull requests merged in 2023-09, with the labels that each got.

#2326 Add manish-janga to OWNERS file
  OWNERS
Labels: lgtm, approved

#2339 fix: avoid deploying sandbox clusterroles in dev mode
  components/sandbox/toolchain-member-operator/development/kustomization.yaml
  hack/bootstrap-cluster.sh
Labels: lgtm, approved

#2236 fix(perf dashboards): Two dashboards had same UID
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, approved

#2342 RHTAP-1201: Fix the path to the secret engine
  components/cluster-secret-store-rh/base/appsre-stonesoup-vault-rh-secret-store.yaml
Labels: lgtm, approved, jira/valid-reference

#2291 Add IBM cloud VMs
  components/multi-arch-controller/base/host-config.yaml
Labels: lgtm, approved

#2358 Add mmorhun to image-controller owners
  components/image-controller/OWNERS
Labels: lgtm, approved

#2334 hac-e2e: update to bonfire 4.18
  hack/hac/installHac.sh
Labels: lgtm, ok-to-test, approved

#2350 Remove pipelines-as-code namespace refs staging
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
  components/pipeline-service/base/external-secrets/kustomization.yaml
  components/pipeline-service/base/external-secrets/pipelines-as-code/kustomization.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/base/pipelines-as-code-secret-deleteme.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/pipelines-as-code-namespace.yaml
Labels: lgtm, approved

#2366 Remove pipelines-as-code namespace refs production
  components/pipeline-service/base/rbac/kustomization.yaml
  components/pipeline-service/base/rbac/pipelines-as-code/kustomization.yaml
  components/pipeline-service/base/rbac/pipelines-as-code/role-binding.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/base/pipelines-as-code-namespace.yaml
  components/pipeline-service/production/base/pipelines-as-code-secret-deleteme.yaml
Labels: lgtm, approved

#2371 Add mmorhun to build-service grafana dashboard owners
  components/monitoring/grafana/base/dashboards/build-service/OWNERS
Labels: lgtm, approved

#2374 Ignore differences for build request annotation
  argo-cd-apps/base/tenants-config/tenants-config.yaml
Labels: lgtm, approved

#2372 Remove PaC ConfigMap Prod
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/base/pipelines-as-code-secret-path.yaml
  components/pipeline-service/production/base/update-tekton-config-pac.yaml
Labels: lgtm, approved

#2388 fixed an issue in setup pac script
  hack/build/setup-pac-integration.sh
Labels: lgtm, approved

#2364 remove references to chains ns
  components/cluster-secret-store/staging/cluster-secret-store-patch.yaml
  components/cluster-secret-store/staging/kustomization.yaml
  components/pipeline-service/base/rbac/kustomization.yaml
  components/pipeline-service/base/rbac/tekton-chains/kustomization.yaml
  components/pipeline-service/base/rbac/tekton-chains/role-binding.yaml
  hack/bootstrap-cluster.sh
  hack/destroy-cluster.sh
Labels: lgtm, approved

#2399 Use new location for EC policy data references
  components/enterprise-contract/ecp.yaml
Labels: lgtm, approved

#2396 Update sprayproxy production
  components/sprayproxy/production/kustomization.yaml
Labels: lgtm, approved

#2400 Add tekton-results roles
  components/pipeline-service/base/rbac/cluster-role/pipeline-service-sre.yaml
Labels: lgtm, approved

#2402 service-provider-integration-operator update with e2e fix
  components/monitoring/grafana/base/dashboards/spi/kustomization.yaml
  components/spi-vault/kustomization.yaml
  components/spi/overlays/development/kustomization.yaml
Labels: lgtm, approved

#2408 Remove git:: prefix from resources urls in pipeline-service
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#2416 Michkov - Bye, Bye
  components/authentication/base/group-sync/group-sync.yaml
  components/build-service/OWNERS
  components/build-service/base/rbac/build-maintainer.yaml
  components/image-controller/base/OWNERS
  components/integration/integration.yaml
  components/internal-services/internal-services.yaml
  components/jvm-build-service/OWNERS
  components/jvm-build-service/base/rbac/jvm-build-maintainer.yaml
  components/release/release-team.yaml
  components/spi/base/rbac/spi.yaml
  components/sprayproxy/OWNERS
  components/tekton-ci/base/tekton-ci-maintainers-rb.yaml
Labels: approved

#2393 Create rhtap-admins cluster role and binding
  components/authentication/base/kustomization.yaml
  components/authentication/base/rhtap-admins.yaml
Labels: lgtm, approved

#2398 fix(RHTAPWATCH-515): stop forwarding argocd metrics to rhobs
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#2422 Grant rhtap-admins access to user.openshift.io resources
  components/authentication/base/rhtap-admins.yaml
Labels: lgtm, approved

#2411 Add plnsvc-codecov secret
  components/tekton-ci/production/kustomization.yaml
  components/tekton-ci/production/plnsvc-codecov-secret.yaml
Labels: lgtm, approved

#2381 Allow build team to list and view SA and list secrets
  components/build-service/base/rbac/build-maintainer.yaml
Labels: lgtm, approved

#2407 managed-gitops update: Cherry pick #2401 to staging only: update components/gitops/staging/base/kustomization.yaml
  components/gitops/staging/base/kustomization.yaml
Labels: approved

#2426 Grant rhtap-admins read access to rolebindings and clusterrolebindings
  components/authentication/base/rhtap-admins.yaml
Labels: lgtm, approved

#2427 bump pipeline-service prod to the same level that has been vetted in stage
  components/pipeline-service/production/base/kustomization.yaml
Labels: lgtm, approved

#2430 Increase the frequency of PaC secret refresh
  components/pipeline-service/production/base/pipelines-as-code-secret.yaml
  components/pipeline-service/staging/base/pipelines-as-code-secret.yaml
  components/sprayproxy/production/pipelines-as-code-secret.yaml
  components/sprayproxy/staging/pipelines-as-code-secret.yaml
Labels: lgtm, approved

#2385 Simplify RBACs for pipeline-service
  components/pipeline-service/base/rbac/cluster-role/kustomization.yaml
  components/pipeline-service/base/rbac/cluster-role/pipeline-maintainer.yaml
  components/pipeline-service/base/rbac/cluster-role/pipeline-service-sre.yaml
Labels: approved

#2390 update HAS owners file and rbac
  components/has/OWNERS
  components/has/base/rbac/has-admin.yaml
  components/has/base/rbac/has.yaml
  components/monitoring/grafana/base/dashboards/has/OWNERS
Labels: lgtm, approved

#2405 Install dvo on rhtap clusters
  argo-cd-apps/base/all-clusters/infra-deployments/enable-dvo-for-all-cluster/enable-dvo.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/enable-dvo-for-all-cluster/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
  configs/enable-dvo-for-all-cluster/configure-dvo.yaml
  configs/enable-dvo-for-all-cluster/install-dvo.yaml
  configs/enable-dvo-for-all-cluster/kustomization.yaml
Labels: lgtm, approved

#2432 HACBS-2658: allow rhtap-admins to create rolebindings
  components/authentication/base/rhtap-admins.yaml
Labels: lgtm, approved, jira/valid-reference

#2392 Update multi platform config
  components/multi-arch-controller/OWNERS
  components/multi-arch-controller/base/host-config.yaml
Labels: lgtm, approved

#2436 Remove dvo from rhtap dev and CI
  argo-cd-apps/overlays/development/delete-applications.yaml
  configs/enable-dvo-for-all-cluster/install-dvo.yaml
Labels: lgtm, approved

#2437 Set connectionIdleTimeout for the Default Ingress Controller
  argo-cd-apps/base/host/ingresscontroller/ingresscontroller.yaml
  argo-cd-apps/base/host/ingresscontroller/kustomization.yaml
  argo-cd-apps/base/host/kustomization.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  configs/ingresscontroller/kustomization.yaml
  configs/ingresscontroller/timeout-patch.yaml
Labels: lgtm, approved

#2438 Add new redhat-no-hermetic ECP
  components/enterprise-contract/ecp.yaml
Labels: lgtm, approved

#2446 RHTAPREL-435: migrate to tenants-config
  argo-cd-apps/base/ci-workspaces/ci-workspaces.yaml
  argo-cd-apps/base/ci-workspaces/kustomization.yaml
  ci/teams/kustomization.yaml
  ci/teams/rhtap-build/external-secrets/infra-deployments-pr-creator.yaml
  ci/teams/rhtap-build/external-secrets/kustomization.yaml
  ci/teams/rhtap-build/kustomization.yaml
  ci/teams/rhtap-build/release.yaml
  ci/teams/rhtap-gitops/kustomization.yaml
  ci/teams/rhtap-gitops/release.yaml
  ci/teams/rhtap-servicerelease/ec-policy.yaml
  ci/teams/rhtap-servicerelease/external-secrets/infra-deployments-pr-creator.yaml
  ci/teams/rhtap-servicerelease/external-secrets/kustomization.yaml
  ci/teams/rhtap-servicerelease/external-secrets/pyxis-secret.yaml
  ci/teams/rhtap-servicerelease/external-secrets/slack-webhook-notification-secret.yaml
  ci/teams/rhtap-servicerelease/kustomization.yaml
  ci/teams/rhtap-servicerelease/persistent-volume-claim.yaml
  ci/teams/rhtap-servicerelease/release-build.yaml
  ci/teams/rhtap-servicerelease/release-external-secrets.yaml
  ci/teams/rhtap-servicerelease/release-pipeline-sa.yaml
  ci/teams/rhtap-servicerelease/release-service-account-build-rb.yaml
  ci/teams/rhtap-servicerelease/release-service-account-external-secrets-rb.yaml
  ci/teams/rhtap-servicerelease/release-strategy.yaml
Labels: lgtm, approved, jira/valid-reference

#2447 RHTAPREL-435: fix missing overlay
  argo-cd-apps/overlays/production/kustomization.yaml
Labels: approved, jira/valid-reference

#2456 RHTAPREL-435: remove release-service from tekton-ci
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved, jira/valid-reference

#2457 Removed component maintainer cluster role from the following components
  components/jvm-build-service/base/kustomization.yaml
  components/jvm-build-service/base/rbac/jvm-build-maintainer.yaml
  components/jvm-build-service/base/rbac/kustomization.yaml
  components/multi-platform-controller/base/rbac/kustomization.yaml
  components/multi-platform-controller/base/rbac/role-binding.yaml
  components/multi-platform-controller/development/kustomization.yaml
  components/multi-platform-controller/staging/kustomization.yaml
Labels: lgtm, approved

#2462 Fix RBACs for Pipeline Service
  components/pipeline-service/base/rbac/openshift-pipelines/pipeline-service-sre.yaml
  components/pipeline-service/base/rbac/tekton-results/pipeline-service-sre.yaml
Labels: lgtm, approved

#2463 bump pipeline-service prod to the same level that has been vetted in stage
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
  components/cluster-secret-store/staging/cluster-secret-store-patch.yaml
  components/cluster-secret-store/staging/kustomization.yaml
  components/pipeline-service/production/base/kustomization.yaml
Labels: lgtm, approved

#2464 release-service update
  components/monitoring/grafana/base/dashboards/release/kustomization.yaml
  components/release/kustomization.yaml
Labels: lgtm, approved

#2466 STONEBLD-1787 deploy multi-platform-controller on prod
  argo-cd-apps/overlays/production/delete-applications.yaml
  argo-cd-apps/overlays/production/kustomization.yaml
  components/multi-platform-controller/base/external-secrets/awskeys.yaml
  components/multi-platform-controller/base/host-config.yaml
  components/multi-platform-controller/base/kustomization.yaml
  components/multi-platform-controller/production/external-secrets.yaml
  components/multi-platform-controller/production/host-config.yaml
  components/multi-platform-controller/production/kustomization.yaml
  components/multi-platform-controller/staging/external-secrets.yaml
  components/multi-platform-controller/staging/host-config.yaml
  components/multi-platform-controller/staging/kustomization.yaml
Labels: lgtm, approved

#2469 Fix multi-platform-controller issues
  components/multi-platform-controller/production/external-secrets.yaml
  components/multi-platform-controller/production/kustomization.yaml
  components/multi-platform-controller/staging/external-secrets.yaml
  components/multi-platform-controller/staging/host-config.yaml
  components/multi-platform-controller/staging/kustomization.yaml
Labels: lgtm, approved

#2454 chore(RHTAPWATCH-518): deploy grafana probe from o11y repo
  components/monitoring/grafana/base/dashboards/kustomization.yaml
  components/monitoring/grafana/base/kustomization.yaml
Labels: lgtm, approved

#2468 Ignore image annotations in Components
  argo-cd-apps/base/tenants-config/tenants-config.yaml
Labels: lgtm, approved
