Repository redhat-appstudio/infra-deployments, pull requests merged in 2024-11, with the labels that each got.

#4817 Update osp stage
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4822 Update CatalogSource mem target to avoid eviction
  components/sandbox/toolchain-member-operator/base/olm/toolchain-member-operator.yaml
Labels: lgtm, approved

#4823 Further reduce maximum application age
  components/tekton-ci/production/cleanup-cronjob.yaml
Labels: lgtm, approved

#4834 Expose the appsre subscription/pull secrets to hcm-eng-prod tenant
  components/cluster-secret-store-rh/base/insights-secret-store.yaml
Labels: lgtm, ok-to-test, approved

#4840 fix(KFLUXBUGS-1764): update staging notification controller
  components/notification-controller/development/kustomization.yaml
Labels: lgtm, approved

#4839 Update OSP prod-m01
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/resources/osp-nightly-version.yaml
Labels: lgtm, approved

#4842 Set number of buckets for OSP resolver controllers
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: approved

#4843 Increase OSP remote resolver replicas to 2
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: approved

#4844 Increase OSP resolvers to 4 replicas
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: approved

#4845 Increase OSP remote resolver replicas to 4
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4847 feat: Added graphs for Tekton Resolver resources and leases
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, approved

#4849 fix(KFLUXBUGS-1764): update staging notification controller
  components/notification-controller/staging/kustomization.yaml
Labels: lgtm, approved

#4850 fix(KFLUXBUGS-1764): update notification-controller production
  components/notification-controller/production/kustomization.yaml
Labels: lgtm, approved

#4852 fix(KFLUXINFRA-777): Adding Error Handling in mount.sh Script
  configs/nvme-storage-configurator/base/install.sh
  configs/nvme-storage-configurator/base/mount.sh
Labels: lgtm, approved

#4860 Align internal stage configuration with the prod one for testing
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#4861 Increase memory of MPC on prd-rh01
  components/multi-platform-controller/production/kustomization.yaml
  components/multi-platform-controller/production/manager_resources_patch.yaml
Labels: approved

#4862 Increase MPC controller to 16Gi
  components/multi-platform-controller/production/manager_resources_patch.yaml
Labels: approved

#4866 fix(KFLUXINFRA-777): Adding a readonly variable in install.sh script
  configs/nvme-storage-configurator/base/install.sh
Labels: lgtm, approved

#4858 chore: project-controller production update
  components/project-controller/production/kustomization.yaml
Labels: lgtm, approved

#4865 chore: separate build and integration pipelineruns in logging
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#4856 update osp prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/resources/osp-nightly-version.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4873 update osp dev and stage
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4874 Update mpc to the latest staging-tested version
  components/multi-platform-controller/production-downstream/host-config.yaml
  components/multi-platform-controller/production-downstream/kustomization.yaml
  components/multi-platform-controller/production/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-m01/kustomization.yaml
Labels: lgtm, approved

#4877 update osp on prod-m01
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/resources/osp-nightly-channel.yaml
  components/pipeline-service/production/stone-prd-m01/resources/osp-nightly-version.yaml
Labels: lgtm, approved

#4878 add perf flags to resolvers on prod-m01
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/resources/osp-perf-resolvers.yaml
Labels: lgtm, approved

#4879 update osp prod-rh01 and prod-p01
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/osp-nightly-channel.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/osp-nightly-version.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/osp-perf-resolvers.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prod-p01/resources/osp-nightly-channel.yaml
  components/pipeline-service/production/stone-prod-p01/resources/osp-nightly-version.yaml
  components/pipeline-service/production/stone-prod-p01/resources/osp-perf-resolvers.yaml
Labels: lgtm, approved

#4869 feat(KONFLUX-5352): Workaround frequent restarts on stone-prd-rh01
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
Labels: lgtm, approved

#4871 feat(KONFLUX-5350): Long term resource usage is far above requests, adding more
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4882 fix logs compression in staging p01
  components/monitoring/logging/staging/stone-stage-p01/configure-logforwarder-compression-patch.yaml
Labels: lgtm, approved

#4885 fix kubearchive PostrgreSQL deployment
  components/kubearchive/development/postgresql.yaml
Labels: lgtm, approved

#4886 update osp stage
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4887 update osp on prd m01 rh01 p01
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/resources/osp-nightly-version.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/osp-nightly-version.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/resources/osp-nightly-version.yaml
Labels: lgtm, approved

#4872 fix: increase memory limit
  components/release/k-components/manager-resources-patch/manager_resources_patch.yaml
Labels: lgtm, approved

#4880 fix: increases memory request/limit for release deletion pod
  components/release/base/cronjobs/remove-expired-releases.yaml
Labels: lgtm, approved

#4894 chore: promote project-controller to production
  components/project-controller/production/kustomization.yaml
Labels: lgtm, approved

#4899 Upgrade MCE to 2.7 in dev and staging
  components/cluster-as-a-service/development/add-hypershift-params.yaml
  components/cluster-as-a-service/development/kustomization.yaml
  components/cluster-as-a-service/staging/add-hypershift-params.yaml
  components/cluster-as-a-service/staging/kustomization.yaml
Labels: lgtm, approved

#4897 Remove specific configuration for MPC stone-prd-m01
  argo-cd-apps/base/member/infra-deployments/multi-platform-controller/multi-platform-controller.yaml
  components/multi-platform-controller/production/common/kustomization.yaml
  components/multi-platform-controller/production/external-secrets.yaml
  components/multi-platform-controller/production/host-config.yaml
  components/multi-platform-controller/production/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-m01/kustomization.yaml
Labels: lgtm, approved

#4901 Upgrade MCE to 2.7 in production
  components/cluster-as-a-service/base/multicluster-engine.yaml
  components/cluster-as-a-service/development/kustomization.yaml
  components/cluster-as-a-service/production/add-hypershift-params.yaml
  components/cluster-as-a-service/staging/kustomization.yaml
Labels: lgtm, approved

#4797 Create overlays for new kflux-ocp-p01 cluster
  argo-cd-apps/base/all-clusters/infra-deployments/authentication/authentication.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml
  argo-cd-apps/base/host/toolchain-host-operator/toolchain-host-operator.yaml
  argo-cd-apps/base/keycloak/keycloak.yaml
  argo-cd-apps/base/member/infra-deployments/build-service/build-service.yaml
  argo-cd-apps/base/member/infra-deployments/integration/integration.yaml
  argo-cd-apps/base/member/infra-deployments/mintmaker/mintmaker.yaml
  argo-cd-apps/base/member/infra-deployments/pipeline-service/pipeline-service.yaml
  argo-cd-apps/base/smee-client/smee-client.yaml
  argo-cd-apps/base/ui/ui.yaml
  components/backup/production/kflux-ocp-p01/backup-s3-credentials-patch.yaml
  components/backup/production/kflux-ocp-p01/dpa-bucket-patch.yaml
  components/backup/production/kflux-ocp-p01/dpa-kmskeyid-patch.yaml
  components/backup/production/kflux-ocp-p01/kustomization.yaml
  components/build-service/production/kflux-ocp-p01/kustomization.yaml
  components/build-service/production/kflux-ocp-p01/pipelines-as-code-secret-path.yaml
  components/build-service/production/kflux-ocp-p01/webhook-config.json
  components/integration/production/kflux-ocp-p01/console-url-config-patch.json
  components/integration/production/kflux-ocp-p01/kustomization.yaml
  components/integration/production/kflux-ocp-p01/pipelines-as-code-secret-path.yaml
  components/keycloak/production/kflux-ocp-p01/kustomization.yaml
  components/keycloak/production/kflux-ocp-p01/set-ocp-idp.yaml
  components/keycloak/production/kflux-ocp-p01/set-redirect-uri.yaml
  components/mintmaker/production/kflux-ocp-p01/kustomization.yaml
  components/mintmaker/production/kflux-ocp-p01/pipelines-as-code-secret-path.yaml
  components/monitoring/logging/production/kflux-ocp-p01/kustomization.yaml
  components/monitoring/prometheus/production/kflux-ocp-p01/cluster-id-label.yaml
  components/monitoring/prometheus/production/kflux-ocp-p01/kustomization.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-ocp-p01/kustomization.yaml
  components/pipeline-service/production/kflux-ocp-p01/resources/kustomization.yaml
  components/pipeline-service/production/kflux-ocp-p01/resources/pipelines-as-code-secret-path.yaml
  components/pipeline-service/production/kflux-ocp-p01/resources/tekton-chains-public-key-path.yaml
  components/pipeline-service/production/kflux-ocp-p01/resources/tekton-chains-signing-secret-path.yaml
  components/pipeline-service/production/kflux-ocp-p01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/kflux-ocp-p01/resources/tekton-results-s3-secret-path.yaml
  components/pipeline-service/production/kflux-ocp-p01/resources/update-tekton-config-pac.yaml
  components/sandbox/toolchain-host-operator/production/kflux-ocp-p01/kustomization.yaml
  components/sandbox/toolchain-host-operator/production/kflux-ocp-p01/network-policy.yaml
  components/sandbox/toolchain-host-operator/production/kflux-ocp-p01/space-provisioner-configs.yaml
  components/sandbox/toolchain-host-operator/production/kflux-ocp-p01/toolchainconfig.yaml
  components/smee-client/production/kflux-ocp-p01/kustomization.yaml
  components/smee-client/production/kflux-ocp-p01/sever-url-patch.yaml
  components/ui/production/kflux-ocp-p01/fed-modules.json
  components/ui/production/kflux-ocp-p01/kustomization.yaml
  components/ui/production/kflux-ocp-p01/set-hostname.yaml
Labels: approved

#4900 Configure MPC memory for staging and production
  components/multi-platform-controller/k-components/manager-resources/kustomization.yaml
  components/multi-platform-controller/k-components/manager-resources/manager_resources_patch.yaml
  components/multi-platform-controller/production-downstream/kustomization.yaml
  components/multi-platform-controller/production/kustomization.yaml
  components/multi-platform-controller/staging-downstream/kustomization.yaml
  components/multi-platform-controller/staging/kustomization.yaml
Labels: lgtm, approved

#4909 update osp stage
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4911 update osp prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/resources/osp-nightly-channel.yaml
  components/pipeline-service/production/stone-prd-m01/resources/osp-nightly-version.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/osp-nightly-channel.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/osp-nightly-version.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prod-p01/resources/osp-nightly-channel.yaml
  components/pipeline-service/production/stone-prod-p01/resources/osp-nightly-version.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4919 KFLUXINFRA-903: Remove additional routing to support route from TGW
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: approved

#4920 KFLUXINFRA-1000: Remove routing setup to support TGW route prod internal
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: approved

#4930 Fix PAC secret in production build service
  components/build-service/production/base/kustomization.yaml
Labels: lgtm, approved

#4925 update hac-dev ui to latest(9522a36)
  components/ui/development/kustomization.yaml
  components/ui/production/kflux-ocp-p01/kustomization.yaml
  components/ui/production/stone-prod-p01/kustomization.yaml
  components/ui/production/stone-prod-p02/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#4924 Promote MPC staging to production
  components/multi-platform-controller/production-downstream/kustomization.yaml
  components/multi-platform-controller/production/kustomization.yaml
Labels: lgtm, approved

#4933 chore: promote project-controller to production
  components/project-controller/production/kustomization.yaml
Labels: lgtm, approved

#4934 fix(KFLUXINFRA-921): Fixing RDS Secret Path
  components/pipeline-service/production/kflux-ocp-p01/resources/tekton-results-database-secret-path.yaml
Labels: lgtm, approved

#4927 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#4936 fix(KFLUXINFRA-921): Fixing Vault Secret Path for RDS
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
Labels: lgtm, approved

#4937 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#4938 chore(KFLUXVNGD-88): Add enable-helm option in github actions file
  .github/workflows/kube-linter.yaml
Labels: lgtm, approved

#4940 Run MintMaker every 4 hours instead of 2 hours
  components/mintmaker/base/cronjobs/create-dependency-update-check.yaml
Labels: lgtm, approved

#4947 Update MintMaker in stage
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#4944 Temporarily adjust Renovate jobs to run every 4 hours from Friday to Sunday
  components/mintmaker/base/cronjobs/create-dependency-update-check.yaml
  components/mintmaker/production/stone-prod-p01/cronjob-patch.yaml
  components/mintmaker/production/stone-prod-p01/kustomization.yaml
  components/mintmaker/production/stone-prod-p02/cronjob-patch.yaml
  components/mintmaker/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#4948 mintmaker: fix invalid k8s cronjob schedule
  components/mintmaker/base/cronjobs/create-dependency-update-check.yaml
Labels: lgtm, approved

#4949 enterprise contract update
  components/enterprise-contract/ecp.yaml
  components/enterprise-contract/kustomization.yaml
Labels: lgtm, approved

#4951 Promote mintmaker from stage to prod
  components/mintmaker/base/cronjobs/create-dependency-update-check.yaml
  components/mintmaker/production/base/kustomization.yaml
  components/mintmaker/production/base/manager_patches.yaml
  components/mintmaker/production/stone-prod-p01/cronjob-patch.yaml
  components/mintmaker/production/stone-prod-p01/kustomization.yaml
  components/mintmaker/production/stone-prod-p02/cronjob-patch.yaml
  components/mintmaker/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#4929 Upgrade kubearchvie to v0.4.0
  components/kubearchive/base/kustomization.yaml
  components/kubearchive/base/rbac.yaml
  components/kubearchive/development/kustomization.yaml
  components/kubearchive/development/postgresql.yaml
  components/kubearchive/staging/database-secret.yaml
  components/kubearchive/staging/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#4864 application-service update
  components/has/base/kustomization.yaml
  components/has/production/kustomization.yaml
  components/has/staging/kustomization.yaml
  components/monitoring/grafana/base/dashboards/has/kustomization.yaml
Labels: lgtm, approved

#4855 chore(KFLUXVNGD-88): Add crossplane component
  argo-cd-apps/base/member/infra-deployments/crossplane-control-plane/crossplane-control-plane.yaml
  argo-cd-apps/base/member/infra-deployments/crossplane-control-plane/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  components/crossplane-control-plane/OWNERS
  components/crossplane-control-plane/base/kustomization.yaml
  components/crossplane-control-plane/development/kustomization.yaml
  components/crossplane-control-plane/production/kustomization.yaml
  components/crossplane-control-plane/staging/kustomization.yaml
  hack/deploy-argocd.sh
Labels: lgtm, approved

#4961 release-service update in production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#4962 Deploy crossplane to member clusters only
  argo-cd-apps/base/member/infra-deployments/crossplane-control-plane/kustomization.yaml
Labels: lgtm, approved

#4958 chore: give integration team permission to update plrs and taskruns
  components/integration/base/kustomization.yaml
  components/integration/base/modify-pipelineruns-taskruns.yaml
Labels: lgtm, approved

#4967 Deploy crossplane functions and namespace XRD
  components/crossplane-control-plane/base/kustomization.yaml
Labels: lgtm, approved

#4904 fix(KFLUXINFRA-777): Changing NodeSelector and Toleration
  argo-cd-apps/overlays/development/delete-applications.yaml
  configs/nvme-storage-configurator/base/daemonset.yaml
  configs/proactive-scaler/base/deployments.yaml
Labels: approved

#4972 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#4971 KFLUXINFRA-1058: Deploy the new UI to public stage
  argo-cd-apps/base/member/infra-deployments/konflux-ui/README
  argo-cd-apps/base/member/infra-deployments/konflux-ui/konflux-ui.yaml
  argo-cd-apps/base/member/infra-deployments/konflux-ui/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  components/konflux-ui/base/ns.yaml
  components/konflux-ui/staging/base/dex/dex.yaml
  components/konflux-ui/staging/base/dex/kustomization.yaml
  components/konflux-ui/staging/base/kustomization.yaml
  components/konflux-ui/staging/base/proxy/kustomization.yaml
  components/konflux-ui/staging/base/proxy/nginx.conf
  components/konflux-ui/staging/base/proxy/proxy.yaml
  components/konflux-ui/staging/base/route-and-oauth.yaml
  components/konflux-ui/staging/stone-stg-rh01/add-service-certs-patch.yaml
  components/konflux-ui/staging/stone-stg-rh01/dex-config.yaml
  components/konflux-ui/staging/stone-stg-rh01/kustomization.yaml
  components/konflux-ui/staging/stone-stg-rh01/oauth2-proxy-args-patch.yaml
  components/konflux-ui/staging/stone-stg-rh01/remove-run-as-user-proxy-patch.yaml
  components/konflux-ui/staging/stone-stg-rh01/set-hostname.yaml
  components/konflux-ui/staging/stone-stg-rh01/set-redirect-uri.yaml
  components/konflux-ui/staging/stone-stg-rh01/set-replicas-patch.yaml
Labels: lgtm, approved

#4976 Turn off self healing for konflux-ui
  argo-cd-apps/base/member/infra-deployments/konflux-ui/konflux-ui.yaml
Labels: approved

#4977 KFLUXINFRA-812: Moving s390x Nodes to dynamic for public-prod-rh01
  components/multi-platform-controller/production/host-config.yaml
Labels: approved

#4978 add s390x to dynamic platforms
  components/multi-platform-controller/production/host-config.yaml
Labels: approved

#4979 Fix s390x base os image
  components/multi-platform-controller/production/host-config.yaml
Labels: approved

#4981 Enable dynamic s390x public prod-rh01
  components/multi-platform-controller/production/host-config.yaml
Labels: approved

#4952 Add Vector for forwarding Pipelines log
  components/pipeline-service/development/dev-only-pipeline-service-storage-configuration.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  hack/secret-creator/create-plnsvc-secrets.sh
Labels: lgtm, ok-to-test, approved

#4982 pub-prod s390x machine to 4cpu 16gib ram
  components/multi-platform-controller/production/host-config.yaml
Labels: approved

#4988 Gihub app and Smee for kflux-ocp-p01
  components/build-service/production/kflux-ocp-p01/pipelines-as-code-secret-path.yaml
  components/mintmaker/production/kflux-ocp-p01/pipelines-as-code-secret-path.yaml
  components/smee-client/production/kflux-ocp-p01/sever-url-patch.yaml
  components/smee/production/ip-allow-list.yaml
Labels: lgtm, approved

#4987 Better token handling for websockets
  components/konflux-ui/staging/base/proxy/proxy.yaml
Labels: lgtm, approved

#4973 Update Tekton Results to v0.13.0
  components/pipeline-service/base/external-secrets/tekton-results/tekton-results-s3.yaml
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4993 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#4999 Add the tekton-logging namespace
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5000 Enable tekton-logging NS access to ClusterSecretStore
  components/cluster-secret-store/base/appsre-vault-secret-store.yml
Labels: lgtm, needs-ok-to-test, approved

#4990 Increase application and components quotas in large tiers
  components/sandbox/tiers/src/appstudio/ns_tenant.yaml
  components/sandbox/tiers/src/appstudiolarge/based_on_tier.yaml
  components/sandbox/tiers/src/appstudioxlarge/based_on_tier.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-tenant-2246724155-2246724155.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-admin-130270397-849337768.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-130270397-593233715.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-contributor-130270397-829105171.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-maintainer-130270397-474752551.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-tenant-130270397-2246724155.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-viewer-130270397-4256863455.yaml
  components/sandbox/tiers/staging/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-admin-1579464439-849337768.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-1579464439-593233715.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-1579464439-829105171.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-1579464439-474752551.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-1579464439-2246724155.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-1579464439-4256863455.yaml
Labels: approved

#5002 [Staging] Fix Error in Vector Manifest
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, ok-to-test, approved

#5008 enable log compression for all staging clusters
  components/monitoring/logging/staging/base/kustomization.yaml
  components/monitoring/logging/staging/base/patches/configure-logforwarder-compression-patch.yaml
  components/monitoring/logging/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#5007 Reduce the Results buffer time to 1m in Development
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
Labels: lgtm, approved

#5011 chore: update internal-services controller
  components/internal-services/kustomization.yaml
Labels: lgtm, approved

#5004 Fix Vector secret name
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  hack/secret-creator/create-plnsvc-secrets.sh
Labels: lgtm, approved

#5017 Fix Environment Variables for tekton results api and s3
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved
