Repository redhat-appstudio/infra-deployments, pull requests merged in 2024-09, with the labels that each got.

#4418 feat(KONFLUX-4180): Dashboard with workers performance
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, approved

#4432 Update MintMaker image in prod
  components/mintmaker/production/base/manager_patches.yaml
Labels: lgtm, approved

#4415 KFLUXINFRA-802: Adding Node Selector and Tolerations in TektonConfig
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/resources/kustomization.yaml
  components/pipeline-service/staging/stone-stg-m01/resources/tekton-config-patch.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4440 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#4416 Deploy test version of MPC with IBM power pc pool on staging
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#4437 feat: add new metrics required by release dashboard and SLO
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#4446 Increase pvc quota in large tier
  components/sandbox/tiers/production/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/production/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-admin-3994678728-849337768.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-3994678728-3180033938.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-contributor-3994678728-829105171.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-maintainer-3994678728-1904354742.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-tenant-3994678728-649666048.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-viewer-3994678728-4256863455.yaml
  components/sandbox/tiers/src/appstudiolarge/based_on_tier.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-admin-3994678728-849337768.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-3994678728-3180033938.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-contributor-3994678728-829105171.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-maintainer-3994678728-1904354742.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-tenant-3994678728-649666048.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-viewer-3994678728-4256863455.yaml
Labels: lgtm, approved

#4444 hac-dev: Promote secrets list page fix
  components/ui/development/kustomization.yaml
  components/ui/production/stone-prod-p01/kustomization.yaml
  components/ui/production/stone-prod-p02/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#4450 redirect kustomiztion to manifests in the conroller
  components/notification-controller/base/deployment.yaml
  components/notification-controller/base/kustomization.yaml
  components/notification-controller/base/namespace.yaml
  components/notification-controller/base/service-account.yaml
  components/notification-controller/development/kustomization.yaml
  components/notification-controller/staging/kustomization.yaml
Labels: lgtm, approved

#4452 Add API group 'apiextensions.k8s.io' to konflux-admins
  components/authentication/base/konflux-admins.yaml
Labels: lgtm, approved

#4453 update environment variable patch
  components/notification-controller/development/topic_region_add.yaml
  components/notification-controller/staging/topic_region_add.yaml
Labels: lgtm, approved

#4454 Fix customresourcedefinitions name
  components/authentication/base/konflux-admins.yaml
Labels: lgtm, approved

#4456 Updated public vlan id for ibm cloud
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#4457 fix: kube_pod_container_status_restarts_total federate match
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#4458 test IBMP dynamic pool
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: approved

#4455 chore: don't remote write taskrun duration metric
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#4459 Added route details as userdata for ppc64le
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#4445 Update pipeline-service OSP version staging
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4461 Grant everyone can view role to konflux-contributors
  components/authentication/base/everyone-can-view-patch.yaml
Labels: lgtm, approved

#4462 Remove EC's download service
  components/enterprise-contract/download-service.yaml
  components/enterprise-contract/kustomization.yaml
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm, approved

#4463 Grant cluster-monitoring-view role to all Konflux teams
  components/authentication/base/everyone-can-view.yaml
  components/authentication/base/kustomization.yaml
Labels: lgtm, approved

#4466 chore(RHTAPWATCH-1266): update external secret location - staging
  components/notification-controller/base/external-secrets/aws-sns-secret.yaml
  components/notification-controller/staging/external-secret-path.yaml
  components/notification-controller/staging/kustomization.yaml
Labels: lgtm, approved

#4473 chore(stoneintg-1023): add IS SLO availability panels
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#4475 Update OSP dev and stage
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4476 Add mftb as owner of the monitoring component
  components/monitoring/OWNERS
Labels: lgtm, approved

#4477 Add more permissions to konflux-admins from tekton.dev
  components/authentication/base/konflux-admins.yaml
Labels: lgtm, approved

#4468 docs(RHTAPWATCH-1261): prepare o11y docs for handoff
  components/monitoring/README.md
  components/monitoring/prometheus/README.md
Labels: lgtm, approved

#4478 chore(RHTAPWATCH-1202): promote notification-controlller to production
  components/notification-controller/production/external-secret-path.yaml
  components/notification-controller/production/kustomization.yaml
  components/notification-controller/production/topic_region_add.yaml
Labels: lgtm, approved

#4481 mintmaker: add ExternalSecret for registry.stage.redhat.io pull secret
  components/mintmaker/base/external-secrets/registry-stage-redhat-io-pull-secret.yaml
Labels: lgtm, approved

#4482 fix: adjusting metrics for release-service
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#4480 Test fix for provision script (temporary)
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#4488 Update MPC provision script
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#4490 fix provision script
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#4491 fix provision script
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm

#4492 fix provision script
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#4494 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#4495 fix MPC provision script
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#4485 Update ClusterLogging CR collection spec
  components/monitoring/logging/base/configure-logging/configure-log-collectors.yaml
Labels: lgtm, approved

#4487 Releasing Workspaces alpha6
  components/workspaces/staging/base/kustomization.yaml
  components/workspaces/staging/base/operator/config/crd/bases/workspaces.konflux-ci.dev_internalworkspaces.yaml
  components/workspaces/staging/base/operator/config/crd/kustomization.yaml
  components/workspaces/staging/base/operator/config/crd/kustomizeconfig.yaml
  components/workspaces/staging/base/operator/config/crd/patches/cainjection_in_workspaces.yaml
  components/workspaces/staging/base/operator/config/crd/patches/webhook_in_workspaces.yaml
  components/workspaces/staging/base/operator/config/default/kustomization.yaml
  components/workspaces/staging/base/operator/config/default/manager_auth_proxy_patch.yaml
  components/workspaces/staging/base/operator/config/manager/kustomization.yaml
  components/workspaces/staging/base/operator/config/manager/manager.yaml
  components/workspaces/staging/base/operator/config/metrics/kustomization.yaml
  components/workspaces/staging/base/operator/config/metrics/metrics-service.yaml
  components/workspaces/staging/base/operator/config/metrics/monitor.yaml
  components/workspaces/staging/base/operator/config/metrics/service-account.yaml
  components/workspaces/staging/base/operator/config/rbac/auth_proxy_client_clusterrole.yaml
  components/workspaces/staging/base/operator/config/rbac/auth_proxy_role.yaml
  components/workspaces/staging/base/operator/config/rbac/auth_proxy_role_binding.yaml
  components/workspaces/staging/base/operator/config/rbac/internalworkspace_editor_role.yaml
  components/workspaces/staging/base/operator/config/rbac/internalworkspace_viewer_role.yaml
  components/workspaces/staging/base/operator/config/rbac/kustomization.yaml
  components/workspaces/staging/base/operator/config/rbac/leader_election_role.yaml
  components/workspaces/staging/base/operator/config/rbac/leader_election_role_binding.yaml
  components/workspaces/staging/base/operator/config/rbac/role.yaml
  components/workspaces/staging/base/operator/config/rbac/role_binding.yaml
  components/workspaces/staging/base/operator/config/rbac/service_account.yaml
  components/workspaces/staging/base/server/config/crd/bases/workspaces.konflux-ci.dev_workspaces.yaml
  components/workspaces/staging/base/server/config/crd/kustomization.yaml
  components/workspaces/staging/base/server/config/default/kustomization.yaml
  components/workspaces/staging/base/server/config/rbac/kustomization.yaml
  components/workspaces/staging/base/server/config/rbac/role_spacebinding_reader.yaml
  components/workspaces/staging/base/server/config/rbac/role_usersignup_reader.yaml
  components/workspaces/staging/base/server/config/rbac/role_workspace_server_editor.yaml
  components/workspaces/staging/base/server/config/rbac/rolebinding_spacebinding_reader.yaml
  components/workspaces/staging/base/server/config/rbac/rolebinding_usersignup_reader.yaml
  components/workspaces/staging/base/server/config/rbac/rolebinding_workspace_server_editor.yaml
  components/workspaces/staging/base/server/config/rbac/serviceaccount.yaml
  components/workspaces/staging/base/server/config/server/deployment.yaml
  components/workspaces/staging/base/server/config/server/kustomization.yaml
  components/workspaces/staging/base/server/config/server/proxy-config/dynamic/config.yaml
  components/workspaces/staging/base/server/config/server/proxy-config/traefik.yaml
  components/workspaces/staging/base/server/config/server/service.yaml
  components/workspaces/staging/stone-stage-p01/kustomization.yaml
  components/workspaces/staging/stone-stg-host/kustomization.yaml
Labels: lgtm, approved

#4500 use latest tag of MPC with memory limit fix
  components/multi-platform-controller/production-downstream/kustomization.yaml
  components/multi-platform-controller/production/kustomization.yaml
Labels: lgtm, approved

#4502 update resources for notification controller
  components/notification-controller/development/kustomization.yaml
  components/notification-controller/production/kustomization.yaml
  components/notification-controller/staging/kustomization.yaml
Labels: lgtm, approved

#4503 add notification controller to production
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
Labels: lgtm, approved

#4505 Make stg-rh01 the default member cluster
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/space-provisioner-configs.yaml
Labels: lgtm, approved

#4508 mintmaker: update secret path for registry.state.redhat.io
  components/mintmaker/base/external-secrets/registry-stage-redhat-io-pull-secret.yaml
Labels: lgtm, approved

#4513 mintmaker: update controller image in production
  components/mintmaker/production/base/kustomization.yaml
Labels: lgtm, approved

#4510 chore(stoneintg-2013): update availability panels to 24h
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#4465 Install minio-operator from upstream
  components/pipeline-service/development/dev-only-pipeline-service-storage-configuration.yaml
  components/pipeline-service/development/kustomization.yaml
  hack/secret-creator/create-plnsvc-secrets.sh
Labels: lgtm, approved

#4511 mintmaker: add label to stage registry pull secret
  components/mintmaker/base/external-secrets/registry-stage-redhat-io-pull-secret.yaml
Labels: lgtm, approved

#4514 Remove stg-m01 spaceProvisionerConfig
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/space-provisioner-configs.yaml
Labels: lgtm, approved

#4516 feat: Add smoothing and choosing workers by workload to Nodes performance dashboard
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, approved

#4521 Add new appstudioxlarge tier
  components/sandbox/tiers/src/appstudioxlarge/based_on_tier.yaml
  components/sandbox/tiers/staging/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-admin-884010306-849337768.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-884010306-3180033938.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-884010306-829105171.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-884010306-1904354742.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-884010306-649666048.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-884010306-4256863455.yaml
  components/sandbox/tiers/staging/kustomization.yaml
Labels: lgtm, approved

#4532 Add new appstudioxlarge tier in production
  components/sandbox/tiers/production/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/production/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-admin-884010306-849337768.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-884010306-3180033938.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-884010306-829105171.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-884010306-1904354742.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-884010306-649666048.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-884010306-4256863455.yaml
  components/sandbox/tiers/production/kustomization.yaml
Labels: lgtm, approved

#4535 KFLUXINFRA-837: Adding AWS GPU Nodes for Dynamic Provisioning
  components/multi-platform-controller/production-downstream/host-config.yaml
  components/multi-platform-controller/production/host-config.yaml
  components/multi-platform-controller/staging-downstream/host-config.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#4539 KFLUXINFRA-837: Changing AWS GPU Instance Type
  components/multi-platform-controller/production-downstream/host-config.yaml
  components/multi-platform-controller/production/host-config.yaml
  components/multi-platform-controller/staging-downstream/host-config.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#4542 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#4504 Drop preview/ from custom console urls
  components/integration/production/base/kustomization.yaml
  components/integration/staging/base/kustomization.yaml
  components/pipeline-service/production/base/update-tekton-config-pac.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/toolchainconfig.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/toolchainconfig.yaml
Labels: lgtm, approved

#4556 Releasing workspaces alpha6 to prod
  components/workspaces/base/operator/config/default/kustomization.yaml
  components/workspaces/base/operator/config/default/manager_auth_proxy_patch.yaml
  components/workspaces/base/operator/config/manager/kustomization.yaml
  components/workspaces/base/operator/config/metrics/kustomization.yaml
  components/workspaces/base/operator/config/metrics/metrics-service.yaml
  components/workspaces/base/operator/config/metrics/monitor.yaml
  components/workspaces/base/operator/config/metrics/service-account.yaml
  components/workspaces/base/operator/config/rbac/auth_proxy_service.yaml
  components/workspaces/base/operator/config/rbac/kustomization.yaml
  components/workspaces/base/operator/config/rbac/role.yaml
  components/workspaces/base/server/config/server/deployment.yaml
  components/workspaces/base/server/config/server/kustomization.yaml
  components/workspaces/production/stone-prd-host1/kustomization.yaml
  components/workspaces/production/stone-prod-p01/kustomization.yaml
  components/workspaces/production/stone-prod-p02/kustomization.yaml
  components/workspaces/staging/base/kustomization.yaml
  components/workspaces/staging/base/operator/config/crd/bases/workspaces.konflux-ci.dev_internalworkspaces.yaml
  components/workspaces/staging/base/operator/config/crd/kustomization.yaml
  components/workspaces/staging/base/operator/config/crd/kustomizeconfig.yaml
  components/workspaces/staging/base/operator/config/crd/patches/cainjection_in_workspaces.yaml
  components/workspaces/staging/base/operator/config/crd/patches/webhook_in_workspaces.yaml
  components/workspaces/staging/base/operator/config/default/kustomization.yaml
  components/workspaces/staging/base/operator/config/default/manager_auth_proxy_patch.yaml
  components/workspaces/staging/base/operator/config/manager/kustomization.yaml
  components/workspaces/staging/base/operator/config/manager/manager.yaml
  components/workspaces/staging/base/operator/config/rbac/auth_proxy_client_clusterrole.yaml
  components/workspaces/staging/base/operator/config/rbac/auth_proxy_role.yaml
  components/workspaces/staging/base/operator/config/rbac/auth_proxy_role_binding.yaml
  components/workspaces/staging/base/operator/config/rbac/internalworkspace_editor_role.yaml
  components/workspaces/staging/base/operator/config/rbac/internalworkspace_viewer_role.yaml
  components/workspaces/staging/base/operator/config/rbac/kustomization.yaml
  components/workspaces/staging/base/operator/config/rbac/leader_election_role.yaml
  components/workspaces/staging/base/operator/config/rbac/leader_election_role_binding.yaml
  components/workspaces/staging/base/operator/config/rbac/role.yaml
  components/workspaces/staging/base/operator/config/rbac/role_binding.yaml
  components/workspaces/staging/base/operator/config/rbac/service_account.yaml
  components/workspaces/staging/base/server/config/crd/bases/workspaces.konflux-ci.dev_workspaces.yaml
  components/workspaces/staging/base/server/config/crd/kustomization.yaml
  components/workspaces/staging/base/server/config/default/kustomization.yaml
  components/workspaces/staging/base/server/config/rbac/kustomization.yaml
  components/workspaces/staging/base/server/config/rbac/role_spacebinding_reader.yaml
  components/workspaces/staging/base/server/config/rbac/role_usersignup_reader.yaml
  components/workspaces/staging/base/server/config/rbac/role_workspace_server_editor.yaml
  components/workspaces/staging/base/server/config/rbac/rolebinding_spacebinding_reader.yaml
  components/workspaces/staging/base/server/config/rbac/rolebinding_usersignup_reader.yaml
  components/workspaces/staging/base/server/config/rbac/rolebinding_workspace_server_editor.yaml
  components/workspaces/staging/base/server/config/rbac/serviceaccount.yaml
  components/workspaces/staging/base/server/config/server/deployment.yaml
  components/workspaces/staging/base/server/config/server/kustomization.yaml
  components/workspaces/staging/base/server/config/server/proxy-config/dynamic/config.yaml
  components/workspaces/staging/base/server/config/server/proxy-config/traefik.yaml
  components/workspaces/staging/base/server/config/server/service.yaml
  components/workspaces/staging/stone-stage-p01/kustomization.yaml
  components/workspaces/staging/stone-stg-host/kustomization.yaml
Labels: lgtm, approved

#4557 chore: Bump MPC on prod-m01
  argo-cd-apps/base/member/infra-deployments/multi-platform-controller/multi-platform-controller.yaml
  components/multi-platform-controller/production/common/external-secrets.yaml
  components/multi-platform-controller/production/common/host-config.yaml
  components/multi-platform-controller/production/common/kustomization.yaml
  components/multi-platform-controller/production/kustomization.yaml
  components/multi-platform-controller/production/stone-prod-m01/kustomization.yaml
Labels: lgtm, approved

#4559 chore: Fix MPC bump on prd-m01
  argo-cd-apps/base/member/infra-deployments/multi-platform-controller/multi-platform-controller.yaml
  components/multi-platform-controller/production/stone-prd-m01/kustomization.yaml
Labels: lgtm, approved

#4560 Set cpu/memory request and memory limit for tkn controllers in staging
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/kustomization.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/update-tekton-controller-resources.yaml
Labels: lgtm, approved

#4534 Upgrade MCE operator to 2.6 in dev & staging
  components/cluster-as-a-service/base/clustertemplates.yaml
  components/cluster-as-a-service/development/add-base-domain-param.yaml
  components/cluster-as-a-service/development/add-hypershift-params.yaml
  components/cluster-as-a-service/development/klusterlet-config.yaml
  components/cluster-as-a-service/development/kustomization.yaml
  components/cluster-as-a-service/production/add-hypershift-params.yaml
  components/cluster-as-a-service/production/kustomization.yaml
  components/cluster-as-a-service/staging/add-base-domain-param.yaml
  components/cluster-as-a-service/staging/add-hypershift-params.yaml
  components/cluster-as-a-service/staging/external-secrets.yaml
  components/cluster-as-a-service/staging/kustomization.yaml
  hack/bootstrap-eaas-cluster.sh
  hack/preview-template.env
  hack/preview.sh
  hack/secret-creator/create-eaas-secrets.sh
Labels: lgtm, approved

#4562 Set cpu/memory request and memory limit for tkn controllers in prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/update-tekton-controller-resources.yaml
Labels: lgtm, approved

#4552 feat(RELEASE-1170): sync vault secrets in release service tenant
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: lgtm, approved

#4574 Updated ppc64le network config
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: approved

#4581 updated cloud config
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#4582 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#4584 adding Raksha as a monitoring component owner
  components/monitoring/OWNERS
Labels: lgtm, approved

#4564 Upgrade MCE operator to 2.6 in production
  components/cluster-as-a-service/base/clustertemplates.yaml
  components/cluster-as-a-service/base/multicluster-engine.yaml
  components/cluster-as-a-service/development/kustomization.yaml
  components/cluster-as-a-service/production/add-hypershift-params.yaml
  components/cluster-as-a-service/production/external-secrets.yaml
  components/cluster-as-a-service/staging/kustomization.yaml
Labels: lgtm, approved

#4589 Fix route commands
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: approved

#4591 Remove ppc static node from internal stage
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: approved

#4593 Increase releases and internalrequests quota
  components/sandbox/tiers/production/appstudio/kustomization.yaml
  components/sandbox/tiers/production/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-tenant-4121561789-4121561789.yaml
  components/sandbox/tiers/production/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/production/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-tenant-3994678728-4121561789.yaml
  components/sandbox/tiers/production/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/production/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-884010306-4121561789.yaml
  components/sandbox/tiers/src/appstudio/ns_tenant.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-tenant-4121561789-4121561789.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-tenant-3994678728-4121561789.yaml
  components/sandbox/tiers/staging/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-884010306-4121561789.yaml
Labels: lgtm, approved

#4583 feat(KONFLUX-4508): Expose metrics for Pipelines leases distribution alerts
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#4601 release pipeline sa reading configmaps
  components/release/base/release-pipeline-resources-clusterrole.yaml
Labels: lgtm, approved

#4361 KFLUXINFRA-777: Config to Configure Worker Nodes with NVMe Disks
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/nvme-storage-configurator/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/nvme-storage-configurator/nvme-storage-configurator.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  configs/nvme-storage-configurator/base/clusterrolebinding.yaml
  configs/nvme-storage-configurator/base/daemonset.yaml
  configs/nvme-storage-configurator/base/install.sh
  configs/nvme-storage-configurator/base/kustomization.yaml
  configs/nvme-storage-configurator/base/mount.sh
  configs/nvme-storage-configurator/base/namespace.yaml
  configs/nvme-storage-configurator/base/nvme-storage.service
  configs/nvme-storage-configurator/base/serviceaccount.yaml
  configs/nvme-storage-configurator/production/kustomization.yaml
  configs/nvme-storage-configurator/staging/kustomization.yaml
Labels: lgtm, approved

#4606 Increase tekton results memory
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4603 Sending traces to SignalFX instead of Honeycomb
  argo-cd-apps/base/member/infra-deployments/tracing-workload-otel-collector/tracing-workload-otel-collector.yaml
  components/tracing/otel-collector/base/external-secrets/kustomization.yaml
  components/tracing/otel-collector/base/external-secrets/signalfx-api-key.yaml
  components/tracing/otel-collector/development/otel-collector-helm-values.yaml
  components/tracing/otel-collector/development/patch-delete-external-secrets.yaml
  components/tracing/otel-collector/production/kustomization.yaml
  components/tracing/otel-collector/production/otel-collector-helm-values.yaml
  components/tracing/otel-collector/production/signalfx-api-key-secret-path.yaml
  components/tracing/otel-collector/staging/kustomization.yaml
  components/tracing/otel-collector/staging/otel-collector-helm-values.yaml
  components/tracing/otel-collector/staging/signalfx-api-key-secret-path.yaml
Labels: lgtm, approved

#4607 add workspaces.konflux-ci.dev to view-appstudio ClusterRole
  components/authentication/base/everyone-can-view.yaml
Labels: lgtm, approved

#4609 Fix SIGNALFX_API_KEY variable name mismatch
  components/tracing/otel-collector/production/otel-collector-helm-values.yaml
  components/tracing/otel-collector/staging/otel-collector-helm-values.yaml
Labels: lgtm, approved

#4569 feat(KONFLUX-4508): Added graph about Tekton Pipelines controller leases distribution + some improvements to other Tekton related graphs
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, approved

#4610 OTel - Remove logging from list of exporters in the pipeline
  components/tracing/otel-collector/production/otel-collector-helm-values.yaml
  components/tracing/otel-collector/staging/otel-collector-helm-values.yaml
Labels: lgtm, approved

#4611 Fixing env name from stage to prod in prod config
  components/tracing/otel-collector/production/otel-collector-helm-values.yaml
Labels: lgtm, approved

#4608 Update MintMaker to use rpm-lockfile script v0.9.0
  components/mintmaker/production/base/manager_patches.yaml
Labels: lgtm, approved

#4616 Changing GPU Instance Type from g4dn.xlarge to g6.xlarge
  components/multi-platform-controller/production-downstream/host-config.yaml
  components/multi-platform-controller/production/common/host-config.yaml
  components/multi-platform-controller/staging-downstream/host-config.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#4602 Update OSP version on stone-prd-m01
  components/multi-platform-controller/production/stone-prd-m01/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/resources/osp-nightly-version.yaml
Labels: lgtm, approved

#4617 Fixing ApplicationSet for the DaemonSet
  argo-cd-apps/base/member/infra-deployments/nvme-storage-configurator/kustomization.yaml
Labels: lgtm, approved

#4619 Fix for nvme disk configuration service
  configs/nvme-storage-configurator/base/nvme-storage.service
Labels: lgtm, approved

#4612 kubesaw: add network policy for in-namespace communication
  components/sandbox/toolchain-host-operator/production/stone-prod-p02/network-policy.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/network-policy.yaml
Labels: lgtm, approved

#4621 adding cloud-init configuration for gpu instances
  components/multi-platform-controller/production-downstream/host-config.yaml
  components/multi-platform-controller/production/common/host-config.yaml
  components/multi-platform-controller/staging-downstream/host-config.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#4620 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#4536 Add KubeArchive to development cluster
  argo-cd-apps/base/member/infra-deployments/kubearchive/kubearchive.yaml
  argo-cd-apps/base/member/infra-deployments/kubearchive/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  components/kubearchive/OWNERS
  components/kubearchive/base/kustomization.yaml
  components/kubearchive/base/rbac.yaml
  components/kubearchive/development/kustomization.yaml
  components/kubearchive/development/postgresql.yaml
  components/kubearchive/staging/database-secret.yaml
  components/kubearchive/staging/kustomization.yaml
Labels: lgtm, needs-ok-to-test, approved
