Repository redhat-appstudio/infra-deployments, pull requests merged in 2024-07, with the labels that each got.

#3976 Promote mintmaker from staging to production
  components/mintmaker/production/base/kustomization.yaml
Labels: lgtm, approved

#3977 Bump Postgres TLS cert lifetime
  hack/secret-creator/create-plnsvc-secrets.sh
Labels: lgtm, approved

#3979 PVCORE-4216 Otel tracing configs for production environment
  components/tracing/otel-collector/production/otel-collector-helm-values.yaml
Labels: lgtm, approved

#3981 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#3983 Add Riley Saar to the Mintmaker owners
  components/mintmaker/OWNERS
Labels: lgtm, approved

#3974 Fix service name for Opentelemetry Collector
  argo-cd-apps/base/member/infra-deployments/tracing-workload-otel-collector/tracing-workload-otel-collector.yaml
Labels: lgtm, approved

#3993 Add otlphttp to the traces pipeline
  components/tracing/otel-collector/staging/otel-collector-helm-values.yaml
Labels: lgtm, approved

#3980 Enable Otel tracing in production environment
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  components/tracing/otel-collector/production/honeycomb-api-key-secret-path.yaml
  components/tracing/otel-collector/production/kustomization.yaml
Labels: lgtm, approved

#3994 Add otlphttp to the production traces pipeline
  components/tracing/otel-collector/production/otel-collector-helm-values.yaml
Labels: lgtm, approved

#3995 Add Honeycomb API secret as env var
  components/tracing/otel-collector/production/otel-collector-helm-values.yaml
  components/tracing/otel-collector/staging/otel-collector-helm-values.yaml
Labels: lgtm, approved

#3996 Patch the tracing ApplicationSets to transform stage to prod
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  components/tracing/otel-collector/production/otel-collector-helm-values.yaml
Labels: lgtm, approved

#3999 Add gitSignOff preset
  components/mintmaker/base/renovate-config.yaml
Labels: lgtm, approved

#4004 Remove konflux e2e repository cr
  components/konflux-ci/base/repository.yaml
Labels: lgtm, approved

#4005 Patch RENOVATE_IMAGE env variable
  components/mintmaker/production/base/kustomization.yaml
  components/mintmaker/production/base/manager_patches.yaml
  components/mintmaker/staging/base/kustomization.yaml
  components/mintmaker/staging/base/manager_patches.yaml
Labels: lgtm, approved

#3997 KFLUXINFRA-651: Adding Instance Types for Multi-Platform Builds
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#4002 Remove OAuth service deployment from SPI for development and STG
  components/monitoring/grafana/base/dashboards/spi/kustomization.yaml
  components/spi-vault/kustomization.yaml
  components/spi/overlays/development/kustomization.yaml
  components/spi/overlays/development/oauth-service-config-patch.json
  components/spi/overlays/staging/base/kustomization.yaml
  components/spi/overlays/staging/stone-stage-p01/kustomization.yaml
  components/spi/overlays/staging/stone-stage-p01/oauth-service-config-patch.json
  components/spi/overlays/staging/stone-stg-m01/kustomization.yaml
  components/spi/overlays/staging/stone-stg-m01/oauth-service-config-patch.json
  components/spi/overlays/staging/stone-stg-rh01/kustomization.yaml
  components/spi/overlays/staging/stone-stg-rh01/oauth-service-config-patch.json
  hack/preview.sh
Labels: lgtm, approved

#3992 Promote release-service from development to staging
  .gitignore
  components/release/staging/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#4012 Grant BKorren permissions for MCP
  components/multi-platform-controller/OWNERS
Labels: lgtm, approved

#4021 Update SPI to the next OAuth-less version on production
  components/spi/overlays/production/base/kustomization.yaml
  components/spi/overlays/production/stone-prd-m01/kustomization.yaml
  components/spi/overlays/production/stone-prd-m01/oauth-service-config-patch.json
  components/spi/overlays/production/stone-prd-rh01/kustomization.yaml
  components/spi/overlays/production/stone-prd-rh01/oauth-service-config-patch.json
  components/spi/overlays/production/stone-prod-p01/kustomization.yaml
  components/spi/overlays/production/stone-prod-p01/oauth-service-config-patch.json
  components/spi/overlays/production/stone-prod-p02/kustomization.yaml
  components/spi/overlays/production/stone-prod-p02/oauth-service-config-patch.json
Labels: lgtm, approved

#4020 Mintmaker: explicitly disable Dependency Dashboard
  components/mintmaker/base/renovate-config.yaml
Labels: lgtm, approved

#4019 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#4013 KFLUXINFRA-651: Adding Instance Types for Multi-Platform Builds
  components/multi-platform-controller/production-downstream/host-config.yaml
  components/multi-platform-controller/production/host-config.yaml
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#4028 Update pipeline-service prod
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4033 Add lgallovi to the MintMaker project
  components/mintmaker/OWNERS
Labels: lgtm, approved

#4040 Add config for konflux-workspaces in staging
  argo-cd-apps/base/host/kustomization.yaml
  argo-cd-apps/base/host/workspaces/kustomization.yaml
  argo-cd-apps/base/host/workspaces/workspaces.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  components/ui/base/proxy/nginx.conf
  components/workspaces/base/kustomization.yaml
  components/workspaces/base/operator/config/crd/bases/workspaces.konflux.io_internalworkspaces.yaml
  components/workspaces/base/operator/config/crd/kustomization.yaml
  components/workspaces/base/operator/config/crd/kustomizeconfig.yaml
  components/workspaces/base/operator/config/crd/patches/cainjection_in_workspaces.yaml
  components/workspaces/base/operator/config/crd/patches/webhook_in_workspaces.yaml
  components/workspaces/base/operator/config/default/kustomization.yaml
  components/workspaces/base/operator/config/default/manager_auth_proxy_patch.yaml
  components/workspaces/base/operator/config/manager/kustomization.yaml
  components/workspaces/base/operator/config/manager/manager.yaml
  components/workspaces/base/operator/config/rbac/auth_proxy_client_clusterrole.yaml
  components/workspaces/base/operator/config/rbac/auth_proxy_role.yaml
  components/workspaces/base/operator/config/rbac/auth_proxy_role_binding.yaml
  components/workspaces/base/operator/config/rbac/auth_proxy_service.yaml
  components/workspaces/base/operator/config/rbac/internalworkspace_editor_role.yaml
  components/workspaces/base/operator/config/rbac/internalworkspace_viewer_role.yaml
  components/workspaces/base/operator/config/rbac/kustomization.yaml
  components/workspaces/base/operator/config/rbac/leader_election_role.yaml
  components/workspaces/base/operator/config/rbac/leader_election_role_binding.yaml
  components/workspaces/base/operator/config/rbac/role.yaml
  components/workspaces/base/operator/config/rbac/role_binding.yaml
  components/workspaces/base/operator/config/rbac/service_account.yaml
  components/workspaces/base/server/config/crd/bases/workspaces.konflux.io_workspaces.yaml
  components/workspaces/base/server/config/crd/kustomization.yaml
  components/workspaces/base/server/config/default/kustomization.yaml
  components/workspaces/base/server/config/rbac/kustomization.yaml
  components/workspaces/base/server/config/rbac/role_spacebinding_reader.yaml
  components/workspaces/base/server/config/rbac/role_usersignup_reader.yaml
  components/workspaces/base/server/config/rbac/role_workspace_server_editor.yaml
  components/workspaces/base/server/config/rbac/rolebinding_spacebinding_reader.yaml
  components/workspaces/base/server/config/rbac/rolebinding_usersignup_reader.yaml
  components/workspaces/base/server/config/rbac/rolebinding_workspace_server_editor.yaml
  components/workspaces/base/server/config/rbac/serviceaccount.yaml
  components/workspaces/base/server/config/server/deployment.yaml
  components/workspaces/base/server/config/server/kustomization.yaml
  components/workspaces/base/server/config/server/proxy-config/dynamic/config.yaml
  components/workspaces/base/server/config/server/proxy-config/traefik.yaml
  components/workspaces/base/server/config/server/service.yaml
  components/workspaces/staging/kustomization.yaml
Labels: lgtm, approved

#4037 fix: promote image-controller component to dev/stage
  components/image-controller/development/kustomization.yaml
  components/image-controller/staging/base/kustomization.yaml
Labels: lgtm, approved

#4048 workspaces: fix server's configmap
  components/workspaces/base/server/config/default/kustomization.yaml
  components/workspaces/base/server/config/server/deployment.yaml
Labels: lgtm, approved

#4050 workspaces: set log level to debug in staging
  components/workspaces/staging/kustomization.yaml
Labels: lgtm, approved

#4049 Add ImageRepositories to everyonecanview role
  components/authentication/base/everyone-can-view.yaml
Labels: lgtm, approved

#4051 Make ArgoCD ignore annotation on ImageRepository when sycning
  argo-cd-apps/base/tenants-config/tenants-config.yaml
Labels: lgtm, approved

#4022 fix(STONEINTG-863): removed bugged snapshot concurrent requests metric
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#4053 SRVKP-5825: move pipeline-metric-exporter PAC repository obj from tekton-ci to konflux-ci
  components/konflux-ci/base/repository.yaml
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#4055 SRVKP-5825: move pipeline-service repository obj from tekton-ci to konflux-ci
  components/konflux-ci/base/repository.yaml
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#4059 Add controls to prBodyTemplate for Tekton updates
  components/mintmaker/base/renovate-config.yaml
Labels: lgtm, approved

#4058 workspaces: fix server image and security context
  components/workspaces/base/server/config/server/deployment.yaml
  components/workspaces/base/server/config/server/kustomization.yaml
Labels: lgtm, approved

#4061 workspaces: fix namespace replacement
  components/workspaces/staging/kustomization.yaml
Labels: lgtm, approved

#4063 KFLUXBUGS-1305: Show the user's first and last name on the UI
  components/keycloak/base/configure-keycloak.yaml
Labels: lgtm, approved

#4066 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#4064 Remove excessive replicas for HAS
  components/has/k-components/replicas-patch/kustomization.yaml
  components/has/k-components/replicas-patch/replicas_patch.yaml
  components/has/production/kustomization.yaml
  components/has/staging/kustomization.yaml
Labels: lgtm, approved

#4068 SRVKP-5832: move to downstream tekton-results PAC CI to konflux-ci namespace
  components/konflux-ci/base/repository.yaml
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#4076 Fix broken urls when user signups in public instances
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/toolchainconfig.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/toolchainconfig.yaml
Labels: lgtm, approved

#4035 MintMaker: enable git-submodules manager
  components/mintmaker/base/renovate-config.yaml
Labels: lgtm, ok-to-test, approved

#4074 Fixing issue with TemplateTier metadata
  components/sandbox/tiers/production/appstudio-env/tiertemplate-appstudio-env-admin-4171108837-4171108837.yaml
  components/sandbox/tiers/production/appstudio-env/tiertemplate-appstudio-env-clusterresources-2916842387-2916842387.yaml
  components/sandbox/tiers/production/appstudio-env/tiertemplate-appstudio-env-contributor-297495683-297495683.yaml
  components/sandbox/tiers/production/appstudio-env/tiertemplate-appstudio-env-env-1575256421-1575256421.yaml
  components/sandbox/tiers/production/appstudio-env/tiertemplate-appstudio-env-maintainer-1039478644-1039478644.yaml
  components/sandbox/tiers/production/appstudio-env/tiertemplate-appstudio-env-viewer-617892940-617892940.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-admin-221167138-221167138.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-clusterresources-750679343-750679343.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-contributor-3696782055-3696782055.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-maintainer-98574726-98574726.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-tenant-1252037388-1252037388.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-viewer-210715919-210715919.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-admin-1884308846-221167138.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-1884308846-750679343.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-contributor-1884308846-3696782055.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-maintainer-1884308846-98574726.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-tenant-1884308846-1252037388.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-viewer-1884308846-210715919.yaml
  components/sandbox/tiers/staging/appstudio-env/tiertemplate-appstudio-env-admin-4171108837-4171108837.yaml
  components/sandbox/tiers/staging/appstudio-env/tiertemplate-appstudio-env-clusterresources-2916842387-2916842387.yaml
  components/sandbox/tiers/staging/appstudio-env/tiertemplate-appstudio-env-contributor-297495683-297495683.yaml
  components/sandbox/tiers/staging/appstudio-env/tiertemplate-appstudio-env-env-1575256421-1575256421.yaml
  components/sandbox/tiers/staging/appstudio-env/tiertemplate-appstudio-env-maintainer-1039478644-1039478644.yaml
  components/sandbox/tiers/staging/appstudio-env/tiertemplate-appstudio-env-viewer-617892940-617892940.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-admin-221167138-221167138.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-clusterresources-750679343-750679343.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-contributor-3696782055-3696782055.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-maintainer-98574726-98574726.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-tenant-1252037388-1252037388.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-viewer-210715919-210715919.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-admin-1884308846-221167138.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-1884308846-750679343.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-contributor-1884308846-3696782055.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-maintainer-1884308846-98574726.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-tenant-1884308846-1252037388.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-viewer-1884308846-210715919.yaml
Labels: lgtm, approved

#4073 Update pipeline-service prod
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4088 rm gabemontero from jvm-buld-svc owners
  components/jvm-build-service/OWNERS
Labels: lgtm, approved

#4071 SRVKP-5832: maintain pinning of watcher image to mem leak version
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#4085 Improve nginx deployment
  components/ui/base/proxy/proxy.yaml
Labels: lgtm, approved

#4101 Update mintmaker-renovate-image digest
  components/mintmaker/production/base/manager_patches.yaml
Labels: lgtm, approved

#4103 rm gabemontero jvm-build-svc
  components/monitoring/grafana/base/dashboards/jvm-build-service/OWNERS
Labels: lgtm, approved

#4096 Fix invalid json in mintmaker renovate config
  components/mintmaker/base/renovate-config.yaml
Labels: lgtm, approved

#4105 SRVKP-4523: make tekton controller restart/deadlock alert metrics available to app-sre grafana
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#4009 Disable automatic approval on stone-prod-p01
  components/sandbox/toolchain-host-operator/production/stone-prod-p01/toolchainconfig.yaml
Labels: lgtm, approved

#4010 Remove entry in .gitignore file
  .gitignore
Labels: lgtm, approved

#4111 Move renovate config to the renovate repo
  components/mintmaker/base/kustomization.yaml
  components/mintmaker/base/renovate-config.yaml
  components/mintmaker/development/kustomization.yaml
  components/mintmaker/production/base/kustomization.yaml
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#4075 Add Tempo operator to enable viewing traces in development environment
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/tempo/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/tempo/tempo.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
  components/tracing/otel-collector/development/otel-collector-helm-values.yaml
  components/tracing/tempo/development/kustomization.yaml
  components/tracing/tempo/development/tempo-operator.yaml
  components/tracing/tempo/development/tempo.yaml
Labels: lgtm, approved

#4118 chore(RELEASE-971): point internal-services to latest commit
  components/internal-services/kustomization.yaml
Labels: lgtm, approved

#4121 Adding tier enablement in production
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/kustomization.yaml
  components/sandbox/toolchain-host-operator/production/stone-prod-p01/kustomization.yaml
  components/sandbox/toolchain-host-operator/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#4108 workspaces: bump to v0.1.0-alpha3
  components/workspaces/base/operator/config/manager/kustomization.yaml
  components/workspaces/base/operator/config/manager/manager.yaml
  components/workspaces/base/server/config/default/kustomization.yaml
  components/workspaces/base/server/config/server/deployment.yaml
  components/workspaces/base/server/config/server/kustomization.yaml
  components/workspaces/staging/kustomization.yaml
Labels: lgtm, approved

#4070 Deploy toolchain-member-operator on staging eaas cluster
  argo-cd-apps/base/local-cluster-secret/all-in-one/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/toolchain-member/kustomization.yaml
  argo-cd-apps/base/toolchain-member/toolchain-member-operator.yaml
  argo-cd-apps/k-components/assign-toolchain-member-role-to-local-cluster/kustomization.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/space-provisioner-configs.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/space-provisioner-configs.yaml
Labels: lgtm, approved

#4124 Restore the toolchain-member-operator in public prod
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
Labels: lgtm, approved

#4126 Disable automated sync for toolchain-member-operator
  argo-cd-apps/base/toolchain-member/toolchain-member-operator.yaml
Labels: approved

#4127 Set prd-m01 as default cluster
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/space-provisioner-configs.yaml
Labels: approved

#4128 Revert "Set prd-m01 as default cluster (#4127)"
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/space-provisioner-configs.yaml
Labels: lgtm, approved

#4119 mintmaker update
  components/mintmaker/development/kustomization.yaml
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#4129 Revert "Disable automated sync for toolchain-member-operator (#4126)"
  argo-cd-apps/base/toolchain-member/toolchain-member-operator.yaml
Labels: approved

#4133 Revert "Disable automatic approval on stone-prod-p01 (#4009)"
  components/sandbox/toolchain-host-operator/production/stone-prod-p01/toolchainconfig.yaml
Labels: approved

#4134 Remove the SpaceProvisionerConfig for EaaS in public staging
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/space-provisioner-configs.yaml
Labels: lgtm, approved

#4125 Remove stuartwdouglas from all OWNERS files
  components/build-service/OWNERS
  components/jvm-build-service/OWNERS
  components/monitoring/grafana/base/dashboards/build-service/OWNERS
  components/monitoring/grafana/base/dashboards/image-controller/OWNERS
  components/monitoring/grafana/base/dashboards/jvm-build-service/OWNERS
  components/multi-platform-controller/OWNERS
  components/sprayproxy/OWNERS
Labels: lgtm, approved

#4123 workspaces: split internal & external staging
  components/workspaces/staging/stone-stage-p01/kustomization.yaml
  components/workspaces/staging/stone-stg-host/kustomization.yaml
  components/workspaces/staging/stone-stg-host/route.yaml
Labels: lgtm, approved

#4145 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#4132 Disable automated pruning for toolchain operators
  argo-cd-apps/base/host/toolchain-host-operator/toolchain-host-operator.yaml
  argo-cd-apps/base/toolchain-member/toolchain-member-operator.yaml
Labels: lgtm, approved

#4151 Promote mintmaker from staging to production
  components/mintmaker/production/base/kustomization.yaml
Labels: lgtm, approved

#4152 Allow mintmaker team members to create delete dependencyupdatechecks
  components/mintmaker/base/rbac/mintmaker-team.yaml
Labels: lgtm, approved

#4157 feat(RHTAPWATCH-1166): update prod project-controller
  components/project-controller/production/kustomization.yaml
Labels: lgtm, approved

#4158 chore(RELEASE-1047): bump internal-services crd commit
  components/internal-services/kustomization.yaml
Labels: lgtm, approved

#4149 workspaces: use correct subdir of staging/ to deploy
  argo-cd-apps/base/host/workspaces/workspaces.yaml
Labels: lgtm, approved

#4160 Increase tekton-pipelines-remote-resolvers mem limit
  components/pipeline-service/production/base/update-tekton-config-performance.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4159 SRVKP-4523: make tekton controller k8s throttle metrics available to app-sre grafana
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#4163 workspaces: specify host for route
  components/workspaces/staging/stone-stg-host/route.yaml
Labels: lgtm, approved

#4162 Enabling role, rolebinding and sa management for workspace admins
  components/sandbox/tiers/src/appstudio/spacerole_admin.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-admin-1876853981-1876853981.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-admin-1884308846-1876853981.yaml
Labels: lgtm, approved

#4168 tekton-ci: prune build-templates-e2e harder
  components/tekton-ci/production/cleanup-cronjob.yaml
Labels: lgtm, approved

#4170 tune remote-resolvers again for memory issues seen on prod-rh01
  components/pipeline-service/production/base/update-tekton-config-performance.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm

#4153 Move staging eaas SpaceProvisionerConfig to public deployment
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/space-provisioner-configs.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/space-provisioner-configs.yaml
Labels: lgtm, approved

#4171 enable OSP pruner again for resolver memory issues and results prune performance issues seen on prod-rh01
  components/pipeline-service/production/base/update-tekton-config-performance.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4175 Revert "enable OSP pruner again for resolver memory issues and result…
  components/pipeline-service/production/base/update-tekton-config-performance.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4090 promote hac-dev to prod
  components/ui/production/stone-prod-p01/kustomization.yaml
  components/ui/production/stone-prod-p02/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: needs-ok-to-test

#4144 feat(KONFLUX-3796): Test arm64 multi-arch builds with lots of VMs
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#4184 enable OSP pruner again
  components/pipeline-service/production/base/update-tekton-config-performance.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4180 workspaces: apply roles to translated service account name
  components/workspaces/base/server/config/default/kustomization.yaml
Labels: lgtm, approved

#4192 chore(STONEINTG-1013): increase Integration Pipeline timeout to 4hr+2hr
  components/integration/development/kustomization.yaml
  components/integration/production/base/kustomization.yaml
  components/integration/staging/base/kustomization.yaml
Labels: lgtm, approved

#4201 [KFLUXINFRA-717] Allow rhoai onboard to internal cluster
  components/repository-validator/production/kustomization.yaml
  components/repository-validator/staging/kustomization.yaml
Labels: lgtm, approved

#4202 chore(RHTAPWATCH-1174): Prod: Bump project-controller
  components/project-controller/production/kustomization.yaml
Labels: lgtm, approved

#4197 workspaces: bump to v0.1.0-alpha4
  components/workspaces/base/operator/config/manager/kustomization.yaml
  components/workspaces/staging/stone-stage-p01/kustomization.yaml
  components/workspaces/staging/stone-stg-host/kustomization.yaml
Labels: lgtm, approved

#4210 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#4211 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#4205 workspaces: correctly override image references
  components/workspaces/base/server/config/server/kustomization.yaml
  components/workspaces/staging/stone-stage-p01/kustomization.yaml
  components/workspaces/staging/stone-stg-host/kustomization.yaml
Labels: lgtm, approved

#4209 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#4207 Update mintmaker-renovate-image digest
  components/mintmaker/production/base/manager_patches.yaml
Labels: lgtm, approved

#4214 Enable EaaS in public staging
  argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
  components/cluster-as-a-service/staging/external-secrets.yaml
  components/cluster-as-a-service/staging/kustomization.yaml
Labels: lgtm, approved

#4221 Fix MintMaker tag digest
  components/mintmaker/production/base/manager_patches.yaml
Labels: lgtm, approved

#4222 Allow ExternalSecrets in namespaces for EaaS
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: lgtm, approved

#4232 Add IBMP dynamic pool for internal stage
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: approved

#4235 Fix staging ExternalSecret for cluster-as-a-service
  components/cluster-as-a-service/staging/external-secrets.yaml
Labels: lgtm, approved

#4237 Fix ExternalSecret labels
  components/cluster-as-a-service/staging/external-secrets.yaml
Labels: lgtm, approved

#4188 adust watcher mem for increased prod-rh01 load
  components/pipeline-service/production/base/bump-results-watcher-mem.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved
