Repository redhat-appstudio/infra-deployments, pull requests merged in 2024-12, with the labels that each got.

#5016 Enable proactive scaler in staging
  argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
Labels: lgtm, approved

#5022 Enable Tekton Log Forwarding in infra nodes
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5005 chore(KFLUXINFRA-930): Bump MPC in production
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
  components/multi-platform-controller/production/kustomization.yaml
Labels: lgtm, approved

#5027 Schedule Tekton Logging Forwarder to konflux-ci.dev/workload
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5032 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#5038 Revert NVMe Disk Configs for Prod Overlays
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
Labels: lgtm, approved

#5028 KFLUXINFRA-1131: Overlays for kflux-prd-rh02
  components/build-service/production/kflux-prd-rh02/kustomization.yaml
  components/build-service/production/kflux-prd-rh02/pipelines-as-code-secret-path.yaml
  components/integration/production/kflux-prd-rh02/console-url-config-patch.json
  components/integration/production/kflux-prd-rh02/kustomization.yaml
  components/integration/production/kflux-prd-rh02/pipelines-as-code-secret-path.yaml
  components/mintmaker/production/kflux-prd-rh02/kustomization.yaml
  components/mintmaker/production/kflux-prd-rh02/pipelines-as-code-secret-path.yaml
  components/monitoring/logging/production/kflux-prd-rh02/kustomization.yaml
  components/monitoring/prometheus/production/kflux-prd-rh02/cluster-id-label.yaml
  components/monitoring/prometheus/production/kflux-prd-rh02/kustomization.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/kustomization.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/kustomization.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/osp-perf-resolvers.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/pipelines-as-code-secret-path.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/tekton-chains-public-key-path.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/tekton-chains-signing-secret-path.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/tekton-results-s3-secret-path.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/update-tekton-config-pac.yaml
Labels: lgtm, approved

#5033 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#5035 chore(KFLUXVNGD-89): Add service account and related config
  argo-cd-apps/base/eaas/crossplane-config/crossplane-config.yaml
  argo-cd-apps/base/eaas/crossplane-config/kustomization.yaml
  argo-cd-apps/base/eaas/kustomization.yaml
  components/crossplane-config/OWNERS
  components/crossplane-config/base/kustomization.yaml
  components/crossplane-config/base/rbac.yaml
  components/crossplane-config/base/secret.yaml
  components/crossplane-config/development/kustomization.yaml
  components/crossplane-config/production/kustomization.yml
  components/crossplane-config/staging/kustomization.yaml
Labels: lgtm, approved

#5048 Increase disk size of ART arm64 instance to 160GB
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, ok-to-test, approved

#5043 chore: add release-monitor secrets
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
  components/release/staging/external-secrets/release-monitor-secret.yaml
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#5046 chore: Remove crossplane-config secret file
  components/crossplane-config/base/kustomization.yaml
  components/crossplane-config/base/secret.yaml
Labels: lgtm, approved

#5047 chore: internal-services update
  components/internal-services/kustomization.yaml
Labels: lgtm, approved

#5050 Create new ARM flavor with larger disk
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5052 Fix IBM s390 VPC name for kflux-ocp-p01
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: approved

#5056 Update Tekton Results to v0.13.0-2
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5057 fix: typo in preview script for integration-service
  hack/preview.sh
Labels: lgtm, approved

#5062 KFLUXINFRA-1131: Add kflux-prd-rh02 to the Argo apps
  argo-cd-apps/base/all-clusters/infra-deployments/authentication/authentication.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml
  argo-cd-apps/base/member/infra-deployments/build-service/build-service.yaml
  argo-cd-apps/base/member/infra-deployments/integration/integration.yaml
  argo-cd-apps/base/member/infra-deployments/mintmaker/mintmaker.yaml
  argo-cd-apps/base/member/infra-deployments/pipeline-service/pipeline-service.yaml
Labels: lgtm, approved

#5060 feat(KONFLUX-5480): Update pipeline references
  components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
Labels: lgtm, approved

#5063 KFLUXINFRA-1131: kflux-prd-rh02 update console urls
  components/integration/production/kflux-prd-rh02/console-url-config-patch.json
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/update-tekton-config-pac.yaml
Labels: lgtm, approved

#5066 Revert "Pass QPS, Burst and Thread Flag to Results Watcher (#5055)"
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: approved

#4859 add konflux-ci-repo-creator secret to konflux-ci
  components/konflux-ci/base/external-secrets/konflux-ci-repo-creator.yaml
  components/konflux-ci/base/external-secrets/kustomization.yaml
Labels: lgtm, approved

#5058 fix: Ingress Controller Configuration
  argo-cd-apps/base/host/ingresscontroller/ingresscontroller.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  configs/ingresscontroller/base/kustomization.yaml
  configs/ingresscontroller/base/timeout-patch.yaml
  configs/ingresscontroller/development/kustomization.yaml
  configs/ingresscontroller/production/stone-prd-host1/kustomization.yaml
  configs/ingresscontroller/staging/stone-stg-host/kustomization.yaml
Labels: approved

#5072 KFLUXINFRA-1131: kflux-prd-rh02 update console urls
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/update-tekton-config-pac.yaml
Labels: approved

#5077 KFLUXINFRA-1131: Remove cluster path from authentication app
  argo-cd-apps/base/all-clusters/infra-deployments/authentication/authentication.yaml
Labels: approved

#5079 KFLUXINFRA-1131: Allow tekton to use the appstudio-scc
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/kustomization.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/scc-rbac.yaml
Labels: lgtm, approved

#5080 Add PipelineAsCode labels selector to the forwarder log
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5084 Remove large nodes from config
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#5067 feat: Pass QPS, Burst and Thread Flag to Results Watcher, attempt 2
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5036 move pipelines and resolvers controller from leader election to state…
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5086 KFLUXINFRA-1099: Move s390x to dynamic for prod-external
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#5068 Allow the pipeline runner SA to list secrets
  components/sandbox/toolchain-member-operator/base/rbac/appstudio-pipelines-runner.yaml
Labels: lgtm, approved

#5088 Revert "feat: Pass QPS, Burst and Thread Flag to Results Watcher, att…
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: approved

#5087 Deploy crossplane XNamespace composition
  components/crossplane-config/base/rbac.yaml
  components/crossplane-control-plane/base/kustomization.yaml
Labels: lgtm, approved

#5098 Update Tekton Results to v0.13.2-1 stage
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5109 Allow repos from quipucords organization
  components/repository-validator/production/kustomization.yaml
Labels: approved

#5093 chore(KFLUXVNGD-89): Add stage kubernetes provider config
  components/crossplane-control-plane/staging/kustomization.yaml
  components/crossplane-control-plane/staging/provider-config.yaml
Labels: lgtm, approved

#5111 chore: Update the External Secret version in crossplane
  components/crossplane-control-plane/staging/provider-config.yaml
Labels: lgtm, approved

#5110 KFLUXINFRA-1131: UI deployment in rh02
  argo-cd-apps/base/member/infra-deployments/konflux-ui/konflux-ui.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  components/konflux-ui/base/kustomization.yaml
  components/konflux-ui/production/base/dex/dex.yaml
  components/konflux-ui/production/base/dex/kustomization.yaml
  components/konflux-ui/production/base/kustomization.yaml
  components/konflux-ui/production/base/proxy/kustomization.yaml
  components/konflux-ui/production/base/proxy/nginx.conf
  components/konflux-ui/production/base/proxy/proxy.yaml
  components/konflux-ui/production/base/route-and-oauth.yaml
  components/konflux-ui/production/empty-base/kustomization.yaml
  components/konflux-ui/production/kflux-prd-rh02/add-service-certs-patch.yaml
  components/konflux-ui/production/kflux-prd-rh02/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/kflux-prd-rh02/dex-config.yaml
  components/konflux-ui/production/kflux-prd-rh02/kustomization.yaml
  components/konflux-ui/production/kflux-prd-rh02/oauth2-proxy-args-patch.yaml
  components/konflux-ui/production/kflux-prd-rh02/remove-run-as-user-proxy-patch.yaml
  components/konflux-ui/production/kflux-prd-rh02/set-hostname.yaml
  components/konflux-ui/production/kflux-prd-rh02/set-redirect-uri.yaml
  components/konflux-ui/production/kflux-prd-rh02/set-replicas-patch.yaml
Labels: lgtm, approved

#5112 chore: add crossplane-system secrets
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: lgtm, approved

#5083 KONFLUX-3273: Add build pipeline for MRRC release process
  components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
Labels: lgtm, ok-to-test, approved

#5116 Increase s390x prod instances to 30 after some maintenance on IBM side
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#5114 KFLUXINFRA-1131: RBAC manifests for rh02
  argo-cd-apps/base/member/infra-deployments/konflux-rbac/konflux-rbac.yaml
  argo-cd-apps/base/member/infra-deployments/konflux-rbac/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
  components/konflux-rbac/production/base/konflux-admin-user-actions.yaml
  components/konflux-rbac/production/base/konflux-contributor-user-actions.yaml
  components/konflux-rbac/production/base/konflux-maintainer-user-actions.yaml
  components/konflux-rbac/production/base/kustomization.yaml
  components/konflux-rbac/production/empty-base/kustomization.yaml
  components/konflux-rbac/production/kflux-prd-rh02/kustomization.yaml
Labels: lgtm, approved

#5118 Fix the crossplane RBAC and staging ProviderConfig
  components/crossplane-config/base/rbac.yaml
  components/crossplane-control-plane/staging/provider-config.yaml
Labels: lgtm, approved

#5119 Deploy latest crossplane resources with a ProviderConfig for dev
  components/crossplane-control-plane/base/kustomization.yaml
  components/crossplane-control-plane/development/kustomization.yaml
Labels: lgtm, approved

#5108 chore(KFLUXVNGD-89): Add crossplane provider config for prod
  components/crossplane-control-plane/production/kustomization.yaml
  components/crossplane-control-plane/production/provider-config.yaml
Labels: lgtm, approved

#5122 Grant everyone can view role to konflux-support
  components/authentication/base/everyone-can-view-patch.yaml
Labels: lgtm, approved

#5121 Increase snapshots quota
  components/sandbox/tiers/production/appstudio/kustomization.yaml
  components/sandbox/tiers/production/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-tenant-1361763024-1361763024.yaml
  components/sandbox/tiers/production/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/production/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-admin-1893065526-849337768.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-1893065526-593233715.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-contributor-1893065526-829105171.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-maintainer-1893065526-474752551.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-tenant-1893065526-1361763024.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-viewer-1893065526-4256863455.yaml
  components/sandbox/tiers/production/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/production/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-admin-2011494876-849337768.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-2011494876-593233715.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-2011494876-829105171.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-2011494876-474752551.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-2011494876-1361763024.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-2011494876-4256863455.yaml
  components/sandbox/tiers/src/appstudio/ns_tenant.yaml
  components/sandbox/tiers/src/appstudiolarge/based_on_tier.yaml
  components/sandbox/tiers/src/appstudioxlarge/based_on_tier.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-tenant-1361763024-1361763024.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-admin-1893065526-849337768.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-1893065526-593233715.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-contributor-1893065526-829105171.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-maintainer-1893065526-474752551.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-tenant-1893065526-1361763024.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-viewer-1893065526-4256863455.yaml
  components/sandbox/tiers/staging/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-admin-2011494876-849337768.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-2011494876-593233715.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-2011494876-829105171.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-2011494876-474752551.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-2011494876-1361763024.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-2011494876-4256863455.yaml
Labels: lgtm, approved

#5120 Roll out MPC update to prod
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
  components/multi-platform-controller/production/kustomization.yaml
Labels: lgtm, approved

#5123 Increase results-watcher number of threads
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5125 Disable OSP operator TektonConfig generation
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#5130 Update Tekton Results to version 0.13.2-2 stage
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5128 Add two grades of s390x VM
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#5127 Deploy Mintmaker to prod
  components/mintmaker/production/base/kustomization.yaml
  components/mintmaker/production/base/manager_patches.yaml
Labels: lgtm, ok-to-test, approved

#5137 fix(KONFLUX-5949): add Snapshot permissions for maintainers
  components/sandbox/tiers/production/appstudio/kustomization.yaml
  components/sandbox/tiers/production/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-maintainer-341231795-341231795.yaml
  components/sandbox/tiers/production/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/production/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-maintainer-1893065526-341231795.yaml
  components/sandbox/tiers/production/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/production/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-2011494876-341231795.yaml
  components/sandbox/tiers/src/appstudio/spacerole_maintainer.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-maintainer-341231795-341231795.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-maintainer-1893065526-341231795.yaml
  components/sandbox/tiers/staging/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-2011494876-341231795.yaml
Labels: lgtm, approved

#5138 Add snapshots permissions for maintainers on rh02
  components/konflux-rbac/production/base/konflux-maintainer-user-actions.yaml
Labels: lgtm, approved

#5133 Add Vector and update Results stone-prod-p01
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/ui/production/stone-prod-p01/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: lgtm, approved

#5054 mintmaker: update kustomization to transform renovate image
  components/mintmaker/production/base/kustomization.yaml
  components/mintmaker/production/base/kustomizeconfig.yaml
  components/mintmaker/production/base/manager_patch.yaml
  components/mintmaker/staging/base/kustomization.yaml
  components/mintmaker/staging/base/kustomizeconfig.yaml
  components/mintmaker/staging/base/manager_patch.yaml
Labels: lgtm, approved

#5154 chore: add secret information to release-monitor
  components/release/base/monitor/staging/configmap.yaml
  components/release/base/monitor/staging/kustomization.yaml
  components/release/base/monitor/staging/patches/env-secrets-patch.yaml
Labels: lgtm, approved

#5160 KFLUXBUGS-1610 - Logging Operator update - Update Splunk secret object to secretName & key
  components/monitoring/logging/base/configure-logging/configure-logforwarder.yaml
Labels: lgtm, approved

#5155 chore: adding pyxis secret reference
  components/release/base/monitor/staging/patches/env-secrets-patch.yaml
Labels: lgtm, approved

#5148 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#5169 Update results prod internal
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/ui/production/kflux-ocp-p01/kustomization.yaml
  components/ui/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#5165 Promoting component mintmaker from stage to prod
  components/mintmaker/production/base/kustomization.yaml
Labels: lgtm, approved

#5170 Reduce mumber of IBM VM's for Ocp-Art cluster account
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5172 Revert "Update results prod internal"
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/ui/production/kflux-ocp-p01/kustomization.yaml
  components/ui/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#5168 KFLUXINFRA-1183: Public Konflux information
  argo-cd-apps/base/member/infra-deployments/konflux-info/konflux-info.yaml
  argo-cd-apps/base/member/infra-deployments/konflux-info/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  components/konflux-info/base/kustomization.yaml
  components/konflux-info/base/rbac.yaml
  components/konflux-info/production/kflux-ocp-p01/info.json
  components/konflux-info/production/kflux-ocp-p01/kustomization.yaml
  components/konflux-info/production/kflux-prd-rh02/info.json
  components/konflux-info/production/kflux-prd-rh02/kustomization.yaml
  components/konflux-info/production/stone-prd-rh01/info.json
  components/konflux-info/production/stone-prd-rh01/kustomization.yaml
  components/konflux-info/production/stone-prod-p01/info.json
  components/konflux-info/production/stone-prod-p01/kustomization.yaml
  components/konflux-info/production/stone-prod-p02/info.json
  components/konflux-info/production/stone-prod-p02/kustomization.yaml
  components/konflux-info/staging/stone-stage-p01/info.json
  components/konflux-info/staging/stone-stage-p01/kustomization.yaml
  components/konflux-info/staging/stone-stg-rh01/info.json
  components/konflux-info/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#5173 KFLUXBUGS-1610 - Remove empty collector settings
  components/monitoring/logging/base/configure-logging/configure-logforwarder.yaml
Labels: lgtm, approved

#5175 KFLUXBUGS-1610 - Move tuning component into Splunk object for the Clu…
  components/monitoring/logging/staging/base/patches/configure-logforwarder-compression-patch.yaml
Labels: lgtm, approved

#5179 feat(KFLUXVNGD-142, KONFLUX-5791): promote project-controller
  components/project-controller/production/kustomization.yaml
Labels: lgtm, approved

#5136 Move cachi2 pipelines from tekton-ci to konflux-ci
  components/konflux-ci/base/repository.yaml
  components/tekton-ci/base/repository.yaml
Labels: lgtm, ok-to-test

#5176 [OCP] Create new flavors with larger disk
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, ok-to-test, approved

#5184 Increase release quota in large tiers
  components/sandbox/tiers/production/appstudio/kustomization.yaml
  components/sandbox/tiers/production/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-tenant-234313038-234313038.yaml
  components/sandbox/tiers/production/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/production/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-admin-3738936794-849337768.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-3738936794-593233715.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-contributor-3738936794-829105171.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-maintainer-3738936794-341231795.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-tenant-3738936794-234313038.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-viewer-3738936794-4256863455.yaml
  components/sandbox/tiers/production/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/production/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-admin-97963453-849337768.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-97963453-593233715.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-97963453-829105171.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-97963453-341231795.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-97963453-234313038.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-97963453-4256863455.yaml
  components/sandbox/tiers/src/appstudio/ns_tenant.yaml
  components/sandbox/tiers/src/appstudiolarge/based_on_tier.yaml
  components/sandbox/tiers/src/appstudioxlarge/based_on_tier.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-tenant-234313038-234313038.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-admin-3738936794-849337768.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-3738936794-593233715.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-contributor-3738936794-829105171.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-maintainer-3738936794-341231795.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-tenant-3738936794-234313038.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-viewer-3738936794-4256863455.yaml
  components/sandbox/tiers/staging/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-admin-97963453-849337768.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-97963453-593233715.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-97963453-829105171.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-97963453-341231795.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-97963453-234313038.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-97963453-4256863455.yaml
Labels: lgtm, approved

#5185 Increase memory limit for EaaS argocd controller
  components/cluster-as-a-service/base/argocd.yaml
Labels: lgtm, approved

#5094 chore(KFLUXVNGD-128): Delete old crossplane namespace claims
  components/crossplane-control-plane/base/configmap.yaml
  components/crossplane-control-plane/base/cronjob.yaml
  components/crossplane-control-plane/base/kustomization.yaml
  components/crossplane-control-plane/base/rbac.yaml
Labels: lgtm, approved

#5186 Updated amd64 concurrent builds to 50 prod-external
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#5178 Install Tekton Logs Collector using Kustomize generator
  .gitignore
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/vector-tekton-logs-collector/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/vector-tekton-logs-collector/vector-tekton-logs-collector.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  components/vector-tekton-logs-collector/development/kustomization.yaml
  components/vector-tekton-logs-collector/development/vector-helm-generator.yaml
  components/vector-tekton-logs-collector/development/vector-helm-values.yaml
  components/vector-tekton-logs-collector/development/vector-pre.yaml
  components/vector-tekton-logs-collector/staging/kustomization.yaml
  components/vector-tekton-logs-collector/staging/vector-helm-generator.yaml
  components/vector-tekton-logs-collector/staging/vector-helm-values.yaml
  components/vector-tekton-logs-collector/staging/vector-pre.yaml
  hack/generate-deploy-config.sh
Labels: lgtm, approved

#5188 KFLUXINFRA-1129: View Only Cluster Role for in-cluster Grafana
  components/authentication/base/grafana-view-only.yaml
  components/authentication/base/kustomization.yaml
Labels: lgtm, approved

#5194 Increase appstudio CR quotas in xlarge tier
  components/sandbox/tiers/production/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/production/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-admin-380792096-849337768.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-380792096-593233715.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-380792096-829105171.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-380792096-341231795.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-380792096-234313038.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-380792096-4256863455.yaml
  components/sandbox/tiers/src/appstudioxlarge/based_on_tier.yaml
  components/sandbox/tiers/staging/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-admin-380792096-849337768.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-380792096-593233715.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-380792096-829105171.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-380792096-341231795.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-380792096-234313038.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-380792096-4256863455.yaml
Labels: lgtm, approved

#5187 KFLUXINFRA-1163: Updating Host Config for MPC
  argo-cd-apps/base/member/infra-deployments/multi-platform-controller/multi-platform-controller.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/external-secrets.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/external-secrets.yaml
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
Labels: lgtm, approved

#5192 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#5199 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#5197 Update OSP to 5.0.5-555 on staging
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5202 fix(KFLUXINFRA-1129): Fix in-cluster grafana permissions
  components/monitoring/grafana/base/grafana-app.yaml
Labels: lgtm, approved

#5201 Update OSP to 5.0.5-555 on prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#5209 Reverting Changes made in PR-5202
  components/monitoring/grafana/base/grafana-app.yaml
Labels: lgtm, approved

#5214 Switch to Kustomize generator for Vector installation
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/vector-tekton-logs-collector/production/kustomization.yaml
  components/vector-tekton-logs-collector/production/vector-helm-generator.yaml
  components/vector-tekton-logs-collector/production/vector-helm-values.yaml
  components/vector-tekton-logs-collector/production/vector-pre.yaml
Labels: lgtm, approved

#5215 Remove enable-tekton-oci-bundles TektonConfig
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#5204 [OCP] Create new linux-d160-cxlarge/arm64 flavor
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5216 Add missing secret for Vector deployment
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#5217 Update results prod internal
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/ui/production/kflux-ocp-p01/kustomization.yaml
  components/ui/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#5218 Allow pipeline-service to delete logging pods
  components/pipeline-service/base/rbac/kustomization.yaml
  components/pipeline-service/base/rbac/tekton-logging/kustomization.yaml
  components/pipeline-service/base/rbac/tekton-logging/pipeline-service-sre.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved
