Repository redhat-appstudio/infra-deployments, pull requests merged in 2024-06, with the labels that each got.

#3825 Update repo validator config to latest revision
  components/repository-validator/production/kustomization.yaml
  components/repository-validator/staging/kustomization.yaml
Labels: lgtm, approved

#3823 Add cluster-as-a-service resources
  argo-cd-apps/base/eaas/cluster-as-a-service/cluster-as-a-service.yaml
  argo-cd-apps/k-components/deploy-to-all-clusters/all-clusters-label-selector.yaml
  components/cluster-as-a-service/base/argocd.yaml
  components/cluster-as-a-service/base/cluster-aas-operator.yaml
  components/cluster-as-a-service/base/clustertemplatequotas.yaml
  components/cluster-as-a-service/base/clustertemplates.yaml
  components/cluster-as-a-service/base/kustomization.yaml
  components/cluster-as-a-service/base/multicluster-engine.yaml
  components/cluster-as-a-service/base/namespaces.yaml
  components/cluster-as-a-service/base/rbac.yaml
  components/cluster-as-a-service/development/add-base-domain-param.yaml
  components/cluster-as-a-service/development/kustomization.yaml
Labels: lgtm, approved

#3818 chore(RHTAPWATCH-1021): enable Tekton StepActions in production
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#3740 PVCORE-4213 - Initial tracing commit
  argo-cd-apps/base/all-clusters/infra-deployments/enable-tekton-tracing/enable-tekton-tracing.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/enable-tekton-tracing/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/tracing-workload-otel-collector/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/tracing-workload-otel-collector/tracing-workload-otel-collector.yaml
  argo-cd-apps/k-components/inject-infra-deployments-repo-details/kustomization.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/kustomization.yaml
  components/tracing/OWNERS
  configs/enable-tekton-tracing/enable-tekton-tracing.yaml
  configs/enable-tekton-tracing/kustomization.yaml
Labels: lgtm, needs-ok-to-test, approved

#3826 Increase IO performance of rootful VMs
  components/multi-platform-controller/production-downstream/host-config.yaml
  components/multi-platform-controller/production/host-config.yaml
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#3804 Support pushing build-definitions images to quay.io/konflux-ci
  components/image-controller/production/stone-prd-rh01/resources/konflux-ci-pull-request-builds-pruner-cronjob.yaml
  components/image-controller/production/stone-prd-rh01/resources/konflux-ci-pull-request-builds-pruner-token.yaml
  components/image-controller/production/stone-prd-rh01/resources/kustomization.yaml
  components/konflux-ci/base/repository.yaml
  components/konflux-ci/production/kustomization.yaml
  components/konflux-ci/production/redhat-appstudio-tekton-catalog-build-definitions-pull-secret.yaml
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#3839 fix: increase ARGOCD_EXEC_TIMEOUT
  components/gitops/development/gitops-service-argocd.yaml
Labels: lgtm, approved

#3829 fix: rename integration configMap console-url to integration-config
  components/integration/development/kustomization.yaml
  components/integration/development/manager_resources_patch.yaml
  components/integration/production/base/kustomization.yaml
  components/integration/production/base/manager_resources_patch.yaml
  components/integration/production/stone-prod-p01/kustomization.yaml
  components/integration/production/stone-prod-p02/kustomization.yaml
  components/integration/staging/base/kustomization.yaml
  components/integration/staging/base/manager_resources_patch.yaml
  components/integration/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#3845 Removing otel-collector from public staging (for now)
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
Labels: lgtm, approved

#3836 Promote SPI/RemoteSecret from staging to prod
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#3848 Migrate build-definitions redhat-appstudio images
  components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
  components/build-service/base/build-pipeline-selectors/build-pipeline-selector.yaml
  components/enterprise-contract/ecp.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3854 fix: openshift-gitops argocd preview mode update
  components/gitops/development/core_service_resources_patch.yaml
  components/gitops/development/gitops-service-argocd.yaml
  components/gitops/development/kustomization.yaml
  components/gitops/development/service_agent_resources_patch.yaml
  hack/deploy-argocd.sh
Labels: lgtm, approved

#3766 Remove BuildPipelineSelector from infra-deployments
  components/build-service/README.md
  components/build-service/base/build-pipeline-selectors/OWNERS
  components/build-service/base/build-pipeline-selectors/build-pipeline-selector.yaml
  components/build-service/base/kustomization.yaml
Labels: lgtm, approved

#3859 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#3798 Introduce Mintmaker
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/mintmaker/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/mintmaker/mintmaker.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  components/mintmaker/OWNERS
  components/mintmaker/base/cronjob.yaml
  components/mintmaker/base/external-secrets/kustomization.yaml
  components/mintmaker/base/external-secrets/pipelines-as-code-secret.yaml
  components/mintmaker/base/kustomization.yaml
  components/mintmaker/base/mintmaker-team.yaml
  components/mintmaker/base/renovate-config.yaml
  components/mintmaker/components/rh-certs/add-rh-certs-patch.yaml
  components/mintmaker/components/rh-certs/kustomization.yaml
  components/mintmaker/development/kustomization.yaml
  components/mintmaker/k-components/manager-resources-patch/kustomization.yaml
  components/mintmaker/k-components/manager-resources-patch/manager_resources_patch.yaml
  components/mintmaker/production/kustomization.yaml
  components/mintmaker/staging/kustomization.yaml
  hack/build/setup-pac-integration.sh
  hack/preview.sh
Labels: lgtm, ok-to-test, approved

#3866 release-service update on production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#3849 release-service update on staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#3861 Update application-api refs
  components/application-api/kustomization.yaml
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#3867 KONFLUX-3382 Add fast VM's for openshift AI
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#3874 Update prod with latest image-controller version
  components/image-controller/production/base/kustomization.yaml
Labels: lgtm, approved

#3873 add image-controller dashboard path to kustomization
  components/monitoring/grafana/base/dashboards/kustomization.yaml
Labels: lgtm, approved

#3880 Fix fast pool AMI
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#3871 feat(RELEASE-977): migrate release-service to konflux-ci
  components/release/base/cronjobs/remove-expired-releases.yaml
  components/release/development/kustomization.yaml
  components/release/production/kustomization.yaml
  components/release/staging/kustomization.yaml
  hack/preview.sh
Labels: lgtm, approved

#3872 Update name of e2e push secret
  components/build-templates/production/e2e-quay-push-secret.yaml
Labels: lgtm, approved

#3879 chore: e2e-tests Repository CR -> konflux-ci ns
  components/konflux-ci/base/repository.yaml
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#3884 KFLUXBUGS-863: introduce results fixes with requisite performance related tuning (dev/stage)
  components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
  components/pipeline-service/development/bump-results-watcher-replicas.yaml
  components/pipeline-service/development/config.env
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/development/update-results-watcher-performance.yaml
  components/pipeline-service/staging/base/bump-results-watcher-replicas.yaml
  components/pipeline-service/staging/base/config.env
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/update-results-watcher-performance.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3887 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#3892 Update renovate's configuration
  components/mintmaker/base/renovate-config.yaml
Labels: lgtm, approved

#3868 Update Mintmaker staging deployment
  argo-cd-apps/base/member/infra-deployments/mintmaker/mintmaker.yaml
  components/mintmaker/staging/base/kustomization.yaml
  components/mintmaker/staging/kustomization.yaml
  components/mintmaker/staging/stone-stage-p01/kustomization.yaml
  components/mintmaker/staging/stone-stage-p01/pipelines-as-code-secret-path.yaml
Labels: lgtm, ok-to-test, approved

#3895 allow mintmaker service to access vault
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: lgtm, approved

#3862 update hac-dev ui to latest
  components/ui/production/stone-prod-p02/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#3904 chore: add psturc and ralphbean to approvers
  OWNERS
Labels: lgtm, approved

#3905 Add external secret for Mintmaker
  components/mintmaker/base/external-secrets/kustomization.yaml
  components/mintmaker/base/external-secrets/registry-redhat-io-pull-secret.yaml
Labels: lgtm, approved

#3896 Correct Mintmaker's configuration for rpm lockfile
  components/mintmaker/base/renovate-config.yaml
Labels: lgtm, approved

#3911 Move stage vms to expansion subnet temporarily
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: approved

#3912 KFLUXINFRA-635: Move the internal-prod s390x builds to ibm expansion temporaily
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: approved

#3910 test: add new keycloak user
  components/dev-sso/keycloak-realm.yaml
Labels: lgtm, approved

#3908 chore: quality-dashboard -> konflux-ci part 1
  components/konflux-ci/base/repository.yaml
  components/tekton-ci/base/repository.yaml
  docs/misc/quality-dashboard.md
  hack/preview-template.env
Labels: lgtm, approved

#3903 Add cronjob to delete old DependencyUpdateCheck CRs
  components/mintmaker/base/cronjobs/create-dependency-update-check.yaml
  components/mintmaker/base/cronjobs/delete-dependency-update-checks.yaml
  components/mintmaker/base/cronjobs/kustomization.yaml
  components/mintmaker/base/kustomization.yaml
Labels: lgtm, approved

#3916 PVCORE-4214 - Otel tracing configs for different environments
  components/tracing/otel-collector/development/otel-collector-helm-values.yaml
  components/tracing/otel-collector/staging/otel-collector-helm-values.yaml
Labels: lgtm, approved

#3919 KFLUXINFRA-635: Restore s390x and add a100 node to internal-stage hostconfig
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: approved

#3922 KFLUXINFRA-635: Restored the prod instances to DC1 and add A100 node to hostconfig
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: approved

#3923 Increase memory allocation for mintmaker controller
  components/mintmaker/k-components/manager-resources-patch/kustomization.yaml
  components/mintmaker/production/kustomization.yaml
  components/mintmaker/staging/base/kustomization.yaml
  components/mintmaker/staging/base/manager_resources_patch.yaml
Labels: lgtm, approved

#3900 Update pipeline-service and enable Results DB TLS
  components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
  components/pipeline-service/base/certificates/kustomization.yaml
  components/pipeline-service/base/certificates/tekton-results/kustomization.yaml
  components/pipeline-service/base/certificates/tekton-results/tekton-results-db-ssl.yaml
  components/pipeline-service/development/config.env
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/config.env
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  hack/secret-creator/create-plnsvc-secrets.sh
Labels: lgtm, approved

#3925 Allow mintmaker team members to create delete cronjobs and jobs
  components/mintmaker/base/kustomization.yaml
  components/mintmaker/base/mintmaker-team.yaml
  components/mintmaker/base/rbac/kustomization.yaml
  components/mintmaker/base/rbac/mintmaker-team.yaml
Labels: lgtm, approved

#3928 fix(typo): fix typo in check for postresql-tls
  hack/secret-creator/create-plnsvc-secrets.sh
Labels: lgtm, approved

#3918 Add ServiceMonitor for multi platform controller
  components/multi-platform-controller/base/kustomization.yaml
  components/multi-platform-controller/base/monitoring.yaml
Labels: lgtm, approved

#3932 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#3927 KFLUXBUGS-863: repin watcher image to mem leak version
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3935 Move Multi Platform Controller to konflux-ci GitHub organization
  components/multi-platform-controller/base/kustomization.yaml
  hack/preview.sh
Labels: lgtm, approved

#3941 KFLUXINFRA-646: Removed host iops from extra fast amd64
  components/multi-platform-controller/production/host-config.yaml
Labels: approved

#3936 Fix logging operator setup for kflux-prd-es01 cluster
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
  components/monitoring/logging/production/kflux-prd-es01/kustomization.yaml
Labels: lgtm, approved

#3931 update hac-dev ui to latest
  components/ui/production/stone-prod-p02/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#3909 Deploy Mintmaker to production
  argo-cd-apps/base/member/infra-deployments/mintmaker/mintmaker.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  components/mintmaker/production/base/kustomization.yaml
  components/mintmaker/production/base/pipelines-as-code-secret-patch.yaml
  components/mintmaker/production/kustomization.yaml
  components/mintmaker/production/stone-prod-p01/kustomization.yaml
  components/mintmaker/production/stone-prod-p01/pipelines-as-code-secret-path.yaml
  components/mintmaker/production/stone-prod-p02/kustomization.yaml
  components/mintmaker/production/stone-prod-p02/pipelines-as-code-secret-path.yaml
Labels: lgtm, approved

#3938 Disable Renovate's Dependency Dashboard by default
  components/mintmaker/base/renovate-config.yaml
Labels: lgtm, approved

#3942 Add gnaponie and qixiang to mintmaker owners
  components/mintmaker/OWNERS
Labels: lgtm, approved

#3943 Increase memory allocation for mintmaker controller in production
  components/mintmaker/production/base/kustomization.yaml
  components/mintmaker/production/base/manager_resources_patch.yaml
Labels: lgtm, approved

#3921 fix: post-setup verification script update
  components/build-service/README.md
  docs/development/deployment.md
  hack/build/build-via-appstudio.sh
  hack/build/templates/component.yaml
  hack/build/templates/secret.yaml
Labels: lgtm, approved

#3946 Fix extra fast instances
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#3947 fix: enlarge memery resouce limsit for integration service
  components/integration/production/base/manager_resources_patch.yaml
Labels: lgtm, approved

#3949 Use newer version of pipeline-docker-build image
  components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
Labels: lgtm, approved

#3958 Update p01 UI to same version as p02
  components/ui/production/stone-prod-p01/kustomization.yaml
Labels: lgtm, approved

#3957 chore(STONEINTG-972): update integration team members
  components/integration/OWNERS
Labels: lgtm, approved

#3937 Add Renovate preset to Renovate's configuration
  components/mintmaker/base/renovate-config.yaml
Labels: lgtm, approved

#3963 Disable tracing across the board
  configs/enable-tekton-tracing/enable-tekton-tracing.yaml
Labels: lgtm, approved

#3970 Deploy tracing application to member clusters only
  argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/tracing-workload-otel-collector/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/tracing-workload-otel-collector/tracing-workload-otel-collector.yaml
  argo-cd-apps/base/member/infra-deployments/tracing-workload-otel-collector/tracing-workload-tracing.yaml
Labels: lgtm, approved

#3968 Adding tracing component to the secret store allow list
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: lgtm, approved

#3973 feat: allow rootful MPC builds to disable entitlement mounts
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: approved
