Repository redhat-appstudio/infra-deployments, pull requests merged in 2024-10, with the labels that each got.

#4627 Increase maximum number of aarch64 nodes can spin up for public prod
  components/multi-platform-controller/production/common/host-config.yaml
Labels: lgtm, approved

#4622 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#4625 Update OSP prod
  components/multi-platform-controller/production/kustomization.yaml
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/resources/osp-nightly-version.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4629 revert release status change to fix ui
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#4630 Upgrade MPC version in internal clusters
  components/multi-platform-controller/production-downstream/kustomization.yaml
Labels: approved

#4631 fix release-service crashloop
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#4632 KFLUXINFRA-888: Increase max number of instances in internal prod s390x
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: approved

#4633 KFLUXINFRA-882: Remove Ax100 GPU node from IBMCloud
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: approved

#4624 Change KubeArchive namespace because of ROSA
  argo-cd-apps/base/member/infra-deployments/kubearchive/kubearchive.yaml
  components/authentication/base/everyone-can-view-patch.yaml
  components/kubearchive/base/kustomization.yaml
  components/kubearchive/development/kustomization.yaml
  components/kubearchive/staging/kustomization.yaml
Labels: lgtm, approved

#4634 Allow app-sre vault access from kubearchive namespace
  components/cluster-secret-store/base/appsre-vault-secret-store.yml
Labels: lgtm, approved

#4635 Fix kubearchive database secret extraction
  components/kubearchive/staging/database-secret.yaml
Labels: lgtm, approved

#4638 Fix DB secret name for KubeArchive
  components/kubearchive/staging/database-secret.yaml
Labels: lgtm, approved

#4639 rollback release-service in staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#4640 Fix DB secret keys for KubeArchive
  components/kubearchive/staging/database-secret.yaml
Labels: lgtm, approved

#4637 feat(KONFLUX-4508): Run more Pipelines Controller replicas across more zones in Prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4599 chore(RHTAPWATCH-1267): Update quay repository for project-controller
  components/project-controller/development/kustomization.yaml
  components/project-controller/staging/kustomization.yaml
Labels: lgtm, approved

#4643 chore(KFLUXVNGD-69): Update prod configuration for project-controller
  components/project-controller/production/kustomization.yaml
Labels: lgtm, approved

#4645 Use MCE provided images for the hypershift CLI
  components/cluster-as-a-service/base/clustertemplates.yaml
  components/cluster-as-a-service/development/add-hypershift-params.yaml
  components/cluster-as-a-service/production/add-hypershift-params.yaml
  components/cluster-as-a-service/staging/add-hypershift-params.yaml
Labels: lgtm, approved

#4646 feat(RELEASE-1192): allow rhtap-releng to use es
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: lgtm, approved

#4650 KFLUXINFRA-777: Unblocking NVME Disk Configuration for Production
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
Labels: lgtm, approved

#4618 Move cachi2 pipelines from tekton-ci to konflux-ci
  components/konflux-ci/base/repository.yaml
  components/tekton-ci/base/repository.yaml
Labels: lgtm, ok-to-test, approved

#4651 Update repo validator config to latest revision
  components/repository-validator/production/kustomization.yaml
Labels: lgtm, approved

#4654 feat(RELEASE-1192): release sa needs plr rbac
  components/release/base/release-pipeline-resources-clusterrole.yaml
Labels: lgtm, approved

#4655 Increase the allowed maximum number of dynamic hosts to 50
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: lgtm, approved

#4652 Backup all resources in toolchain member namespace
  components/backup/base/member/schedules/backup-toolchain-member-schedule.yaml
Labels: lgtm, approved

#4657 Adding pacho-rh to monitoring component
  components/monitoring/OWNERS
Labels: lgtm, approved

#4659 KFLUXINFRA-640: Enable dynamic nodes for ppc64le internal production
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: lgtm, approved

#4661 KFLUXINFRA-640: Removed static ppc-nodes and added ppc-large nodes for internal prod
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: approved

#4656 Add custom tags to apply on MPC VM's
  components/multi-platform-controller/production-downstream/host-config.yaml
  components/multi-platform-controller/production/common/host-config.yaml
  components/multi-platform-controller/staging-downstream/host-config.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#4660 chore(KFLUXVNGD-38): remove maintainers delete permissions
  components/sandbox/tiers/production/appstudio/kustomization.yaml
  components/sandbox/tiers/production/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-maintainer-474752551-474752551.yaml
  components/sandbox/tiers/production/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/production/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-maintainer-3994678728-474752551.yaml
  components/sandbox/tiers/production/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/production/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-884010306-474752551.yaml
  components/sandbox/tiers/src/appstudio/spacerole_maintainer.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-maintainer-474752551-474752551.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-maintainer-3994678728-474752551.yaml
  components/sandbox/tiers/staging/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-884010306-474752551.yaml
Labels: lgtm, approved

#4669 fix: increase release controller memory
  components/release/k-components/manager-resources-patch/manager_resources_patch.yaml
Labels: lgtm, approved

#4673 KFLUXINFRA-812: Dynamic host for s390x in external stage
  components/multi-platform-controller/staging/host-config.yaml
Labels: approved

#4668 add Workspace CRD in staging's member cluster
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/workspaces/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/workspaces/workspaces.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  components/workspaces/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#4677 KFLUXINFRA-799: Creating Cluster Secret Store for Insights
  components/cluster-secret-store/base/insights-secret-store.yaml
  components/cluster-secret-store/base/kustomization.yaml
  components/cluster-secret-store/production/insights-approle-id-patch.yaml
  components/cluster-secret-store/production/kustomization.yaml
  components/cluster-secret-store/staging/insights-approle-id-patch.yaml
  components/cluster-secret-store/staging/kustomization.yaml
Labels: lgtm, approved

#4648 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#4679 feat(KONFLUX-4940,KONFLUX-4941): New/updated perf-related dashboards
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, approved

#4681 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#4682 fix(KONFLUX-4941): These metrics are not supposed to be summed, but averaged
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, approved

#4687 KFLUXINFRA-799: adjusted tenant name for insights
  components/cluster-secret-store/base/insights-secret-store.yaml
Labels: lgtm, needs-ok-to-test, approved

#4690 fix(KONFLUX-4955): Update cluster monitoring permission for Perf-Monitoring Service Account
  components/perf-team-prometheus-reader/base/serviceaccount.yaml
Labels: lgtm, approved

#4689 fix: Fix name in one graph and disable stacking in another
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, approved

#4649 workspaces: deploy v0.1.0-alpha7 to production
  components/workspaces/base/operator/config/manager/kustomization.yaml
  components/workspaces/base/operator/config/metrics/kustomization.yaml
  components/workspaces/base/operator/config/metrics/monitor.yaml
  components/workspaces/base/server/config/server/kustomization.yaml
  components/workspaces/production/stone-prd-host1/kustomization.yaml
  components/workspaces/production/stone-prod-p01/kustomization.yaml
  components/workspaces/production/stone-prod-p02/kustomization.yaml
  components/workspaces/staging/base/kustomization.yaml
  components/workspaces/staging/base/operator/config/crd/bases/workspaces.konflux-ci.dev_internalworkspaces.yaml
  components/workspaces/staging/base/operator/config/crd/kustomization.yaml
  components/workspaces/staging/base/operator/config/crd/kustomizeconfig.yaml
  components/workspaces/staging/base/operator/config/crd/patches/cainjection_in_workspaces.yaml
  components/workspaces/staging/base/operator/config/crd/patches/webhook_in_workspaces.yaml
  components/workspaces/staging/base/operator/config/default/kustomization.yaml
  components/workspaces/staging/base/operator/config/default/manager_auth_proxy_patch.yaml
  components/workspaces/staging/base/operator/config/manager/kustomization.yaml
  components/workspaces/staging/base/operator/config/manager/manager.yaml
  components/workspaces/staging/base/operator/config/metrics/kustomization.yaml
  components/workspaces/staging/base/operator/config/metrics/metrics-service.yaml
  components/workspaces/staging/base/operator/config/metrics/monitor.yaml
  components/workspaces/staging/base/operator/config/metrics/service-account.yaml
  components/workspaces/staging/base/operator/config/rbac/auth_proxy_client_clusterrole.yaml
  components/workspaces/staging/base/operator/config/rbac/auth_proxy_role.yaml
  components/workspaces/staging/base/operator/config/rbac/auth_proxy_role_binding.yaml
  components/workspaces/staging/base/operator/config/rbac/internalworkspace_editor_role.yaml
  components/workspaces/staging/base/operator/config/rbac/internalworkspace_viewer_role.yaml
  components/workspaces/staging/base/operator/config/rbac/kustomization.yaml
  components/workspaces/staging/base/operator/config/rbac/leader_election_role.yaml
  components/workspaces/staging/base/operator/config/rbac/leader_election_role_binding.yaml
  components/workspaces/staging/base/operator/config/rbac/role.yaml
  components/workspaces/staging/base/operator/config/rbac/role_binding.yaml
  components/workspaces/staging/base/operator/config/rbac/service_account.yaml
  components/workspaces/staging/base/server/config/crd/bases/workspaces.konflux-ci.dev_workspaces.yaml
  components/workspaces/staging/base/server/config/crd/kustomization.yaml
  components/workspaces/staging/base/server/config/default/kustomization.yaml
  components/workspaces/staging/base/server/config/rbac/kustomization.yaml
  components/workspaces/staging/base/server/config/rbac/role_spacebinding_reader.yaml
  components/workspaces/staging/base/server/config/rbac/role_usersignup_reader.yaml
  components/workspaces/staging/base/server/config/rbac/role_workspace_server_editor.yaml
  components/workspaces/staging/base/server/config/rbac/rolebinding_spacebinding_reader.yaml
  components/workspaces/staging/base/server/config/rbac/rolebinding_usersignup_reader.yaml
  components/workspaces/staging/base/server/config/rbac/rolebinding_workspace_server_editor.yaml
  components/workspaces/staging/base/server/config/rbac/serviceaccount.yaml
  components/workspaces/staging/base/server/config/server/deployment.yaml
  components/workspaces/staging/base/server/config/server/kustomization.yaml
  components/workspaces/staging/base/server/config/server/proxy-config/dynamic/config.yaml
  components/workspaces/staging/base/server/config/server/proxy-config/traefik.yaml
  components/workspaces/staging/base/server/config/server/service.yaml
  components/workspaces/staging/stone-stg-host/kustomization.yaml
Labels: lgtm, approved

#4696 Fix kustomize build in workspaces component
  components/workspaces/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#4694 workspaces: ensure validation of JWT's sub and exp
  components/workspaces/base/server/config/server/proxy-config/dynamic/config.yaml
Labels: lgtm, approved

#4704 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#4710 KFLUXINFRA-799: Fixing Role ID for Insights Vault App Role
  components/cluster-secret-store/production/insights-approle-id-patch.yaml
  components/cluster-secret-store/staging/insights-approle-id-patch.yaml
Labels: lgtm, approved

#4711 Promote MPC fixes to production
  components/multi-platform-controller/production/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-m01/kustomization.yaml
Labels: lgtm, approved

#4699 feat: Added current tenant quotas
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, approved

#4715 fix: fixing the api version for vault
  components/cluster-secret-store/base/insights-secret-store.yaml
Labels: approved

#4705 fix: workspaces resources required on member clusters
  argo-cd-apps/base/member/infra-deployments/workspaces/kustomization.yaml
  components/workspaces/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#4713 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#4719 chore: update release-service owners
  components/monitoring/grafana/base/dashboards/release/OWNERS
  components/release/OWNERS
Labels: lgtm, approved

#4718 Fix sync issues in the cluster-as-a-service component
  components/cluster-as-a-service/base/multicluster-engine.yaml
  components/cluster-as-a-service/development/klusterlet-config.yaml
Labels: lgtm, approved

#4721 Promote MPC fixes to internal production
  components/multi-platform-controller/production-downstream/kustomization.yaml
Labels: lgtm, approved

#4723 fix(KFLUXBUGS-1735): increase memory limits for integration service
  components/integration/production/base/manager_resources_patch.yaml
Labels: lgtm, approved

#4726 fix: promote latest hac-dev to staging
  components/ui/development/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#4729 [temporary] Test MPC metrics refactoring to secure endpoint
  components/multi-platform-controller/base/common/monitoring.yaml
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#4731 Fixup role binding
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#4732 Fixup MPC role
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#4733 Fixup SA
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#4734 Fixup RBAC
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#4735 adding martysp21 to o11y OWNERS
  components/monitoring/OWNERS
  components/tracing/OWNERS
Labels: lgtm, approved

#4737 Fixup MPC RBAC
  components/multi-platform-controller/base/common/monitoring.yaml
Labels: lgtm, approved

#4738 Revert MpC test changes
  components/multi-platform-controller/base/common/monitoring.yaml
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#4736 Deploy insight vault only to RH member clusters
  components/cluster-secret-store-rh/base/insights-secret-store.yaml
  components/cluster-secret-store-rh/base/kustomization.yaml
  components/cluster-secret-store-rh/production/insights-approle-id-patch.yaml
  components/cluster-secret-store-rh/production/kustomization.yaml
  components/cluster-secret-store/base/kustomization.yaml
  components/cluster-secret-store/production/kustomization.yaml
Labels: lgtm, approved

#4743 fix(KFLUXBUGS-1600): internalrequests for timed out pipelineruns are not removed
  components/release/base/cronjobs/remove-internal-requests.yaml
Labels: lgtm, approved

#4741 Set MPC deployment replicas to 5 for internal clusters
  components/multi-platform-controller/production-downstream/kustomization.yaml
  components/multi-platform-controller/production-downstream/replicas_patch.yaml
Labels: lgtm, approved

#4752 Increase ppc count to 200
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: lgtm, approved

#4753 Increase MPC VM allocation timeout
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: lgtm, approved

#4754 increase MPC replica count
  components/multi-platform-controller/production-downstream/replicas_patch.yaml
Labels: lgtm, approved

#4755 More replicas do not seem to improve the situation
  components/multi-platform-controller/production-downstream/replicas_patch.yaml
Labels: lgtm, approved

#4759 Reduce number of IBM VMs in internal prod
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: lgtm, approved

#4761 Update MPC on internal-prod with multi-threaded version
  components/multi-platform-controller/production-downstream/kustomization.yaml
Labels: lgtm, approved

#4763 Fixup MPC container patch
  components/multi-platform-controller/development/logs-in-console-format-cmd-arg-patch.yaml
Labels: lgtm, approved

#4762 Enabling Proactive Autoscaling for the Production Clusters
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  configs/proactive-scaler/base/deployments.yaml
Labels: lgtm, approved

#4749 fix: updating kustomization file
  components/release/base/cronjobs/kustomization.yaml
Labels: lgtm, approved

#4768 Fix priority class of the proactive scaler pods
  configs/proactive-scaler/base/deployments.yaml
  configs/proactive-scaler/base/priority-class.yaml
Labels: lgtm, approved

#4767 remove workspaces from production clusters
  argo-cd-apps/base/host/workspaces/workspaces.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  components/workspaces/production/stone-prd-host1/kustomization.yaml
  components/workspaces/production/stone-prd-host1/route.yaml
  components/workspaces/production/stone-prod-p01/kustomization.yaml
  components/workspaces/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#4774 Update production to the latest MPC with all recent fixes
  components/multi-platform-controller/production-downstream/kustomization.yaml
  components/multi-platform-controller/production/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-m01/kustomization.yaml
Labels: lgtm, approved

#4776 Increase tekton remote resolver resources
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4777 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#4778 Reduce Tekton resolver resources
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4764 Add Knative Event, KubeArchive dependency, as infra component
  argo-cd-apps/base/member/infra-deployments/knative-eventing/knative-eventing.yaml
  argo-cd-apps/base/member/infra-deployments/knative-eventing/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  components/knative-eventing/OWNERS
  components/knative-eventing/base/kustomization.yaml
  components/knative-eventing/development/kustomization.yaml
  components/knative-eventing/staging/kustomization.yaml
Labels: lgtm, approved

#4775 Temporary dev MPC image for staging
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#4779 Ignore Aggregated Roles in Knative Eventing
  argo-cd-apps/base/member/infra-deployments/knative-eventing/knative-eventing.yaml
Labels: lgtm, approved

#4783 create internal certs config map in all cluster for build-service
  components/build-service/production/base/kustomization.yaml
  components/build-service/production/stone-prod-p01/kustomization.yaml
  components/build-service/production/stone-prod-p02/kustomization.yaml
  components/build-service/staging/base/kustomization.yaml
  components/build-service/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#4765 Update KubeArchive to v0.3.0
  argo-cd-apps/base/member/infra-deployments/kubearchive/kubearchive.yaml
  components/kubearchive/base/alternative-service.yaml
  components/kubearchive/base/kustomization.yaml
  components/kubearchive/development/kustomization.yaml
  components/kubearchive/staging/database-secret.yaml
Labels: lgtm, approved

#4785 Include myself in MintMaker code owners
  components/mintmaker/OWNERS
Labels: lgtm, approved

#4784 Promote mintmaker from stage to prod
  components/mintmaker/production/base/kustomization.yaml
Labels: lgtm, approved

#4786 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#4788 Fix authentication for new kflux-ocp-p01 cluster
  components/authentication/production/kflux-ocp-p01/kustomization.yaml
Labels: lgtm, approved

#4787 Make sure we have 2 worker nodes in advance
  configs/proactive-scaler/base/deployments.yaml
Labels: lgtm, approved

#4792 enable compression in SPLUNK log forwarder for the staging cluster
  components/monitoring/logging/staging/stone-stage-p01/configure-logforwarder-compression-patch.yaml
  components/monitoring/logging/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#4791 Configure Pipelines as Code to require /ok-to-test on every new commit
  components/pipeline-service/production/base/update-tekton-config-pac.yaml
  components/pipeline-service/production/stone-prod-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/stone-prod-p02/resources/update-tekton-config-pac.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/update-tekton-config-pac.yaml
Labels: lgtm, approved

#4807 Promote latest MPC to the internal prod
  components/multi-platform-controller/production-downstream/kustomization.yaml
Labels: lgtm, approved

#4809 feat(KONFLUX-5124): Test with more VMs available
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#4819 Bump hypershift-aws-template chart version
  components/cluster-as-a-service/base/clustertemplates.yaml
Labels: lgtm, approved

#4818 Generate stone-stage-p01 pipeline deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
Labels: lgtm, approved
