Repository redhat-appstudio/infra-deployments, pull requests merged in 2024-04, with the labels that each got.

#3489 Add cronjobs for pruning repositories:
  .tekton/image-controller-prod-overlay-update.yaml
  argo-cd-apps/base/member/infra-deployments/image-controller/image-controller.yaml
  components/image-controller/production/base/kustomization.yaml
  components/image-controller/production/base/manager_resources_patch.yaml
  components/image-controller/production/base/quaytoken.yaml
  components/image-controller/production/stone-prd-rh01/kustomization.yaml
  components/image-controller/production/stone-prd-rh01/resources/image_pruner/prune_images.py
  components/image-controller/production/stone-prd-rh01/resources/kustomization.yaml
  components/image-controller/production/stone-prd-rh01/resources/redhat-appstudio-pr-cronjob.yaml
  components/image-controller/production/stone-prd-rh01/resources/redhat-appstudio-pr-token.yaml
  components/image-controller/production/stone-prd-rh01/resources/redhat-appstudio-tekton-catalog-pr-cronjob.yaml
  components/image-controller/production/stone-prd-rh01/resources/redhat-appstudio-tekton-catalog-pr-token.yaml
  components/image-controller/staging/base/kustomization.yaml
  components/image-controller/staging/base/manager_resources_patch.yaml
Labels: lgtm, approved

#3516 Remove capacityThresholds from the ToolchainConfig on staging
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/toolchainconfig.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/toolchainconfig.yaml
Labels: lgtm, approved

#3533 update kubesaw READMEs with changes in ksctl
  components/sandbox/user-management/production/README.adoc
  components/sandbox/user-management/staging/README.adoc
Labels: lgtm, approved

#3409 PLNSRVCE-1514: enable results-from sidecar-logs for pipelines
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/update-tekton-config-features.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3538 Revert "PLNSRVCE-1514: enable results-from sidecar-logs for pipelines…
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/update-tekton-config-features.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3535 image-controller update
  components/image-controller/development/kustomization.yaml
  components/image-controller/staging/base/kustomization.yaml
Labels: lgtm, approved

#3542 release-service update
  components/monitoring/grafana/base/dashboards/release/kustomization.yaml
  components/release/development/kustomization.yaml
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#3517 Remove capacityThresholds from the ToolchainConfig on prod
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/toolchainconfig.yaml
  components/sandbox/toolchain-host-operator/production/stone-prod-p01/toolchainconfig.yaml
Labels: lgtm, approved

#3547 fix: increase release-service memory limit
  components/release/k-components/manager-resources-patch/manager_resources_patch.yaml
Labels: lgtm, approved

#3546 bump prod to staging level
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3541 chore(RHTAPWATCH-766): add spacerequest cleaner app
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/spacerequest-cleaner/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/spacerequest-cleaner/spacerequest-cleaner.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  components/spacerequest-cleaner/OWNERS
  components/spacerequest-cleaner/base/cronjob.yaml
  components/spacerequest-cleaner/base/kustomization.yaml
  components/spacerequest-cleaner/base/namespace.yaml
  components/spacerequest-cleaner/base/rbac.yaml
  components/spacerequest-cleaner/development/kustomization.yaml
  components/spacerequest-cleaner/production/kustomization.yaml
  components/spacerequest-cleaner/staging/kustomization.yaml
Labels: lgtm, approved

#3548 Adding retarget access for user eedri
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/retarget-user-eedri-host.yaml
  components/sandbox/user-management/production/kubesaw-admins.yaml
Labels: lgtm, approved

#3531 fix: setup pac integration after the tekton crds are ready
  hack/preview.sh
Labels: lgtm, approved

#3553 chore(RHTAPWATCH-891): Update o11y commit sha
  components/monitoring/grafana/development/kustomization.yaml
  components/monitoring/grafana/staging/kustomization.yaml
Labels: lgtm, approved

#3556 chore(RHTAPWATCH-891): Update o11y prod commit sha
  components/monitoring/grafana/production/kustomization.yaml
Labels: lgtm, approved

#3557 chore(RHTAPWATCH-891): Add check label to grafana
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#3560 KFLUXINFRA-470: Replace stonesoups01ue1 with appsres05ue1 in Secret Paths
  components/backup/staging/stone-stage-p01/backup-s3-credentials-patch.yaml
  components/backup/staging/stone-stg-host/backup-s3-credentials-patch.yaml
  components/backup/staging/stone-stg-m01/backup-s3-credentials-patch.yaml
  components/backup/staging/stone-stg-rh01/backup-s3-credentials-patch.yaml
  components/remote-secret-controller/overlays/staging/stone-stg-m01/aws-credentials-path-patch.yaml
  components/remote-secret-controller/overlays/staging/stone-stg-rh01/aws-credentials-path-patch.yaml
  components/spi/overlays/staging/stone-stg-m01/spi-aws-credentials-path-patch.yaml
  components/spi/overlays/staging/stone-stg-rh01/spi-aws-credentials-path-patch.yaml
Labels: lgtm, approved

#3437 Replace redhat-appstudio-sre/stage group by konflux groups
  components/authentication/base/all/everyone-can-view-patch.yaml
  components/authentication/base/all/everyone-can-view.yaml
  components/authentication/base/all/kustomization.yaml
  components/authentication/base/github/everyone-can-view-patch.yaml
  components/authentication/base/github/group-sync/external-secrets/github-redhat-appstudio-sre.yaml
  components/authentication/base/github/group-sync/external-secrets/kustomization.yaml
  components/authentication/base/github/group-sync/github-redhat-appstudio-sre.yaml
  components/authentication/base/github/group-sync/kustomization.yaml
  components/authentication/base/github/kustomization.yaml
  components/authentication/base/rh-idp/kustomization.yaml
  components/authentication/production/base/github-redhat-appstudio-sre-secret-patch.yaml
  components/authentication/production/base/kustomization.yaml
Labels: approved

#3569 Move stone-stg-m01 and stone-stg-rh01 authentication to rh-idp
  argo-cd-apps/base/all-clusters/infra-deployments/authentication/authentication.yaml
  components/authentication/staging/base/kustomization.yaml
  components/authentication/staging/stone-stg-host/kustomization.yaml
Labels: approved

#3571 KFLUXINFRA-471: Replacing stonesoupp01ue1 with appsrep05ue1 in Secret Paths
  components/backup/production/stone-prd-host1/backup-s3-credentials-patch.yaml
  components/backup/production/stone-prd-m01/backup-s3-credentials-patch.yaml
  components/backup/production/stone-prd-rh01/backup-s3-credentials-patch.yaml
  components/backup/production/stone-prod-p01/backup-s3-credentials-patch.yaml
  components/cluster-secret-store-rh/base/rh-artifacts-bucket-writer-secret-store.yml
  components/remote-secret-controller/overlays/production/stone-prd-m01/aws-credentials-path-patch.yaml
  components/remote-secret-controller/overlays/production/stone-prd-rh01/aws-credentials-path-patch.yaml
  components/spi/overlays/production/stone-prd-m01/spi-aws-credentials-path-patch.yaml
  components/spi/overlays/production/stone-prd-rh01/spi-aws-credentials-path-patch.yaml
Labels: approved

#3570 Move all public prod clusters authentication to rhsso
  components/authentication/base/admin-checker/admin-checker-sa.yaml
  components/authentication/base/admin-checker/cronjob.yaml
  components/authentication/base/admin-checker/external-secrets/kustomization.yaml
  components/authentication/base/admin-checker/external-secrets/rhtap-infra-secrets.yaml
  components/authentication/base/admin-checker/kustomization.yaml
  components/authentication/base/admin-checker/namespace.yaml
  components/authentication/base/component-maintainer.yaml
  components/authentication/base/everyone-can-view-patch.yaml
  components/authentication/base/everyone-can-view.yaml
  components/authentication/base/github/group-sync/external-secrets/github-redhat-appstudio.yaml
  components/authentication/base/github/group-sync/external-secrets/kustomization.yaml
  components/authentication/base/github/group-sync/github-redhat-appstudio.yaml
  components/authentication/base/github/group-sync/kustomization.yaml
  components/authentication/base/github/kustomization.yaml
  components/authentication/base/group-sync/external-secrets/konflux-ldap-sa.yaml
  components/authentication/base/group-sync/external-secrets/kustomization.yaml
  components/authentication/base/group-sync/external-secrets/mtls-ca-validators.yaml
  components/authentication/base/group-sync/group-sync.yaml
  components/authentication/base/group-sync/konflux-rover-groups.yaml
  components/authentication/base/group-sync/kustomization.yaml
  components/authentication/base/group-sync/namespaces.yaml
  components/authentication/base/group-sync/subscription.yaml
  components/authentication/base/konflux-admins.yaml
  components/authentication/base/kustomization.yaml
  components/authentication/base/rh-idp/group-sync/kustomization.yaml
  components/authentication/base/rh-idp/kustomization.yaml
  components/authentication/production/base/github-redhat-appstudio-secret-patch.yaml
  components/authentication/production/base/konflux-ldap-sa-patch.yaml
  components/authentication/production/base/kustomization.yaml
  components/authentication/production/base/mtls-ca-validators-patch.yaml
  components/authentication/production/base/rhtap-infra-secrets-patch.yaml
  components/authentication/production/k-components/rhtap-infra-secrets-patch/kustomization.yaml
  components/authentication/production/stone-prod-p01/kustomization.yaml
  components/authentication/staging/base/kustomization.yaml
  components/authentication/staging/stone-stage-p01/kustomization.yaml
Labels: approved

#3549 Adding ksctl access to the workspaces team
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/sandbox-sre-host/serviceaccounts/dperaza4dustbit.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/sandbox-sre-host/serviceaccounts/filariow.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/sandbox-sre-host/serviceaccounts/kustomization.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/sandbox-sre-host/serviceaccounts/sadlerap.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/approve-user-dperaza4dustbit-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/approve-user-filariow-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/approve-user-sadlerap-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/ban-user-dperaza4dustbit-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/ban-user-filariow-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/ban-user-sadlerap-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-view-dperaza4dustbit-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-view-filariow-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-view-sadlerap-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/deactivate-user-dperaza4dustbit-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/deactivate-user-filariow-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/deactivate-user-sadlerap-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/gdpr-delete-dperaza4dustbit-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/gdpr-delete-filariow-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/gdpr-delete-sadlerap-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/promote-user-dperaza4dustbit-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/promote-user-filariow-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/promote-user-sadlerap-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/restart-deployment-dperaza4dustbit-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/restart-deployment-filariow-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/restart-deployment-sadlerap-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/retarget-user-dperaza4dustbit-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/retarget-user-filariow-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/retarget-user-sadlerap-host.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/sandbox-sre-member/serviceaccounts/dperaza4dustbit.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/sandbox-sre-member/serviceaccounts/filariow.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/sandbox-sre-member/serviceaccounts/kustomization.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/sandbox-sre-member/serviceaccounts/sadlerap.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-view-dperaza4dustbit-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-view-filariow-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-view-sadlerap-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/restart-deployment-dperaza4dustbit-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/restart-deployment-filariow-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/restart-deployment-sadlerap-member.yaml
  components/sandbox/user-management/production/kubesaw-admins.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/sandbox-sre-host/serviceaccounts/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/sandbox-sre-host/serviceaccounts/sadlerap.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/approve-user-sadlerap-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/ban-user-sadlerap-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-view-sadlerap-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/deactivate-user-sadlerap-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/gdpr-delete-sadlerap-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/promote-user-sadlerap-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/restart-deployment-sadlerap-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/retarget-user-sadlerap-host.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/sandbox-sre-member/serviceaccounts/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/sandbox-sre-member/serviceaccounts/sadlerap.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-view-sadlerap-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/restart-deployment-sadlerap-member.yaml
  components/sandbox/user-management/staging/kubesaw-admins.yaml
Labels: approved

#3576 Delete toolchain host and member application from dev overlay
  argo-cd-apps/overlays/development/delete-applications.yaml
  components/sandbox/toolchain-host-operator/development/kustomization.yaml
  components/sandbox/toolchain-member-operator/development/kustomization.yaml
Labels: lgtm, approved

#3370 chore: re-add quality dashboard
  argo-cd-apps/base/quality-dashboard/kustomization.yaml
  argo-cd-apps/base/quality-dashboard/quality-dashboard.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
  components/quality-dashboard/OWNERS
  components/quality-dashboard/base/backend/kustomization.yaml
  components/quality-dashboard/base/dex/kustomization.yaml
  components/quality-dashboard/base/frontend/kustomization.yaml
  components/quality-dashboard/base/kustomization.yaml
  components/quality-dashboard/base/rbac/kustomization.yaml
  components/quality-dashboard/base/rbac/quality-dashboard.yaml
  components/quality-dashboard/development/kustomization.yaml
  components/quality-dashboard/staging/external-secrets/kustomization.yaml
  components/quality-dashboard/staging/external-secrets/quality-dashboard-secrets.yaml
  components/quality-dashboard/staging/kustomization.yaml
  docs/_data/navigation.yml
  docs/misc/quality-dashboard.md
  hack/bootstrap-host-cluster.sh
  hack/destroy-cluster.sh
  hack/preview-template.env
  hack/secret-creator/quality-dashboard/.gitignore
  hack/secret-creator/quality-dashboard/create-quality-dashboard-secrets.sh
  hack/secret-creator/quality-dashboard/dex-config-template.yaml
Labels: lgtm, approved

#3575 fix: CONSOLE_URL_TASKLOG for prod integration-service
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#3574 stage: bump tekton-pipeline-webhook to 6 minimum replicas to avoid intermittent context deadline exceeded performance issues
  components/pipeline-service/staging/base/update-tekton-config-performance.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3559 chore: deploy obo on internal staging cluster
  components/monitoring/prometheus/base/observability-operator/kustomization.yaml
  components/monitoring/prometheus/base/observability-operator/observability-operator.yaml
  components/monitoring/prometheus/development/monitoringstack/kustomization.yaml
  components/monitoring/prometheus/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#3550 chore(RHTAPWATCH-766): spacerequest cleaner to production
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  components/spacerequest-cleaner/production/kustomization.yaml
Labels: lgtm, approved

#3582 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#3578 prod: bump tekton-pipeline-webhook to 6 minimum replicas to avoid intermittent context deadline exceeded performance issues
  components/pipeline-service/production/base/update-tekton-config-performance.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3580 try enabling chains deep inspection via infra change only given tekto…
  components/pipeline-service/development/chains-deployment-perf-bump.yaml
  components/pipeline-service/development/chains-tekton-config-patches.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/chains-deployment-perf-bump.yaml
  components/pipeline-service/staging/base/chains-tekton-config-patches.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3583 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#3584 Allow qe admins to get secrets in quality-dashboard namespace
  components/quality-dashboard/base/rbac/quality-dashboard.yaml
Labels: lgtm, approved

#3588 feat(STONEINTG-872): update ref for integration service health dashboard
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#3497 Clarify use of secrets in tekton-ci/konflux-ci
  components/konflux-ci/base/external-secrets/kustomization.yaml
  components/konflux-ci/base/external-secrets/quay-push-secret.yaml
  components/konflux-ci/base/serviceaccount.yaml
  components/konflux-ci/production/kustomization.yaml
  components/konflux-ci/production/quay-push-secret.yaml
  components/tekton-ci/base/external-secrets/kustomization.yaml
  components/tekton-ci/base/external-secrets/quay-push-secret-konflux-ci.yaml
  components/tekton-ci/production/kustomization.yaml
  components/tekton-ci/production/quay-push-secret-konflux-ci.yaml
Labels: lgtm, approved

#3590 Fix deployment of kubesaw-common application
  argo-cd-apps/base/all-clusters/infra-deployments/kubesaw-common/kubesaw-common.yaml
  components/sandbox/common/kustomization.yaml
  components/sandbox/common/namespace.yaml
  components/sandbox/common/olm-restart/kustomization.yaml
Labels: lgtm, approved

#3586 PLNSRVCE-1692: bump prod pipeline service level to stage level
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3595 Renaming kubesaw-common namespace to bypass validation rules
  argo-cd-apps/base/all-clusters/infra-deployments/kubesaw-common/kubesaw-common.yaml
  components/sandbox/common/kustomization.yaml
  components/sandbox/common/namespace.yaml
  components/sandbox/common/olm-restart/kustomization.yaml
Labels: lgtm, approved

#3565 fix: adding line break to enable proper release removal
  components/release/base/cronjobs/remove-expired-releases.yaml
Labels: lgtm, approved

#3598 Remove unsupported defaultTier from ToolchainConfig
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/toolchainconfig.yaml
Labels: lgtm, approved

#3599 chore(KFLUXBUGS-1200): update UI images
  components/ui/production/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: lgtm, approved

#3602 chore(KFLUXBUGS-1200): update UI images for production
  components/ui/production/kustomization.yaml
Labels: lgtm, approved

#3603 fix(KFLUXBUGS-1200): update console url for integration service
  components/integration/production/stone-prod-p01/console-url-config-patch.json
Labels: lgtm, approved

#3601 chore: add ci-helper-app Repository CR
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#3610 fix(KFLUXBUGS-1200): update console url for PaC config
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/resources/update-tekton-config-pac.yaml
Labels: lgtm, approved

#3608 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#3624 Image controller update to dev & stg
  components/image-controller/development/kustomization.yaml
  components/image-controller/staging/base/kustomization.yaml
Labels: lgtm, approved

#3632 Bump prod images for UI
  components/ui/production/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#3623 Build service update
  components/build-service/development/kustomization.yaml
  components/build-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#3636 Promote SPI/RemoteSecret from staging to prod
  components/remote-secret-controller/overlays/production/base/kustomization.yaml
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#3631 chore: move ci-helper-app Repo CR to konflux-ci
  components/konflux-ci/base/repository.yaml
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved
