Repository redhat-appstudio/infra-deployments, pull requests merged in 2024-02, with the labels that each got.

#3193 Deduplicate ip addresses for pooled ppc64le
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#3187 Prune the deleted Rover groups
  components/authentication/base/rh-idp/group-sync/konflux-rover-groups.yaml
Labels: lgtm, approved

#3186 Deploy authentication component to stone-prod-p01
  argo-cd-apps/base/all-clusters/infra-deployments/authentication/authentication.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  components/authentication/production/base/kustomization.yaml
  components/authentication/production/k-components/rhtap-infra-secrets-patch/kustomization.yaml
  components/authentication/production/k-components/rhtap-infra-secrets-patch/rhtap-infra-secrets-patch.yaml
  components/authentication/production/stone-prod-p01/kustomization.yaml
Labels: lgtm, approved

#3194 Promote integration-service from staging to production
  components/integration/production/kustomization.yaml
Labels: lgtm, approved

#3188 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#3198 move toolchainconfig from sandbox-sre
  components/sandbox/toolchain-host-operator/staging/toolchainconfig.yaml
Labels: lgtm, approved

#3168 RHTAPWATCH-666: Deploy smee server for prod
  components/smee/base/deployment.yaml
  components/smee/base/kustomization.yaml
  components/smee/base/route.yaml
  components/smee/base/service.yaml
  components/smee/production/ip-allow-list.yaml
  components/smee/production/kustomization.yaml
  components/smee/staging/ip-allow-list.yaml
  components/smee/staging/kustomization.yaml
  components/smee/staging/route.yaml
Labels: approved

#3205 Bump pipeline-service prod to version in staging
  components/pipeline-service/production/base/kustomization.yaml
Labels: lgtm, approved

#3202 fix(sandbox stage): add missing kustomization entry for toolchainconfig
  components/sandbox/toolchain-host-operator/staging/kustomization.yaml
Labels: lgtm, approved

#3212 Promote integration-service from staging to production
  components/integration/production/kustomization.yaml
Labels: lgtm, approved

#3207 Promote SPI/RemoteSecret from staging to prod
  components/remote-secret-controller/overlays/production/base/kustomization.yaml
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#3214 Use GH group for RBACs in segment-bridge component
  components/segment-bridge/base/serviceaccount.yaml
Labels: lgtm, approved

#3210 sandbox(stage): add stage space provisioner configs
  components/sandbox/toolchain-host-operator/staging/kustomization.yaml
  components/sandbox/toolchain-host-operator/staging/space-provisioner-configs.yaml
Labels: lgtm, approved

#3221 RHTAPSRE-379: Add toolchain host config for internal staging
  argo-cd-apps/base/host/toolchain-host-operator/toolchain-host-operator.yaml
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/kustomization.yaml
  components/sandbox/toolchain-host-operator/production/stone-prod-p01/kustomization.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/kustomization.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/toolchainconfig.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/kustomization.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/space-provisioner-configs.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/toolchainconfig.yaml
Labels: lgtm, approved

#3215 Replace `Performance` group by `konflux-performance`
  components/authentication/base/rh-idp/everyone-can-view-patch.yaml
  components/perf-team-prometheus-reader/base/perf-team.yaml
Labels: lgtm, approved

#3222 Fix cluster name for internal staging Prometheus
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml
Labels: lgtm, approved

#3216 Use new konflux-gitops[-admins] groups
  components/gitops/base/authentication/gitops-clusterrolebindings.yaml
  components/gitops/production/base/authentication/gitops-rolebindings.yaml
  components/gitops/production/stone-prd-m01/gitops-team-member-namespaces.yaml
  components/gitops/staging/base/authentication/gitops-rolebindings.yaml
  components/gitops/staging/stone-stg-m01/gitops-team-member-namespaces.yaml
Labels: lgtm, approved

#3217 Use GH group for RBACs in has component
  components/has/base/rbac/has-admin.yaml
  components/has/base/rbac/has.yaml
  components/has/staging/rbac/has-exec.yaml
Labels: lgtm, approved

#3225 Remove unsupported defaultTier from ToolchainConfig
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/toolchainconfig.yaml
Labels: lgtm, approved

#3226 Use GH group for RBACs in sandbox component
  components/sandbox/base/rbac/sandbox-sre-admins.yaml
  components/sandbox/toolchain-host-operator/base/rbac/sandbox-sre-admins.yaml
  components/sandbox/toolchain-member-operator/base/rbac/register-cluster-extra-member-permissions.yaml
  components/sandbox/toolchain-member-operator/base/rbac/sandbox-sre-admins.yaml
Labels: lgtm, approved

#3018 add rhtap core owners for sandbox component
  components/sandbox/OWNERS
Labels: lgtm, approved

#3232 update respone time formula proxy metrics
  components/monitoring/grafana/base/dashboards/core/sandbox-proxy-metrics.json
Labels: lgtm, approved

#3234 complete bump pipeline-service prod to version in staging
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3235 Bump UI in the internal cluster
  components/ui/staging/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#3236 fix: move the production update pipelines to run under tekton-ci ns in prod
  .tekton/build-service-prod-overlay-update.yaml
  .tekton/image-controller-prod-overlay-update.yaml
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#3229 add space provisioner config for new cluster
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/kustomization.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/space-provisioner-configs.yaml
Labels: lgtm, approved

#3242 pipeline-service update (manual)
  components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3244 PLNSRVCE-1526: bump tekton operator proxy webhook to 2 replicas
  components/pipeline-service/development/update-tekton-config-performance.yaml
  components/pipeline-service/staging/base/update-tekton-config-performance.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3245 Add scaffolding to migrate the chains secret to Vault
  components/pipeline-service/staging/base/chains-signing-secrets.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/tekton-chains-signing-secret-path.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/resources/kustomization.yaml
  components/pipeline-service/staging/stone-stg-m01/resources/tekton-chains-signing-secret-path.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/kustomization.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/tekton-chains-signing-secret-path.yaml
Labels: lgtm, approved

#3247 PLNSRVCE-1526: bump prod to staging level, including the operator proxy webhook replica bump
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/base/update-tekton-config-performance.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3249 Fix pipeline-service signing-secrets-vault configuration
  components/pipeline-service/staging/base/chains-signing-secrets.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3250 PLNSRVCE-1526: bump eligible tekton controllers and webhooks in openshift-pipelines to 2 replicas
  components/pipeline-service/development/update-tekton-config-performance.yaml
  components/pipeline-service/staging/base/update-tekton-config-performance.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3253 PLNSRVCE-1526: pipeline-service update (manual)
  components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/development/update-tekton-config-performance.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/update-tekton-config-performance.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3258 PLNSRVCE-1526: bump prod to staging level, including the remote-resolver,pac replica bumps
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/base/update-tekton-config-performance.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3237 konflux(prod): move configuration from sandbox-sre
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/kustomization.yaml
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/space-provisioner-configs.yaml
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/toolchainconfig.yaml
  components/sandbox/toolchain-host-operator/production/stone-prod-p01/kustomization.yaml
  components/sandbox/toolchain-host-operator/production/stone-prod-p01/space-provisioner-configs.yaml
  components/sandbox/toolchain-host-operator/production/stone-prod-p01/toolchainconfig.yaml
Labels: lgtm, approved

#3239 Disabling staging promotion pipeline run and repository
  .tekton/hack/check-pr-label.py
  .tekton/hack/get-component-name.py
  .tekton/hack/get-git-token.py
  .tekton/hack/merge-pr.py
  .tekton/hack/remove-pr-label.py
  .tekton/hack/update-argocd-app-revision.sh
  .tekton/pipeline/rhtap-staging-e2e.yaml
  .tekton/rhtap-staging-e2e-ci.yaml.disabled
  .tekton/tasks/check-pr-label.yaml
  .tekton/tasks/check-pr-rebase-label.yaml
  .tekton/tasks/component-app-name.yaml
  .tekton/tasks/get-git-token.yaml
  .tekton/tasks/get-pr-modified-files.yaml
  .tekton/tasks/merge-pr.yaml
  .tekton/tasks/rebase-pr.yaml
  .tekton/tasks/remove-pr-label.yaml
  .tekton/tasks/replace-revision.yaml
  .tekton/tasks/revert-replace-revision.yaml
  .tekton/tasks/verify-smoke-e2e.yaml
  argo-cd-apps/base/promotion/kustomization.yaml
  argo-cd-apps/base/promotion/promotion.yaml
  argo-cd-apps/overlays/staging/kustomization.yaml
  components/promotion/base/appstudio-gitops-service-argocd-argocd-application-controller-clusterrolebinding.yaml
  components/promotion/base/appstudio-pipelines-runner-rolebinding.yaml
  components/promotion/base/external-secrets/infra-deployments-pr-creator.yaml
  components/promotion/base/external-secrets/kustomization.yaml
  components/promotion/base/external-secrets/stage-test-e2e.yaml
  components/promotion/base/kustomization.yaml
  components/promotion/base/namespace.yaml
  components/promotion/base/promotion-maintainers-rb.yaml
  components/promotion/base/repository.yaml
  components/promotion/base/serviceaccount.yaml
  components/promotion/staging/stone-stg-rh01/infra-deployments-pr-creator.yaml
  components/promotion/staging/stone-stg-rh01/kustomization.yaml
  components/promotion/staging/stone-stg-rh01/stage-test-e2e.yaml
Labels: lgtm, approved

#3224 PLNSRVCE-1598: update sprayproxy repository with konflux-ci org
  components/sprayproxy/staging/kustomization.yaml
  components/tekton-ci/base/repository.yaml
Labels: lgtm, ok-to-test, approved

#3266 Grant grafana component maintainer to o11y team
  components/authentication/base/all/component-maintainer.yaml
  components/monitoring/grafana/base/kustomization.yaml
  components/monitoring/grafana/base/rbac/grafana-maintainers.yaml
  components/monitoring/grafana/base/rbac/kustomization.yaml
Labels: lgtm, approved

#3252 PLNSRVCE-1526: bump results watcher to 2 replicas in dev/staging
  components/pipeline-service/development/bump-results-watcher-replicas.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/bump-results-watcher-replicas.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3260 Rename plnscv ExternalSecret target
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/tekton-chains-signing-secret-name.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3276 Rename plnscv ExternalSecret target in prd
  components/pipeline-service/base/external-secrets/openshift-pipelines/chains-signing-secrets.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/tekton-chains-signing-secret-name.yaml
Labels: lgtm, approved

#3279 Revert "Promote integration-service from staging to production"
  components/integration/production/kustomization.yaml
Labels: lgtm, approved

#3286 Fix proxyplugin route
  components/sandbox/toolchain-host-operator/base/proxy/proxyplugin.yaml
Labels: lgtm, approved

#3285 fix(hack): integration service has multiple config refs
  hack/preview.sh
Labels: lgtm, approved

#3288 Set pipeline signing-secrets to orphan
  components/pipeline-service/base/external-secrets/openshift-pipelines/chains-signing-secrets.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3292 Promote integration-service from staging to production
  components/integration/production/kustomization.yaml
Labels: lgtm, approved

#3267 Link GitHub Check Results to RHTAP UI for pipelinerun details and pip…
  components/pipeline-service/staging/base/update-tekton-config-pac.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3294 Add utility to generate deploy.yaml
  hack/generate-deploy-config.sh
Labels: lgtm, approved

#3295 chore: add env var to snapshotgc cronjob
  components/integration/development/kustomization.yaml
  components/integration/development/snapshotgc_inputs_patch.yaml
Labels: lgtm, approved

#3301 pipeline-service update (manual)
  components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3306 Promote integration-service from staging to production
  components/integration/production/kustomization.yaml
Labels: lgtm, approved

#3305 removing amfred from approvers list
  OWNERS
Labels: lgtm, approved

#3274 promote update of spraproxy repo form staging to production
  components/sprayproxy/production/kustomization.yaml
Labels: lgtm, approved

#3316 Add lcarva to root OWNERS
  OWNERS
Labels: lgtm, approved

#3323 bump pipeline-service in prod to staging level
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3325 Update pipeline-service, manual, stone-stg-rh01 only
  components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3326 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#3327 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#3318 PLNSRVCE-1650: bump stagging sprayproxy to 2 replicas
  components/sprayproxy/staging/bump-replicas.yaml
  components/sprayproxy/staging/kustomization.yaml
Labels: lgtm, approved

#3329 Promote SPI/RemoteSecret from staging to prod
  components/remote-secret-controller/overlays/production/base/kustomization.yaml
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#3330 Promote integration-service from staging to production
  components/integration/production/kustomization.yaml
Labels: lgtm, approved

#3334 RHTAPSRE-401: Add custom CA bundle to internal clusters
  argo-cd-apps/base/ca-bundle/ca-bundle.yaml
  argo-cd-apps/base/ca-bundle/kustomization.yaml
  argo-cd-apps/base/local-cluster-secret/all-in-one/kustomization.yaml
  argo-cd-apps/k-components/assign-internal-cluster-role-to-local-cluster/kustomization.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/staging-downstream/kustomization.yaml
Labels: lgtm, approved

#3336 bump pipeline metrics exporter mem in prod
  components/pipeline-service/production/base/bump-exporter-mem.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3338 RHTAPSRE-403: Deploy ca-bundle app to production
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
Labels: lgtm, approved

#3340 increase Tekton Results pruner gracePeriod for Dev env
  components/pipeline-service/development/increase-results-pruner-gracePeriod.yaml
  components/pipeline-service/development/kustomization.yaml
Labels: lgtm, approved

#3333 pipeline-service update manual
  components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3344 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#3348 enterprise contract update
  components/enterprise-contract/ecp.yaml
  components/enterprise-contract/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#3346 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#3350 pipeline-service update manual
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
Labels: lgtm, approved

#3328 RHTAPSRE-400: Remove Backup Application from Delete Group List
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
Labels: lgtm, approved

#3353 konflux(prod) : remove inspect pods
  components/sandbox/toolchain-member-operator/base/rbac/inspect-pods.yaml
  components/sandbox/toolchain-member-operator/base/rbac/kustomization.yaml
Labels: lgtm, approved

#3317 feat(STONEINTG-811): Add CA certs for internal deployments
  argo-cd-apps/base/member/infra-deployments/integration/integration.yaml
  components/integration/development/kustomization.yaml
  components/integration/production/base/kustomization.yaml
  components/integration/production/base/manager_resources_patch.yaml
  components/integration/production/base/pipelines-as-code-secret.yaml
  components/integration/production/stone-prod-p01/kustomization.yaml
  components/integration/rh-certs/add-rh-certs-patch.yaml
  components/integration/rh-certs/kustomization.yaml
  components/integration/staging/base/kustomization.yaml
  components/integration/staging/base/manager_resources_patch.yaml
  components/integration/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#3354 konflux(prod): rename grafana core component to kubesaw
  components/monitoring/grafana/base/dashboards/kubesaw/dashboard.yaml
  components/monitoring/grafana/base/dashboards/kubesaw/kubesaw-proxy-metrics.json
  components/monitoring/grafana/base/dashboards/kubesaw/kustomization.yaml
  components/monitoring/grafana/base/dashboards/kustomization.yaml
Labels: lgtm, approved

#3360 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#3341 make request watcher mem req/limit equal to better ensure we get the amount of mem desired
  components/pipeline-service/production/base/bump-results-watcher-mem.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3356 feat(RHTAPREL-815): add ReleaseServiceConfig RBAC
  components/release/base/kustomization.yaml
  components/release/base/release-service-config-rbac.yaml
Labels: lgtm, approved

#3361 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved
