Repository redhat-appstudio/infra-deployments, pull requests merged in 2024-03, with the labels that each got.

#3367 konflux(prod internal): registration service fix keycloak url
  components/sandbox/toolchain-host-operator/production/stone-prod-p01/toolchainconfig.yaml
Labels: lgtm, approved

#3371 Update sprayproxy prod to 2 replicas
  components/sprayproxy/production/bump-replicas.yaml
  components/sprayproxy/production/kustomization.yaml
Labels: lgtm, approved

#3377 release service update
  components/monitoring/grafana/base/dashboards/release/kustomization.yaml
  components/release/development/kustomization.yaml
Labels: lgtm, approved

#3379 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#3375 chore(RHTAPWATCH-838): promote snapshot gc to prod
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#3382 mmulholla offboarding
  components/remote-secret-controller/OWNERS
  components/spi/OWNERS
Labels: lgtm, approved

#3378 KFLUXBUGS-863: bump stg results watcher controller tuning
  components/pipeline-service/staging/base/bump-results-watcher-mem.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/update-results-watcher-performance.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3388 Update integration-service version
  components/integration/development/kustomization.yaml
  components/integration/staging/base/kustomization.yaml
Labels: lgtm, approved

#3394 Reduce from 8 to 4 threads to run kustomize build
  .github/workflows/kube-linter.yaml
Labels: lgtm, approved

#3395 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#3386 Backup all resources in workspaces host namespace
  components/backup/base/host/schedules/backup-toolchain-host-schedule.yaml
Labels: lgtm, approved

#3384 fix(stoneinteg-761): update the kustomization to latest integration-service
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#3398 Revert "integration-service update"
  components/integration/development/kustomization.yaml
  components/integration/staging/base/kustomization.yaml
Labels: lgtm, approved

#3399 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#3387 RHTAPSRE-404: Update build-service to use auto generated ca bundle
  components/build-service/components/rh-certs/2015-RH-IT-Root-CA.pem
  components/build-service/components/rh-certs/2022-IT-Root-CA.pem
  components/build-service/components/rh-certs/add-rh-certs-patch.yaml
  components/build-service/components/rh-certs/kustomization.yaml
Labels: lgtm, approved

#3400 remove duplicate results watcher threadiness in stage
  components/pipeline-service/staging/base/update-results-watcher-performance.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3391 KONFLUX-2040: Add robot push token for quay.io/konflux-ci
  components/tekton-ci/base/external-secrets/kustomization.yaml
  components/tekton-ci/base/external-secrets/quay-push-secret-konflux-ci.yaml
  components/tekton-ci/base/serviceaccount.yaml
  components/tekton-ci/production/kustomization.yaml
  components/tekton-ci/production/quay-push-secret-konflux-ci.yaml
Labels: lgtm, approved

#3401 KFLUXBUGS-863: bump results to stage level to address memory leak, help performance; keep at OSP 1.13 for now
  components/pipeline-service/production/base/bump-results-watcher-mem.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/base/stay-at-1-13-until-nightly-revert-sorted.yaml
  components/pipeline-service/production/base/update-results-watcher-performance.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3403 tekton-ci: unlink quay-push-konflux-ci secret
  components/tekton-ci/base/serviceaccount.yaml
Labels: lgtm, approved

#3406 KFLUXBUGS-863: Revert "bump prod to stage, minus nightlies for the time being"
  components/pipeline-service/production/base/bump-results-watcher-mem.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/base/stay-at-1-13-until-nightly-revert-sorted.yaml
  components/pipeline-service/production/base/update-results-watcher-performance.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3408 PLNSRVCE-1484: Link GitHub Check Results to RHTAP UI for pipelinerun …
  components/pipeline-service/production/base/update-tekton-config-pac.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/resources/update-tekton-config-pac.yaml
Labels: lgtm, approved

#3413 add pod/exec permissions in tekton-results namespace to pipeline-service-sre related rbac
  components/pipeline-service/base/rbac/tekton-results/pipeline-service-sre.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3411 Bump UI in the internal cluster
  components/ui/staging/kustomization.yaml
Labels: lgtm, approved

#3420 add david to konflux cli
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/sandbox-sre-host/serviceaccounts/dperaza4dustbit.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/sandbox-sre-host/serviceaccounts/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/approve-user-dperaza4dustbit-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/ban-user-dperaza4dustbit-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-edit-dperaza4dustbit-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-view-dperaza4dustbit-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/deactivate-user-dperaza4dustbit-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/gdpr-delete-dperaza4dustbit-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/install-operator-dperaza4dustbit-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/promote-user-dperaza4dustbit-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/restart-deployment-dperaza4dustbit-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/retarget-user-dperaza4dustbit-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/view-secrets-dperaza4dustbit-host.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/sandbox-sre-member/serviceaccounts/dperaza4dustbit.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/sandbox-sre-member/serviceaccounts/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-edit-dperaza4dustbit-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-view-dperaza4dustbit-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/install-operator-dperaza4dustbit-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/restart-deployment-dperaza4dustbit-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/view-secrets-dperaza4dustbit-member.yaml
  components/sandbox/user-management/staging/sandbox-config.yaml
Labels: lgtm, approved

#3423 drop obsolete permissions needed to install/configure operator (managed by ArgoCD)
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-edit-alkazako-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-edit-fmuntean-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-edit-mjobanek-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/install-operator-alkazako-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/install-operator-mjobanek-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/retarget-user-fmuntean-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/view-secrets-alkazako-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/view-secrets-fmuntean-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/view-secrets-mjobanek-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/roles/install-operator-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/roles/kustomization.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-edit-alkazako-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-edit-fmuntean-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-edit-mjobanek-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/install-operator-alkazako-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/install-operator-mjobanek-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/view-secrets-alkazako-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/view-secrets-fmuntean-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/view-secrets-mjobanek-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/roles/install-operator-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/roles/kustomization.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/roles/view-secrets-member.yaml
  components/sandbox/user-management/production/sandbox-config.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-edit-alkazako-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-edit-dperaza4dustbit-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-edit-fmuntean-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-edit-mjobanek-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/install-operator-alkazako-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/install-operator-dperaza4dustbit-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/install-operator-mjobanek-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/view-secrets-alkazako-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/view-secrets-dperaza4dustbit-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/view-secrets-fmuntean-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/view-secrets-mjobanek-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/roles/install-operator-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/roles/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/roles/view-secrets-host.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-edit-alkazako-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-edit-dperaza4dustbit-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-edit-fmuntean-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-edit-mjobanek-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/install-operator-alkazako-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/install-operator-dperaza4dustbit-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/install-operator-mjobanek-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/view-secrets-alkazako-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/view-secrets-dperaza4dustbit-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/view-secrets-fmuntean-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/view-secrets-mjobanek-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/roles/install-operator-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/roles/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/roles/view-secrets-member.yaml
  components/sandbox/user-management/staging/sandbox-config.yaml
Labels: lgtm, approved

#3415 KFLUXBUGS-1150: reduce watcher cpu/mem reqs for smaller e2e clusters; finish enabling widening of prune interval for e2e
  components/pipeline-service/development/increase-results-pruner-gracePeriod.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/development/reduce-watcher-cpu-mem-reqs.yaml
Labels: lgtm, approved

#3424 enable francesco to use sandbox-cli
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/sandbox-sre-host/serviceaccounts/filariow.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/sandbox-sre-host/serviceaccounts/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/approve-user-filariow-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/ban-user-filariow-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-view-filariow-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/deactivate-user-filariow-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/gdpr-delete-filariow-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/promote-user-filariow-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/restart-deployment-filariow-host.yaml
  components/sandbox/user-management/staging/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/retarget-user-filariow-host.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/sandbox-sre-member/serviceaccounts/filariow.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/sandbox-sre-member/serviceaccounts/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-view-filariow-member.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/staging/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/restart-deployment-filariow-member.yaml
  components/sandbox/user-management/staging/sandbox-config.yaml
Labels: lgtm, approved

#3422 RHTAPSRE-429: Disabling Sync Policy for Staging Public ArgoCD
  argo-cd-apps/overlays/staging/kustomization.yaml
  argo-cd-apps/overlays/staging/migration.patch.yaml
Labels: lgtm, approved

#3414 Grant konflux-admins to konflux-sre team
  components/authentication/base/all/konflux-admins.yaml
Labels: lgtm, approved

#3428 Link registry.redhat.io pullsecret to SA under tekton-ci
  components/tekton-ci/base/external-secrets/kustomization.yaml
  components/tekton-ci/base/external-secrets/registry-redhat-io-pull-secret.yaml
  components/tekton-ci/base/serviceaccount.yaml
Labels: lgtm, approved

#3421 Update setup-nfs-quickcluster.sh to work with RHEL-8
  hack/quickcluster/setup-nfs-quickcluster.sh
Labels: lgtm, ok-to-test, approved

#3358 feat(STONE-812): IS mapping to console URL
  components/integration/development/kustomization.yaml
  components/integration/development/manager_resources_patch.yaml
  components/integration/production/base/kustomization.yaml
  components/integration/production/base/manager_resources_patch.yaml
  components/integration/staging/base/kustomization.yaml
  components/integration/staging/base/manager_resources_patch.yaml
Labels: lgtm, approved

#3434 Link registry.redhat.io credential in SA secrets
  components/tekton-ci/base/serviceaccount.yaml
Labels: lgtm, approved

#3433 fix: reduce resource requests/limits for gitops
  components/gitops/development/core_service_resources_patch.yaml
  components/gitops/development/gitops-service-argocd.yaml
  components/gitops/development/kustomization.yaml
  components/gitops/development/service_agent_resources_patch.yaml
Labels: lgtm, approved

#3426 fix(stoneinteg-818): Add external secrets of GH app for stage/prod
  components/integration/production/stone-prod-p01/kustomization.yaml
  components/integration/production/stone-prod-p01/pipelines-as-code-secret-path.yaml
  components/integration/staging/stone-stage-p01/kustomization.yaml
  components/integration/staging/stone-stage-p01/pipelines-as-code-secret-path.yaml
Labels: lgtm, approved

#3435 add quay-push-secret-konflux-ci to ci serviceaccount
  components/tekton-ci/base/serviceaccount.yaml
Labels: lgtm, approved

#3438 chore: re-add quality-dashboard Repository CR
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#3351 PLNSRVCE-1674: Migrate SprayProxy images to quay.io/konflux-ci on stagging
  components/sprayproxy/staging/kustomization.yaml
Labels: lgtm, approved

#3429 fix: release-expiration cronjob incorrect directory
  components/release/base/cronjobs/remove-expired-releases.yaml
Labels: lgtm, approved

#3441 KFLUXBUGS-863: bump results to stage level to address memory leak, help performance; keep at OSP 1.13 for now; add timeout, goroutine dump in dynamic reconciler
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/base/stay-at-1-13-handle-bump-to-nightly-separately.yaml
  components/pipeline-service/production/base/update-results-watcher-performance.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3444 Revert "bump results to stage level to address memory leak, help performance; keep at OSP 1.13 for now; add timeout, goroutine dump in dynamic reconciler (#3441)"
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/base/stay-at-1-13-handle-bump-to-nightly-separately.yaml
  components/pipeline-service/production/base/update-results-watcher-performance.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3440 fix: update integration owners
  components/build-service/base/build-pipeline-selectors/OWNERS
  components/integration/OWNERS
Labels: lgtm, approved

#3450 RHTAPSRE-429: enable auto sync for Konflux Public Staging ArgoCD
  argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-staging/migration.patch.yaml
Labels: lgtm, approved

#3449 PLNSRVCE-1674: Migrate SprayProxy images to quay.io/konflux-ci on pro…
  components/sprayproxy/production/kustomization.yaml
Labels: lgtm, approved

#3451 Revert "enterprise contract update"
  components/enterprise-contract/kustomization.yaml
Labels: lgtm, approved

#3454 rename sandbox-cli to ksctl
  components/sandbox/user-management/production/README.adoc
  components/sandbox/user-management/production/kubesaw-admins.yaml
  components/sandbox/user-management/staging/README.adoc
  components/sandbox/user-management/staging/kubesaw-admins.yaml
Labels: lgtm, approved

#3447 Promote SPI/RemoteSecret from staging to prod
  components/remote-secret-controller/overlays/production/base/kustomization.yaml
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#3460 chore(RHTAPWATCH-886): add konflux metrics to service monitor
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#3463 RHTAPSRE-431: enable auto sync for production argocd instance
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-production/migration.patch.yaml
Labels: lgtm, approved

#3465 Increase memory of production build controller
  components/build-service/production/base/increase-build-controller-memory.yaml
  components/build-service/production/base/kustomization.yaml
Labels: approved

#3462 fix(stoneinteg-761): update integration grafana dashboards
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#3469 Revert "add quay-push-secret-konflux-ci to ci serviceaccount"
  components/tekton-ci/base/serviceaccount.yaml
Labels: lgtm, approved

#3472 Configure ArgoCD to not prune signing-secrets secret
  components/pipeline-service/base/external-secrets/openshift-pipelines/chains-signing-secrets.yaml
Labels: lgtm, approved

#3473 Regenerate pipeline service deployments
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3471 adjust exporter mem to account for increased prod load
  components/pipeline-service/production/base/bump-exporter-mem.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3476 Remove former argo-cd-apps/overlays/production folder
  argo-cd-apps/overlays/production/kustomization.yaml
  argo-cd-apps/overlays/production/migration.patch.yaml
  argo-cd-apps/overlays/production/production-overlay-patch.yaml
Labels: lgtm, approved

#3477 Adding Hugo access to manage konflux user
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/sandbox-sre-host/serviceaccounts/hugares.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/sandbox-sre-host/serviceaccounts/kustomization.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/approve-user-hugares-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-view-hugares-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/deactivate-user-hugares-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/gdpr-delete-hugares-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/promote-user-hugares-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/retarget-user-hugares-host.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/sandbox-sre-member/serviceaccounts/hugares.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/sandbox-sre-member/serviceaccounts/kustomization.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-view-hugares-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/production/kubesaw-admins.yaml
Labels: lgtm, approved

#3475 Remove former argo-cd-apps/overlays/staging folder
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  argo-cd-apps/overlays/staging-downstream/kustomization.yaml
  argo-cd-apps/overlays/staging/kustomization.yaml
  argo-cd-apps/overlays/staging/migration.patch.yaml
Labels: lgtm, approved

#3480 Promote image-controller component from stage to prod
  components/image-controller/production/kustomization.yaml
Labels: lgtm, approved

#3483 Promote Build Service from Staging to Production
  components/build-service/production/base/kustomization.yaml
Labels: lgtm, approved

#3485 go back to 1 watcher replica, asses impact on prod-rh01 results RDS hang
  components/pipeline-service/production/base/bump-results-watcher-replicas.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3484 Allowing Eyal to approve user
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/sandbox-sre-host/serviceaccounts/eedri.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/sandbox-sre-host/serviceaccounts/kustomization.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/approve-user-eedri-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/clusterrole-view-eedri-host.yaml
  components/sandbox/user-management/production/generated-manifests/host/namespace-scoped/toolchain-host-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/sandbox-sre-member/serviceaccounts/eedri.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/sandbox-sre-member/serviceaccounts/kustomization.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/clusterrole-view-eedri-member.yaml
  components/sandbox/user-management/production/generated-manifests/member/namespace-scoped/toolchain-member-operator/rolebindings/kustomization.yaml
  components/sandbox/user-management/production/kubesaw-admins.yaml
Labels: lgtm, approved

#3488 bump tekton results api pod resources
  components/pipeline-service/production/base/bump-results-api-resources.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3487 Revert "Increase memory of production build controller"
  components/build-service/production/base/increase-build-controller-memory.yaml
  components/build-service/production/base/kustomization.yaml
Labels: lgtm, approved

#3481 Create a new konflux-ci workspace, sibling of tekton-ci
  argo-cd-apps/base/konflux-ci/konflux-ci.yaml
  argo-cd-apps/base/konflux-ci/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  components/build-templates/base/e2e/rolebinding.yaml
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
  components/konflux-ci/base/appstudio-pipelines-runner-rolebinding.yaml
  components/konflux-ci/base/external-secrets/clair-in-ci-db-github-token.yaml
  components/konflux-ci/base/external-secrets/github-secret.yaml
  components/konflux-ci/base/external-secrets/infra-deployments-pr-creator.yaml
  components/konflux-ci/base/external-secrets/kustomization.yaml
  components/konflux-ci/base/external-secrets/quay-push-secret-konflux-ci.yaml
  components/konflux-ci/base/external-secrets/quay-push-secret.yaml
  components/konflux-ci/base/external-secrets/registry-redhat-io-pull-secret.yaml
  components/konflux-ci/base/external-secrets/slack-webhook-notification-secret.yaml
  components/konflux-ci/base/external-secrets/snyk-shared-token.yaml
  components/konflux-ci/base/konflux-ci-maintainers-rb.yaml
  components/konflux-ci/base/kustomization.yaml
  components/konflux-ci/base/namespace.yaml
  components/konflux-ci/base/repository.yaml
  components/konflux-ci/base/serviceaccount.yaml
  components/konflux-ci/production/infra-deployments-pr-creator.yaml
  components/konflux-ci/production/kustomization.yaml
  components/konflux-ci/production/plnsvc-ci-secret.yaml
  components/konflux-ci/production/plnsvc-codecov-secret.yaml
  components/konflux-ci/production/quay-push-secret-konflux-ci.yaml
  components/konflux-ci/production/quay-push-secret.yaml
  components/konflux-ci/production/snyk-shared-token.yaml
  components/konflux-ci/staging/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  components/tekton-ci/base/repository.yaml
  docs/deployment/extending-the-service.md
Labels: lgtm, approved

#3492 pipeline-service update prod
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3504 RHTAPSRE-353: RBAC for creating workspaces in internal clusters
  argo-cd-apps/base/keycloak/keycloak.yaml
  argo-cd-apps/base/keycloak/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  argo-cd-apps/overlays/staging-downstream/kustomization.yaml
  components/keycloak/base/konflux-workspace-admins/kustomization.yaml
  components/keycloak/base/konflux-workspace-admins/rbac.yaml
  components/keycloak/base/kustomization.yaml
  components/keycloak/production/base/kustomization.yaml
  components/keycloak/staging/base/kustomization.yaml
Labels: lgtm, approved

#3496 KFLUXBUGS-24: bump dev/stage overlay chains deployment to use performance arguments
  components/pipeline-service/development/chains-deployment-perf-bump.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/chains-deployment-perf-bump.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3505 Keycloak RBAC fix typo
  components/keycloak/base/konflux-workspace-admins/rbac.yaml
Labels: lgtm, approved

#3494 RHTAPSRE-489: Deploy repository-validator
  .github/workflows/kube-linter.yaml
  argo-cd-apps/base/repository-validator/kustomization.yaml
  argo-cd-apps/base/repository-validator/repository-validator.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  argo-cd-apps/overlays/staging-downstream/kustomization.yaml
  components/repository-validator/development/config.json
  components/repository-validator/development/kustomization.yaml
  components/repository-validator/production/kustomization.yaml
  components/repository-validator/staging/kustomization.yaml
Labels: lgtm, approved

#3456 chore(RHTAPWATCH-819): Add project controller
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/project-controller/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/project-controller/project-controller.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  components/project-controller/OWNERS
  components/project-controller/README.md
  components/project-controller/base/allow-argocd-to-manage.yaml
  components/project-controller/base/argocd-permissions.yaml
  components/project-controller/base/kustomization.yaml
  components/project-controller/base/project-controller.yaml
  components/project-controller/development/kustomization.yaml
  components/project-controller/production/kustomization.yaml
  components/project-controller/staging/kustomization.yaml
Labels: lgtm, approved

#3510 Remove JVM Build Service Builder Images Repo
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#3512 RHTAPSRE-467: Webhook configuration for internal staging
  components/build-service/components/webhook-config/kustomization.yaml
  components/build-service/components/webhook-config/webhook-config-patch.yaml
  components/build-service/staging/stone-stage-p01/add-webhook-target-patch.yaml
  components/build-service/staging/stone-stage-p01/kustomization.yaml
  components/build-service/staging/stone-stage-p01/webhook-config.json
Labels: lgtm, approved

#3513 RHTAPSRE-467: Webhook configuration for internal production
  components/build-service/production/stone-prod-p01/add-webhook-target-patch.yaml
  components/build-service/production/stone-prod-p01/kustomization.yaml
  components/build-service/production/stone-prod-p01/webhook-config.json
Labels: lgtm, approved

#3507 KFLUXBUGS-24: bump prod overlay chains deployment to use performance arguments
  components/pipeline-service/production/base/chains-deployment-perf-bump.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3509 chore: project-controller deployment in production
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
Labels: lgtm, approved

#3495 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#3520 Enable auto-approval for internal production
  components/sandbox/toolchain-host-operator/production/stone-prod-p01/toolchainconfig.yaml
Labels: approved

#3493 feat(STONEINTG-844): add configuration template of task URL
  components/integration/development/kustomization.yaml
  components/integration/development/manager_resources_patch.yaml
  components/integration/production/base/kustomization.yaml
  components/integration/production/base/manager_resources_patch.yaml
  components/integration/production/stone-prod-p01/console-url-config-patch.json
  components/integration/production/stone-prod-p01/kustomization.yaml
  components/integration/staging/base/kustomization.yaml
  components/integration/staging/base/manager_resources_patch.yaml
  components/integration/staging/stone-stage-p01/console-url-config-patch.json
  components/integration/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#3518 Replace rhtap-infra by konflux-infra email
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/toolchainconfig.yaml
  components/sandbox/toolchain-host-operator/production/stone-prod-p01/toolchainconfig.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/toolchainconfig.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/toolchainconfig.yaml
Labels: lgtm, approved

#3514 fix(stoneinteg-761): update tag for integration grafana dashboard
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
Labels: lgtm, approved

#3523 KFLUXINFRA-366: Register build VMs for int prod
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: approved
