Repository redhat-appstudio/infra-deployments, pull requests merged in 2024-05, with the labels that each got.

#3649 Revert "fix: set concurrency limit to 1 for build-definitions repo"
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#3653 STONEINTG-840: migrate clair-in-ci-db to konflux-ci org
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#3650 fix: increase cpu and mem for release cleanup cronjob
  components/release/base/cronjobs/remove-expired-releases.yaml
Labels: lgtm, approved

#3657 feat(STONEINTG-839): hacbs-test migration
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#3658 build-service: move repo to konflux-ci org
  components/build-service/README.md
  components/build-service/development/kustomization.yaml
  components/build-service/production/base/kustomization.yaml
  components/build-service/staging/base/kustomization.yaml
  components/monitoring/grafana/base/dashboards/build-service/kustomization.yaml
  components/tekton-ci/base/repository.yaml
  docs/deployment/extending-the-service.md
  docs/development/deployment.md
  hack/preview.sh
Labels: lgtm, approved

#3593 RHTAPSRE-296: Keycloak deployment
  argo-cd-apps/base/keycloak/keycloak.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/development/set-local-cluster-label.yaml
  components/keycloak/README.md
  components/keycloak/base/configure-keycloak.yaml
  components/keycloak/base/kustomization.yaml
  components/keycloak/base/namespace.yaml
  components/keycloak/base/rhsso-operator.yaml
  components/keycloak/development/kustomization.yaml
  components/keycloak/development/reduce-replicas.yaml
  components/keycloak/development/set-ocp-idp.yaml
  components/keycloak/development/set-redirect-uri.yaml
  components/keycloak/production/base/kustomization.yaml
  components/keycloak/production/stone-prod-p01/kustomization.yaml
  components/keycloak/production/stone-prod-p01/set-ocp-idp.yaml
  components/keycloak/production/stone-prod-p01/set-redirect-uri.yaml
  components/keycloak/staging/base/kustomization.yaml
  components/keycloak/staging/stone-stage-p01/kustomization.yaml
  components/keycloak/staging/stone-stage-p01/set-ocp-idp.yaml
  components/keycloak/staging/stone-stage-p01/set-redirect-uri.yaml
  components/ui/development/fed-modules.json
  components/ui/development/kustomization.yaml
  components/ui/development/reduce-replicas.yaml
  components/ui/development/set-hostname.yaml
Labels: lgtm, approved

#3668 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#3655 fix(KFLUXBUGS-1218): add pipelineRun timeout environment vars
  components/integration/development/kustomization.yaml
  components/integration/development/manager_resources_patch.yaml
  components/integration/production/base/kustomization.yaml
  components/integration/production/base/manager_resources_patch.yaml
  components/integration/staging/base/kustomization.yaml
  components/integration/staging/base/manager_resources_patch.yaml
Labels: lgtm, approved

#3677 KFLUXINFRA-567: Replacing appsrep05ue1 to appsrep09ue1
  components/backup/production/stone-prd-host1/backup-s3-credentials-patch.yaml
  components/backup/production/stone-prd-m01/backup-s3-credentials-patch.yaml
  components/backup/production/stone-prd-rh01/backup-s3-credentials-patch.yaml
  components/backup/production/stone-prod-p01/backup-s3-credentials-patch.yaml
  components/cluster-secret-store-rh/base/rh-artifacts-bucket-writer-secret-store.yml
  components/gitops/production/stone-prod-p01/gitops-service-postgres-rds-config-path.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/stone-prod-p01/resources/tekton-results-s3-secret-path.yaml
  components/remote-secret-controller/overlays/production/stone-prd-m01/aws-credentials-path-patch.yaml
  components/remote-secret-controller/overlays/production/stone-prd-rh01/aws-credentials-path-patch.yaml
  components/remote-secret-controller/overlays/production/stone-prod-p01/aws-credentials-path-patch.yaml
  components/spi/overlays/production/stone-prd-m01/spi-aws-credentials-path-patch.yaml
  components/spi/overlays/production/stone-prd-rh01/spi-aws-credentials-path-patch.yaml
  components/spi/overlays/production/stone-prod-p01/spi-aws-credentials-path-patch.yaml
  hack/hac/installHac.sh
Labels: lgtm, approved

#3675 Deploy backup on clusters with backup label only
  argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
  argo-cd-apps/base/backup/backup.yaml
  argo-cd-apps/base/backup/kustomization.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
Labels: lgtm, approved

#3680 Fix logging operator installation on kflux-stg-es01
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
  components/monitoring/logging/staging/kflux-stg-es01/kustomization.yaml
Labels: lgtm, approved

#3683 Do not create openshift-logging namespace
  components/monitoring/logging/base/logging-operator-prerequisite/kustomization.yaml
  components/monitoring/logging/base/logging-operator-prerequisite/namespace.yaml
Labels: lgtm, approved

#3685 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#3686 feat: allow integration team to manage integrationtestscenarios
  components/integration/base/kustomization.yaml
  components/integration/base/manage-integrationtestscenarios.yaml
Labels: lgtm, approved

#3678 tekton-ci: remove build-service PaC Repository
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#3656 Bump hac-dev, chrome service, chrome frontend tags
  components/ui/production/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#3687 build-service update
  components/build-service/development/kustomization.yaml
  components/build-service/production/base/kustomization.yaml
  components/build-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#3616 KFLUXBUGS-863: introduce results fixes with requisite performance related tuning (dev/stage)
  components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
  components/pipeline-service/development/bump-results-watcher-replicas.yaml
  components/pipeline-service/development/config.env
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/development/update-results-watcher-performance.yaml
  components/pipeline-service/staging/base/bump-results-watcher-replicas.yaml
  components/pipeline-service/staging/base/config.env
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/update-results-watcher-performance.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3688 KFLUXBUGS-863: Revert "KFLUXBUGS-863: introduce results fixes with requisite performance related tuning (dev/stage) (#3616)"
  components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
  components/pipeline-service/development/bump-results-watcher-replicas.yaml
  components/pipeline-service/development/config.env
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/development/update-results-watcher-performance.yaml
  components/pipeline-service/staging/base/bump-results-watcher-replicas.yaml
  components/pipeline-service/staging/base/config.env
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/update-results-watcher-performance.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3567 Rotate Keycloak secret
  components/dev-sso/keycloak-realm.yaml
Labels: lgtm, approved

#3644 pin results image until watcher mem leak fix is deemed ok
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
Labels: lgtm, approved

#3691 chore(STONEINTG-836): migrate integration-service to konflux-ci
  components/integration/README.md
  components/integration/development/kustomization.yaml
  components/integration/production/base/kustomization.yaml
  components/integration/staging/base/kustomization.yaml
  components/monitoring/grafana/base/dashboards/integration/kustomization.yaml
  hack/preview.sh
Labels: lgtm, approved

#3682 Create first application/component on eaas cluster
  argo-cd-apps/base/eaas/kustomization.yaml
  argo-cd-apps/base/eaas/some-component/kustomization.yaml
  argo-cd-apps/base/eaas/some-component/some-component.yaml
  argo-cd-apps/k-components/deploy-to-eaas-cluster-merge-generator/eaas-cluster-label-selector.yaml
  argo-cd-apps/k-components/deploy-to-eaas-cluster-merge-generator/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  argo-cd-apps/overlays/staging-downstream/kustomization.yaml
  components/some-component/base/kustomization.yaml
  components/some-component/base/namespace.yaml
  components/some-component/production/kustomization.yaml
  components/some-component/staging/kustomization.yaml
Labels: lgtm, approved

#3693 Enable Tekton StepActions in dev and staging
  components/pipeline-service/development/enable-step-actions.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3695 Fix eaas component path
  argo-cd-apps/base/eaas/some-component/some-component.yaml
Labels: lgtm, approved

#3643 chore: add ci-helper-app
  argo-cd-apps/base/ci-helper-app/ci-helper-app.yaml
  argo-cd-apps/base/ci-helper-app/kustomization.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
  components/backup/base/member/schedules/backup-tenants-schedule.yaml
  components/ci-helper-app/OWNERS
  components/ci-helper-app/base/kustomization.yaml
  components/ci-helper-app/base/rbac/ci-helper-app.yaml
  components/ci-helper-app/base/rbac/kustomization.yaml
  components/ci-helper-app/development/kustomization.yaml
  components/ci-helper-app/staging/external-secrets/ci-helper-app-secrets.yaml
  components/ci-helper-app/staging/external-secrets/kustomization.yaml
  components/ci-helper-app/staging/kustomization.yaml
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
  docs/_data/navigation.yml
  docs/misc/ci-helper-app.md
  hack/bootstrap-host-cluster.sh
  hack/destroy-cluster.sh
  hack/preview-template.env
  hack/secret-creator/create-ci-helper-app-secret.sh
Labels: lgtm, approved

#3629 Build config for build pipelines for build-service,
  components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
  components/build-service/base/kustomization.yaml
  components/build-service/base/rbac/build-config.yaml
  components/build-service/base/rbac/kustomization.yaml
Labels: lgtm, approved

#3699 SRVKP-4361: enable results-from sidecar-logs for pipelines
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/development/tekton-pipelines-controller-pods-log-access-rbac.yaml
  components/pipeline-service/development/update-tekton-config-features.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/tekton-pipelines-controller-pods-log-access-rbac.yaml
  components/pipeline-service/staging/base/update-tekton-config-features.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3700 Deploy ci-helper-app only on clusters with matching label
  argo-cd-apps/base/ci-helper-app/ci-helper-app.yaml
Labels: lgtm, approved

#3702 Only deploy quality-dashboard ApplicationSet on public staging
  argo-cd-apps/base/local-cluster-secret/all-in-one/kustomization.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
Labels: lgtm, approved

#3706 chore: qd: konflux-qe-admins perms for pods
  components/ci-helper-app/base/rbac/ci-helper-app.yaml
  components/quality-dashboard/base/rbac/quality-dashboard.yaml
Labels: lgtm, approved

#3709 Update routes for internal staging and update Keycloak IDP config
  components/keycloak/README.md
  components/keycloak/base/configure-keycloak.yaml
  components/keycloak/staging/stone-stage-p01/set-ocp-idp.yaml
  components/keycloak/staging/stone-stage-p01/set-redirect-uri.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/update-tekton-config-pac.yaml
  components/ui/staging/fed-modules.json
  components/ui/staging/set-hostname.yaml
Labels: lgtm, approved

#3708 Improve deployment
  components/keycloak/base/namespace.yaml
  components/keycloak/base/rhsso-operator.yaml
  components/sandbox/toolchain-host-operator/base/kustomization.yaml
  components/sandbox/toolchain-host-operator/base/ns.yaml
  components/sandbox/toolchain-host-operator/base/olm/toolchain-host-operator.yaml
  components/sandbox/toolchain-member-operator/base/kustomization.yaml
  components/sandbox/toolchain-member-operator/base/ns.yaml
  components/sandbox/toolchain-member-operator/base/olm/toolchain-member-operator.yaml
Labels: lgtm, approved

#3716 KFLUXINFRA-570: Config Change for Multi-Arch Builds Public Staging
  components/multi-platform-controller/staging/external-secrets.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#3717 Update Keycloak routes for the registration-service int stage
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/toolchainconfig.yaml
Labels: approved

#3724 build-service: fix prod image reference
  components/build-service/production/base/kustomization.yaml
Labels: lgtm, approved

#3730 feat(RELEASE-230): update release service ref to konflux ci org
  components/monitoring/grafana/base/dashboards/release/kustomization.yaml
  components/release/development/kustomization.yaml
  components/release/production/kustomization.yaml
  components/release/staging/kustomization.yaml
  hack/preview.sh
Labels: lgtm, approved

#3738 Reverting to Old AMIs
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#3739 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#3742 Removing Spot Instance Option for Multi-Platform Build
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#3720 Move Image Controller operator to konflux-ci organization
  components/image-controller/README.md
  components/image-controller/development/kustomization.yaml
  components/image-controller/production/base/kustomization.yaml
  components/image-controller/staging/base/kustomization.yaml
  components/monitoring/grafana/base/dashboards/image-controller/kustomization.yaml
  hack/preview.sh
Labels: lgtm, approved

#3703 feat: Add ability to run the e2e-tests from rhtap-build-tenant ns
  components/build-templates/base/e2e/rolebinding.yaml
Labels: lgtm, approved

#3721 build-definitions: move repo to konflux-ci
  components/build-service/README.md
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#3747 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#3752 fix: sync snapshotgc reference in integration component
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#3758 KFLUXINFRA-579: Configuring New AWS Account for Multi Platform Build
  components/multi-platform-controller/production/external-secrets.yaml
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#3760 GITOPSRVCE-801: Remove gitops from dev and stage
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
Labels: lgtm, approved

#3769 KFLUXINFRA-580: Configuring New AWS Account for Multi Platform Build
  components/multi-platform-controller/staging-downstream/external-secrets.yaml
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#3776 KFLUXINFRA-581: Configuring New AWS Account for Multi Platform Build
  components/multi-platform-controller/production-downstream/external-secrets.yaml
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: lgtm, approved

#3763 feat(STONEINTG-861): add CONSOLE_NAME for integration
  components/integration/development/kustomization.yaml
  components/integration/development/manager_resources_patch.yaml
  components/integration/production/base/kustomization.yaml
  components/integration/production/base/manager_resources_patch.yaml
  components/integration/production/stone-prod-p01/console-url-config-patch.json
  components/integration/production/stone-prod-p01/kustomization.yaml
  components/integration/staging/base/kustomization.yaml
  components/integration/staging/base/manager_resources_patch.yaml
  components/integration/staging/stone-stage-p01/console-url-config-patch.json
  components/integration/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#3777 KFLUXINFRA-533: Added IBM Z and Power machines to internal-stage hostconfig
  components/multi-platform-controller/staging-downstream/external-secrets.yaml
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#3768 Remove gitops prod
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
Labels: approved

#3782 Router and UI proxy access for the registration service
  components/sandbox/toolchain-host-operator/production/stone-prod-p02/kustomization.yaml
  components/sandbox/toolchain-host-operator/production/stone-prod-p02/network-policy.yaml
Labels: approved

#3783 Skip dry run on missing resources for sandbox host
  components/sandbox/toolchain-host-operator/base/proxy/proxyplugin.yaml
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/space-provisioner-configs.yaml
  components/sandbox/toolchain-host-operator/production/stone-prod-p01/space-provisioner-configs.yaml
  components/sandbox/toolchain-host-operator/production/stone-prod-p02/space-provisioner-configs.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/space-provisioner-configs.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/space-provisioner-configs.yaml
Labels: approved

#3785 Deploy Keycloak on stone-prod-p02
  components/keycloak/production/stone-prod-p02/kustomization.yaml
Labels: approved

#3786 Skip dry run on missing resources for keycloak
  components/keycloak/base/configure-keycloak.yaml
Labels: approved

#3787 Skip dry run on missing resources for backup
  components/backup/base/all-clusters/oadp/dpa.yaml
  components/backup/base/host/schedules/backup-toolchain-host-schedule.yaml
  components/backup/base/member/schedules/backup-tenants-schedule.yaml
  components/backup/base/member/schedules/backup-toolchain-member-schedule.yaml
Labels: approved

#3775 Bump prod pipeline service level to stage level
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
Labels: lgtm, approved

#3792 Updating Secret Path for stone-prod-p02
  components/gitops/production/stone-prod-p02/gitops-service-postgres-rds-config-path.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/stone-prod-p02/resources/tekton-results-s3-secret-path.yaml
  components/remote-secret-controller/overlays/production/stone-prod-p02/aws-credentials-path-patch.yaml
  components/spi/overlays/production/stone-prod-p02/spi-aws-credentials-path-patch.yaml
Labels: approved

#3788 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#3793 updating secrets prefix for spi and remote secret controller
  components/remote-secret-controller/overlays/production/stone-prod-p02/config-patch.json
  components/spi/overlays/production/stone-prod-p02/config-patch.json
Labels: approved

#3784 sandbox-host: Allow traffic from olm namespace
  components/sandbox/toolchain-host-operator/base/olm/toolchain-host-operator.yaml
Labels: lgtm, approved

#3796 Build CM - fix docker build pipeline name
  components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
Labels: lgtm, approved

#3797 KFLUXINFRA-581: Configuring New AWS Account for Multi Platform Build
  components/multi-platform-controller/production-downstream/external-secrets.yaml
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: lgtm, approved

#3802 Update base image for ibmz machines
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: approved

#3805 fix(STONEINTG-861): update intg configMap name for CONSOLE_NAME
  components/integration/development/manager_resources_patch.yaml
  components/integration/production/base/manager_resources_patch.yaml
  components/integration/staging/base/manager_resources_patch.yaml
Labels: lgtm, approved

#3773 chore: add cronjob to cleanup stale applications in build-templates-e2e ns
  components/tekton-ci/production/cleanup-cronjob.yaml
  components/tekton-ci/production/kustomization.yaml
Labels: lgtm, approved

#3808 KFLUXINFRA-532: Internal Prod host-config for IBM builds
  components/multi-platform-controller/production-downstream/external-secrets.yaml
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: lgtm, approved

#3800 Enable auto-approval for external prod
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/space-provisioner-configs.yaml
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/toolchainconfig.yaml
Labels: lgtm, approved

#3807 fix(STONEINTG-861): add 'Konflux Dev version' to CONSOLE_NAME
  components/integration/development/kustomization.yaml
Labels: lgtm, approved

#3812 Increase rootful VM disk size
  components/multi-platform-controller/production/host-config.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: approved

#3814 Add Public network to the PowerVMS
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#3815 update network value for ppc
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: approved

#3757 Skeleton w/ArgoCD for cluster-as-a-service component
  argo-cd-apps/base/eaas/cluster-as-a-service/cluster-as-a-service.yaml
  argo-cd-apps/base/eaas/cluster-as-a-service/kustomization.yaml
  argo-cd-apps/base/eaas/kustomization.yaml
  argo-cd-apps/k-components/assign-eaas-role-to-local-cluster/kustomization.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  argo-cd-apps/overlays/staging-downstream/kustomization.yaml
  components/cluster-as-a-service/OWNERS
  components/cluster-as-a-service/base/argocd.yaml
  components/cluster-as-a-service/base/kustomization.yaml
  components/cluster-as-a-service/development/kustomization.yaml
  components/cluster-as-a-service/production/kustomization.yaml
  components/cluster-as-a-service/staging/kustomization.yaml
  components/gitops/openshift-gitops/overlays/production-and-dev/kustomization.yaml
  components/gitops/openshift-gitops/overlays/staging/kustomization.yaml
  components/openshift-gitops/cluster-rbac/argocd-application-controller-clusterrole.yaml
  components/openshift-gitops/cluster-rbac/argocd-application-controller-clusterrolebinding.yaml
  components/openshift-gitops/cluster-rbac/argocd-server-clusterrole.yaml
  components/openshift-gitops/cluster-rbac/argocd-server-clusterrolebinding.yaml
  components/openshift-gitops/cluster-rbac/kustomization.yaml
  components/openshift-gitops/kustomization.yaml
  components/openshift-gitops/subscription.yaml
  components/some-component/base/namespace.yaml
  hack/bootstrap-cluster.sh
  hack/bootstrap-eaas-cluster.sh
  hack/deploy-argocd.sh
  hack/preview-template.env
  hack/preview.sh
  hack/secret-creator/create-eaas-secrets.sh
Labels: lgtm, approved

#3824 feat(RELEASE-935): update release-pipeline clusterrole
  components/release/base/release-pipeline-resources-clusterrole.yaml
Labels: lgtm, approved

#3827 Added static hostconfig for internal stage ppc64le
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: approved

#3828 Remove ppc64le from dynamic provisioning
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: approved

#3774 image-controller: move base/OWNERS to OWNERS
  components/build-service/OWNERS
  components/image-controller/OWNERS
  components/image-controller/base/OWNERS
  components/monitoring/grafana/base/dashboards/build-service/OWNERS
Labels: lgtm, approved

#3821 chore: reflect moving e2e-tests to konflux-ci org
  components/tekton-ci/base/repository.yaml
  docs/testing/e2e-tests.md
Labels: lgtm, approved

#3830 KFLUXINFRA-532: Added static hosts for IBM Power internal prod
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: lgtm, approved
