Repository redhat-appstudio/infra-deployments, pull requests merged in 2024-01, with the labels that each got.

#2980 chore(RHTAPWATCH-590): remove CloudWatch log forwarding
  components/monitoring/logging/base/configure-logging/configure-logforwarder.yaml
  components/monitoring/logging/base/external-secrets/kustomization.yaml
  components/monitoring/logging/base/external-secrets/monitoring-logging-cloudwatch-forwarder.yaml
  components/monitoring/logging/production/kustomization.yaml
  components/monitoring/logging/production/monitoring-logging-cloudwatch-forwarder-path.yaml
  components/monitoring/logging/staging/kustomization.yaml
  components/monitoring/logging/staging/monitoring-logging-cloudwatch-forwarder-path.yaml
Labels: lgtm, approved

#2991 Switch IBM Cloud for multi-platform to new account
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#2987 Promote SPI/RemoteSecret from staging to prod
  components/remote-secret-controller/overlays/production/base/kustomization.yaml
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#2994 Revert "Switch IBM Cloud for multi-platform to new account (#2991)"
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#2996 Switch IBM Cloud for multi-platform to new account
  components/multi-platform-controller/production/external-secrets.yaml
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#2995 add mfrancisc as sandbox sre admin
  components/sandbox/base/rbac/sandbox-sre-admins.yaml
Labels: lgtm, approved

#3001 Update pipeline-service in prd
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
Labels: lgtm, approved

#2999 Revert "Switch IBM Cloud for multi-platform to new account (#2996)"
  components/multi-platform-controller/production/external-secrets.yaml
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#3003 Fail kube-linter check if issues are found
  .github/workflows/kube-linter.yaml
Labels: lgtm, approved

#3002 Adding the prod multi-platform VMs to stage
  components/multi-platform-controller/staging/external-secrets.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#3005 Revert pipeline-service
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3007 Update pipeline-service in prd/stg
  components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3000 Used latest RemoteSecret's grafana dashboard
  components/monitoring/grafana/base/dashboards/spi/kustomization.yaml
Labels: lgtm, approved

#3008 add update verb for rolebinding resources
  components/authentication/base/rhtap-admins.yaml
Labels: lgtm, approved

#2830 Reduce admin-checker cron frequency to once a week
  components/authentication/base/admin-checker/cronjob.yaml
Labels: lgtm, approved

#3015 Promote SPI/RemoteSecret from staging to prod
  components/remote-secret-controller/overlays/production/base/kustomization.yaml
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#3017 Promote integration-service from staging to production
  components/integration/production/kustomization.yaml
Labels: lgtm, approved

#3013 Fix build-service production application path
  components/build-service/production/base/kustomization.yaml
  components/build-service/production/base/pipelines-as-code-secret-patch.yaml
Labels: lgtm, approved

#3024 chore: Update commit sha based on o11y pr
  components/monitoring/grafana/base/kustomization.yaml
Labels: lgtm, approved

#2988 fix: image-contoller and build-service overlay changes for refactoring dev/stage and prod
  .tekton/build-service-prod-overlay-update.yaml
  .tekton/image-controller-prod-overlay-update.yaml
  .tekton/tasks/promote-component.yaml
  components/build-service/base/kustomization.yaml
  components/build-service/development/kustomization.yaml
  components/build-service/production/base/kustomization.yaml
  components/build-service/staging/base/kustomization.yaml
  components/image-controller/base/kustomization.yaml
  components/image-controller/development/kustomization.yaml
  components/image-controller/development/manager_resources_patch.yaml
  components/image-controller/production/kustomization.yaml
  components/image-controller/production/manager_resources_patch.yaml
  components/image-controller/staging/kustomization.yaml
  components/image-controller/staging/manager_resources_patch.yaml
Labels: lgtm, approved

#3025 Upgrade pipeline-service
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
Labels: lgtm, approved

#3028 RHTAPSRE-252: UI url for the internal cluster
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/update-tekton-config-pac.yaml
Labels: lgtm, approved, jira/valid-reference

#3010 RHTAP-1134: Build service mount RH certs
  components/build-service/components/rh-certs/2015-RH-IT-Root-CA.pem
  components/build-service/components/rh-certs/2022-IT-Root-CA.pem
  components/build-service/components/rh-certs/add-rh-certs-patch.yaml
  components/build-service/components/rh-certs/kustomization.yaml
  components/build-service/development/kustomization.yaml
  components/build-service/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved, jira/valid-reference

#3031 chore: update commit sha based on o11y pr
  components/monitoring/grafana/base/kustomization.yaml
Labels: lgtm, approved

#3036 Remove gorkem from OWNERS file
  OWNERS
Labels: lgtm, approved

#3033 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#3027 RHTAP-2116: Webhook target for the internal cluster
  components/build-service/staging/stone-stage-p01/add-webhook-target-patch.yaml
  components/build-service/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved, jira/valid-reference

#3016 grant admin permissions in sandbox namespaces
  components/sandbox/base/rbac/sandbox-sre-admins.yaml
  components/sandbox/toolchain-host-operator/base/kustomization.yaml
  components/sandbox/toolchain-host-operator/base/rbac/sandbox-sre-admins.yaml
  components/sandbox/toolchain-member-operator/base/rbac/sandbox-sre-admins.yaml
Labels: lgtm, approved

#3012 Create logging namespace and operatorgroup on stone-stage-p01
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
  components/monitoring/logging/base/configure-logging/configure-log-collectors.yaml
  components/monitoring/logging/base/configure-logging/configure-logforwarder.yaml
  components/monitoring/logging/base/install-logging-operator.yaml
  components/monitoring/logging/base/logging-operator-prerequisite/kustomization.yaml
  components/monitoring/logging/base/logging-operator-prerequisite/namespace.yaml
  components/monitoring/logging/base/logging-operator-prerequisite/operatorgroup.yaml
  components/monitoring/logging/production/base/kustomization.yaml
  components/monitoring/logging/staging/base/kustomization.yaml
  components/monitoring/logging/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#3043 Remove EC components from tekton-ci
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#2910 Add grafana dashboards for build-service initial build/provision upon…
  components/monitoring/grafana/base/dashboards/build-service/dashboard.yaml
  components/monitoring/grafana/base/dashboards/build-service/kustomization.yaml
Labels: lgtm, approved

#2978 Add grafana dashboards for image-controller, image repository provision
  components/monitoring/grafana/base/dashboards/image-controller/OWNERS
  components/monitoring/grafana/base/dashboards/image-controller/dashboard.yaml
  components/monitoring/grafana/base/dashboards/image-controller/kustomization.yaml
Labels: lgtm, approved

#3044 Remove unused controller image reference
  components/enterprise-contract/kustomization.yaml
Labels: lgtm, approved

#3051 PLNSRVCE-1525: bump tekton pipeline controller to 2 replicas and 4 buckets
  components/pipeline-service/development/update-tekton-config-performance.yaml
  components/pipeline-service/staging/base/update-tekton-config-performance.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved, jira/valid-reference

#3054 Fix kustomize build of logging development overlay
  components/monitoring/logging/development/kustomization.yaml
Labels: lgtm, approved

#3059 Bump sprayproxy version prod
  components/sprayproxy/production/kustomization.yaml
Labels: lgtm, approved

#3060 RHTAPSRE-340: Add build vms to the internal env
  argo-cd-apps/overlays/staging-downstream/kustomization.yaml
  argo-cd-apps/overlays/staging-downstream/staging-downstream-overlay-patch.yaml
  components/multi-platform-controller/staging-downstream/external-secrets.yaml
  components/multi-platform-controller/staging-downstream/host-config.yaml
  components/multi-platform-controller/staging-downstream/kustomization.yaml
Labels: lgtm, approved, jira/valid-reference

#3063 RemoteSecret && SPI CODEOWNERS refinement
  components/remote-secret-controller/OWNERS
  components/spi/OWNERS
Labels: lgtm, approved

#3062 Fix the git clone failure
  .tekton/rhtap-staging-e2e-ci.yaml
Labels: lgtm, approved

#3037 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#3065 feat(RHTAPWATCH-660): IP filter for smee sever
  components/smee/staging/route.yaml
Labels: lgtm, approved

#3069 bump pipeline servicve prod to current staging level
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
Labels: lgtm, approved

#3055 Fix kustomize build of toolchain development overlay
  components/sandbox/toolchain-host-operator/development/kustomization.yaml
  components/sandbox/toolchain-member-operator/development/kustomization.yaml
Labels: lgtm, approved

#3061 Promote SPI/RemoteSecret from staging to prod
  components/remote-secret-controller/overlays/production/base/kustomization.yaml
  components/spi/overlays/production/base/kustomization.yaml
Labels: lgtm, approved

#3071 fix(RHTAPWATCH-660): Smee server IP filter fix
  components/smee/staging/route.yaml
Labels: lgtm, approved

#3035 feat: Allow integration team to delete snapshots
  components/integration/base/delete-snapshots.yaml
  components/integration/base/kustomization.yaml
Labels: lgtm, approved

#3073 enterprise contract update
  components/enterprise-contract/ecp.yaml
  components/enterprise-contract/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#3075 Remove OSP pruner configuration
  components/pipeline-service/staging/base/greedy-pruner.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3074 bump exporter mem limit in prod
  components/pipeline-service/production/base/bump-exporter-mem.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
Labels: lgtm, approved

#3053 Remove emtpy gitops-repo-pruner component
  components/gitops-repo-pruner/OWNERS
  components/gitops-repo-pruner/kustomization.yaml
Labels: lgtm, approved

#3047 Promoting component image-controller from stage to prod
  components/image-controller/production/kustomization.yaml
Labels: lgtm, approved

#3077 Remove application-service from tekton-ci
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#3066 konflux core: create service monitor for registration service
  components/sandbox/base/kustomization.yaml
  components/sandbox/base/monitoring/sandbox-registration-service-proxy.yaml
  components/sandbox/toolchain-host-operator/base/monitoring/sandbox-registration-service-proxy.yaml
Labels: lgtm, approved

#3084 Offboarding of Shoubhik Bose
  OWNERS
  components/authentication/base/group-sync/group-sync.yaml
  components/has/base/rbac/has.yaml
  components/image-controller/base/OWNERS
  components/multi-platform-controller/OWNERS
  components/tekton-ci/base/tekton-ci-maintainers-rb.yaml
Labels: lgtm, approved

#3086 PLNSRVCE-1525: bump prod tekton pipeline controller to 2 replicas and 4 buckets
  components/pipeline-service/production/base/update-tekton-config-performance.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
Labels: lgtm, approved, jira/valid-reference

#3052 Fail kustomize build step on failure
  .github/workflows/kube-linter.yaml
Labels: lgtm, approved

#3090 Promote integration-service from staging to production
  components/integration/production/kustomization.yaml
Labels: lgtm, approved

#3091 image-controller update
  components/image-controller/production/kustomization.yaml
Labels: lgtm, approved

#3092 add prometheus monitor for image-controller
  components/image-controller/base/kustomization.yaml
  components/image-controller/base/monitoring.yaml
Labels: lgtm, approved

#3093 bump results watcher watcher container to 3Gi
  components/pipeline-service/production/base/bump-results-watcher-mem.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
Labels: lgtm, approved

#3097 enable UWM to scrape toolchain-host-operator namespace
  components/sandbox/toolchain-host-operator/base/monitoring/kustomization.yaml
  components/sandbox/toolchain-host-operator/base/monitoring/prometheus-network-policy.yaml
Labels: lgtm, approved

#3094 fix(integration): define resources per deployments
  components/integration/development/kustomization.yaml
  components/integration/development/manager_resources_patch.yaml
  components/integration/k-components/manager-resources-patch/kustomization.yaml
  components/integration/production/kustomization.yaml
  components/integration/production/manager_resources_patch.yaml
  components/integration/staging/kustomization.yaml
  components/integration/staging/manager_resources_patch.yaml
Labels: lgtm, approved

#3100 Used latest RemoteSecret's grafana dashboard
  components/monitoring/grafana/base/dashboards/spi/kustomization.yaml
Labels: lgtm, approved

#3104 bump prod to staging level
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
Labels: lgtm, approved

#3106 add sandbox proxy metrics grafana dashboard
  components/monitoring/grafana/base/dashboards/core/dashboard.yaml
  components/monitoring/grafana/base/dashboards/core/kustomization.yaml
  components/monitoring/grafana/base/dashboards/core/sandbox-proxy-metrics.json
  components/monitoring/grafana/base/dashboards/kustomization.yaml
Labels: lgtm, approved

#3105 Promote integration-service from staging to production
  components/integration/production/kustomization.yaml
  components/integration/production/manager_resources_patch.yaml
Labels: lgtm, approved

#3067 fix(test): add api.console scope to keycloak
  components/dev-sso/keycloak-realm.yaml
Labels: lgtm, approved

#3095 Update PaC name in staging with Konflux
  components/pipeline-service/staging/base/update-tekton-config-pac.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#3111 Extract Gitops and plnsvc app-sre secrets from new cluster
  components/gitops/staging/stone-stg-m01/gitops-service-postgres-rds-config-path.yaml
  components/gitops/staging/stone-stg-rh01/gitops-service-postgres-rds-config-path.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/staging/stone-stg-m01/resources/tekton-results-s3-secret-path.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/tekton-results-s3-secret-path.yaml
Labels: lgtm, approved

#3123 fix: Fix the indentation in pipelineruns
  .tekton/build-service-prod-overlay-update.yaml
  .tekton/image-controller-prod-overlay-update.yaml
Labels: lgtm, approved

#3088 STONEBLD-2010: Added build-team as maintainer tekton-ci component
  components/tekton-ci/base/tekton-ci-maintainers-rb.yaml
Labels: lgtm, approved

#3129 Fix: Update preview.sh script to reflect overlay change
  hack/preview.sh
Labels: lgtm, approved

#3114 Fix delete-snapshots ClusterRole
  components/integration/base/delete-snapshots.yaml
Labels: lgtm, approved

#3130 Fix kube-linter version to 0.6.5
  .github/workflows/kube-linter.yaml
Labels: lgtm, approved

#3125 Update the UI in the internal cluster
  components/ui/staging/kustomization.yaml
Labels: lgtm, approved

#3128 Update Build Service production layout
  components/build-service/production/base/kustomization.yaml
Labels: lgtm, approved

#3117 Add ECP for verifying Tasks
  components/enterprise-contract/ecp.yaml
Labels: lgtm, approved

#3116 Replace `Infra Team` group by `konflux-infra`
  components/authentication/base/group-sync/group-sync.yaml
Labels: lgtm, approved

#3115 Replace `RHTAP Admins` group by `konflux-admins`
  components/authentication/base/konflux-admins.yaml
  components/authentication/base/kustomization.yaml
Labels: lgtm, approved

#3118 Replace `Build [Admins] team` groups by `konflux-build[-admins]`
  components/build-service/base/rbac/build-admin.yaml
  components/build-service/base/rbac/build-maintainer.yaml
  components/build-templates/base/e2e/rolebinding.yaml
  components/image-controller/base/rbac/image-controller-admin.yaml
  components/image-controller/base/rbac/image-controller-maintainer.yaml
  components/tekton-ci/base/tekton-ci-maintainers-rb.yaml
Labels: lgtm, approved

#3134 Replace dora-metrics RBAC users by `konflux-qe-admins` group
  components/dora-metrics/base/rbac/dora-metrics.yaml
Labels: lgtm, approved

#3135 Re-enable IBM Cloud prod account for multi-platform
  components/multi-platform-controller/production/external-secrets.yaml
  components/multi-platform-controller/production/host-config.yaml
  components/multi-platform-controller/staging/external-secrets.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#3143 chore: Update the o11y kustomization files
  components/monitoring/grafana/base/kustomization.yaml
  components/monitoring/grafana/development/kustomization.yaml
  components/monitoring/grafana/production/kustomization.yaml
  components/monitoring/grafana/staging/kustomization.yaml
Labels: lgtm, approved

#3145 Remove unneeded results-cluster-viewer ClusterRole
  components/authentication/staging/kustomization.yaml
  components/authentication/staging/results-cluster-viewer.yaml
Labels: lgtm, approved

#3144 Replace `Pipeline Service` group by `konflux-pipeline-service`
  components/pipeline-service/base/rbac/cluster-role/pipeline-service-sre.yaml
  components/pipeline-service/base/rbac/openshift-pipelines/pipeline-service-sre.yaml
  components/pipeline-service/base/rbac/tekton-results/pipeline-service-sre.yaml
  components/pipeline-service/base/testing/rbac.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  components/sprayproxy/base/rbac/pipeline-service-sre.yaml
Labels: lgtm, approved

#3149 Remove unneeded authentication development overlay
  components/authentication/development/kustomization.yaml
  components/authentication/development/spi-vault-admin.yaml
Labels: lgtm, approved

#3150 chore(integration-service): update controller resources
  components/integration/production/manager_resources_patch.yaml
Labels: lgtm, approved

#3142 Do not swallow errors on ec downloads
  components/enterprise-contract/download-service.yaml
Labels: lgtm, approved

#3152 Disable the rhtap-staging-e2e test
  .tekton/rhtap-staging-e2e-ci.yaml.disabled
Labels: lgtm, approved

#3153 Rename PaC in prd
  components/pipeline-service/production/base/update-tekton-config-pac.yaml
Labels: lgtm, approved

#3151 Replace `Release Team` group by `konflux-release-team`
  components/internal-services/internal-services.yaml
  components/release/base/release-team.yaml
Labels: lgtm, approved

#3159 fix: remove datasource to fallback on default one, fix example link
  components/monitoring/README.md
  components/monitoring/grafana/base/dashboards/core/sandbox-proxy-metrics.json
Labels: lgtm, approved

#3164 Use new konflux-o11y[-admins] groups
  components/monitoring/logging/base/rbac/logging-admin.yaml
  components/segment-bridge/rbac/segment-bridge.yaml
Labels: lgtm, approved

#3165 Replace `Integration Team` group by `konflux-integration`
  components/integration/base/delete-snapshots.yaml
Labels: lgtm, approved

#3167 RHTAPSRE-351: Add manifests for the internal production deployment
  argo-cd-apps/app-of-app-sets/production-downstream/change-source-path.yaml
  argo-cd-apps/app-of-app-sets/production-downstream/change-target-namespace.yaml
  argo-cd-apps/app-of-app-sets/production-downstream/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml
  argo-cd-apps/base/member/infra-deployments/build-service/build-service.yaml
  argo-cd-apps/base/member/infra-deployments/gitops/gitops.yaml
  argo-cd-apps/base/member/infra-deployments/pipeline-service/pipeline-service.yaml
  argo-cd-apps/base/member/infra-deployments/remote-secret-controller/remote-secret-controller.yaml
  argo-cd-apps/base/member/infra-deployments/spi/spi.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/production-downstream-overlay-patch.yaml
  argo-cd-apps/overlays/production-downstream/production-overlay-patch.yaml
  components/build-service/production/stone-prod-p01/add-webhook-target-patch.yaml
  components/build-service/production/stone-prod-p01/kustomization.yaml
  components/build-service/production/stone-prod-p01/pipelines-as-code-secret-path.yaml
  components/gitops/production/stone-prod-p01/gitops-service-postgres-rds-config-path.yaml
  components/gitops/production/stone-prod-p01/kustomization.yaml
  components/monitoring/prometheus/production/stone-prod-p01/cluster-id-label.yaml
  components/monitoring/prometheus/production/stone-prod-p01/kustomization.yaml
  components/multi-platform-controller/production-downstream/external-secrets.yaml
  components/multi-platform-controller/production-downstream/host-config.yaml
  components/multi-platform-controller/production-downstream/kustomization.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/kustomization.yaml
  components/pipeline-service/production/stone-prod-p01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prod-p01/resources/pipelines-as-code-secret-path.yaml
  components/pipeline-service/production/stone-prod-p01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/stone-prod-p01/resources/tekton-results-s3-secret-path.yaml
  components/pipeline-service/production/stone-prod-p01/resources/update-tekton-config-pac.yaml
  components/remote-secret-controller/overlays/production/stone-prod-p01/aws-credentials-path-patch.yaml
  components/remote-secret-controller/overlays/production/stone-prod-p01/config-patch.json
  components/remote-secret-controller/overlays/production/stone-prod-p01/kustomization.yaml
  components/smee-client/base/deployment.yaml
  components/smee-client/base/kustomization.yaml
  components/smee-client/production/kustomization.yaml
  components/smee-client/production/sever-url-patch.yaml
  components/smee-client/staging/kustomization.yaml
  components/smee-client/staging/sever-url-patch.yaml
  components/spi/overlays/production/stone-prod-p01/config-patch.json
  components/spi/overlays/production/stone-prod-p01/kustomization.yaml
  components/spi/overlays/production/stone-prod-p01/oauth-service-config-patch.json
  components/spi/overlays/production/stone-prod-p01/spi-aws-credentials-path-patch.yaml
  components/spi/overlays/production/stone-prod-p01/spi-shared-configuration-file-config-path.yaml
  components/ui/README.md
  components/ui/production/fed-modules.json
  components/ui/production/kustomization.yaml
  components/ui/production/set-hostname.yaml
Labels: lgtm, approved

#3172 Add a ServiceMonitor to collect OADP/velero metrics
  components/backup/base/all-clusters/kustomization.yaml
  components/backup/base/all-clusters/servicemonitor.yaml
Labels: lgtm, approved

#3174 Keep `schedule` label on remote written metrics
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#3170 Change refresh interval for Build Service and Image Controller to red…
  components/build-service/base/external-secrets/pipelines-as-code-secret.yaml
  components/image-controller/base/external-secrets/quaytoken.yaml
Labels: lgtm, approved

#3113 release-service update
  components/monitoring/grafana/base/dashboards/release/kustomization.yaml
  components/release/development/kustomization.yaml
Labels: lgtm, approved

#3177 Add `ec-automation[bot]` as approver
  components/enterprise-contract/OWNERS
Labels: lgtm, approved

#3180 release-service staging update
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#3179 Use RH IdP authentication for stone-stage-p01
  argo-cd-apps/base/all-clusters/infra-deployments/authentication/authentication.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  components/authentication/base/rh-idp/everyone-can-view-patch.yaml
  components/authentication/base/rh-idp/group-sync/external-secrets/kustomization.yaml
  components/authentication/base/rh-idp/group-sync/external-secrets/mtls-ca-validators.yaml
  components/authentication/base/rh-idp/group-sync/konflux-rover-groups.yaml
  components/authentication/base/rh-idp/group-sync/kustomization.yaml
  components/authentication/base/rh-idp/kustomization.yaml
  components/authentication/production/base/github-redhat-appstudio-secret-patch.yaml
  components/authentication/production/base/github-redhat-appstudio-sre-secret-patch.yaml
  components/authentication/production/base/kustomization.yaml
  components/authentication/production/base/rhtap-infra-secrets-patch.yaml
  components/authentication/staging/base/kustomization.yaml
  components/authentication/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#3182 RHTAPSRE-376: Deploy operator group for the openshift-logging operator
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
  components/monitoring/logging/production/stone-prod-p01/kustomization.yaml
Labels: lgtm, approved

#3181 release-service prod update
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#3184 Add temporarily ZAPLOGLEVEL as debug in remote-secret configmap to help debug RHTAPBUGS-1105
  components/remote-secret-controller/overlays/development/config-patch.json
Labels: lgtm, approved
