Repository redhat-appstudio/infra-deployments, pull requests merged in 2024-08, with the labels that each got.

#4242 SRVKP-4523: need both old and new tekton k8s throttle metrics available to app-sre
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#4072 fix(RHTAPWATCH-1140): Remove segment-bridge components from infra-deployments
  argo-cd-apps/base/host/kustomization.yaml
  argo-cd-apps/base/host/segment-bridge/kustomization.yaml
  argo-cd-apps/base/host/segment-bridge/segment-bridge-host.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/segment-bridge/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/segment-bridge/segment-bridge-member.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  components/backup/base/member/schedules/backup-tenants-schedule.yaml
  components/segment-bridge/OWNERS
  components/segment-bridge/README.md
  components/segment-bridge/base/kustomization.yaml
  components/segment-bridge/base/serviceaccount.yaml
  components/segment-bridge/development/kustomization.yaml
  components/segment-bridge/production/base/kustomization.yaml
  components/segment-bridge/production/rbac/kustomization.yaml
  components/segment-bridge/production/stone-prd-host1/kustomization.yaml
  components/segment-bridge/production/stone-prd-m01/kustomization.yaml
  components/segment-bridge/production/stone-prd-rh01/kustomization.yaml
  components/segment-bridge/rbac/kustomization.yaml
  components/segment-bridge/rbac/segment-bridge.yaml
  components/segment-bridge/staging/base/kustomization.yaml
  components/segment-bridge/staging/rbac/kustomization.yaml
  components/segment-bridge/staging/stone-stg-host/kustomization.yaml
  components/segment-bridge/staging/stone-stg-m01/kustomization.yaml
  components/segment-bridge/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#4223 Add prod SpaceProvisionerConfig for EaaS
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/space-provisioner-configs.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/space-provisioner-configs.yaml
Labels: lgtm, approved

#4189 Add konflux-eaas kubesaw tier
  components/sandbox/tiers/production/konflux-eaas/kustomization.yaml
  components/sandbox/tiers/production/konflux-eaas/nstemplatetier-konflux-eaas.yaml
  components/sandbox/tiers/production/konflux-eaas/tiertemplate-konflux-eaas-admin-37575401-37575401.yaml
  components/sandbox/tiers/production/konflux-eaas/tiertemplate-konflux-eaas-clusterresources-885501723-885501723.yaml
  components/sandbox/tiers/production/konflux-eaas/tiertemplate-konflux-eaas-contributor-37575401-37575401.yaml
  components/sandbox/tiers/production/konflux-eaas/tiertemplate-konflux-eaas-eaas-3975606140-3975606140.yaml
  components/sandbox/tiers/production/konflux-eaas/tiertemplate-konflux-eaas-maintainer-37575401-37575401.yaml
  components/sandbox/tiers/production/konflux-eaas/tiertemplate-konflux-eaas-viewer-37575401-37575401.yaml
  components/sandbox/tiers/production/kustomization.yaml
  components/sandbox/tiers/src/konflux-eaas/cluster.yaml
  components/sandbox/tiers/src/konflux-eaas/ns_eaas.yaml
  components/sandbox/tiers/src/konflux-eaas/spacerole_admin.yaml
  components/sandbox/tiers/src/konflux-eaas/spacerole_contributor.yaml
  components/sandbox/tiers/src/konflux-eaas/spacerole_maintainer.yaml
  components/sandbox/tiers/src/konflux-eaas/spacerole_viewer.yaml
  components/sandbox/tiers/src/konflux-eaas/tier.yaml
  components/sandbox/tiers/staging/konflux-eaas/kustomization.yaml
  components/sandbox/tiers/staging/konflux-eaas/nstemplatetier-konflux-eaas.yaml
  components/sandbox/tiers/staging/konflux-eaas/tiertemplate-konflux-eaas-admin-37575401-37575401.yaml
  components/sandbox/tiers/staging/konflux-eaas/tiertemplate-konflux-eaas-clusterresources-885501723-885501723.yaml
  components/sandbox/tiers/staging/konflux-eaas/tiertemplate-konflux-eaas-contributor-37575401-37575401.yaml
  components/sandbox/tiers/staging/konflux-eaas/tiertemplate-konflux-eaas-eaas-3975606140-3975606140.yaml
  components/sandbox/tiers/staging/konflux-eaas/tiertemplate-konflux-eaas-maintainer-37575401-37575401.yaml
  components/sandbox/tiers/staging/konflux-eaas/tiertemplate-konflux-eaas-viewer-37575401-37575401.yaml
  components/sandbox/tiers/staging/kustomization.yaml
Labels: lgtm, approved

#4248 KFLUXINFRA-744: Migrating Konflux Resources from appsres05ue1 to 09ue1
  components/backup/staging/stone-stage-p01/backup-s3-credentials-patch.yaml
  components/backup/staging/stone-stg-host/backup-s3-credentials-patch.yaml
  components/backup/staging/stone-stg-m01/backup-s3-credentials-patch.yaml
  components/backup/staging/stone-stg-rh01/backup-s3-credentials-patch.yaml
  components/gitops/staging/stone-stage-p01/gitops-service-postgres-rds-config-path.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/tekton-results-s3-secret-path.yaml
  components/remote-secret-controller/overlays/staging/stone-stage-p01/aws-credentials-path-patch.yaml
  components/remote-secret-controller/overlays/staging/stone-stg-m01/aws-credentials-path-patch.yaml
  components/remote-secret-controller/overlays/staging/stone-stg-rh01/aws-credentials-path-patch.yaml
  components/spi/overlays/staging/stone-stage-p01/spi-aws-credentials-path-patch.yaml
  components/spi/overlays/staging/stone-stg-m01/spi-aws-credentials-path-patch.yaml
  components/spi/overlays/staging/stone-stg-rh01/spi-aws-credentials-path-patch.yaml
Labels: lgtm, approved

#4243 chore(RHTAPWATCH-1188): prevent cascade deletion
  argo-cd-apps/base/rh-managed-workspaces-config/rh-managed-workspaces-config.yaml
  argo-cd-apps/base/tenants-config/tenants-config.yaml
Labels: lgtm, approved

#4251 Enable kflux-stg-es01 SpaceProvisionerConfig
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/space-provisioner-configs.yaml
Labels: lgtm, approved

#4252 Add baseDomain param to EaaS cluster templates in staging
  components/cluster-as-a-service/staging/add-base-domain-param.yaml
  components/cluster-as-a-service/staging/kustomization.yaml
Labels: lgtm, approved

#4255 Allow ExternalSecrets in namespaces konflux-qe-team-tenant and rhtap-shared-tenant
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: lgtm

#4258 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#4244 SRVKP-4524: give tekton perms to konflux-sre
  components/pipeline-service/base/rbac/openshift-pipelines/pipeline-service-sre.yaml
  components/pipeline-service/base/rbac/tekton-results/pipeline-service-sre.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4246 SRVKP-4532: bump metrics exporter only dev/stage
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4256 tekton-ci: remove jvm-build-service PaC Repository
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#4261 Fix ExternalSecret paths for staging EaaS
  components/cluster-as-a-service/staging/external-secrets.yaml
Labels: lgtm, approved

#4265 Fix another ExternalSecret path for EaaS
  components/cluster-as-a-service/staging/external-secrets.yaml
Labels: lgtm, approved

#4266 fixing hcp secret foe eaas
  components/cluster-as-a-service/staging/external-secrets.yaml
Labels: approved

#4268 chore(RHTAPWATCH-1188): part 2: rm tenants-config
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
Labels: lgtm, approved

#4269 KFLUXBUGS-1451: Added more PPC nodes and reduced concurrency
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: lgtm, approved

#4272 adding hcp namespace for appsre-vault cluster secret store
  components/cluster-as-a-service/staging/external-secrets.yaml
  components/cluster-secret-store/base/appsre-vault-secret-store.yml
Labels: approved

#4263 SRVKP-4532: add resolver crd to exporter permissions
  components/pipeline-service/base/rbac/openshift-pipelines/kustomization.yaml
  components/pipeline-service/base/rbac/openshift-pipelines/resolution-req-perms-exporter.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4283 Changing Paths for EaaS External Secrets
  components/cluster-as-a-service/staging/external-secrets.yaml
  components/cluster-secret-store/base/appsre-vault-secret-store.yml
Labels: lgtm, approved

#4285 SRVKP-4532: bump metrics exporter on prod
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4288 Promote mintmaker from staging to production
  components/mintmaker/production/base/kustomization.yaml
Labels: lgtm, approved

#4271 chore(RHTAPWATCH-1188): part 3: rm tenants-config (#4268)
  argo-cd-apps/base/rh-managed-workspaces-config/kustomization.yaml
  argo-cd-apps/base/rh-managed-workspaces-config/rh-managed-workspaces-config.yaml
  argo-cd-apps/base/tenants-config/kustomization.yaml
  argo-cd-apps/base/tenants-config/tenants-config.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
Labels: lgtm, approved

#4290 Bump version for hypershift-aws-cluster template
  components/cluster-as-a-service/base/clustertemplates.yaml
Labels: lgtm, approved

#4262 chore(RHTAPWATCH-1164): onboard notification-controller to staging
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/notification-controller/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/notification-controller/notification-controller.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
  components/notification-controller/OWNERS
  components/notification-controller/README.md
  components/notification-controller/base/deployment.yaml
  components/notification-controller/base/external-secrets/aws-sns-secret.yaml
  components/notification-controller/base/external-secrets/kustomization.yaml
  components/notification-controller/base/kustomization.yaml
  components/notification-controller/base/namespace.yaml
  components/notification-controller/base/service-account.yaml
  components/notification-controller/development/kustomization.yaml
  components/notification-controller/development/topic_region_add.yaml
  components/notification-controller/staging/kustomization.yaml
  components/notification-controller/staging/topic_region_add.yaml
Labels: lgtm, approved

#4294 Enable EaaS in public production
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  components/cluster-as-a-service/production/add-base-domain-param.yaml
  components/cluster-as-a-service/production/external-secrets.yaml
  components/cluster-as-a-service/production/kustomization.yaml
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/space-provisioner-configs.yaml
Labels: lgtm, approved

#4296 Fix merge generator for cluster-as-a-service in prod
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
Labels: lgtm, approved

#4295 workspaces: enable public-viewer support in public staging
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/toolchainconfig.yaml
Labels: lgtm, approved

#4267 KONFLUX-2256: multi-platform controller can spawn GPU accelerated nodes
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, ok-to-test, approved

#4300 Increase staging limitRange CPU requests
  components/sandbox/tiers/src/appstudio/ns_tenant.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-tenant-2313893948-2313893948.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-tenant-1884308846-2313893948.yaml
Labels: lgtm, approved

#4303 feat(RHTAPWATCH-1192): Bump prod. project-controller
  components/project-controller/production/kustomization.yaml
Labels: lgtm, approved

#4297 update notification-controller container
  components/notification-controller/base/deployment.yaml
Labels: lgtm, approved

#4291 SRVKP-5855: move all tekton related config to infra-deployments
  components/monitoring/grafana/base/dashboards/pipeline-service/grafana-config.yaml
  components/monitoring/grafana/base/dashboards/pipeline-service/kustomization.yaml
  components/pipeline-service/base/testing/rbac.yaml
  components/pipeline-service/development/bump-results-watcher-replicas.yaml
  components/pipeline-service/development/chains-tekton-config-patches.yaml
  components/pipeline-service/development/config.env
  components/pipeline-service/development/dev-only-pipeline-service-storage-configuration.yaml
  components/pipeline-service/development/enable-step-actions.yaml
  components/pipeline-service/development/increase-results-pruner-gracePeriod.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/development/metrics-exporter-trace.yaml
  components/pipeline-service/development/reduce-watcher-cpu-mem-reqs.yaml
  components/pipeline-service/development/scale-down-exporter.yaml
  components/pipeline-service/development/update-results-watcher-performance.yaml
  components/pipeline-service/development/update-tekton-config-performance.yaml
  components/pipeline-service/production/base/bump-exporter-mem.yaml
  components/pipeline-service/production/base/bump-results-api-resources.yaml
  components/pipeline-service/production/base/bump-results-watcher-mem.yaml
  components/pipeline-service/production/base/bump-results-watcher-replicas.yaml
  components/pipeline-service/production/base/chains-tekton-config-patches.yaml
  components/pipeline-service/production/base/kustomization.yaml
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/base/pac-config.yaml
  components/pipeline-service/production/base/scale-down-exporter.yaml
  components/pipeline-service/production/base/update-tekton-config-performance.yaml
  components/pipeline-service/staging/base/bump-results-watcher-mem.yaml
  components/pipeline-service/staging/base/bump-results-watcher-replicas.yaml
  components/pipeline-service/staging/base/chains-tekton-config-patches.yaml
  components/pipeline-service/staging/base/config.env
  components/pipeline-service/staging/base/kustomization.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/metrics-exporter-trace.yaml
  components/pipeline-service/staging/base/scale-down-exporter.yaml
  components/pipeline-service/staging/base/update-results-watcher-performance.yaml
  components/pipeline-service/staging/base/update-tekton-config-pac.yaml
  components/pipeline-service/staging/base/update-tekton-config-performance.yaml
Labels: lgtm, approved

#4313 update workspaces to v0.1.0-alpha5
  components/workspaces/base/operator/config/crd/bases/workspaces.konflux-ci.dev_internalworkspaces.yaml
  components/workspaces/base/operator/config/crd/kustomization.yaml
  components/workspaces/base/operator/config/manager/kustomization.yaml
  components/workspaces/base/operator/config/rbac/internalworkspace_editor_role.yaml
  components/workspaces/base/operator/config/rbac/internalworkspace_viewer_role.yaml
  components/workspaces/base/operator/config/rbac/role.yaml
  components/workspaces/base/server/config/crd/bases/workspaces.konflux-ci.dev_workspaces.yaml
  components/workspaces/base/server/config/crd/kustomization.yaml
  components/workspaces/base/server/config/default/kustomization.yaml
  components/workspaces/base/server/config/rbac/role_workspace_server_editor.yaml
  components/workspaces/base/server/config/server/kustomization.yaml
  components/workspaces/base/server/config/server/proxy-config/dynamic/config.yaml
  components/workspaces/staging/stone-stage-p01/kustomization.yaml
  components/workspaces/staging/stone-stg-host/kustomization.yaml
Labels: lgtm, approved

#4309 Add the docker-build-oci-ta pipeline to the configmap
  components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
Labels: lgtm, approved

#4314 Increase s390x capacity for supporting more production load
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: lgtm, approved

#4319 SRVKP-5855: add README for update openshift pipeline related configuration
  components/pipeline-service/README.md
Labels: lgtm, approved

#4304 chore(KFLUXINFRA-743): Add "local" platform hosts
  components/multi-platform-controller/OWNERS
  components/multi-platform-controller/staging-downstream/host-config.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#4324 install ksctl during kubesaw deployment
  hack/sandbox-development-mode.sh
Labels: lgtm, approved

#4318 chore: add Jen to integration-service's OWNERS file
  components/integration/OWNERS
Labels: lgtm, approved

#4333 KFLUXINFRA-786: Add resource pool for ppc64le in public prod
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#4323 Disable autogeneration of TektonConfig
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4334 KFLUXINFRA-786: Added s390x as dynamic hosts for public prod
  components/multi-platform-controller/production/external-secrets.yaml
  components/multi-platform-controller/production/host-config.yaml
Labels: approved

#4336 Fix s390x image for podman installation
  components/multi-platform-controller/production/host-config.yaml
Labels: approved

#4337 Reverting the s390x host machines for fixing the subnet
  components/multi-platform-controller/production/host-config.yaml
Labels: approved

#4339 Re-enable dynamic hosts for s390x
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#4341 Revert s390x dynamic to static
  components/multi-platform-controller/production/host-config.yaml
Labels: approved

#4344 mintmaker: add label to registry pull secret
  components/mintmaker/base/external-secrets/registry-redhat-io-pull-secret.yaml
Labels: lgtm, approved

#4328 feat(KFLUXINFRA-741): PROD: MPC w/ "local" support
  components/multi-platform-controller/production-downstream/kustomization.yaml
  components/multi-platform-controller/production/kustomization.yaml
Labels: lgtm, approved

#4327 chore(KLUXINFRA-743): STAGE: Add "mlarge" platform
  components/multi-platform-controller/staging-downstream/host-config.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#4321 Remove deployment related quotas from staging
  components/sandbox/tiers/src/appstudio/cluster.yaml
  components/sandbox/tiers/src/appstudiolarge/based_on_tier.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-clusterresources-3180033938-3180033938.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-admin-1929014883-1876853981.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-1929014883-3180033938.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-contributor-1929014883-1817914940.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-maintainer-1929014883-293087644.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-tenant-1929014883-2313893948.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-viewer-1929014883-4059797645.yaml
Labels: lgtm, approved

#4329 chore(KFLUXINFRA-743) Prod local platforms
  components/multi-platform-controller/production-downstream/host-config.yaml
  components/multi-platform-controller/production/host-config.yaml
Labels: lgtm, approved

#4343 PVCORE-4433 - Add Power Monitoring Operator
  argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/power-monitoring/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/power-monitoring/power-monitoring.yaml
  components/power-monitoring/OWNERS
  components/power-monitoring/kepler.yaml
  components/power-monitoring/kustomization.yaml
  components/power-monitoring/power-monitoring-operator.yaml
Labels: lgtm, approved

#4224 workspaces: fix outdated namespace reference
  argo-cd-apps/base/host/workspaces/workspaces.yaml
Labels: lgtm, approved

#4347 Fix IBM a100 ssh key
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: lgtm, approved

#4349 Remove compute-deployment quota from staging
  components/sandbox/tiers/src/appstudio/ns_tenant.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-tenant-3815075241-3815075241.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-tenant-1929014883-3815075241.yaml
Labels: lgtm, approved

#4338 Sync grafan dashboard panel for pipeline service
  components/monitoring/grafana/base/dashboards/pipeline-service/grafana-config.yaml
Labels: lgtm, ok-to-test, approved

#4352 Remove deployment related quotas from production
  components/sandbox/tiers/production/appstudio/kustomization.yaml
  components/sandbox/tiers/production/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-clusterresources-3180033938-3180033938.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-tenant-3815075241-3815075241.yaml
  components/sandbox/tiers/production/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/production/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-admin-1929014883-1876853981.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-1929014883-3180033938.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-contributor-1929014883-1817914940.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-maintainer-1929014883-293087644.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-tenant-1929014883-3815075241.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-viewer-1929014883-4059797645.yaml
Labels: lgtm, approved

#4355 Promote mintmaker from staging to production
  components/mintmaker/production/base/kustomization.yaml
  components/mintmaker/production/base/manager_patches.yaml
Labels: lgtm, approved

#4356 Add dynamic vm for ppc internal stage
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: approved

#4357 Update public vlan id for stage-internal
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: approved

#4348 update Notification-Controller image
  components/notification-controller/base/deployment.yaml
  components/notification-controller/development/kustomization.yaml
  components/notification-controller/development/topic_region_add.yaml
  components/notification-controller/staging/kustomization.yaml
  components/notification-controller/staging/topic_region_add.yaml
Labels: lgtm, approved

#4358 SRVKP-4524: add metrics/labels for results alerts/panels
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#4312 PVCORE-4435 - Move otel image to Quay. Pin versions of image and chart
  argo-cd-apps/base/member/infra-deployments/tracing-workload-otel-collector/tracing-workload-otel-collector.yaml
  components/tracing/otel-collector/development/otel-collector-helm-values.yaml
  components/tracing/otel-collector/production/otel-collector-helm-values.yaml
  components/tracing/otel-collector/staging/otel-collector-helm-values.yaml
Labels: lgtm, approved

#4275 feat(KONFLUX-3985): Bump up default `requests` for task containers in Stage
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4372 Dynamic s390x for external stage
  components/multi-platform-controller/staging/external-secrets.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: approved

#4373 Dynamic env to the list for stage
  components/multi-platform-controller/staging/host-config.yaml
Labels: approved

#4374 Fix ssh key for s390x stage ext
  components/multi-platform-controller/staging/external-secrets.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: approved

#4376 point stage env to staging keys
  components/multi-platform-controller/staging/external-secrets.yaml
Labels: lgtm, approved

#4380 fix: release controller oomkill on start up
  components/release/k-components/manager-resources-patch/manager_resources_patch.yaml
Labels: lgtm, approved

#4379 Add the multi-arch pipeline to the pipeline config
  components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
Labels: lgtm, approved

#4381 Update UI images to the latest
  components/ui/development/kustomization.yaml
  components/ui/production/stone-prod-p01/kustomization.yaml
  components/ui/production/stone-prod-p02/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: lgtm, approved

#4383 Revert "Update UI images to the latest"
  components/ui/development/kustomization.yaml
  components/ui/production/stone-prod-p01/kustomization.yaml
  components/ui/production/stone-prod-p02/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: approved

#4382 Send traces via honeycomb refinery for sampling purposes
  components/tracing/otel-collector/production/otel-collector-helm-values.yaml
  components/tracing/otel-collector/staging/otel-collector-helm-values.yaml
Labels: lgtm, approved

#4378 Replace chains public key Job by ExternalSecret
  components/pipeline-service/base/external-secrets/openshift-pipelines/chains-public-key.yaml
  components/pipeline-service/base/external-secrets/openshift-pipelines/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prod-p01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prod-p02/resources/kustomization.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/kustomization.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/tekton-chains-public-key-path.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/resources/kustomization.yaml
  components/pipeline-service/staging/stone-stg-m01/resources/tekton-chains-public-key-path.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/kustomization.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/tekton-chains-public-key-path.yaml
Labels: lgtm, approved

#4385 KFLUXBUGS-1557: Add Large nodes for s390x and ppc64le to internal prod
  components/multi-platform-controller/production-downstream/host-config.yaml
Labels: lgtm, approved

#4386 KFLUXINFRA-808: Set default pipelines timeout to 2 hours - stage
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4384 update hac code for development and staging
  components/ui/development/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: lgtm, approved

#4387 update hac code for prod
  components/ui/production/stone-prod-p01/kustomization.yaml
  components/ui/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#4388 Add cluster-secret-store-rh to internal clusters
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
Labels: lgtm, approved

#4369 SRVKP-5900: enable pprof for results thread dumps, prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4391 KFLUXINFRA-801: reverting tekton config changes
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
Labels: lgtm, approved

#4394 Add view permissions for CaaS and hypershift resources
  components/authentication/base/everyone-can-view.yaml
Labels: lgtm, approved

#4354 Change unit from percent to none
  components/monitoring/grafana/base/dashboards/pipeline-service/grafana-config.yaml
Labels: lgtm, ok-to-test, approved

#4393 workspaces: add production configuration
  argo-cd-apps/base/host/workspaces/workspaces.yaml
  components/workspaces/production/stone-prd-host1/kustomization.yaml
  components/workspaces/production/stone-prd-host1/route.yaml
  components/workspaces/production/stone-prod-p01/kustomization.yaml
  components/workspaces/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#4397 KFLUXINFRA-802: Segregate Konflux and Tenants Workload using TektonConfig
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/resources/kustomization.yaml
  components/pipeline-service/staging/stone-stg-m01/resources/tekton-config-patch.yaml
Labels: lgtm, approved

#4403 Replace chains public key Job by ExternalSecret - prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/resources/tekton-chains-public-key-path.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/tekton-chains-public-key-path.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prod-p01/resources/tekton-chains-public-key-path.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/resources/kustomization.yaml
  components/pipeline-service/production/stone-prod-p02/resources/tekton-chains-public-key-path.yaml
Labels: lgtm, approved

#4408 chore: Give access to integration service to access vault secrets for e2e tests
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: lgtm, approved

#4395 bump versions of github actions dependencies
  .github/workflows/kube-linter.yaml
Labels: lgtm, approved

#4410 KFLUXINFRA-808: Set default pipelines timeout to 2 hours - prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#4411 Migrate ClusterRole appstudio-pipelines-runner
  components/sandbox/toolchain-member-operator/base/rbac/appstudio-pipelines-runner.yaml
  components/sandbox/toolchain-member-operator/base/rbac/kustomization.yaml
Labels: lgtm, approved

#4405 chore(RHTAPWATCH-1169): Reduce permissions in the appstudio-env tier
  components/sandbox/tiers/production/appstudio-env/kustomization.yaml
  components/sandbox/tiers/production/appstudio-env/nstemplatetier-appstudio-env.yaml
  components/sandbox/tiers/production/appstudio-env/tiertemplate-appstudio-env-clusterresources-1854252301-1854252301.yaml
  components/sandbox/tiers/src/appstudio-env/cluster.yaml
  components/sandbox/tiers/staging/appstudio-env/kustomization.yaml
  components/sandbox/tiers/staging/appstudio-env/nstemplatetier-appstudio-env.yaml
  components/sandbox/tiers/staging/appstudio-env/tiertemplate-appstudio-env-clusterresources-1854252301-1854252301.yaml
Labels: lgtm, approved

#4389 SRVKP-4530: Expose metrics for pac controller deadlock/performace alerts
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, ok-to-test, approved

#4412 Add ArgoCD view permissions for cluster-as-a-service
  components/cluster-as-a-service/base/argocd.yaml
  components/cluster-as-a-service/development/argocd-rbac.yaml
  components/cluster-as-a-service/development/kustomization.yaml
Labels: lgtm, approved

#4399 Remove PaC secret reaper CronJob
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4413 Enable pipeline SA to read and list plrs
  components/sandbox/toolchain-member-operator/base/rbac/appstudio-pipelines-runner.yaml
Labels: lgtm, approved

#4406 workspaces: don't delete applicationset from prod
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
Labels: lgtm, approved

#4398 feat(RELEASE-996): add release-service-monitor to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#4417 More SPI leftovers cleanup
  components/sandbox/tiers/production/appstudio/kustomization.yaml
  components/sandbox/tiers/production/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-admin-849337768-849337768.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-contributor-829105171-829105171.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-maintainer-1904354742-1904354742.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-tenant-649666048-649666048.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-viewer-4256863455-4256863455.yaml
  components/sandbox/tiers/production/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/production/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-admin-1929014883-849337768.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-contributor-1929014883-829105171.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-maintainer-1929014883-1904354742.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-tenant-1929014883-649666048.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-viewer-1929014883-4256863455.yaml
  components/sandbox/tiers/src/appstudio/ns_tenant.yaml
  components/sandbox/tiers/src/appstudio/spacerole_admin.yaml
  components/sandbox/tiers/src/appstudio/spacerole_contributor.yaml
  components/sandbox/tiers/src/appstudio/spacerole_maintainer.yaml
  components/sandbox/tiers/src/appstudio/spacerole_viewer.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-admin-849337768-849337768.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-contributor-829105171-829105171.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-maintainer-1904354742-1904354742.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-tenant-649666048-649666048.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-viewer-4256863455-4256863455.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-admin-1929014883-849337768.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-contributor-1929014883-829105171.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-maintainer-1929014883-1904354742.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-tenant-1929014883-649666048.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-viewer-1929014883-4256863455.yaml
  hack/preview-template.env
Labels: lgtm, approved

#4409 allow pipeline service SREs to view openshift-pipelines webhook configuration
  components/pipeline-service/base/rbac/cluster-role/pipeline-service-sre.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4424 forgot to re-run generate-deploy-config
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-m01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#4421 Bump version of hypershift-aws-template to 0.0.4
  components/cluster-as-a-service/base/clustertemplates.yaml
Labels: lgtm, approved

#4422 promote hac-dev latest changes
  components/ui/development/kustomization.yaml
  components/ui/production/stone-prod-p01/kustomization.yaml
  components/ui/production/stone-prod-p02/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#4425 Allow admins and SRE to manage EaaS resources
  components/authentication/base/konflux-admins.yaml
  components/cluster-as-a-service/base/argocd.yaml
Labels: lgtm, approved

#4427 ui: pass relevant requests to workspaces
  components/ui/base/proxy/nginx.conf
Labels: lgtm, approved

#4429 Add power-monitoring grafana dashboard
  components/monitoring/grafana/base/dashboards/kustomization.yaml
  components/monitoring/grafana/base/dashboards/power-monitoring/dashboard.yaml
  components/monitoring/grafana/base/dashboards/power-monitoring/kepler.json
  components/monitoring/grafana/base/dashboards/power-monitoring/kustomization.yaml
Labels: lgtm, approved

#4426 Fix image value for opentelemetry image
  argo-cd-apps/base/member/infra-deployments/tracing-workload-otel-collector/tracing-workload-otel-collector.yaml
  components/tracing/otel-collector/development/otel-collector-helm-values.yaml
  components/tracing/otel-collector/production/otel-collector-helm-values.yaml
  components/tracing/otel-collector/staging/otel-collector-helm-values.yaml
Labels: lgtm, approved

#4430 set port when forwarding requests to workspaces
  components/ui/base/proxy/nginx.conf
Labels: lgtm, approved

#4431 chore: Add environment to disable ec_download_service when e2e tests
  hack/preview-template.env
  hack/preview.sh
Labels: lgtm, approved
