Repository redhat-appstudio/infra-deployments, pull requests merged in 2025-05, with the labels that each got.

#6279 Configure prod-p02 cluster to test static PVMs
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: lgtm, approved

#6283 Fix platform name for p02 static s390x under test
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: approved

#6185 feat(RELEASE-1541): use trusted artifacts (#6147)
  components/release/production/release_service_config.yaml
Labels: lgtm, approved

#6284 Change s390x and ppc64le to static VMs on P02
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: lgtm, approved

#6287 Add 2 more s390x machines for p02
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: lgtm, approved

#6271 add konflux-viewer-user-actions role to stg and prod
  components/konflux-rbac/production/base/konflux-viewer-user-actions.yaml
  components/konflux-rbac/production/base/kustomization.yaml
  components/konflux-rbac/staging/base/konflux-viewer-user-actions.yaml
  components/konflux-rbac/staging/base/kustomization.yaml
Labels: lgtm, approved

#6290 Configure RH02 cluster to test static PVMs
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
Labels: lgtm, approved

#6293 fix: use newer version of OSP (tag "next")
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
Labels: lgtm, approved

#6281 fix-up(PVO11Y-4681): Fix typo - pipelinerun -> pipelineruns
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, ok-to-test, approved

#6261 Add enable enum feature
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, ok-to-test, approved

#6294 chore: promote konflux-ui
  components/konflux-ui/production/base/kustomization.yaml
Labels: lgtm, approved

#6266 fix-up(PVO11Y-4652): Keep node cpu label
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, ok-to-test, approved

#6280 add restrict-binding-system-authenticated Policy
  components/konflux-rbac/policies/restrict-binding-system-authenticated/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
  components/konflux-rbac/policies/restrict-binding-system-authenticated/.chainsaw-test/chainsaw-test.yaml
  components/konflux-rbac/policies/restrict-binding-system-authenticated/.chainsaw-test/resources/invalid-systemauthenticated-rolebinding.yaml
  components/konflux-rbac/policies/restrict-binding-system-authenticated/.chainsaw-test/resources/tenant-namespace.yaml
  components/konflux-rbac/policies/restrict-binding-system-authenticated/.chainsaw-test/resources/valid-systemauthenticated-rolebinding.yaml
  components/konflux-rbac/policies/restrict-binding-system-authenticated/kustomization.yaml
  components/konflux-rbac/policies/restrict-binding-system-authenticated/kyverno_rbac.yaml
  components/konflux-rbac/policies/restrict-binding-system-authenticated/validate-restrict-binding-system-authenticated-clusterpolicy.yaml
  components/konflux-rbac/staging/base/kustomization.yaml
Labels: lgtm, approved

#6278 konflux-rbac: disallow certain groups in rolebindings
  components/konflux-rbac/policies/validate-rolebindings/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
  components/konflux-rbac/policies/validate-rolebindings/.chainsaw-test/chainsaw-test.yaml
  components/konflux-rbac/policies/validate-rolebindings/.chainsaw-test/resources/masters-rolebinding.yaml
  components/konflux-rbac/policies/validate-rolebindings/.chainsaw-test/resources/rolebinding.yaml
  components/konflux-rbac/policies/validate-rolebindings/.chainsaw-test/resources/tenant-namespace.yaml
  components/konflux-rbac/policies/validate-rolebindings/invalid-subjects.yaml
  components/konflux-rbac/policies/validate-rolebindings/kustomization.yaml
  components/konflux-rbac/policies/validate-rolebindings/kyverno_rbac.yaml
  components/konflux-rbac/staging/base/kustomization.yaml
Labels: lgtm, approved

#6303 Configure RH01 cluster to test static PVMs (#6290)
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#6256 build-service update
  components/build-service/development/kustomization.yaml
  components/build-service/staging/base/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#6309 Add one s390x static machine to rh02 from Tokyo DC
  components/multi-platform-controller/production/kflux-prd-rh02/external-secrets.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
Labels: lgtm, approved

#6172 Expose etcd_disk_defrag_inflight for cluster capacity monitoring
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, ok-to-test, approved

#6276 Update Results v0.14.0-3 staging
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#6317 update mintmaker controller
  components/mintmaker/development/kustomization.yaml
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#6288 fix: use devel tag instead of commit_id tag for the pipeline bundles
  components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
Labels: lgtm, approved

#6327 Change s390x and ppc64le to static VMs on RH02
  components/multi-platform-controller/production/kflux-prd-rh02/external-secrets.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
Labels: lgtm, approved

#6329 rbac: disallow certain groups from rolebindings in prod
  components/konflux-rbac/production/base/kustomization.yaml
Labels: lgtm, approved

#6316 Add temporary permissions to the nginx proxy sa
  components/konflux-ui/staging/base/proxy/proxy.yaml
Labels: lgtm, approved

#6295 etcd-shield: deploy to staging
  argo-cd-apps/base/member/infra-deployments/etcd-shield/etcd-shield.yaml
  argo-cd-apps/base/member/infra-deployments/etcd-shield/kustomization.yaml
  components/etcd-shield/OWNERS
  components/etcd-shield/base/config.yaml
  components/etcd-shield/base/deployment.yaml
  components/etcd-shield/base/etcd_shield_alerts.yaml
  components/etcd-shield/base/kustomization.yaml
  components/etcd-shield/base/ns.yaml
  components/etcd-shield/base/rbac.yaml
  components/etcd-shield/base/service.yaml
  components/etcd-shield/base/webhook.yaml
  components/etcd-shield/staging/stone-stage-p01/kustomization.yaml
  components/etcd-shield/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#6334 etcd-shield: fix ApplicationSet name
  argo-cd-apps/base/member/infra-deployments/etcd-shield/etcd-shield.yaml
Labels: lgtm, approved

#6333 Add first static s390x VM to rh03
  components/multi-platform-controller/production/kflux-prd-rh03/external-secrets.yaml
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
Labels: approved

#6335 Remove s390x from dynamic platforms
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
Labels: approved

#6320 Update Results v0.14.0-4 prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#6253 Cleanup Knative Eventing deployment folders
  argo-cd-apps/base/member/infra-deployments/knative-eventing/knative-eventing.yaml
  components/knative-eventing/production/stone-prd-m01/kustomization.yaml
  components/knative-eventing/production/stone-prd-rh01/kustomization.yaml
Labels: lgtm, approved

#6339 etcd-shield: fixes
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  components/etcd-shield/base/etcd_shield_alerts.yaml
Labels: lgtm, approved

#6340 Add static s390x hosts for stone-prd-rh01
  components/multi-platform-controller/production/stone-prd-rh01/external-secrets.yaml
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#6341 Change s390x and ppc64le to static VMs on RH01
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#6342 konflux-rbac: remove unnecessary testing resource
  components/konflux-rbac/policies/validate-rolebindings/.chainsaw-test/resources/masters-rolebinding.yaml
Labels: lgtm, approved

#6348 Remove P02 larger dynamic s390x and ppc64le platforms
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: approved

#6345 optimize kyverno policies
  components/konflux-rbac/policies/restrict-binding-system-authenticated/validate-restrict-binding-system-authenticated-clusterpolicy.yaml
  components/konflux-rbac/policies/validate-rolebindings/invalid-subjects.yaml
Labels: lgtm, approved

#6344 promote restrict-binding-system-authenticated Policy to prod
  components/konflux-rbac/production/base/kustomization.yaml
Labels: lgtm, approved

#6351 Add one more s390x VM to rh01
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#6349 Remove IBM from stone-prod-p01
  components/multi-platform-controller/production-downstream/stone-prod-p01/host-config.yaml
Labels: lgtm, approved

#6353 test correct default pipelines security group in kflux-rh02
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/kustomization.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/temp-set-pipelines-default-scc.yaml
Labels: lgtm, approved

#6337 KubeArchive: bump to v1, breaking changes
  components/authentication/base/everyone-can-view.yaml
  components/kubearchive/base/kubearchive-config.yaml
  components/kubearchive/base/kubearchive-maintainer.yaml
  components/kubearchive/base/kustomization.yaml
  components/kubearchive/policies/.chainsaw-test/resources/actual-kubeconfig-archive.yaml
  components/kubearchive/policies/.chainsaw-test/resources/expected-kubearchiveconfig.yaml
  components/kubearchive/policies/.chainsaw-test/resources/kubearchive-crd.yaml
  components/kubearchive/policies/bootstrap-namespace.yaml
  components/kubearchive/policies/kyverno_rbac.yaml
  components/kubearchive/policies/resources/expected-kubearchiveconfig-konflux.yaml
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#6365 Update rh03 host config
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
Labels: lgtm, approved

#6367 Fix security group on rh03
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
Labels: lgtm, approved

#6368 Add s390x static VMs to rh03
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
Labels: approved

#6369 Fix AWS key name for all AWS architectures
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
Labels: lgtm, approved

#6370 Re-create all s390x VMs for rh03
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
Labels: approved

#6371 Add all remaining rh01 ppc VMs
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
Labels: approved

#6374 Bump mintmaker on stage
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#6376 etcd-shield: enable in production
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
Labels: lgtm, approved

#6379 Test new e1080 PPC static VMs for stage-p02
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: lgtm, approved

#6380 Builder serviceaccounts should be able to inspect events
  components/konflux-rbac/production/base/konflux-builder-bot-actions.yaml
Labels: lgtm, approved

#6387 Increase releaseplan and releaseplanadmission quotas
  components/sandbox/tiers/production/appstudio/kustomization.yaml
  components/sandbox/tiers/production/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-tenant-2654763221-2654763221.yaml
  components/sandbox/tiers/production/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/production/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-admin-607699003-1621311634.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-607699003-2781377949.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-contributor-607699003-923669109.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-maintainer-607699003-664949573.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-tenant-607699003-2654763221.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-viewer-607699003-3768244154.yaml
  components/sandbox/tiers/production/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/production/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-admin-1081386182-1621311634.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-1081386182-2781377949.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-1081386182-923669109.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-1081386182-664949573.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-1081386182-2654763221.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-1081386182-3768244154.yaml
  components/sandbox/tiers/src/appstudio/ns_tenant.yaml
  components/sandbox/tiers/src/appstudiolarge/based_on_tier.yaml
  components/sandbox/tiers/src/appstudioxlarge/based_on_tier.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-tenant-2654763221-2654763221.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-admin-607699003-1621311634.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-607699003-2781377949.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-contributor-607699003-923669109.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-maintainer-607699003-664949573.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-tenant-607699003-2654763221.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-viewer-607699003-3768244154.yaml
  components/sandbox/tiers/staging/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-admin-1081386182-1621311634.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-1081386182-2781377949.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-1081386182-923669109.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-1081386182-664949573.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-1081386182-2654763221.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-1081386182-3768244154.yaml
Labels: lgtm, approved

#6385 Switch to e1080 PPC VMs for prod-p02
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: lgtm, approved

#6378 fix(PVO11Y-4653): Add es01 clusterDir for monitoring-workload-prometheus
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml
Labels: lgtm, approved

#6388 etcd-shield: lower trigger thresholds
  components/etcd-shield/base/etcd_shield_alerts.yaml
  components/etcd-shield/production/base/etcd_shield_alerts.yaml
Labels: lgtm, approved

#6383 disable KubeSaw's autoapproval for prod rh01
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/toolchainconfig.yaml
Labels: lgtm, approved

#6372 promote bootstrap-tenant-namespace policy to prod
  components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
  components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-test.yaml
  components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-existing-resources.yaml
  components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/expected-resources.yaml
  components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.kyverno-test/kyverno-test.yaml
  components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-configmap_trusted-ca.yml
  components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-networkpolicy_allow-from-console-namespaces.yml
  components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-networkpolicy_allow-from-olm-namespaces.yml
  components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-networkpolicy_allow-from-openshift-ingress.yml
  components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-networkpolicy_allow-from-openshift-monitoring.yml
  components/konflux-rbac/production/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-networkpolicy_allow-same-namespace.yml
  components/konflux-rbac/production/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-clusterpolicy.yaml
  components/konflux-rbac/production/policies/bootstrap-tenant-namespace/kyverno_rbac.yaml
Labels: lgtm, approved

#6373 add list RoleBindings to maintainers and contributors in staging
  components/konflux-rbac/staging/base/konflux-contributor-user-actions.yaml
  components/konflux-rbac/staging/base/konflux-maintainer-user-actions.yaml
Labels: lgtm, approved

#6389 Bump kubelinter
  .github/workflows/kube-linter.yaml
  .kube-linter.yaml
Labels: lgtm, approved

#6391 Removing power-monitoring from all-clusters directory for Konflux
  argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/power-monitoring/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/power-monitoring/power-monitoring.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
  components/monitoring/grafana/base/dashboards/kustomization.yaml
Labels: lgtm, approved

#6394 Increase Kyverno UpdateRequests threshold
  components/kyverno/development/kyverno-helm-values.yaml
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#6357 Revert "test correct default pipelines security group in kflux-rh02"
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/kustomization.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/temp-set-pipelines-default-scc.yaml
Labels: lgtm, approved

#6390 dev: Increase Argo's application controller resource limits
  hack/deploy-argocd.sh
Labels: lgtm, approved

#6393 Update KubeArchive to fix an error
  components/kubearchive/base/kubearchive-config.yaml
  components/kubearchive/base/kubearchive-maintainer.yaml
  components/kubearchive/base/kustomization.yaml
Labels: lgtm, approved

#6400 Reset `ec-task-policy` to floating tag.
  components/enterprise-contract/ecp.yaml
Labels: lgtm, approved

#6410 etcd-shield: decrease severity level to warning
  components/etcd-shield/base/etcd_shield_alerts.yaml
  components/etcd-shield/production/base/etcd_shield_alerts.yaml
Labels: lgtm, approved

#6415 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#6405 Disable Tekton Pruner
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#6406 perfscale/grafana: Extending the Grafana dashboard(controllers-overview) to include data from more controllers
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#6420 etcd-shield: decrease thresholds by 10%
  components/etcd-shield/base/etcd_shield_alerts.yaml
  components/etcd-shield/production/base/etcd_shield_alerts.yaml
Labels: approved

#6404 etcd-shield: remove cluster-monitoring label
  components/etcd-shield/base/ns.yaml
  components/etcd-shield/production/base/ns.yaml
Labels: lgtm, approved

#6422 Etcd shield updates
  components/etcd-shield/base/deployment.yaml
  components/etcd-shield/production/base/deployment.yaml
Labels: lgtm, approved

#6421 MintMaker weekly release: promote stage to prod
  components/mintmaker/production/base/kustomization.yaml
Labels: lgtm, approved

#6426 Revert "Disable Tekton Pruner"
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#6432 update o11y dsexporter in stage
  components/monitoring/grafana/staging/kustomization.yaml
Labels: lgtm, approved

#6427 fix(PVO11Y-4776): Include new cpu label
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, ok-to-test, approved

#6441 Remove rh02 larger dynamic s390x and ppc64le platforms
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
Labels: lgtm, approved

#6444 Replace static-1 ppc machine on ocp-p01 cluster
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#6451 Update stage-p01 to use IBM stage account s390x VM
  components/multi-platform-controller/staging-downstream/external-secrets.yaml
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#6449 Add testplatform ProviderConfig in Staging
  components/crossplane-control-plane/staging/kustomization.yaml
  components/crossplane-control-plane/staging/testplatform-provider-config.yaml
Labels: lgtm, ok-to-test, approved

#6458 bump resources for kyverno
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#6461 fix: promote integration-service to get hotfix in production
  components/integration/development/kustomization.yaml
  components/integration/production/base/kustomization.yaml
  components/integration/staging/base/kustomization.yaml
Labels: lgtm, approved

#6462 chore: promote integration-service
  components/integration/development/kustomization.yaml
  components/integration/production/base/kustomization.yaml
  components/integration/staging/base/kustomization.yaml
Labels: lgtm, approved

#6460 Update stage-p01 to use IBM stage account PPC VM
  components/multi-platform-controller/staging-downstream/external-secrets.yaml
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#6467 Upgrade etcd-defrag image to latest revision
  configs/etcd-defrag/base/cronjob.yaml
Labels: lgtm, approved

#6468 feat(PVO11Y-4784): Include new etcd-shield related metrics
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, ok-to-test, approved

#6476 Ensure directory is present in new-cluster playbook
  hack/new-cluster/tasks/components.yaml
Labels: lgtm, approved

#6511 Remove pulp-access-controller from development
  argo-cd-apps/overlays/development/delete-applications.yaml
Labels: approved

#6494 fix kyverno dev overlay configuration
  components/kyverno/development/kustomization.yaml
  components/kyverno/development/kyverno-helm-values.yaml
Labels: lgtm, approved
