Repository redhat-appstudio/infra-deployments, pull requests merged in 2025-01, with the labels that each got.

#5196 KFLUXINFRA-1154: Configure Backup for kflux-prd-rh02
  components/backup/production/kflux-prd-rh02/backup-s3-credentials-patch.yaml
  components/backup/production/kflux-prd-rh02/backup-tenants-schedule.yaml
  components/backup/production/kflux-prd-rh02/dpa-bucket-patch.yaml
  components/backup/production/kflux-prd-rh02/dpa-kmskeyid-patch.yaml
  components/backup/production/kflux-prd-rh02/kustomization.yaml
Labels: lgtm, approved

#5223 chore(KFLUXVNGD-136): export replica count for project-controller
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#5227 Test custom IBM volumes size feature
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#5228 KFLUXINFRA-1129: In-Cluster Grafana Dashboard Access
  components/authentication/base/grafana-view-only.yaml
Labels: lgtm, approved

#5231 KONFLUX-5693 - Upgrade logging operator in prod
  components/monitoring/logging/production/base/configure-logging/configure-log-collectors.yaml
  components/monitoring/logging/production/base/configure-logging/configure-logforwarder.yaml
  components/monitoring/logging/production/base/configure-logging/kustomization.yaml
  components/monitoring/logging/production/base/external-secrets/kustomization.yaml
  components/monitoring/logging/production/base/external-secrets/splunk-log-forwarder-external-secrets.yaml
  components/monitoring/logging/production/base/install-logging-operator.yaml
  components/monitoring/logging/production/base/kustomization.yaml
  components/monitoring/logging/production/base/logging-operator-prerequisite/kustomization.yaml
  components/monitoring/logging/production/base/logging-operator-prerequisite/operatorgroup.yaml
  components/monitoring/logging/production/base/patches/configure-logforwarder-compression-patch.yaml
Labels: lgtm, approved

#5229 chore(KFLUXVNGD-136): export label deployment
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#5233 KONFLUX-5670: Disable NVMe Disk Configuration
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
Labels: lgtm, approved

#5234 Temporarily increase MPC memory on rh01
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/manager_resources_patch.yaml
Labels: approved

#5232 chore(KFLUXVNGD-93): Grant appstudio-pipelines-runner permissions to manage namespaces
  components/sandbox/toolchain-member-operator/base/rbac/appstudio-pipelines-runner.yaml
Labels: lgtm, approved

#5238 Update Results ext prod clusters
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#5240 Adding everyone from PV O11Y to the proper OWNERS files
  components/monitoring/OWNERS
  components/tracing/OWNERS
Labels: lgtm, approved

#5243 Switch back to local Minio in development
  components/pipeline-service/development/dev-only-pipeline-service-storage-configuration.yaml
  components/pipeline-service/development/kustomization.yaml
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  hack/secret-creator/create-plnsvc-secrets.sh
Labels: lgtm, approved

#5237 Multi platform controller update
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#5244 KONFLUX-5670: Enable NVMe Disk Configuration
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
Labels: lgtm, approved

#5246 Ibm multi prod rh02 ppc64le static nodes
  components/multi-platform-controller/production/kflux-prd-rh02/external-secrets.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
Labels: approved

#5242 enterprise contract update
  components/enterprise-contract/ecp.yaml
  components/enterprise-contract/kustomization.yaml
Labels: lgtm, approved

#5248 multi-platform-controller update
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#5252 Fix AWS host config for rh02
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
Labels: lgtm, approved

#5254 chore(KFLUXVNGD-160): project-controller prod update
  components/project-controller/production/kustomization.yaml
Labels: lgtm, approved

#5255 temporary disable broken node
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
Labels: lgtm, approved

#5258 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#5259 Revert "Promote integration-service from staging to production"
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#5263 Promote konflux-ui image from stage to prod
  components/konflux-ui/production/base/kustomization.yaml
Labels: approved

#5203 add kyverno to staging
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kyverno/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  components/kyverno/staging/values.yaml
Labels: lgtm, approved

#5270 revert production patch for notification-service
  components/notification-controller/production/topic_region_add.yaml
Labels: lgtm, approved

#5265 Remove CPU limits from quotas and limitranges
  components/sandbox/tiers/src/appstudio/ns_tenant.yaml
  components/sandbox/tiers/src/appstudiolarge/based_on_tier.yaml
  components/sandbox/tiers/src/appstudioxlarge/based_on_tier.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-tenant-3054647054-3054647054.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-admin-2084392855-849337768.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-2084392855-593233715.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-contributor-2084392855-829105171.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-maintainer-2084392855-341231795.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-tenant-2084392855-3054647054.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-viewer-2084392855-4256863455.yaml
  components/sandbox/tiers/staging/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-admin-3195294905-849337768.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-3195294905-593233715.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-3195294905-829105171.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-3195294905-341231795.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-3195294905-3054647054.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-3195294905-4256863455.yaml
Labels: lgtm, approved

#5273 Remove cpu limits from quotas and limitranges
  components/sandbox/tiers/production/appstudio/kustomization.yaml
  components/sandbox/tiers/production/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-tenant-3054647054-3054647054.yaml
  components/sandbox/tiers/production/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/production/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-admin-2084392855-849337768.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-2084392855-593233715.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-contributor-2084392855-829105171.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-maintainer-2084392855-341231795.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-tenant-2084392855-3054647054.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-viewer-2084392855-4256863455.yaml
  components/sandbox/tiers/production/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/production/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-admin-3195294905-849337768.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-3195294905-593233715.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-3195294905-829105171.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-3195294905-341231795.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-3195294905-3054647054.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-3195294905-4256863455.yaml
Labels: lgtm, approved

#5274 kyverno: specify values inline
  argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
  components/kyverno/staging/values.yaml
Labels: lgtm, approved

#5277 chore(KFLUXVNGD-164): promote notification controller to production
  components/notification-controller/production/kustomization.yaml
  components/notification-controller/production/topic_region_add.yaml
Labels: lgtm, approved

#5269 Multi platform controller
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#5276 kyverno: delete security context from policy reports cleanup job
  argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
Labels: lgtm, approved

#4975 Update KubeArchive version
  components/kubearchive/base/alternative-service.yaml
  components/kubearchive/base/kustomization.yaml
Labels: needs-ok-to-test, approved

#5282 Increase Build Service memory request to be bigger than actual average usage
  components/build-service/production/base/manager_resources_patch.yaml
  components/build-service/staging/base/manager_resources_patch.yaml
Labels: lgtm, approved

#5163 add namespace-lister deployment to staging
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/namespace-lister/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/namespace-lister/namespace-lister.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  components/namespace-lister/OWNERS
  components/namespace-lister/base/deployment.yaml
  components/namespace-lister/base/kustomization.yaml
  components/namespace-lister/base/namespace.yaml
  components/namespace-lister/base/nginx.conf
  components/namespace-lister/base/patches/with-header-auth.yaml
  components/namespace-lister/base/proxy.yaml
  components/namespace-lister/base/rbac.yaml
  components/namespace-lister/base/route.yaml
  components/namespace-lister/base/service.yaml
  components/namespace-lister/staging/stone-stg-rh01/kustomization.yaml
  components/namespace-lister/staging/stone-stg-rh01/rbac.yaml
Labels: lgtm, approved

#5284 Promote konflux-ui from stage to prod
  components/konflux-ui/production/base/kustomization.yaml
Labels: approved

#5275 fix: deploy kyverno only on member clusters
  argo-cd-apps/base/member/infra-deployments/kyverno/kustomization.yaml
Labels: lgtm, approved

#5264 [OCP] Create new ppc64le flavor with larger disk
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5286 kyverno: use server-side apply
  argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
Labels: lgtm, approved

#5288 namespace-lister: disable configmap name suffix hashing
  components/namespace-lister/base/kustomization.yaml
Labels: lgtm, approved

#5280 Promote new mintmaker image to prod
  components/mintmaker/production/base/kustomization.yaml
Labels: lgtm, approved

#5294 feat(KFLUXDP-19): Move dora metrics image to konflux-ci org
  components/dora-metrics/development/kustomization.yaml
  components/dora-metrics/production/kustomization.yaml
  components/dora-metrics/staging/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#5295 Promote konflux-ui from stage to prod
  components/konflux-ui/production/base/kustomization.yaml
Labels: approved

#5298 Fix config typo
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5300 stage: Add RBAC details to konflux-public-info cm
  components/konflux-info/staging/stone-stg-rh01/info.json
Labels: lgtm, approved

#5303 Giving me temp access to test rolebinding migration
  components/workspaces/staging/stone-stg-rh01/kustomization.yaml
  components/workspaces/staging/stone-stg-rh01/temp-dperaza-rbac.yaml
Labels: lgtm, approved

#5302 Bump hypershift-aws-template to 0.1.4
  components/cluster-as-a-service/base/clustertemplates.yaml
Labels: lgtm, approved

#5287 Fix staging kubearchive external secret
  components/kubearchive/staging/database-secret.yaml
Labels: lgtm, approved

#5314 remove rhopp from OWNERS
  OWNERS
Labels: lgtm, approved

#5313 Push refactored version of MintMaker to stage
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5271 Add CPU optimized host configs for ppc64le and s390x
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, ok-to-test, approved

#5311 remove the namespace-lister's test proxy
  components/namespace-lister/base/kustomization.yaml
  components/namespace-lister/base/nginx.conf
  components/namespace-lister/base/proxy.yaml
  components/namespace-lister/base/route.yaml
  components/namespace-lister/base/service.yaml
Labels: lgtm, approved

#5318 Update refs to Minio images
  components/pipeline-service/development/kustomization.yaml
Labels: lgtm, approved

#5320 Promote a new MintMaker stage version
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5321 mintmaker staging: update mintmaker manifests
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5301 feat(STONEINTG-948): Migrate redhat-appstudio/clair-in-ci
  components/konflux-ci/base/repository.yaml
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#5235 feat(KONFLUX-5451): Expose metrics for Performance alerts
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#5322 Deploy konflux-rbac to public staging
  argo-cd-apps/base/member/infra-deployments/konflux-rbac/konflux-rbac.yaml
  argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
  components/konflux-rbac/staging/base/konflux-admin-user-actions.yaml
  components/konflux-rbac/staging/base/konflux-contributor-user-actions.yaml
  components/konflux-rbac/staging/base/konflux-maintainer-user-actions.yaml
  components/konflux-rbac/staging/base/kustomization.yaml
  components/konflux-rbac/staging/empty-base/kustomization.yaml
  components/konflux-rbac/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#5324 [Staging] Optimizing Vector Configuration to avoid missing logs
  components/vector-tekton-logs-collector/development/vector-helm-values.yaml
  components/vector-tekton-logs-collector/staging/vector-helm-values.yaml
Labels: lgtm, approved

#5330 Remove zregvart as owner
  OWNERS
  components/enterprise-contract/OWNERS
Labels: lgtm, approved

#5336 chore(KFLUXVNGD-167): project-controller to prod
  components/project-controller/production/kustomization.yaml
Labels: lgtm, approved

#5337 Promote new version of MintMaker in stage
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5334 [Prod] Optimizing Vector Configuration to avoid missing logs
  components/vector-tekton-logs-collector/production/vector-helm-values.yaml
Labels: lgtm, approved

#5297 integrate konflux-ui with namespace-lister
  components/konflux-ui/staging/base/proxy/nginx.conf
  components/namespace-lister/base/kustomization.yaml
  components/namespace-lister/base/network_policy.yaml
  components/namespace-lister/base/patches/with-header-auth-email.yaml
  components/namespace-lister/base/service.yaml
  components/namespace-lister/staging/stone-stg-rh01/kustomization.yaml
  components/namespace-lister/staging/stone-stg-rh01/rbac.yaml
Labels: lgtm, approved

#5329 Promote latest MPC version from stg to prod
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
Labels: lgtm, approved

#5304 Increase memory for Eventing mt-broker-controller
  components/knative-eventing/base/kustomization.yaml
Labels: lgtm, approved

#5347 Promote MintMaker stage
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5344 KONFLUX-5674: Adding Resource Requests and Limits
  components/external-secrets-operator/base/operator-config.yaml
  components/external-secrets-operator/staging/kustomization.yaml
  components/external-secrets-operator/staging/resource-requests.patch.yaml
Labels: lgtm, approved

#5339 Bump hypershift-aws-template to 0.1.5
  components/cluster-as-a-service/base/clustertemplates.yaml
Labels: lgtm, approved

#5345 Increase line size for vector tekton log collection
  components/vector-tekton-logs-collector/development/vector-helm-values.yaml
  components/vector-tekton-logs-collector/staging/vector-helm-values.yaml
Labels: lgtm, approved

#5349 Promote MintMaker to stage
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5350 Remove limit for one knative eventing component
  components/knative-eventing/base/kustomization.yaml
Labels: lgtm, approved

#5341 Increase ephemeral storage quota
  components/sandbox/tiers/production/appstudio/kustomization.yaml
  components/sandbox/tiers/production/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-tenant-3035149355-3035149355.yaml
  components/sandbox/tiers/production/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/production/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-admin-2128555184-1611646139.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-2128555184-593233715.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-contributor-2128555184-3265408548.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-maintainer-2128555184-1881194462.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-tenant-2128555184-3035149355.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-viewer-2128555184-3768244154.yaml
  components/sandbox/tiers/production/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/production/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-admin-2094191734-1611646139.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-2094191734-593233715.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-2094191734-3265408548.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-2094191734-1881194462.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-2094191734-3035149355.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-2094191734-3768244154.yaml
  components/sandbox/tiers/src/appstudio/ns_tenant.yaml
  components/sandbox/tiers/src/appstudiolarge/based_on_tier.yaml
  components/sandbox/tiers/src/appstudioxlarge/based_on_tier.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-tenant-3035149355-3035149355.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-admin-2128555184-1611646139.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-2128555184-593233715.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-contributor-2128555184-3265408548.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-maintainer-2128555184-1881194462.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-tenant-2128555184-3035149355.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-viewer-2128555184-3768244154.yaml
  components/sandbox/tiers/staging/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-admin-2094191734-1611646139.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-2094191734-593233715.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-2094191734-3265408548.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-2094191734-1881194462.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-2094191734-3035149355.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-2094191734-3768244154.yaml
Labels: lgtm, approved

#5355 [OCP] Bumping ppc disk from 200 to 400 GB
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5340 Fixing application sync complaint about workspaces-system
  argo-cd-apps/base/member/infra-deployments/workspaces/workspaces.yaml
  components/workspaces/staging/stone-stage-p01/kustomization.yaml
  components/workspaces/staging/stone-stg-host/kustomization.yaml
  components/workspaces/team/base/kustomization.yaml
  components/workspaces/team/base/workspaces-team-role.yaml
  components/workspaces/team/base/workspaces-team-rolebinding.yaml
Labels: lgtm, approved

#5343 fix: add pod reader role to appstudio-pipeline SA
  components/konflux-ci/base/kustomization.yaml
  components/konflux-ci/base/pod-logs-reader-role.yaml
  components/konflux-ci/base/pod-logs-reader-rolebinding.yaml
Labels: lgtm, approved

#5359 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#5360 Promote new version of MintMaker to stage
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5323 Upgrade KubeArchive to v0.9.0: TLS fix
  components/kubearchive/base/kustomization.yaml
  components/kubearchive/development/postgresql.yaml
Labels: lgtm, ok-to-test, approved

#5365 Promote MintMaker stage
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5362 Increase application-service requests nearer to current usage
  components/has/k-components/manager-resources/manager_resources_patch.yaml
Labels: lgtm, approved

#5361 bump namespace lister
  components/namespace-lister/base/deployment.yaml
  components/namespace-lister/base/kustomization.yaml
Labels: lgtm, approved

#5367 [OCP] Increasing linux-d400-large-ppc64le.max-instances to 30
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5371 fix memory request for sandbox's member-operator
  components/sandbox/toolchain-member-operator/production/patch_resources.yaml
  components/sandbox/toolchain-member-operator/staging/patch_resources.yaml
Labels: lgtm, approved

#5372 set cpu request for sandbox's member-operator
  components/sandbox/toolchain-member-operator/production/patch_resources.yaml
  components/sandbox/toolchain-member-operator/staging/patch_resources.yaml
Labels: lgtm, approved

#5370 namespace-lister: disable https temporarily
  components/namespace-lister/base/deployment.yaml
Labels: lgtm, approved

#5369 increase memory request for sandbox's host-operator
  components/sandbox/toolchain-host-operator/production/kflux-ocp-p01/kustomization.yaml
  components/sandbox/toolchain-host-operator/production/kflux-ocp-p01/patch_resources.yaml
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/kustomization.yaml
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/patch_resources.yaml
  components/sandbox/toolchain-host-operator/production/stone-prod-p01/kustomization.yaml
  components/sandbox/toolchain-host-operator/production/stone-prod-p01/patch_resources.yaml
  components/sandbox/toolchain-host-operator/production/stone-prod-p02/kustomization.yaml
  components/sandbox/toolchain-host-operator/production/stone-prod-p02/patch_resources.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/kustomization.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/patch_resources.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/kustomization.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/patch_resources.yaml
Labels: lgtm, approved

#5346 remove jduimovich from OWNERS
  OWNERS
Labels: lgtm, approved

#5374 deploy new version of namespace-lister
  components/namespace-lister/base/kustomization.yaml
Labels: lgtm, approved

#5378 mintmaker: add configmaps and secrets permissions for mintmaker team
  components/mintmaker/base/rbac/mintmaker-team.yaml
Labels: lgtm, approved

#5380 Remove invalid fields from monitoring kustomize transformation
  components/monitoring/grafana/base/dashboards/cm-dashboard.yaml
Labels: lgtm, approved

#5348 KFLUXINFRA-1211: Upgrade OpenShift GitOps to 1.15
  components/openshift-gitops/subscription.yaml
Labels: lgtm, approved

#5363 Update HAS owners
  components/has/OWNERS
Labels: lgtm, approved

#5377 feat: Add quay secret to push test artifacts
  components/konflux-ci/base/external-secrets/kustomization.yaml
  components/konflux-ci/base/external-secrets/test-artifacts-push-secret.yaml
Labels: lgtm, approved

#5392 Promote MintMaker prod
  components/mintmaker/development/kustomization.yaml
  components/mintmaker/production/base/kustomization.yaml
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5397 Promote MintMaker stage
  components/mintmaker/development/kustomization.yaml
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5402 expose metrics for namespace lister
  components/namespace-lister/base/kustomization.yaml
  components/namespace-lister/base/metrics/kustomization.yaml
  components/namespace-lister/base/metrics/monitor.yaml
  components/namespace-lister/base/metrics/service-account.yaml
Labels: lgtm, approved

#5328 Add maruiz93 and mafh314 as owners of kubearchive and knative
  components/knative-eventing/OWNERS
  components/kubearchive/OWNERS
Labels: lgtm, needs-ok-to-test, approved

#5403 KONFLUX-5674: Setting Resource Requests and Limits [ESO]
  components/external-secrets-operator/base/operator-config.yaml
  components/external-secrets-operator/base/subscription.yaml
  components/external-secrets-operator/staging/kustomization.yaml
  components/external-secrets-operator/staging/resource-requests.patch.yaml
  components/external-secrets-operator/staging/starting-csv-patch.yaml
Labels: lgtm, approved

#5400 Improve MintMaker memory resources
  components/mintmaker/production/base/manager_patch.yaml
Labels: lgtm, approved

#5404 Bump mintmaker-renovate-image
  components/mintmaker/production/base/kustomization.yaml
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5408 Promote MintMaker to stage
  components/mintmaker/development/kustomization.yaml
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5409 Update OSP on staging
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5411 Update OSP version on prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#5358 Revert "KONFLUX-5670: Enable NVMe Disk Configuration (#5244)"
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
Labels: lgtm, approved

#5412 namespace-lister: allow incoming traffic from openshift-monitoring
  components/namespace-lister/base/network_policy.yaml
Labels: lgtm, approved

#5415 PVO11Y-4603 Deploy cluster observability operator
  components/monitoring/prometheus/base/observability-operator/observability-operator.yaml
Labels: lgtm, approved

#5406 Move pipelines remote resolvers to statefulset
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5410 improve namespace-lister monitoring manifests
  components/namespace-lister/base/metrics/kustomization.yaml
  components/namespace-lister/base/metrics/rbac.yaml
  components/namespace-lister/base/metrics/service-account.yaml
Labels: lgtm, approved

#5417 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#5416 kvyerno: move helm values to file
  argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
  components/kyverno/OWNERS
  components/kyverno/staging/kyverno-values.yaml
Labels: lgtm, approved

#5418 namespace-lister: label service
  components/namespace-lister/base/service.yaml
Labels: lgtm, approved

#5421 konflux-ci: add dockerhub pull secret
  components/konflux-ci/base/external-secrets/dockerhub-pull-secret.yaml
  components/konflux-ci/base/external-secrets/kustomization.yaml
  components/konflux-ci/base/serviceaccount.yaml
Labels: lgtm, approved

#5413 unset securityContext for kyverno's components
  components/kyverno/staging/kyverno-values.yaml
Labels: lgtm, approved

#5414 kyverno: set fullnameOverride and namespaceOverride to konflux-kyverno
  components/kyverno/staging/kyverno-values.yaml
Labels: lgtm, approved

#5424 fix: the target name of the test-artifacts-push-secret
  components/konflux-ci/base/external-secrets/test-artifacts-push-secret.yaml
Labels: lgtm, approved

#5425 Update internal prods with recent MPC version
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5373 Namespace-lister: use https instead of http
  components/konflux-ui/staging/base/proxy/nginx.conf
  components/namespace-lister/base/deployment.yaml
  components/namespace-lister/base/service.yaml
Labels: lgtm, approved

#5430 namespace-lister: provide a tls config to ServiceMonitor
  components/namespace-lister/base/metrics/monitor.yaml
Labels: lgtm, approved

#5429 PVO11Y-4603 Install Cluster Observability Operator in stage and prod
  components/monitoring/prometheus/README.md
  components/monitoring/prometheus/production/base/kustomization.yaml
  components/monitoring/prometheus/staging/base/kustomization.yaml
  components/monitoring/prometheus/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#5432 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#5433 fix: the secret key name and use `_` instead
  components/konflux-ci/base/external-secrets/test-artifacts-push-secret.yaml
Labels: lgtm, approved

#5435 fix: remove template part from the external secret
  components/konflux-ci/base/external-secrets/test-artifacts-push-secret.yaml
Labels: lgtm, approved

#5439 bump namespace-lister in staging
  components/namespace-lister/base/deployment.yaml
  components/namespace-lister/base/kustomization.yaml
Labels: lgtm, approved

#5443 increase namespace-lister resources
  components/namespace-lister/base/deployment.yaml
Labels: lgtm, approved
