Repository redhat-appstudio/infra-deployments, pull requests merged in 2025-09, with the labels that each got.

#7908 KFLUXINFRA-2007: Multi Platform Configuration for IBMZ and PPC Nodes (PenTest Cluster)
  components/kueue/production/pentest-p01/queue-config/cluster-queue.yaml
  components/multi-platform-controller/production-downstream/pentest-p01/external-secrets.yaml
  components/multi-platform-controller/production-downstream/pentest-p01/host-config.yaml
Labels: lgtm, approved

#7909 fix(KFLUXSPRT-4896): increase pod requests/limits
  components/release/base/cronjobs/remove-expired-releases.yaml
Labels: lgtm, approved

#7917 Eventing: change kflux-prd-rh03 image to be verbose
  components/knative-eventing/production/kflux-prd-rh03/kustomization.yaml
Labels: lgtm, approved

#7932 sandbox: remove member sub from prd-es01
  components/sandbox/toolchain-member-operator/production/kflux-prd-es01/kustomization.yaml
Labels: lgtm, approved

#7935 sandbox: remove host sub from ocp-p01
  components/sandbox/toolchain-host-operator/production/kflux-ocp-p01/kustomization.yaml
Labels: lgtm, approved

#7915 fix: use pac latest images in development overlays
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
Labels: lgtm, approved

#7941 Fix readd grafana SA to staging
  components/vector-kubearchive-log-collector/staging/base/kustomization.yaml
  components/vector-kubearchive-log-collector/staging/base/sa.yaml
Labels: lgtm, approved

#7944 Promote tekton-kueue to production
  components/kueue/production/base/tekton-kueue/config.yaml
  components/kueue/production/base/tekton-kueue/kustomization.yaml
  components/kueue/production/kflux-ocp-p01/queue-config/cluster-queue.yaml
  components/kueue/production/kflux-osp-p01/queue-config/cluster-queue.yaml
  components/kueue/production/kflux-prd-rh02/queue-config/cluster-queue.yaml
  components/kueue/production/kflux-prd-rh03/queue-config/cluster-queue.yaml
  components/kueue/production/kflux-rhel-p01/queue-config/cluster-queue.yaml
  components/kueue/production/pentest-p01/queue-config/cluster-queue.yaml
  components/kueue/production/stone-prd-rh01/queue-config/cluster-queue.yaml
  components/kueue/production/stone-prod-p01/queue-config/cluster-queue.yaml
  components/kueue/production/stone-prod-p02/queue-config/cluster-queue.yaml
Labels: lgtm, approved

#7842 Allow to patch QPS setting on production
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
Labels: lgtm, approved

#7603 gpu instances: make /var/run/cdi world-writable
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
Labels: lgtm, approved

#7957 feat: add the infra team as owners
  components/konflux-ui/OWNERS
Labels: lgtm, approved

#7973 Update owner for info repo
  components/konflux-info/OWNERS
Labels: lgtm, approved

#7958 ocp-p01: Support user defined workload priority class
  components/kueue/production/kflux-ocp-p01/config.yaml
  components/kueue/production/kflux-ocp-p01/kustomization.yaml
  hack/test-tekton-kueue-config.py
Labels: lgtm, approved

#7975 Remove the whole new build banner
  components/konflux-info/production/kflux-ocp-p01/banner-content.yaml
  components/konflux-info/production/kflux-osp-p01/banner-content.yaml
  components/konflux-info/production/kflux-prd-rh02/banner-content.yaml
  components/konflux-info/production/kflux-prd-rh03/banner-content.yaml
  components/konflux-info/production/kflux-rhel-p01/banner-content.yaml
  components/konflux-info/production/stone-prd-rh01/banner-content.yaml
  components/konflux-info/production/stone-prod-p01/banner-content.yaml
  components/konflux-info/production/stone-prod-p02/banner-content.yaml
  components/konflux-info/staging/stone-stage-p01/banner-content.yaml
  components/konflux-info/staging/stone-stg-rh01/banner-content.yaml
Labels: lgtm, approved

#7974 Temporarily add new RHEL s390x VMs in FRA
  components/kueue/production/kflux-rhel-p01/queue-config/cluster-queue.yaml
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/external-secrets.yaml
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml
Labels: lgtm, approved

#7885 Moving IBMZ Instances to Frankfurt(EU) for RHEL Environment
  components/kueue/production/kflux-rhel-p01/queue-config/cluster-queue.yaml
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml
Labels: lgtm, do-not-merge/hold, approved

#8007 updating commit reference
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
Labels: lgtm, approved

#8012 Eventing: apply a fix on kflux-prd-rh03
  components/knative-eventing/production/kflux-prd-rh03/kustomization.yaml
Labels: lgtm, approved

#7949 Fix kubelet app to avoid unwanted fields modification
  argo-cd-apps/base/all-clusters/infra-deployments/kubelet-config/kubelet.yaml
Labels: lgtm, approved

#8027 PVO11Y-4774 - Adding Prometheus metrics to determine Prometheus healt…
  components/monitoring/prometheus/staging/base/monitoringstack/endpoints-params.yaml
Labels: lgtm, approved

#8046 itn-2025-00225: Updating Host Config for New Workspace and Instances
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/external-secrets.yaml
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml
Labels: lgtm, approved

#7994 Update MintMaker OWNERS
  components/mintmaker/OWNERS
Labels: lgtm, approved

#7918 feat(KFLUXVNGD-469): add trust-manager to development and staging
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/trust-manager/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/trust-manager/trust-manager.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  components/trust-manager/OWNERS
  components/trust-manager/development/kustomization.yaml
  components/trust-manager/development/trust-manager-helm-generator.yaml
  components/trust-manager/staging/kustomization.yaml
  components/trust-manager/staging/trust-manager-helm-generator.yaml
Labels: lgtm, approved

#8016 remove unused set-visibility policy
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/chainsaw-test.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/authenticated-rolebinding.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/expected-private-tenant-namespace.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/expected-public-tenant-namespace.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/non-clusterrole-rolebinding.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/non-tenant-namespace.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/tenant-namespace.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/wrong-clusterrole-rolebinding.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/kustomization.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/kyverno_rbac.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/set-tenant-namespace-visibility-clusterpolicy.yaml
Labels: lgtm, approved

#8123 Increase the max global streams in prod
  components/vector-kubearchive-log-collector/production/stone-prod-p02/loki-helm-prod-values.yaml
Labels: lgtm, approved

#8106 ensure self-provisioning is turned off by default in prod
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
Labels: lgtm, approved

#8069 Remove old UI
  argo-cd-apps/base/ui/kustomization.yaml
  argo-cd-apps/base/ui/ui.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  argo-cd-apps/overlays/staging-downstream/kustomization.yaml
  components/ui/OWNERS
  components/ui/README.md
  components/ui/base/chrome/chrome-frontend.yaml
  components/ui/base/chrome/kustomization.yaml
  components/ui/base/hac/hac-core-frontend.yaml
  components/ui/base/hac/hac-dev.yaml
  components/ui/base/hac/kustomization.yaml
  components/ui/base/kustomization.yaml
  components/ui/base/ns.yaml
  components/ui/base/proxy/kustomization.yaml
  components/ui/base/proxy/nginx.conf
  components/ui/base/proxy/proxy.yaml
  components/ui/development/fed-modules.json
  components/ui/development/kustomization.yaml
  components/ui/development/reduce-replicas.yaml
  components/ui/development/set-hostname.yaml
  components/ui/production/kflux-ocp-p01/fed-modules.json
  components/ui/production/kflux-ocp-p01/kustomization.yaml
  components/ui/production/kflux-ocp-p01/set-hostname.yaml
  components/ui/production/stone-prod-p01/fed-modules.json
  components/ui/production/stone-prod-p01/kustomization.yaml
  components/ui/production/stone-prod-p01/set-hostname.yaml
  components/ui/production/stone-prod-p02/fed-modules.json
  components/ui/production/stone-prod-p02/kustomization.yaml
  components/ui/production/stone-prod-p02/set-hostname.yaml
  components/ui/staging/fed-modules.json
  components/ui/staging/kustomization.yaml
  components/ui/staging/set-hostname.yaml
  docs/_data/navigation.yml
Labels: lgtm, approved

#8130 Update repo-validator
  components/repository-validator/staging/kustomization.yaml
Labels: lgtm, approved

#8128 KFLUXINFRA-2150 - Update AWS AMIs for x86_64 and ARM64 architectures
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml
Labels: lgtm, approved

#8134 Fix staging gosmee client URLs
  components/build-service/staging/stone-stage-p01/webhook-config.json
  components/smee-client/staging/sever-url-patch.yaml
Labels: lgtm, approved

#8145 Give users permission to view Kueue Workloads
  components/konflux-rbac/production/base/konflux-admin-user-actions.yaml
  components/konflux-rbac/production/base/konflux-contributor-user-actions.yaml
  components/konflux-rbac/production/base/konflux-maintainer-user-actions.yaml
  components/konflux-rbac/production/base/konflux-viewer-user-actions.yaml
  components/konflux-rbac/staging/base/konflux-admin-user-actions.yaml
  components/konflux-rbac/staging/base/konflux-contributor-user-actions.yaml
  components/konflux-rbac/staging/base/konflux-maintainer-user-actions.yaml
  components/konflux-rbac/staging/base/konflux-viewer-user-actions.yaml
Labels: lgtm, approved

#8070 Remove custom code review and use Gemini API
  .github/workflows/code-review.yml
  .github/workflows/gemini-dispatch.yml
  .github/workflows/gemini-review.yml
Labels: lgtm, approved

#8150 KONFLUX-9160 - Recommended lease configuration for kyverno
  components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
  components/kyverno/production/kflux-osp-p01/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh03/kyverno-helm-values.yaml
  components/kyverno/production/kflux-rhel-p01/kyverno-helm-values.yaml
  components/kyverno/production/pentest-p01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Labels: lgtm, approved

#8139 reduce number of streams for product-kubearchive-logging
  components/kubearchive/production/stone-prod-p02/kustomization.yaml
  components/kubearchive/staging/base/kustomization.yaml
  components/vector-kubearchive-log-collector/development/loki-helm-dev-values.yaml
  components/vector-kubearchive-log-collector/development/loki-helm-minio-values.yaml
  components/vector-kubearchive-log-collector/development/vector-helm-values.yaml
  components/vector-kubearchive-log-collector/production/stone-prod-p02/loki-helm-prod-values.yaml
  components/vector-kubearchive-log-collector/production/stone-prod-p02/vector-helm-values.yaml
  components/vector-kubearchive-log-collector/staging/stone-stg-rh01/loki-helm-stg-values.yaml
  components/vector-kubearchive-log-collector/staging/stone-stg-rh01/vector-helm-values.yaml
Labels: lgtm, approved

#8151 Update gosmee server webhooks
  components/build-service/production/kflux-osp-p01/webhook-config.json
  components/build-service/production/stone-prod-p01/webhook-config.json
  components/smee-client/production/kflux-osp-p01/sever-url-patch.yaml
  components/smee-client/production/stone-prod-p01/sever-url-patch.yaml
Labels: lgtm, approved

#8156 Fix rhel webhook spacing
  components/build-service/production/kflux-rhel-p01/webhook-config.json
  components/smee-client/production/kflux-rhel-p01/sever-url-patch.yaml
Labels: lgtm, approved

#8168 promote project-controller from STAGE to PROD
  components/project-controller/production/kustomization.yaml
Labels: lgtm, approved

#8155 increase loki stream rate
  components/vector-kubearchive-log-collector/development/loki-helm-dev-values.yaml
  components/vector-kubearchive-log-collector/production/stone-prod-p02/loki-helm-prod-values.yaml
  components/vector-kubearchive-log-collector/staging/stone-stg-rh01/loki-helm-stg-values.yaml
Labels: lgtm, approved

#8142 chore: bump konflux-ui (production) e16d3ec760ad...4dca539d8f28
  components/konflux-ui/production/base/kustomization.yaml
Labels: lgtm, approved

#8184 Remove trigger for pull_request open event
  .github/workflows/gemini-dispatch.yml
  .github/workflows/gemini-review.yml
Labels: lgtm, approved

#8187 optimize chunk flushing to s3 to avoid slowdown error
  components/vector-kubearchive-log-collector/production/stone-prod-p02/loki-helm-prod-values.yaml
  components/vector-kubearchive-log-collector/production/stone-prod-p02/vector-helm-values.yaml
Labels: lgtm, approved

#8191 feat(SRVKP-8847) Exposing Stage Metrics
  components/monitoring/prometheus/staging/base/monitoringstack/endpoints-params.yaml
Labels: lgtm, approved

#8199 remove retry configuration
  components/vector-kubearchive-log-collector/production/stone-prod-p02/loki-helm-prod-values.yaml
  components/vector-kubearchive-log-collector/production/stone-prod-p02/vector-helm-values.yaml
Labels: lgtm, approved

#8013 feat(KFLUXVNGD-416): deploy squid to development and staging
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/squid/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/squid/squid.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  components/squid/OWNERS
  components/squid/development/kustomization.yaml
  components/squid/development/squid-helm-generator.yaml
  components/squid/staging/kustomization.yaml
  components/squid/staging/squid-helm-generator.yaml
Labels: lgtm, approved

#8229 Clean up old teams from everyone can view
  components/authentication/base/everyone-can-view-patch.yaml
  components/has/base/rbac/has-admin.yaml
  components/has/base/rbac/has.yaml
  components/has/staging/rbac/has-exec.yaml
Labels: lgtm, approved

#8231 Remove workspace component
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/workspaces/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/workspaces/workspaces.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  components/workspaces/OWNERS
  components/workspaces/production/kflux-ocp-p01/kustomization.yaml
  components/workspaces/production/stone-prd-rh01/kustomization.yaml
  components/workspaces/production/stone-prod-p01/kustomization.yaml
  components/workspaces/production/stone-prod-p02/kustomization.yaml
  components/workspaces/staging/stone-stage-p01/kustomization.yaml
  components/workspaces/staging/stone-stg-rh01/kustomization.yaml
  components/workspaces/team/kyverno/konflux-core-kyverno-clusterrolebindings.yaml
  components/workspaces/team/kyverno/kustomization.yaml
  components/workspaces/team/migration/kustomization.yaml
  components/workspaces/team/migration/temp-workspace-team-rbac.yaml
Labels: lgtm, approved

#8233 ci: bump kubelinter to v0.7.6
  .github/workflows/kube-linter.yaml
  components/konflux-ui/production/kflux-ocp-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/kflux-osp-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/kflux-prd-rh02/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/kflux-prd-rh03/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/kflux-rhel-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/pentest-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/stone-prd-rh01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/stone-prod-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/stone-prod-p02/configure-oauth-proxy-secret.yaml
  components/konflux-ui/staging/stone-stage-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/staging/stone-stg-rh01/configure-oauth-proxy-secret.yaml
  components/kubearchive/base/migration-job.yaml
  components/kyverno/development/job_resources.yaml
  components/kyverno/production/kflux-ocp-p01/job_resources.yaml
  components/kyverno/production/kflux-osp-p01/job_resources.yaml
  components/kyverno/production/kflux-prd-rh02/job_resources.yaml
  components/kyverno/production/kflux-prd-rh03/job_resources.yaml
  components/kyverno/production/kflux-rhel-p01/job_resources.yaml
  components/kyverno/production/pentest-p01/job_resources.yaml
  components/kyverno/production/stone-prd-rh01/job_resources.yaml
  components/kyverno/production/stone-prod-p01/job_resources.yaml
  components/kyverno/production/stone-prod-p02/job_resources.yaml
  components/kyverno/staging/stone-stage-p01/job_resources.yaml
  components/kyverno/staging/stone-stg-rh01/job_resources.yaml
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
Labels: lgtm, approved

#8243 KFLUXINFRA-2300: Add nvidia container toolkit
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
Labels: lgtm, approved

#8248 feat(SRVKP-8847) Stage metrics, second set
  components/monitoring/prometheus/staging/base/monitoringstack/endpoints-params.yaml
Labels: lgtm, approved

#8249 feat(SRVKP-8847) new production metrics
  components/monitoring/prometheus/production/base/monitoringstack/endpoints-params.yaml
  components/monitoring/prometheus/staging/base/monitoringstack/endpoints-params.yaml
Labels: lgtm, approved

#8252 KubeArchive: downscale to 0 on stage-stg-rh01 for tests
  components/kubearchive/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#8255 disable job autocleanup
  .kube-linter.yaml
  components/konflux-ui/production/kflux-ocp-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/kflux-osp-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/kflux-prd-rh02/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/kflux-prd-rh03/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/kflux-rhel-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/pentest-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/stone-prd-rh01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/stone-prod-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/stone-prod-p02/configure-oauth-proxy-secret.yaml
  components/konflux-ui/staging/stone-stage-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/staging/stone-stg-rh01/configure-oauth-proxy-secret.yaml
  components/kubearchive/base/migration-job.yaml
  components/kyverno/development/job_resources.yaml
  components/kyverno/production/kflux-ocp-p01/job_resources.yaml
  components/kyverno/production/kflux-osp-p01/job_resources.yaml
  components/kyverno/production/kflux-prd-rh02/job_resources.yaml
  components/kyverno/production/kflux-prd-rh03/job_resources.yaml
  components/kyverno/production/kflux-rhel-p01/job_resources.yaml
  components/kyverno/production/pentest-p01/job_resources.yaml
  components/kyverno/production/stone-prd-rh01/job_resources.yaml
  components/kyverno/production/stone-prod-p01/job_resources.yaml
  components/kyverno/production/stone-prod-p02/job_resources.yaml
  components/kyverno/staging/stone-stage-p01/job_resources.yaml
  components/kyverno/staging/stone-stg-rh01/job_resources.yaml
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
Labels: lgtm, approved

#8285 Allow release team repos on internal staging
  components/repository-validator/staging/kustomization.yaml
Labels: lgtm, approved

#8276 Upgrade staging to v1.7.0
  components/kubearchive/development/kubearchive.yaml
  components/kubearchive/development/kustomization.yaml
Labels: lgtm, approved

#8292 chore: update the squid image tag
  components/squid/development/squid-helm-generator.yaml
  components/squid/staging/squid-helm-generator.yaml
Labels: lgtm, approved

#8306 chore: bump repository-validator staging commit ref
  components/repository-validator/staging/kustomization.yaml
Labels: lgtm, approved

#8307 Change RHEL AMIs to Cloud Access for Prod
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
  components/multi-platform-controller/production-downstream/kflux-osp-p01/host-config.yaml
  components/multi-platform-controller/production-downstream/pentest-p01/host-config.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p01/host-config.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
  hack/new-cluster/templates/multi-platform-controller/host-config.yaml
Labels: lgtm, approved

#8272 KAR-615: setup log collector stone-stage-p01 config
  argo-cd-apps/base/member/infra-deployments/vector-kubearchive-log-collector/vector-kubearchive-log-collector.yaml
  components/vector-kubearchive-log-collector/development/loki-helm-dev-values.yaml
  components/vector-kubearchive-log-collector/staging/stone-stage-p01/grafana-helm-generator.yaml
  components/vector-kubearchive-log-collector/staging/stone-stage-p01/grafana-helm-values.yaml
  components/vector-kubearchive-log-collector/staging/stone-stage-p01/kustomization.yaml
  components/vector-kubearchive-log-collector/staging/stone-stage-p01/loki-helm-generator.yaml
  components/vector-kubearchive-log-collector/staging/stone-stage-p01/loki-helm-stg-values.yaml
  components/vector-kubearchive-log-collector/staging/stone-stage-p01/loki-helm-values.yaml
  components/vector-kubearchive-log-collector/staging/stone-stage-p01/vector-helm-generator.yaml
  components/vector-kubearchive-log-collector/staging/stone-stage-p01/vector-helm-stg-values.yaml
  components/vector-kubearchive-log-collector/staging/stone-stage-p01/vector-helm-values.yaml
Labels: lgtm, approved

#8312 Update external production with recent MPC version
  components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh03/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
Labels: lgtm, approved

#8330 product-kubearchive-logging: remove staging deletion patch
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
Labels: lgtm, approved

#8333 kubearchive-logging: remove production deletion patch
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
Labels: lgtm, approved

#8340 feat(SPRE-1609): Update monitorinstack log level
  components/monitoring/prometheus/staging/base/monitoringstack/monitoringstack-log-level.yaml
Labels: lgtm, approved

#8350 chore(KFLUXVNGD-481): Revert change to trust-manager
  components/trust-manager/base/argocd-permissions.yaml
  components/trust-manager/base/kustomization.yaml
  components/trust-manager/development/kustomization.yaml
  components/trust-manager/staging/kustomization.yaml
Labels: lgtm, approved

#8349 Add kyverno grafana dashboard
  components/monitoring/grafana/base/dashboards/kustomization.yaml
  components/monitoring/grafana/base/dashboards/kyverno/dashboard.yaml
  components/monitoring/grafana/base/dashboards/kyverno/kustomization.yaml
  components/monitoring/grafana/base/dashboards/kyverno/kyverno.json
Labels: lgtm, approved

#8361 Add external secret for kubearchive-logging
  components/kubearchive/staging/stone-stage-p01/external-secret.yaml
  components/kubearchive/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#8380 MintMaker: promote manual update to prod
  components/mintmaker/production/base/kustomization.yaml
Labels: lgtm, approved

#8379 fix kyverno background permission for integration policies
  components/policies/development/integration/bootstrap-namespace/kyverno-rbac.yaml
Labels: lgtm, approved

#8384 feat: update cost-management operator to latest version
  components/cost-management/OWNERS
  components/cost-management/base/costmanagement-metrics-operator.yaml
Labels: lgtm, approved

#8394 Increase loki log level to debug
  components/vector-kubearchive-log-collector/production/stone-prod-p02/loki-helm-prod-values.yaml
Labels: lgtm, approved

#8344 kyverno: bump to v1.15.2 in development overlay
  components/kyverno/development/kustomization.yaml
  components/kyverno/development/kyverno-helm-generator.yaml
  components/kyverno/development/kyverno-helm-values.yaml
  components/policies/development/integration/bootstrap-namespace/bootstrap-namespace.yaml
Labels: lgtm, approved

#8403 KubeArchive: increase memory assigned to the operator
  components/kubearchive/staging/stone-stage-p01/kustomization.yaml
  components/kubearchive/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#8412 Fix operational_config in loki
  components/vector-kubearchive-log-collector/production/stone-prod-p02/loki-helm-prod-values.yaml
Labels: lgtm, approved

#8414 Allow bigger chunks of logs in loki
  components/vector-kubearchive-log-collector/production/stone-prod-p02/loki-helm-prod-values.yaml
Labels: lgtm, approved

#8405 Upgrade the Crossplane Component
  components/crossplane-control-plane/base/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#8261 update reference to enterprise-contract crds
  components/enterprise-contract/kustomization.yaml
Labels: lgtm, approved
