Repository redhat-appstudio/infra-deployments, pull requests merged in 2025-03, with the labels that each got.

#5691 [OCP] rename linux 250d variant
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5703 Bump Vector (Results) batch max size
  components/vector-tekton-logs-collector/development/vector-helm-values.yaml
  components/vector-tekton-logs-collector/staging/vector-helm-values.yaml
Labels: lgtm, approved

#5704 chore: Remove Pat from integration-service's OWNERS file
  components/integration/OWNERS
Labels: lgtm, approved

#5677 Enable konflux-ui on internal-production clusters
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
Labels: lgtm, approved

#5641 kyverno: refactor component folder
  argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
  components/kyverno/staging/empty-base/kustomization.yaml
  components/kyverno/staging/empty-base/namespace.yaml
  components/kyverno/staging/stone-stage-p01/job_resources.yaml
  components/kyverno/staging/stone-stage-p01/kustomization.yaml
  components/kyverno/staging/stone-stage-p01/kyverno-helm-generator.yaml
  components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stg-rh01/job_resources.yaml
  components/kyverno/staging/stone-stg-rh01/kustomization.yaml
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-generator.yaml
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#5684 konflux-ui: generate oauth2 secrets on stone-stage-p01
  components/konflux-ui/staging/stone-stage-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#5706 Increase memory request and limit for appstudio-federate-ms
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#5670 KFLUXINFRA-1269: Adding Configuration to etcd defrag periodically
  argo-cd-apps/base/member/infra-deployments/etcd-defrag/etcd-defrag.yaml
  argo-cd-apps/base/member/infra-deployments/etcd-defrag/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  configs/etcd-defrag/base/cluster-role.yaml
  configs/etcd-defrag/base/cronjob.yaml
  configs/etcd-defrag/base/kustomization.yaml
  configs/etcd-defrag/base/namespace.yaml
  configs/etcd-defrag/base/role-binding.yaml
  configs/etcd-defrag/base/serviceaccount.yaml
  configs/etcd-defrag/production/kustomization.yaml
  configs/etcd-defrag/staging/kustomization.yaml
Labels: lgtm, approved

#5705 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#5709 fix UI's proxy websocket support in prod
  components/konflux-ui/production/base/proxy/nginx.conf
Labels: lgtm, approved

#5711 Upgrade Vector for Tekton Results
  components/vector-tekton-logs-collector/development/vector-helm-generator.yaml
  components/vector-tekton-logs-collector/staging/vector-helm-generator.yaml
Labels: lgtm, approved

#5713 clean konflux-ui dex config in stage-p01
  components/konflux-ui/staging/stone-stage-p01/dex-config.yaml
Labels: lgtm, approved

#5707 chore(KFLUXVNGD-195): add tekton-bundle-builder to build configmap
  components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
Labels: lgtm, approved

#5680 add AccessCache panels to namespace-lister's grafana dashboard
  components/monitoring/grafana/base/dashboards/namespace-lister/namespace-lister-metrics.json
Labels: lgtm, approved

#5719 Revert "Deploy Namespaces to konflux-ui staging."
  components/konflux-ui/staging/base/kustomization.yaml
Labels: lgtm, approved

#5722 increase resources for image pruner
  components/image-controller/production/base/kustomization.yaml
  components/image-controller/production/base/pruner_cronjob_resources_patch.yaml
  components/image-controller/staging/base/kustomization.yaml
  components/image-controller/staging/base/pruner_cronjob_resources_patch.yaml
Labels: lgtm, approved

#5723 bump namespace lister in staging
  components/namespace-lister/base/kustomization.yaml
Labels: lgtm, approved

#5644 kyverno: release in prod rh02
  argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  components/kyverno/production/empty-base/kustomization.yaml
  components/kyverno/production/empty-base/namespace.yaml
  components/kyverno/production/kflux-prd-rh02/job_resources.yaml
  components/kyverno/production/kflux-prd-rh02/kustomization.yaml
  components/kyverno/production/kflux-prd-rh02/kyverno-helm-generator.yaml
  components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
Labels: lgtm, approved

#5726 Tune Vector Results config
  components/vector-tekton-logs-collector/development/vector-helm-values.yaml
  components/vector-tekton-logs-collector/staging/vector-helm-values.yaml
Labels: lgtm, approved

#5710 Correct c6gd2xlarge platform host configurations
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p01/host-config.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
  components/multi-platform-controller/staging-downstream/host-config.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#5732 KFLUXINFRA-1269: Adding Environment Variable for ETCD Defragmentation
  configs/etcd-defrag/base/cronjob.yaml
Labels: lgtm, approved

#5728 add konflux-ui to kflux-ocp-p01
  argo-cd-apps/base/member/infra-deployments/konflux-ui/konflux-ui.yaml
  components/konflux-ui/production/kflux-ocp-p01/add-service-certs-patch.yaml
  components/konflux-ui/production/kflux-ocp-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/kflux-ocp-p01/dex-config.yaml
  components/konflux-ui/production/kflux-ocp-p01/kustomization.yaml
  components/konflux-ui/production/kflux-ocp-p01/oauth2-proxy-args-patch.yaml
  components/konflux-ui/production/kflux-ocp-p01/remove-run-as-user-proxy-patch.yaml
  components/konflux-ui/production/kflux-ocp-p01/set-hostname.yaml
  components/konflux-ui/production/kflux-ocp-p01/set-redirect-uri.yaml
  components/konflux-ui/production/kflux-ocp-p01/set-replicas-patch.yaml
Labels: lgtm, approved

#5727 add namespace-lister to ocp-kflux-p01
  argo-cd-apps/base/member/infra-deployments/namespace-lister/namespace-lister.yaml
  components/namespace-lister/production/kflux-ocp-p01/kustomization.yaml
Labels: lgtm, approved

#5725 enterprise contract update
  components/enterprise-contract/ecp.yaml
  components/enterprise-contract/kustomization.yaml
Labels: lgtm, approved

#5342 fix: environment configuration for mintmaker in preview mode
  hack/preview.sh
Labels: lgtm, approved

#5652 bump namespace-lister to latest version in production
  components/namespace-lister/production/base/kustomization.yaml
Labels: lgtm, approved

#5737 konflux-ui: add dex secret genetor job to stg-rh01
  components/konflux-ui/staging/stone-stg-rh01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#5730 kyverno: git-ignore `charts` folder at component level
  components/kyverno/.gitignore
  components/kyverno/staging/.gitignore
Labels: lgtm, approved

#5743 fix(KFLUXSPRT-2070): fix taskrun PaC url template for rh02
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/update-tekton-config-pac.yaml
Labels: lgtm, approved

#5731 kyverno: unset `runAsUser` and `runAsGroup` fields in Jobs
  components/kyverno/development/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#5735 Reduce minio replicas to 1 for development
  components/pipeline-service/development/kustomization.yaml
Labels: lgtm, approved

#5741 Update workspace manager to latest
  components/konflux-ui/production/base/kustomization.yaml
  components/konflux-ui/production/base/proxy/proxy.yaml
  components/konflux-ui/staging/base/kustomization.yaml
  components/konflux-ui/staging/base/proxy/proxy.yaml
  components/konflux-ui/staging/stone-stg-rh01/base/kustomization.yaml
  components/konflux-ui/staging/stone-stg-rh01/base/proxy/proxy.yaml
Labels: lgtm, approved

#5739 namespace-lister: remove datasource from grafana dashboard
  components/monitoring/grafana/base/dashboards/namespace-lister/namespace-lister-metrics.json
Labels: lgtm, approved

#5749 namespace-lister: remove datasource from grafana dashboard
  components/monitoring/grafana/base/dashboards/namespace-lister/namespace-lister-metrics.json
Labels: lgtm, approved

#5733 Deploy latest crossplane configs
  components/crossplane-control-plane/base/kustomization.yaml
Labels: lgtm, approved

#5742 Allow Konflux devs to see compute tab
  components/authentication/base/everyone-can-view.yaml
  components/authentication/base/kustomization.yaml
Labels: lgtm, approved

#5758 namespace-lister: add healthz and readyz checks to staging
  components/namespace-lister/base/deployment.yaml
  components/namespace-lister/base/kustomization.yaml
Labels: lgtm, approved

#5753 scaffold kyverno across all relevant clusters
  argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  components/kyverno/production/kflux-ocp-p01/kustomization.yaml
  components/kyverno/production/stone-prd-rh01/kustomization.yaml
  components/kyverno/production/stone-prod-p01/kustomization.yaml
  components/kyverno/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#5751 add kyverno to stone-prd-rh01
  components/kyverno/production/stone-prd-rh01/job_resources.yaml
  components/kyverno/production/stone-prd-rh01/kustomization.yaml
  components/kyverno/production/stone-prd-rh01/kyverno-helm-generator.yaml
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#5755 nslister: add egress NetworkPolicy
  components/namespace-lister/base/kustomization.yaml
  components/namespace-lister/base/network_policy_allow_from_konfluxui.yaml
  components/namespace-lister/base/network_policy_allow_to_apiserver.yaml
Labels: lgtm, approved

#5762 mintmaker: grant pod management permissions to mintmaker-team
  components/mintmaker/base/rbac/mintmaker-team.yaml
Labels: lgtm, approved

#5766 nslister: promote egress NetworkPolicy to prod
  components/namespace-lister/production/base/kustomization.yaml
  components/namespace-lister/production/base/network_policy_allow_from_konfluxui.yaml
  components/namespace-lister/production/base/network_policy_allow_to_apiserver.yaml
Labels: lgtm, approved

#5770 namespace-lister: add healthz and readyz checks to prod
  components/namespace-lister/production/base/deployment.yaml
  components/namespace-lister/production/base/kustomization.yaml
Labels: lgtm, approved

#5773 add kyverno to stone-prod-p01
  components/kyverno/production/stone-prod-p01/job_resources.yaml
  components/kyverno/production/stone-prod-p01/kustomization.yaml
  components/kyverno/production/stone-prod-p01/kyverno-helm-generator.yaml
  components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
Labels: lgtm, approved

#5748 rollout kyverno to prod p02
  components/kyverno/production/stone-prod-p02/job_resources.yaml
  components/kyverno/production/stone-prod-p02/kustomization.yaml
  components/kyverno/production/stone-prod-p02/kyverno-helm-generator.yaml
  components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Labels: lgtm, approved

#5767 Optimize Vector Results
  components/vector-tekton-logs-collector/development/vector-helm-values.yaml
  components/vector-tekton-logs-collector/staging/vector-helm-values.yaml
Labels: lgtm, approved

#5781 Add successfulJobsHistoryLimit to CronJob
  configs/etcd-defrag/base/cronjob.yaml
Labels: lgtm, approved

#5785 Allocate more memory for MPC on RH02
  components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/manager_resources_patch.yaml
Labels: lgtm, approved

#5775 Only enable pause pods in production
  components/cluster-as-a-service/base/clustertemplates.yaml
  components/cluster-as-a-service/production/add-hypershift-params.yaml
Labels: lgtm, approved

#5789 Allocate more memory for MPC on RH02
  components/multi-platform-controller/production/kflux-prd-rh02/manager_resources_patch.yaml
Labels: approved

#5784 Upgrade and optimize Vector Results
  components/vector-tekton-logs-collector/production/vector-helm-generator.yaml
  components/vector-tekton-logs-collector/production/vector-helm-values.yaml
Labels: lgtm, approved

#5790 konfluxui: promote prod manifests to stg
  components/konflux-ui/staging/base/proxy/nginx.conf
  components/konflux-ui/staging/stone-stg-rh01/base/dex/dex.yaml
  components/konflux-ui/staging/stone-stg-rh01/base/dex/kustomization.yaml
  components/konflux-ui/staging/stone-stg-rh01/base/kustomization.yaml
  components/konflux-ui/staging/stone-stg-rh01/base/proxy/kustomization.yaml
  components/konflux-ui/staging/stone-stg-rh01/base/proxy/nginx.conf
  components/konflux-ui/staging/stone-stg-rh01/base/proxy/proxy.yaml
  components/konflux-ui/staging/stone-stg-rh01/base/route-and-oauth.yaml
  components/konflux-ui/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#5794 fix konflux-ui stg rh01
  components/konflux-ui/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#5791 konfluxui: deprecate workspaces endpoints
  components/konflux-ui/staging/base/proxy/nginx.conf
Labels: lgtm, approved

#5795 konflux-ui: fix tekton enpoint in stage
  components/konflux-ui/staging/base/proxy/nginx.conf
Labels: lgtm, approved

#5783 fix: deploy partial data fetch for pipeline runs
  components/ui/development/kustomization.yaml
  components/ui/production/kflux-ocp-p01/kustomization.yaml
  components/ui/production/stone-prod-p01/kustomization.yaml
  components/ui/production/stone-prod-p02/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: lgtm, approved

#5786 Bump Vector S3 batch max bytes
  components/vector-tekton-logs-collector/development/vector-helm-values.yaml
  components/vector-tekton-logs-collector/staging/vector-helm-values.yaml
Labels: lgtm, approved

#5796 konfluxui: fix job to create proxy's secrets
  components/konflux-ui/production/kflux-ocp-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/kflux-prd-rh02/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/stone-prd-rh01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/stone-prod-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/stone-prod-p02/configure-oauth-proxy-secret.yaml
  components/konflux-ui/staging/stone-stage-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/staging/stone-stg-rh01/configure-oauth-proxy-secret.yaml
Labels: lgtm, approved

#5802 konfluxui: restart deployments on secret update
  components/konflux-ui/staging/stone-stage-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/staging/stone-stg-rh01/configure-oauth-proxy-secret.yaml
Labels: lgtm, approved

#5801 Run Vector pods only on nodes running pipelines
  components/vector-tekton-logs-collector/development/vector-helm-values.yaml
  components/vector-tekton-logs-collector/staging/vector-helm-values.yaml
Labels: lgtm, approved

#5804 konfluxui: add replace and force argocd annotation to job
  components/konflux-ui/staging/stone-stage-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/staging/stone-stg-rh01/configure-oauth-proxy-secret.yaml
Labels: lgtm, approved

#5805 Run Vector pods only on nodes running pipelines prod
  components/vector-tekton-logs-collector/production/vector-helm-values.yaml
Labels: lgtm, approved

#5759 add kyverno policy for standardizing namespace's tenant label
  .chainsaw.yaml
  .github/workflows/chainsaw-tests.yaml
  .github/workflows/kube-linter.yaml
  components/kyverno/chainsaw/kustomization.yaml
  components/namespace-lister/base/kustomization.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/chainsaw-test.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/actual-namespace-konflux-toolchain.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/actual-namespace-konflux.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/actual-namespace-toolchain.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/actual-namespace-unlabeled.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/expected-namespace-konflux-toolchain.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/expected-namespace-konflux.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/expected-namespace-toolchain.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/expected-namespace-unlabeled.yaml
  components/namespace-lister/policies/ns-label/kustomization.yaml
  components/namespace-lister/policies/ns-label/kyverno-background-konflux-ns-label-clusterrole.yaml
  components/namespace-lister/policies/ns-label/namespace-enforce-label-clusterpolicy.yaml
  hack/chainsaw/chainsaw-prepare.sh
Labels: lgtm, approved

#5813 kyverno: increase resources in staging
  components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#5817 fix kyverno config in staging
  components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#5816 Disable pause pods in production for ephemeral cluster provisioning
  components/cluster-as-a-service/base/clustertemplates.yaml
  components/cluster-as-a-service/base/kustomization.yaml
  components/cluster-as-a-service/base/priorityclass.yaml
  components/cluster-as-a-service/production/add-hypershift-params.yaml
Labels: lgtm, approved

#5819 chore: remove konflux-test repository from tekton-ci namespace
  components/tekton-ci/base/repository.yaml
Labels: lgtm, approved

#5800 feat(STONEINTG-569): add github application config to integration-config
  components/integration/development/kustomization.yaml
  components/integration/development/manager_resources_patch.yaml
  components/integration/production/base/kustomization.yaml
  components/integration/production/base/manager_resources_patch.yaml
  components/integration/staging/base/kustomization.yaml
  components/integration/staging/base/manager_resources_patch.yaml
Labels: lgtm, approved

#5824 KFLUXINFRA-1269: Enable ETCD Defrag Config
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
Labels: lgtm, approved

#5820 Add VMs with larger disks in RH01
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#5832 Align MPC VMs between p02 and rh01
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: lgtm, approved

#5835 Update prod MPC w/ code cleanup changes
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
Labels: lgtm, approved

#5837 Test MPC code cleanup part 2 changes
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#5797 fix: add ServerSideApply to sync release-service
  argo-cd-apps/base/member/infra-deployments/release/release.yaml
Labels: lgtm, ok-to-test, approved

#5812 nslister: promote label policy to production
  components/namespace-lister/production/base/kustomization.yaml
Labels: lgtm, approved

#5811 namespace-lister: filter by konflux-ci.dev label
  components/namespace-lister/base/patches/with_cachenamespacelabelselector.yaml
Labels: lgtm, approved

#5844 Revert "Update prod MPC w/ code cleanup changes"
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
Labels: lgtm, approved

#5845 kyverno: more resources to background controller in prod
  components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Labels: lgtm, approved

#5846 ensure kyverno has Guaranteed QoS in staging
  components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#5645 kubearchive: add generate kyverno policy
  .github/workflows/kyverno-policies-tests.yaml
  components/kubearchive/development/kustomization.yaml
  components/kubearchive/policies/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
  components/kubearchive/policies/.chainsaw-test/chainsaw-test.yaml
  components/kubearchive/policies/.chainsaw-test/resources/actual-kubeconfig-archive.yaml
  components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-konflux-toolchain.yaml
  components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-konflux.yaml
  components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-toolchain.yaml
  components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-unlabeled.yaml
  components/kubearchive/policies/.chainsaw-test/resources/expected-kubearchiveconfig.yaml
  components/kubearchive/policies/.chainsaw-test/resources/kubearchive-crd.yaml
  components/kubearchive/policies/.kyverno-test/kyverno-test.yaml
  components/kubearchive/policies/bootstrap-namespace.yaml
  components/kubearchive/policies/kustomization.yaml
  components/kubearchive/policies/kyverno_rbac.yaml
  components/kubearchive/policies/resources/expected-kubearchiveconfig-konflux.yaml
  components/kubearchive/policies/resources/expected-kubearchiveconfig-toolchain.yaml
  components/kubearchive/policies/resources/labeled-namespace-konflux.yaml
  components/kubearchive/policies/resources/labeled-namespace-toolchain.yaml
  components/kubearchive/staging/kustomization.yaml
Labels: lgtm, approved

#5850 kyverno: give more resources in prod rh01
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#5854 feat: update kustomize binary
  .github/workflows/kube-linter.yaml
Labels: lgtm, approved

#5853 feat: release-service update
  components/release/development/kustomization.yaml
  components/release/production/kustomization.yaml
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#5856 nslister: use the new tenant label in prod
  components/namespace-lister/production/base/patches/with_cachenamespacelabelselector.yaml
Labels: lgtm, approved

#5857 fix(RELEASE-1441): allow rsc in production
  components/release/production/kustomization.yaml
  components/release/production/release_service_config.yaml
Labels: lgtm, approved

#5855 nslister-ui: add group support in staging
  components/konflux-ui/staging/base/proxy/proxy.yaml
  components/namespace-lister/base/kustomization.yaml
  components/namespace-lister/base/patches/with_header_auth_groups.yaml
Labels: lgtm, approved

#5859 update components/has/production/kustomization.yaml
  components/has/production/kustomization.yaml
Labels: approved

#5860 kyverno: pull kubectl from mirror.gcr.io in staging
  components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#5861 kyverno: bump memory limits in stone-stg-rh01 to 1Gi
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#5862 kyverno: pull kubectl from mirror.gcr.io in prod
  components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Labels: lgtm, approved

#5864 increase integration stage memory limit
  components/integration/staging/base/manager_resources_patch.yaml
Labels: lgtm, approved

#5865 increase integration stage memory limit
  components/integration/staging/base/manager_resources_patch.yaml
Labels: lgtm, approved

#5874 konfluxui: fix proxy permissions on staging clusters
  components/konflux-ui/staging/base/proxy/proxy.yaml
Labels: lgtm, approved

#5868 Run Mintmaker DependencyUpdateCheck cronjobs as non-root
  components/mintmaker/base/cronjobs/create-dependency-update-check.yaml
  components/mintmaker/base/cronjobs/delete-dependency-update-checks.yaml
Labels: lgtm, approved

#5840 MPC Staging clusters update
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#5878 konfluxui: restart dex on secret change in prod
  components/konflux-ui/production/kflux-ocp-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/kflux-prd-rh02/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/stone-prd-rh01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/stone-prod-p01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/stone-prod-p02/configure-oauth-proxy-secret.yaml
Labels: lgtm, approved

#5879 bump namespace-lister in production
  components/konflux-ui/production/base/proxy/proxy.yaml
  components/namespace-lister/production/base/kustomization.yaml
  components/namespace-lister/production/base/patches/with_header_auth_groups.yaml
Labels: lgtm, approved

#5880 namespace-lister: fix prod configuration
  components/konflux-ui/production/base/proxy/nginx.conf
  components/namespace-lister/production/base/patches/with-header-auth-email.yaml
  components/namespace-lister/production/base/patches/with_header_auth_groups.yaml
Labels: lgtm, approved

#5882 konfluxui: rollback x-user header value in prod
  components/konflux-ui/production/base/proxy/nginx.conf
Labels: lgtm, approved

#5884 Update repository validator w/ new allow list
  components/repository-validator/production/kustomization.yaml
Labels: lgtm, approved

#5885 remove rights on workspaces CRs from everyone-can-view
  components/authentication/base/everyone-can-view.yaml
Labels: lgtm, approved

#5869 rollback integration development and stage to version from intg pr 1048
  components/integration/development/kustomization.yaml
  components/integration/staging/base/kustomization.yaml
Labels: lgtm, approved

#5881 Create new flavors of ppc in internal staging
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#5886 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#5887 fix(STONEINTG-1137): fix kubearchiveconfig kustomization
  components/integration/staging/stone-stage-rh01/kustomization.yaml
Labels: lgtm, approved

#5889 Add RBAC data to Konflux info for all clusters
  components/konflux-info/production/kflux-ocp-p01/info.json
  components/konflux-info/production/kflux-prd-rh02/info.json
  components/konflux-info/production/stone-prd-rh01/info.json
  components/konflux-info/production/stone-prod-p01/info.json
  components/konflux-info/production/stone-prod-p02/info.json
  components/konflux-info/staging/stone-stage-p01/info.json
Labels: lgtm, approved

#5888 mintmaker: Revert mintmaker cronjobs security context change
  components/mintmaker/base/cronjobs/create-dependency-update-check.yaml
  components/mintmaker/base/cronjobs/delete-dependency-update-checks.yaml
Labels: lgtm, approved

#5890 konfluxui: allow proxy to only impersonate the system:authenticated group
  components/konflux-ui/production/base/proxy/proxy.yaml
  components/konflux-ui/staging/base/proxy/proxy.yaml
Labels: lgtm, approved

#5898 fix: set the integration staging memory requests equal to limits
  components/integration/staging/base/manager_resources_patch.yaml
Labels: lgtm, approved

#5899 Update prod repository validator w/ new allow list
  components/repository-validator/production/kustomization.yaml
Labels: lgtm, approved

#5896 Update OSP dev and stage
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5900 fix(KONFLUX-7357): increase integration service memory to 8gb
  components/integration/production/base/manager_resources_patch.yaml
  components/integration/staging/base/manager_resources_patch.yaml
Labels: lgtm, approved

#5839 Update prod MPC w/ part 2 code cleanup
  components/multi-platform-controller/production-downstream/stone-prod-p01/external-secrets.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p01/kustomization.yaml
Labels: lgtm, do-not-merge/hold, approved

#5902 fix(STONEINTG-1137-clusterrole): fix authetication for kubrarchiveconfig
  components/authentication/base/everyone-can-view.yaml
Labels: lgtm, approved

#5904 Add new PPC VMs to dynamic-platforms
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#5903 update kubearchive to v0.11.0 with the memory patch
  argo-cd-apps/overlays/konflux-public-staging/delete-sync-policy.yaml
  argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
  components/kubearchive/base/kustomization.yaml
Labels: lgtm, approved

#5906 Fix dynamic-platforms on stg-p01
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#5914 Remove power monitoring from staging
  argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
Labels: lgtm, approved

#5919 Temporarily disable sync of kubearchive application
  argo-cd-apps/overlays/konflux-public-staging/delete-sync-policy.yaml
  argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
Labels: lgtm, approved

#5920 scale down kubearchive operator to avoid secrets issue
  components/kubearchive/base/kustomization.yaml
Labels: lgtm, approved

#5826 Fix Role Binding
  argo-cd-apps/overlays/development/delete-applications.yaml
  configs/etcd-defrag/base/role-binding.yaml
Labels: lgtm, approved

#5917 Update Konflux Openshift Pipelines nightly release
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#5923 Use Vector mirrored image
  components/vector-tekton-logs-collector/development/vector-helm-generator.yaml
  components/vector-tekton-logs-collector/development/vector-helm-values.yaml
  components/vector-tekton-logs-collector/staging/vector-helm-generator.yaml
  components/vector-tekton-logs-collector/staging/vector-helm-values.yaml
Labels: lgtm, approved

#5928 Promote MintMaker to production
  components/mintmaker/base/cronjobs/create-dependency-update-check.yaml
  components/mintmaker/base/cronjobs/delete-dependency-update-checks.yaml
  components/mintmaker/production/base/kustomization.yaml
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5910 fix: release operator config update
  components/release/production/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#5933 KFLUXSPRT-2395: Update base image for ppc external cluster
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#5930 Remove Namespace from Kustomization File
  configs/etcd-defrag/base/kustomization.yaml
Labels: lgtm, approved

#5932 Use Vector mirrored image prod
  components/vector-tekton-logs-collector/production/vector-helm-generator.yaml
  components/vector-tekton-logs-collector/production/vector-helm-values.yaml
Labels: lgtm, approved

#5942 Updated the base image for ppc with updated rhsm conf
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#5922 nslister-monitoring: add panel for subject types
  components/monitoring/grafana/base/dashboards/namespace-lister/namespace-lister-metrics.json
Labels: lgtm, approved

#5937 PVO11Y-4689 Update the Konflux Splunk logging endpoint
  components/monitoring/logging/base/configure-logging/configure-logforwarder.yaml
Labels: lgtm, approved

#5952 bump namespace-lister in staging
  components/namespace-lister/base/kustomization.yaml
Labels: lgtm, approved

#5958 bump namespace-lister in staging
  components/namespace-lister/base/kustomization.yaml
Labels: lgtm, approved

#5957 Update KubeArchive to release 12.1.
  components/kubearchive/base/kustomization.yaml
Labels: lgtm, approved

#5807 PVO11Y-4652 - Expose Konflux etcd metrics for export to RHOBS
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, ok-to-test, approved

#5891 konfluxui: clean proxy's configuration
  components/konflux-ui/staging/base/proxy/nginx.conf
Labels: lgtm, approved

#5959 Renaming cachi2 to hermeto
  components/konflux-ci/base/repository.yaml
Labels: lgtm, approved

#5913 Update prod-p02 MPC w/ code cleanup
  components/multi-platform-controller/production-downstream/stone-prod-p02/external-secrets.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#5967 align konflux users permissions in staging
  components/konflux-rbac/staging/base/konflux-admin-user-actions.yaml
  components/konflux-rbac/staging/base/konflux-maintainer-user-actions.yaml
Labels: lgtm, approved

#5971 Update prd-rh02 MPC w/ code cleanup (#5968)
  components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
Labels: lgtm, approved

#5972 align konflux users permissions in production
  components/konflux-rbac/production/base/konflux-admin-user-actions.yaml
  components/konflux-rbac/production/base/konflux-contributor-user-actions.yaml
  components/konflux-rbac/production/base/konflux-maintainer-user-actions.yaml
Labels: lgtm, approved

#5847 kubearchive's policy: add support for new tenant label
  components/kubearchive/policies/.chainsaw-test/chainsaw-test.yaml
  components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-konfluxcidev.yaml
  components/kubearchive/policies/bootstrap-namespace.yaml
Labels: lgtm, approved

#5974 Add one more ppc flavor in staging
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#5975 Add more PPc VM flavors in prod-p02
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: lgtm, approved

#5976 Add more PPc VM flavors in prd-rh01
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#5977 Add more PPC VM flavors in prd-rh02
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
Labels: lgtm, approved

#5543 Allow contributors and maintainers to list and watch pods
  components/konflux-rbac/production/base/konflux-contributor-user-actions.yaml
  components/konflux-rbac/production/base/konflux-maintainer-user-actions.yaml
  components/konflux-rbac/staging/base/konflux-contributor-user-actions.yaml
  components/konflux-rbac/staging/base/konflux-maintainer-user-actions.yaml
Labels: lgtm, ok-to-test, approved

#5981 ETCD Changes for Konflux Internal Environment
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
Labels: lgtm, approved

#5992 update endpoint for tekton-results in production
  components/konflux-ui/production/base/proxy/nginx.conf
Labels: lgtm, approved

#5993 Add more memory for MPC on RH01
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/manager_resources_patch.yaml
Labels: lgtm, approved
