Repository redhat-appstudio/infra-deployments, pull requests merged in 2025-04, with the labels that each got.

#5994 remove old ui labels from kubearchive's policy
  components/kubearchive/policies/.chainsaw-test/chainsaw-test.yaml
  components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-konflux-toolchain.yaml
  components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-konflux.yaml
  components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-toolchain.yaml
  components/kubearchive/policies/.kyverno-test/kyverno-test.yaml
  components/kubearchive/policies/bootstrap-namespace.yaml
  components/kubearchive/policies/resources/expected-kubearchiveconfig-toolchain.yaml
  components/kubearchive/policies/resources/labeled-namespace-konflux.yaml
  components/kubearchive/policies/resources/labeled-namespace-toolchain.yaml
Labels: lgtm, approved

#6002 Promote konflux-ui to prod
  components/konflux-ui/production/base/kustomization.yaml
Labels: lgtm, approved

#5924 remove workspaces manager from staging clusters
  components/konflux-ui/staging/base/proxy/proxy.yaml
  components/konflux-ui/staging/stone-stage-p01/oauth2-proxy-args-patch.yaml
  components/konflux-ui/staging/stone-stage-p01/remove-run-as-user-proxy-patch.yaml
  components/konflux-ui/staging/stone-stg-rh01/oauth2-proxy-args-patch.yaml
  components/konflux-ui/staging/stone-stg-rh01/remove-run-as-user-proxy-patch.yaml
Labels: lgtm, approved

#5997 Remove 2 larger s390x VM size
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#5999 KubeArchive: store Releases
  components/kubearchive/base/kubearchive-config.yaml
Labels: lgtm, approved

#6004 add emptyDir config to devel layer
  components/release/development/release_service_config.yaml
Labels: lgtm, approved

#6005 Revert "Temporarily disable sync of kubearchive application"
  argo-cd-apps/overlays/konflux-public-staging/delete-sync-policy.yaml
  argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
Labels: lgtm, approved

#5995 Update staging MPCs w/ more code cleanup
  components/multi-platform-controller/base/kustomization.yaml
Labels: lgtm, approved

#6007 increase memory limit for kubearchive sink again
  components/kubearchive/base/kustomization.yaml
Labels: lgtm, approved

#6013 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#6009 Promote konflux-ui to prod
  components/konflux-ui/production/base/kustomization.yaml
Labels: lgtm, approved

#6016 Move s390x subnet to us-east-3 due to IBM capacity issues
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#6010 smee base - livenesProbe creation
  components/smee/base/deployment.yaml
Labels: lgtm, ok-to-test, approved

#6025 Add missing env patch to konflux-rbac
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
Labels: lgtm, approved

#6021 ensure namespace-lister has Guaranteed QoS
  components/namespace-lister/base/deployment.yaml
  components/namespace-lister/production/base/deployment.yaml
Labels: lgtm, approved

#6023 use emptyDir workspace for all oci-ta pipelines
  components/release/development/release_service_config.yaml
  components/release/production/release_service_config.yaml
  components/release/staging/release_service_config.yaml
Labels: lgtm, approved

#6024 bump namespace-lister in staging
  components/konflux-ui/staging/base/proxy/nginx.conf
  components/namespace-lister/base/kustomization.yaml
Labels: lgtm, approved

#6028 promote latest hac-dev to staging and prod
  components/ui/development/kustomization.yaml
  components/ui/production/kflux-ocp-p01/kustomization.yaml
  components/ui/production/stone-prod-p01/kustomization.yaml
  components/ui/production/stone-prod-p02/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: lgtm, approved

#5818 Add Role For Monitoring Release Pipelines
  components/release/base/kustomization.yaml
  components/release/base/monitor-pipeline-role.yaml
Labels: lgtm, ok-to-test, approved

#6034 Revert "Move s390x subnet to us-east-3 due to IBM capacity issues"
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#6022 smee-client - livenessProbe creation
  components/smee-client/base/deployment.yaml
Labels: lgtm, ok-to-test, approved

#6037 bump namespace-lister in staging
  components/namespace-lister/base/kustomization.yaml
Labels: lgtm, approved

#6040 Update staging RDS vault secret paths
  components/kubearchive/staging/database-secret.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/tekton-results-database-secret-path.yaml
Labels: lgtm, approved

#6041 Update production RDS vault secret paths
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-ocp-p01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5978 Export non-idle cpu seconds total
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, ok-to-test, approved

#6026 disable dex/proxy's secrets generator job in staging
  components/konflux-ui/staging/stone-stage-p01/kustomization.yaml
  components/konflux-ui/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#6044 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#6046 PVO11Y-4717 Increase memory allocation for Observability Operator pods
  components/monitoring/prometheus/base/observability-operator/observability-operator.yaml
Labels: lgtm, approved

#6048 removing livenessprobe
  components/smee-client/base/deployment.yaml
Labels: lgtm, ok-to-test, approved

#6047 PVO11Y-4717 Add permissions to monitoring role
  components/monitoring/prometheus/base/rbac/monitoring-admin.yaml
Labels: lgtm, approved

#6050 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#6051 Allow 50ppc VMs with default profile
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: approved

#6052 Remove Bama from Owners
  OWNERS
Labels: lgtm, approved

#6053 Allow 70ppc VMs with default profile
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#6011 chore(KFLUXVNGD-240): add tekton-bundle-builder-oci-ta to config
  components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
Labels: lgtm, approved

#6055 Revert "Allow 70ppc VMs with default profile"
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: approved

#6054 fix(KONFLUX-7569): Add container='' to memory consumption graphs to get right memory consumption
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, approved

#6042 fix-up(PVO11Y-4652): Export missing etcd metrics
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, ok-to-test, approved

#5927 Export total running pipelinerun count
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, ok-to-test, approved

#6061 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#6064 PVO11Y-4717 Increase the limit to 4Gi
  components/monitoring/prometheus/base/observability-operator/observability-operator.yaml
Labels: lgtm, approved

#6057 Update MintMaker owners
  components/mintmaker/OWNERS
Labels: lgtm, approved

#6029 Update stone-prod-p02's MPC w/ capacity checking
  components/multi-platform-controller/production-downstream/stone-prod-p02/external-secrets.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#6067 actions: run chainsaw tests concurrently
  .github/workflows/chainsaw-tests.yaml
Labels: lgtm, approved

#6062 add policy to create appstudio-pipeline rolebinding in staging
  components/konflux-ci/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
  components/konflux-ci/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-test.yaml
  components/konflux-ci/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-appstudio-pipeline-clusterrole.yaml
  components/konflux-ci/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-existing-rolebinding.yaml
  components/konflux-ci/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-namespace-konfluxcidev.yaml
  components/konflux-ci/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-namespace-unlabeled.yaml
  components/konflux-ci/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/expected-rolebinding.yaml
  components/konflux-ci/policies/bootstrap-tenant-namespace/.kyverno-test/kyverno-test.yaml
  components/konflux-ci/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-rolebinding-appstudio-runner.yaml
  components/konflux-ci/policies/bootstrap-tenant-namespace/.kyverno-test/resources/labeled-namespace-konflux.yaml
  components/konflux-ci/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-clusterpolicy.yaml
  components/konflux-ci/policies/bootstrap-tenant-namespace/kustomization.yaml
  components/konflux-ci/policies/bootstrap-tenant-namespace/kyverno_rbac.yaml
  components/konflux-ci/staging/kustomization.yaml
Labels: lgtm, approved

#6074 Add support for Tekton Results multipart logs
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  components/vector-tekton-logs-collector/development/vector-helm-values.yaml
  components/vector-tekton-logs-collector/staging/vector-helm-values.yaml
Labels: lgtm, approved

#6078 use ubuntu-latest instead of ubuntu-20.04
  .github/workflows/chainsaw-tests.yaml
Labels: lgtm, approved

#6076 move create pipeline-runner sa policy to konflux-rbac
  components/konflux-ci/staging/kustomization.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-test.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-appstudio-pipeline-clusterrole.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-existing-rolebinding.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-namespace-konfluxcidev.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-namespace-unlabeled.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/expected-rolebinding.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.kyverno-test/kyverno-test.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-rolebinding-appstudio-runner.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.kyverno-test/resources/labeled-namespace-konflux.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/kustomization.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/kyverno_rbac.yaml
  components/konflux-rbac/staging/stone-stage-p01/kustomization.yaml
  components/konflux-rbac/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#6079 add OWNERS for components/konflux-rbac
  components/konflux-rbac/OWNERS
Labels: lgtm, approved

#6082 Add support for Tekton Results multipart logs prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/vector-tekton-logs-collector/production/vector-helm-values.yaml
Labels: lgtm, approved

#6086 fix clusterrole in bootstrap tenant policy
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-appstudio-pipeline-clusterrole.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-existing-rolebinding.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/expected-rolebinding.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.kyverno-test/resources/expected-rolebinding-appstudio-runner.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-clusterpolicy.yaml
Labels: lgtm, approved

#6075 Fix KubeArchive metrics collection
  components/kubearchive/base/monitoring-servicemonitor.yaml
  components/kubearchive/base/otel-collector-config.yaml
Labels: lgtm, approved

#6080 promote pipeline-runner sa policy to prod-p02
  components/konflux-rbac/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#6087 Update prod MPCs w/ capacity checking
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/external-secrets.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
Labels: lgtm, approved

#6095 bump kyverno resources in production
  components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Labels: lgtm, approved

#6101 Adding liveness Probe for sme server
  components/smee/base/deployment.yaml
Labels: lgtm, ok-to-test, approved

#6098 fix chainsaw tests for bootstrap tenant ns policy
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-test.yaml
Labels: lgtm, approved

#6107 rename tenant namespace boostrap policy
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.kyverno-test/kyverno-test.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-clusterpolicy.yaml
Labels: lgtm, approved

#6102 fix kubearchive policy's tests
  components/kubearchive/policies/.chainsaw-test/chainsaw-test.yaml
Labels: lgtm, approved

#6112 give kyverno permission to create appstudio-pipeline rolebinding
  components/konflux-rbac/policies/bootstrap-tenant-namespace/kyverno_rbac.yaml
Labels: lgtm, approved

#6108 Fix for KFLUXINFRA-1473, which is the action item for KFLUXSPRT-2674
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p01/host-config.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#6110 bump kyverno to 3.3.7 in production
  components/kyverno/production/kflux-ocp-p01/kyverno-helm-generator.yaml
  components/kyverno/production/kflux-prd-rh02/kyverno-helm-generator.yaml
  components/kyverno/production/stone-prd-rh01/kyverno-helm-generator.yaml
  components/kyverno/production/stone-prod-p01/kyverno-helm-generator.yaml
  components/kyverno/production/stone-prod-p02/kyverno-helm-generator.yaml
Labels: lgtm, approved

#6104 disable dex/proxy's secrets generator job in production
  components/konflux-ui/production/kflux-ocp-p01/kustomization.yaml
  components/konflux-ui/production/kflux-prd-rh02/kustomization.yaml
  components/konflux-ui/production/stone-prd-rh01/kustomization.yaml
  components/konflux-ui/production/stone-prod-p01/kustomization.yaml
  components/konflux-ui/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#6089 use new UI in PaC custom console urls in staging
  components/pipeline-service/staging/stone-stage-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#6088 rollout pipeline sa rolebinding policy to all clusters
  components/konflux-rbac/production/base/kustomization.yaml
  components/konflux-rbac/production/stone-prod-p02/kustomization.yaml
  components/konflux-rbac/staging/base/kustomization.yaml
  components/konflux-rbac/staging/stone-stage-p01/kustomization.yaml
  components/konflux-rbac/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#6125 update PaC's custom console URL in prod
  components/pipeline-service/production/base/update-tekton-config-pac.yaml
  components/pipeline-service/production/kflux-ocp-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/stone-prod-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/stone-prod-p02/resources/update-tekton-config-pac.yaml
Labels: lgtm, approved

#6132 Promote konflux-ui to prod
  components/konflux-ui/production/base/kustomization.yaml
Labels: lgtm, approved

#6127 [dev+stage] Add SCC for nested containerization
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  components/sandbox/toolchain-member-operator/staging/kustomization.yaml
  components/sandbox/toolchain-member-operator/staging/patch-appstudio-pipelines-runner.yaml
Labels: lgtm, approved

#6137 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#6142 Offboard Dheeraj from Integration service
  components/integration/OWNERS
Labels: lgtm, approved

#6148 Update Cluster-logging operator to stable-6.1
  components/monitoring/logging/base/install-logging-operator.yaml
Labels: lgtm, approved

#6149 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#6143 Grant Build Service rights to run build pipelines
  components/build-service/base/build-pipeline-runner-rolebinding.yaml
  components/build-service/base/kustomization.yaml
Labels: lgtm, approved

#6154 livenessprobe for smee-client and refine of smee-base
  components/smee-client/base/deployment.yaml
  components/smee/base/deployment.yaml
Labels: lgtm, ok-to-test, approved

#6160 Change s390x cobfiguration to static for ocp-art-p01
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#6162 Rollout new Component Service Account model to staging
  components/build-service/development/kustomization.yaml
  components/build-service/staging/base/kustomization.yaml
  components/image-controller/development/kustomization.yaml
  components/image-controller/staging/base/kustomization.yaml
Labels: lgtm, approved

#6169 allow authenticated metrics for namespace-lister
  components/namespace-lister/base/kustomization.yaml
  components/namespace-lister/base/rbac.yaml
Labels: lgtm, approved

#6170 prod: allow authenticated metrics for namespace-lister
  components/namespace-lister/production/base/kustomization.yaml
  components/namespace-lister/production/base/rbac.yaml
Labels: lgtm, approved

#6147 feat(RELEASE-1532): use trusted artifacts
  components/release/development/release_service_config.yaml
  components/release/staging/release_service_config.yaml
Labels: lgtm, approved

#6171 chore: make integration service imagePullPolicy Always for dev
  components/integration/development/manager_resources_patch.yaml
Labels: lgtm, approved

#6179 Only suggest TA pipelines for newer functionality
  components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
Labels: lgtm, approved

#6187 Fix PaC's custom console URL in prod
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#6181 Configure OCP cluster to use static PPC64le VMs
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#6081 Add manifests for rh03
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-logging/monitoring-workload-logging.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml
  argo-cd-apps/base/member/infra-deployments/build-service/build-service.yaml
  argo-cd-apps/base/member/infra-deployments/integration/integration.yaml
  argo-cd-apps/base/member/infra-deployments/konflux-info/konflux-info.yaml
  argo-cd-apps/base/member/infra-deployments/konflux-rbac/konflux-rbac.yaml
  argo-cd-apps/base/member/infra-deployments/konflux-ui/konflux-ui.yaml
  argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
  argo-cd-apps/base/member/infra-deployments/mintmaker/mintmaker.yaml
  argo-cd-apps/base/member/infra-deployments/multi-platform-controller/multi-platform-controller.yaml
  argo-cd-apps/base/member/infra-deployments/namespace-lister/namespace-lister.yaml
  argo-cd-apps/base/member/infra-deployments/pipeline-service/pipeline-service.yaml
  components/backup/production/kflux-prd-rh03/backup-s3-credentials-patch.yaml
  components/backup/production/kflux-prd-rh03/backup-tenants-schedule.yaml
  components/backup/production/kflux-prd-rh03/dpa-bucket-patch.yaml
  components/backup/production/kflux-prd-rh03/dpa-kmskeyid-patch.yaml
  components/backup/production/kflux-prd-rh03/kustomization.yaml
  components/build-service/production/kflux-prd-rh03/kustomization.yaml
  components/build-service/production/kflux-prd-rh03/pipelines-as-code-secret-path.yaml
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
  components/integration/production/kflux-prd-rh03/console-url-config-patch.json
  components/integration/production/kflux-prd-rh03/kustomization.yaml
  components/integration/production/kflux-prd-rh03/pipelines-as-code-secret-path.yaml
  components/konflux-info/production/kflux-prd-rh03/info.json
  components/konflux-info/production/kflux-prd-rh03/kustomization.yaml
  components/konflux-rbac/production/kflux-prd-rh03/kustomization.yaml
  components/konflux-ui/production/kflux-prd-rh03/add-service-certs-patch.yaml
  components/konflux-ui/production/kflux-prd-rh03/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/kflux-prd-rh03/dex-config.yaml
  components/konflux-ui/production/kflux-prd-rh03/kustomization.yaml
  components/konflux-ui/production/kflux-prd-rh03/oauth2-proxy-args-patch.yaml
  components/konflux-ui/production/kflux-prd-rh03/remove-run-as-user-proxy-patch.yaml
  components/konflux-ui/production/kflux-prd-rh03/set-hostname.yaml
  components/konflux-ui/production/kflux-prd-rh03/set-redirect-uri.yaml
  components/konflux-ui/production/kflux-prd-rh03/set-replicas-patch.yaml
  components/kyverno/production/kflux-prd-rh03/job_resources.yaml
  components/kyverno/production/kflux-prd-rh03/kustomization.yaml
  components/kyverno/production/kflux-prd-rh03/kyverno-helm-generator.yaml
  components/kyverno/production/kflux-prd-rh03/kyverno-helm-values.yaml
  components/mintmaker/production/kflux-prd-rh03/kustomization.yaml
  components/mintmaker/production/kflux-prd-rh03/pipelines-as-code-secret-path.yaml
  components/monitoring/logging/production/kflux-prd-rh03/kustomization.yaml
  components/monitoring/prometheus/production/kflux-prd-rh03/cluster-id-label.yaml
  components/monitoring/prometheus/production/kflux-prd-rh03/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh03/external-secrets.yaml
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
  components/multi-platform-controller/production/kflux-prd-rh03/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh03/manager_resources_patch.yaml
  components/namespace-lister/production/kflux-prd-rh03/kustomization.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/kustomization.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/kustomization.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/pipelines-as-code-secret-path.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/scc-rbac.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/tekton-chains-public-key-path.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/tekton-chains-signing-secret-path.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/tekton-results-s3-secret-path.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/update-tekton-config-pac.yaml
Labels: lgtm, approved

#6191 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#6195 Rollout new Component Service Account model to production
  components/build-service/production/base/kustomization.yaml
  components/image-controller/production/base/kustomization.yaml
Labels: lgtm, approved

#6196 MintMaker: Deploy Redis for Renovate cache in stage
  components/mintmaker/base/redis-cache/kustomization.yaml
  components/mintmaker/base/redis-cache/redis-configmap.yaml
  components/mintmaker/base/redis-cache/redis-deployment.yaml
  components/mintmaker/base/redis-cache/redis-networkpolicy.yaml
  components/mintmaker/base/redis-cache/redis-pvc.yaml
  components/mintmaker/base/redis-cache/redis-service.yaml
  components/mintmaker/development/kustomization.yaml
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#6207 Increase secrets quotas to accommodate new build model
  components/sandbox/tiers/production/appstudio/kustomization.yaml
  components/sandbox/tiers/production/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-admin-1621311634-1621311634.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-clusterresources-2781377949-2781377949.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-contributor-923669109-923669109.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-maintainer-664949573-664949573.yaml
  components/sandbox/tiers/production/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/production/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-admin-336420259-1621311634.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-336420259-2781377949.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-contributor-336420259-923669109.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-maintainer-336420259-664949573.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-tenant-336420259-3035149355.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-viewer-336420259-3768244154.yaml
  components/sandbox/tiers/production/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/production/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-admin-451426537-1621311634.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-451426537-2781377949.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-451426537-923669109.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-451426537-664949573.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-451426537-3035149355.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-451426537-3768244154.yaml
  components/sandbox/tiers/src/appstudio/cluster.yaml
  components/sandbox/tiers/src/appstudiolarge/based_on_tier.yaml
  components/sandbox/tiers/src/appstudioxlarge/based_on_tier.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-admin-1621311634-1621311634.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-clusterresources-2781377949-2781377949.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-contributor-923669109-923669109.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-maintainer-664949573-664949573.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-admin-336420259-1621311634.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-336420259-2781377949.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-contributor-336420259-923669109.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-maintainer-336420259-664949573.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-tenant-336420259-3035149355.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-viewer-336420259-3768244154.yaml
  components/sandbox/tiers/staging/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-admin-451426537-1621311634.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-451426537-2781377949.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-451426537-923669109.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-451426537-664949573.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-tenant-451426537-3035149355.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-viewer-451426537-3768244154.yaml
Labels: lgtm, approved

#6209 Install External secret operator version 0.11.0 on staging
  components/external-secrets-operator/staging/starting-csv-patch.yaml
Labels: lgtm, approved

#6200 Deploy Redis for MintMaker to production
  components/mintmaker/base/kustomization.yaml
  components/mintmaker/development/kustomization.yaml
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#6214 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#6220 mintmaker update
  components/mintmaker/development/kustomization.yaml
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#6221 Increase memory limit for crossplane controller in prod and staging
  components/crossplane-control-plane/production/kustomization.yaml
  components/crossplane-control-plane/staging/kustomization.yaml
Labels: lgtm, approved

#6208 Update prod-p02 MPC
  components/multi-platform-controller/production-downstream/stone-prod-p02/external-secrets.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#6139 Knative-Eventing: going to production
  argo-cd-apps/base/member/infra-deployments/knative-eventing/knative-eventing.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  components/knative-eventing/production/base/kustomization.yaml
  components/knative-eventing/production/kflux-ocp-p01/kustomization.yaml
  components/knative-eventing/production/kflux-prd-rh02/kustomization.yaml
  components/knative-eventing/production/kflux-prd-rh03/kustomization.yaml
  components/knative-eventing/production/stone-prod-p01/kustomization.yaml
  components/knative-eventing/production/stone-prod-rh02/kustomization.yaml
  components/knative-eventing/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#6012 KubeArchive: change when resources are archived
  components/kubearchive/base/kubearchive-config.yaml
Labels: lgtm, approved

#6232 Update MPC on prod-p02
  components/multi-platform-controller/production-downstream/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#6234 Fix MPC on prod-p02
  components/multi-platform-controller/production-downstream/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#6236 Update all production MPCs
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/external-secrets.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh03/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
Labels: lgtm, approved

#6206 Expose KubeArchive API
  components/konflux-ui/staging/base/proxy/nginx.conf
  components/konflux-ui/staging/base/proxy/proxy.yaml
  components/konflux-ui/staging/stone-stage-p01/kustomization.yaml
  components/konflux-ui/staging/stone-stg-rh01/kustomization.yaml
  components/kubearchive/base/kubearchive-routes.yaml
Labels: lgtm, ok-to-test, approved

#6242 Disable kyverno WebhookCleanup job in dev and stg
  components/kyverno/development/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#6245 deploy knative-eventing to stone-prod-p02
  components/knative-eventing/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#6231 fix-up(PVO11Y-4652): Export new cluster and etcd metrics
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, ok-to-test, approved

#6251 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#6244 fix: running ir shold not be removed
  components/release/base/cronjobs/remove-internal-requests.yaml
Labels: lgtm, approved

#6259 Knative Eventing: increase memory usage for controller
  components/knative-eventing/base/kustomization.yaml
Labels: lgtm, approved

#6263 update console urls in integration component
  components/integration/production/base/kustomization.yaml
  components/integration/production/kflux-ocp-p01/console-url-config-patch.json
  components/integration/production/stone-prod-p01/console-url-config-patch.json
  components/integration/production/stone-prod-p02/console-url-config-patch.json
  components/integration/staging/base/kustomization.yaml
  components/integration/staging/stone-stage-p01/console-url-config-patch.json
Labels: lgtm, approved

#6272 Align pipeline-service base with cluster configs
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#6113 make chainsaw tests more robust
  .github/workflows/chainsaw-tests.yaml
  components/kyverno/chainsaw/job_resources.yaml
  components/kyverno/chainsaw/kustomization.yaml
  components/kyverno/chainsaw/kyverno-helm-generator.yaml
  components/kyverno/chainsaw/kyverno-helm-values.yaml
  components/kyverno/chainsaw/namespace.yaml
  hack/chainsaw/chainsaw-prepare.sh
Labels: lgtm, approved

#6226 Application-layer new-cluster automation
  hack/new-cluster/README.md
  hack/new-cluster/playbook.yaml
  hack/new-cluster/tasks/applicationsets.yaml
  hack/new-cluster/tasks/components.yaml
  hack/new-cluster/tasks/github/app.yaml
  hack/new-cluster/tasks/github/find-latest-commits.yaml
  hack/new-cluster/tasks/github/github-app-flow.py
  hack/new-cluster/tasks/quay/find-digest.yaml
  hack/new-cluster/tasks/variables.yaml
  hack/new-cluster/tasks/vault/chains.yaml
  hack/new-cluster/tasks/vault/login.yaml
  hack/new-cluster/tasks/vault/verify.yaml
  hack/new-cluster/templates/backup/backup-s3-credentials-patch.yaml
  hack/new-cluster/templates/backup/backup-tenants-schedule.yaml
  hack/new-cluster/templates/backup/dpa-bucket-patch.yaml
  hack/new-cluster/templates/backup/dpa-kmskeyid-patch.yaml
  hack/new-cluster/templates/backup/kustomization.yaml
  hack/new-cluster/templates/build-service/kustomization.yaml
  hack/new-cluster/templates/build-service/pipelines-as-code-secret-path.yaml
  hack/new-cluster/templates/integration/console-url-config-patch.json
  hack/new-cluster/templates/integration/kustomization.yaml
  hack/new-cluster/templates/integration/pipelines-as-code-secret-path.yaml
  hack/new-cluster/templates/konflux-info/info.json
  hack/new-cluster/templates/konflux-info/kustomization.yaml
  hack/new-cluster/templates/konflux-rbac/kustomization.yaml
  hack/new-cluster/templates/konflux-ui/add-service-certs-patch.yaml
  hack/new-cluster/templates/konflux-ui/configure-oauth-proxy-secret.yaml
  hack/new-cluster/templates/konflux-ui/dex-config.yaml
  hack/new-cluster/templates/konflux-ui/kustomization.yaml
  hack/new-cluster/templates/konflux-ui/oauth2-proxy-args-patch.yaml
  hack/new-cluster/templates/konflux-ui/remove-run-as-user-proxy-patch.yaml
  hack/new-cluster/templates/konflux-ui/set-hostname.yaml
  hack/new-cluster/templates/konflux-ui/set-redirect-uri.yaml
  hack/new-cluster/templates/konflux-ui/set-replicas-patch.yaml
  hack/new-cluster/templates/kyverno/job_resources.yaml
  hack/new-cluster/templates/kyverno/kustomization.yaml
  hack/new-cluster/templates/kyverno/kyverno-helm-generator.yaml
  hack/new-cluster/templates/kyverno/kyverno-helm-values.yaml
  hack/new-cluster/templates/mintmaker/kustomization.yaml
  hack/new-cluster/templates/mintmaker/pipelines-as-code-secret-path.yaml
  hack/new-cluster/templates/monitoring/logging/kustomization.yaml
  hack/new-cluster/templates/monitoring/prometheus/cluster-id-label.yaml
  hack/new-cluster/templates/monitoring/prometheus/kustomization.yaml
  hack/new-cluster/templates/multi-platform-controller/external-secrets.yaml
  hack/new-cluster/templates/multi-platform-controller/host-config.yaml
  hack/new-cluster/templates/multi-platform-controller/kustomization.yaml
  hack/new-cluster/templates/multi-platform-controller/manager_resources_patch.yaml
  hack/new-cluster/templates/namespace-lister/kustomization.yaml
  hack/new-cluster/templates/pipeline-service/deploy.yaml
  hack/new-cluster/templates/pipeline-service/kustomization.yaml
  hack/new-cluster/templates/pipeline-service/resources/kustomization.yaml
  hack/new-cluster/templates/pipeline-service/resources/pipelines-as-code-secret-path.yaml
  hack/new-cluster/templates/pipeline-service/resources/scc-rbac.yaml
  hack/new-cluster/templates/pipeline-service/resources/tekton-chains-public-key-path.yaml
  hack/new-cluster/templates/pipeline-service/resources/tekton-chains-signing-secret-path.yaml
  hack/new-cluster/templates/pipeline-service/resources/tekton-results-database-secret-path.yaml
  hack/new-cluster/templates/pipeline-service/resources/tekton-results-s3-secret-path.yaml
  hack/new-cluster/templates/pipeline-service/resources/update-tekton-config-pac.yaml
Labels: lgtm, approved
