Repository redhat-appstudio/infra-deployments, pull requests merged in 2025-07, with the labels that each got.

#6924 chore: reference smee sidecar by tag
  components/smee-client/staging/deployment.yaml
  components/smee-client/staging/kustomization.yaml
  components/smee/staging/deployment.yaml
  components/smee/staging/kustomization.yaml
Labels: lgtm, approved

#6937 Upgrade to KubeArchive v1.2.0
  components/konflux-ui/staging/base/proxy/proxy.yaml
  components/kubearchive/development/kustomization.yaml
Labels: lgtm, approved

#6948 Upgrade to KubeArchive v1.2.0
  components/kubearchive/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#6951 add generated kubearchive.conf to konflux ui prod
  components/konflux-ui/production/base/proxy/nginx.conf
Labels: lgtm, approved

#6822 scrape kyverno metrics in prod
  components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh03/kyverno-helm-values.yaml
  components/kyverno/production/kflux-rhel-p01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Labels: lgtm, ok-to-test, approved

#6970 Konflux admin update
  components/authentication/base/konflux-admins.yaml
Labels: lgtm, ok-to-test, approved

#6983 Disable pipleline-runner role for staging in toolchain-member-operator
  components/konflux-rbac/staging/base/kustomization.yaml
  components/konflux-rbac/staging/base/patch-appstudio-pipelines-runner.yaml
  components/sandbox/toolchain-member-operator/staging/kustomization.yaml
Labels: lgtm, approved

#6989 Increase kyverno UpdateRequests in p02
  components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Labels: lgtm, approved

#6988 fix(SPRE-1522): Fix API group access to APF
  components/authentication/base/konflux-admins.yaml
Labels: lgtm, approved

#6991 Revert "etcd-shield: fix metrics in staging"
  argo-cd-apps/overlays/development/delete-applications.yaml
  components/etcd-shield/base/metrics/metrics-service.yaml
  components/etcd-shield/base/metrics/monitor.yaml
  components/etcd-shield/base/metrics/network-policy.yaml
  components/etcd-shield/base/metrics/rbac.yaml
Labels: lgtm, approved

#6987 Add 2 MPC VM profiles to p02
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: lgtm, approved

#6994 etcd-shield: re-enable metrics in staging
  argo-cd-apps/overlays/development/delete-applications.yaml
  components/etcd-shield/base/metrics/kustomization.yaml
  components/etcd-shield/base/metrics/metrics-service.yaml
  components/etcd-shield/base/metrics/monitor.yaml
  components/etcd-shield/base/metrics/network-policy.yaml
  components/etcd-shield/base/metrics/rbac.yaml
Labels: lgtm, approved

#6996 etcd-shield: add ClusterRole for metrics auth
  components/etcd-shield/production/base/rbac.yaml
Labels: lgtm, approved

#7001 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#7002 Adding apiserver namespaces to monitoringstack
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, ok-to-test, approved

#7000 feat: Add kyverno, kueue and etcd-shield to controllers overview dashboard
  components/monitoring/grafana/base/dashboards/performance/kustomization.yaml
Labels: lgtm, approved

#7013 Update Tekton Results v0.15.2-1 staging
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#6630 feat(KFLUXUI-504): Add banner content yaml and its kustomization files
  .github/workflows/validate-banner.yaml
  components/konflux-info/README.md
  components/konflux-info/auto-alert-schema.json
  components/konflux-info/banner-schema.json
  components/konflux-info/production/kflux-ocp-p01/auto-alerts/auto-alert-1.yaml
  components/konflux-info/production/kflux-ocp-p01/auto-alerts/kustomization.yaml
  components/konflux-info/production/kflux-ocp-p01/banner-content.yaml
  components/konflux-info/production/kflux-ocp-p01/kustomization.yaml
  components/konflux-info/production/kflux-prd-rh02/auto-alerts/auto-alert-1.yaml
  components/konflux-info/production/kflux-prd-rh02/auto-alerts/kustomization.yaml
  components/konflux-info/production/kflux-prd-rh02/banner-content.yaml
  components/konflux-info/production/kflux-prd-rh02/kustomization.yaml
  components/konflux-info/production/kflux-prd-rh03/auto-alerts/auto-alert-1.yaml
  components/konflux-info/production/kflux-prd-rh03/auto-alerts/kustomization.yaml
  components/konflux-info/production/kflux-prd-rh03/banner-content.yaml
  components/konflux-info/production/kflux-prd-rh03/kustomization.yaml
  components/konflux-info/production/kflux-rhel-p01/auto-alerts/auto-alert-1.yaml
  components/konflux-info/production/kflux-rhel-p01/auto-alerts/kustomization.yaml
  components/konflux-info/production/kflux-rhel-p01/banner-content.yaml
  components/konflux-info/production/kflux-rhel-p01/kustomization.yaml
  components/konflux-info/production/stone-prd-rh01/auto-alerts/auto-alert-1.yaml
  components/konflux-info/production/stone-prd-rh01/auto-alerts/kustomization.yaml
  components/konflux-info/production/stone-prd-rh01/banner-content.yaml
  components/konflux-info/production/stone-prd-rh01/kustomization.yaml
  components/konflux-info/production/stone-prod-p01/auto-alerts/auto-alert-1.yaml
  components/konflux-info/production/stone-prod-p01/auto-alerts/kustomization.yaml
  components/konflux-info/production/stone-prod-p01/banner-content.yaml
  components/konflux-info/production/stone-prod-p01/kustomization.yaml
  components/konflux-info/production/stone-prod-p02/auto-alerts/auto-alert-1.yaml
  components/konflux-info/production/stone-prod-p02/auto-alerts/kustomization.yaml
  components/konflux-info/production/stone-prod-p02/banner-content.yaml
  components/konflux-info/production/stone-prod-p02/kustomization.yaml
  components/konflux-info/staging/stone-stage-p01/auto-alerts/auto-alert-1.yaml
  components/konflux-info/staging/stone-stage-p01/auto-alerts/kustomization.yaml
  components/konflux-info/staging/stone-stage-p01/banner-content.yaml
  components/konflux-info/staging/stone-stage-p01/kustomization.yaml
  components/konflux-info/staging/stone-stg-rh01/auto-alerts/auto-alert-1.yaml
  components/konflux-info/staging/stone-stg-rh01/auto-alerts/kustomization.yaml
  components/konflux-info/staging/stone-stg-rh01/banner-content.yaml
  components/konflux-info/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#7030 chore: set GOMEMLIMIT for smee-sidecar in staging
  components/smee-client/staging/deployment.yaml
Labels: lgtm, approved

#7034 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#7037 Use v0.1.7 of the hypershift-aws-cluster chart with EaaS
  components/cluster-as-a-service/base/clustertemplates.yaml
Labels: lgtm, approved

#6929 Create namespace visibility Kyverno policy
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/chainsaw-test.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/authenticated-rolebinding.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/expected-private-tenant-namespace.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/expected-public-tenant-namespace.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/non-clusterrole-rolebinding.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/non-tenant-namespace.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/tenant-namespace.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/.chainsaw-test/resources/wrong-clusterrole-rolebinding.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/kustomization.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/kyverno_rbac.yaml
  components/policies/staging/base/konflux-rbac/set-tenant-namespace-visibility/set-tenant-namespace-visibility-clusterpolicy.yaml
Labels: lgtm, approved

#7038 Update Results in Production, disable storing incomplete runs
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-osp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#7050 Fix kflux-osp-p01's smee configuration
  argo-cd-apps/base/smee-client/smee-client.yaml
  components/smee/production/ip-allow-list.yaml
Labels: lgtm, approved

#7052 Fix kflux-osp-p01 smee-client IP typo
  components/smee/production/ip-allow-list.yaml
Labels: lgtm, approved

#6679 chore: give integration team permission to manage resolutionrequests
  components/integration/base/kustomization.yaml
  components/integration/base/manage-resolutionrequests.yaml
Labels: lgtm, approved

#7055 public-stage: Increase pipelines controller memory
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/update-tekton-controller-resources.yaml
Labels: lgtm, approved

#7045 mintmaker: update brew.registry.redhat.io secret labels
  components/mintmaker/base/external-secrets/brew-registry-redhat-io-pull-secret.yaml
Labels: lgtm, approved

#7057 chore: enable pprof for smee-sidecar in staging
  components/smee-client/staging/deployment.yaml
  components/smee/staging/deployment.yaml
Labels: lgtm, approved

#7060 stage: Give the Vanguard team admin permission on the smee-client ns
  components/smee-client/staging/kustomization.yaml
  components/smee-client/staging/rbac.yaml
Labels: lgtm, approved

#7035 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#7069 Revert "update downstream prod with a recent MPC bugfix"
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
Labels: lgtm, approved

#7061 Set memory limit as Mi
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#7073 Update kflux-osp-p01 MPC host config for IBM VMS
  components/multi-platform-controller/production-downstream/kflux-osp-p01/host-config.yaml
Labels: lgtm, approved

#7074 Update Tekton Results to v0.15.2-2 prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-osp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#7095 Set the qps and burst for Results watcher
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#7076 Upgrade MCE operator to 2.8 in prod
  components/cluster-as-a-service/base/multicluster-engine.yaml
  components/cluster-as-a-service/production/add-hypershift-params.yaml
Labels: lgtm, approved

#7097 KubeArchive: allow exported_job to reach Prometheus
  components/kubearchive/base/monitoring-servicemonitor.yaml
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#7104 Set the qps and burst for Results api
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-osp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#7107 Increase Tekton Results Watcher CPU resources
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-osp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#7112 ensure kyverno has Guaranteed QoS in stg
  components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#7114 ensure kyverno admission controller has Guaranteed QoS in stg
  components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#7119 Allow o11y admins to view all monitoring resources in cluster
  components/monitoring/prometheus/base/rbac/monitoring-all-admin.yaml
Labels: lgtm, approved

#7124 chore: upgrade gosmee image in production
  components/smee-client/base/deployment.yaml
  components/smee/base/deployment.yaml
Labels: lgtm, approved

#7126 feat: install smee-sidecar for smee client
  components/smee-client/base/deployment.yaml
  components/smee-client/production/base/kustomization.yaml
  components/smee-client/production/kflux-ocp-p01/kustomization.yaml
  components/smee-client/production/kflux-ocp-p01/sever-url-patch.yaml
  components/smee-client/production/kflux-osp-p01/kustomization.yaml
  components/smee-client/production/kflux-osp-p01/sever-url-patch.yaml
  components/smee-client/production/kflux-rhel-p01/kustomization.yaml
  components/smee-client/production/stone-prod-p01/kustomization.yaml
  components/smee-client/production/stone-prod-p01/sever-url-patch.yaml
  components/smee-client/production/stone-prod-p02/kustomization.yaml
  components/smee-client/production/stone-prod-p02/sever-url-patch.yaml
  components/smee-client/staging/deployment.yaml
  components/smee-client/staging/enable-pprof.yaml
  components/smee-client/staging/kustomization.yaml
  components/smee-client/staging/rbac.yaml
Labels: lgtm, approved

#7066 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#7134 PVO11Y-4852 Fix: add new rolebinding to kustomization file
  components/monitoring/prometheus/base/rbac/kustomization.yaml
Labels: lgtm, approved

#7080 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#6717 add deployment visibility to konflux-info
  components/konflux-info/production/kflux-ocp-p01/info.json
  components/konflux-info/production/kflux-prd-rh02/info.json
  components/konflux-info/production/kflux-prd-rh03/info.json
  components/konflux-info/production/kflux-rhel-p01/info.json
  components/konflux-info/production/stone-prd-rh01/info.json
  components/konflux-info/production/stone-prod-p01/info.json
  components/konflux-info/production/stone-prod-p02/info.json
  components/konflux-info/staging/stone-stage-p01/info.json
  components/konflux-info/staging/stone-stg-rh01/info.json
  hack/new-cluster/templates/konflux-info/info.json
Labels: lgtm, ok-to-test, approved

#7053 KFLUXUI-220: Deploy Kite service to development cluster
  argo-cd-apps/base/member/infra-deployments/konflux-kite/konflux-kite.yaml
  argo-cd-apps/base/member/infra-deployments/konflux-kite/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
  components/konflux-kite/OWNERS
  components/konflux-kite/base/deployment.yaml
  components/konflux-kite/base/kustomization.yaml
  components/konflux-kite/base/ns.yaml
  components/konflux-kite/base/rbac.yaml
  components/konflux-kite/base/service.yaml
  components/konflux-kite/development/kustomization.yaml
  components/konflux-kite/development/postgresql.yaml
Labels: lgtm, approved

#7152 chore: integration-service update
  components/integration/development/kustomization.yaml
  components/integration/staging/base/kustomization.yaml
Labels: lgtm, approved

#7157 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#7165 fix(KFLUXSPRT-4158): revert integration production to 5a79cbc
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#7160 KubeArchive: disable leader election
  components/kubearchive/development/kustomization.yaml
Labels: lgtm, approved

#7170 Update p02 cluster with recent MPC version
  components/multi-platform-controller/production-downstream/stone-prod-p02/controller-image-patch.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#7177 Revert "Update p02 cluster with recent MPC version"
  components/multi-platform-controller/production-downstream/stone-prod-p02/controller-image-patch.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/kustomization.yaml
Labels: approved

#7077 ClusterRole for integration pipeline service account runner
  components/konflux-rbac/base/konflux-integration-runner.yaml
  components/konflux-rbac/base/kustomization.yaml
  components/konflux-rbac/production/base/konflux-integration-runner.yaml
  components/konflux-rbac/production/base/kustomization.yaml
Labels: lgtm, approved

#6995 Allow rh-subs-watch-tenant access to insights-secret-store
  components/cluster-secret-store-rh/production/stone-prd-rh01/insights-secret-store.yaml
Labels: lgtm, ok-to-test, approved

#7176 KubeArchive: add labels for histograms
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#7189 feat: set pipeline priority and multi-platform build quotas for development
  components/kueue/development/queue-config/cluster-queue.yaml
  components/kueue/development/queue-config/kustomization.yaml
  components/kueue/development/queue-config/workload-priority-class.yaml
  components/kueue/development/tekton-kueue/config.yaml
  components/kueue/development/tekton-kueue/kustomization.yaml
Labels: lgtm, approved

#7033 Refactor nginx configs structure
  components/konflux-ui/staging/base/proxy/auth.conf
  components/konflux-ui/staging/base/proxy/kubearchive.conf
  components/konflux-ui/staging/base/proxy/kustomization.yaml
  components/konflux-ui/staging/base/proxy/nginx.conf
  components/konflux-ui/staging/base/proxy/proxy.yaml
  components/konflux-ui/staging/base/proxy/tekton-results.conf
  components/konflux-ui/staging/stone-stage-p01/kubearchive.conf
  components/konflux-ui/staging/stone-stage-p01/kustomization.yaml
  components/konflux-ui/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#7206 KFLUXINFRA-1964: Create multi platform cluster queue staging
  components/kueue/staging/base/kustomization.yaml
  components/kueue/staging/base/queue-config/cluster-queue.yaml
  components/kueue/staging/stone-stage-p01/kustomization.yaml
  components/kueue/staging/stone-stage-p01/queue-config/cluster-queue.yaml
  components/kueue/staging/stone-stage-p01/queue-config/kustomization.yaml
  components/kueue/staging/stone-stg-rh01/kustomization.yaml
  components/kueue/staging/stone-stg-rh01/queue-config/cluster-queue.yaml
  components/kueue/staging/stone-stg-rh01/queue-config/kustomization.yaml
  hack/kueue-vm-quotas/README.md
  hack/kueue-vm-quotas/generate-queue-config.sh
  hack/kueue-vm-quotas/update-kueue-vm-quotas.py
Labels: lgtm, approved

#7214 add additional permissions for build team to build related CRs
  components/build-service/base/rbac/build-maintainer.yaml
Labels: lgtm, approved

#7202 Eventing: SubjectAccessReview fix
  components/knative-eventing/base/kustomization.yaml
Labels: lgtm, approved

#7217 kueue: replace "_" with "-" in build platforms
  components/kueue/staging/base/tekton-kueue/config.yaml
Labels: lgtm, approved

#7216 Replace rhel-p01 AMD VMs by m7a
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml
Labels: lgtm, approved

#7218 Gran konflux-infra member permissions to debug MPC
  components/multi-platform-controller/base/rbac/pod-debug-restart.yaml
Labels: lgtm, approved

#7219 Update downstream clusters with recent MPC
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
  components/multi-platform-controller/production-downstream/kflux-osp-p01/kustomization.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/controller-image-patch.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#7200 Update pipelines version in dev and staging
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#7223 Update upstream clusters with recent MPC
  components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh03/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
Labels: lgtm, approved

#7224 chore: add Nigel to the integration owners
  components/integration/OWNERS
Labels: lgtm, approved

#7221 chore: move konflux-ci config to rh03
  components/konflux-ci/production/kflux-prd-rh03/infra-deployments-pr-creator.yaml
  components/konflux-ci/production/kflux-prd-rh03/kustomization.yaml
  components/konflux-ci/production/kflux-prd-rh03/plnsvc-ci-secret.yaml
  components/konflux-ci/production/kflux-prd-rh03/plnsvc-codecov-secret.yaml
  components/konflux-ci/production/kflux-prd-rh03/quay-push-secret-konflux-ci.yaml
  components/konflux-ci/production/kflux-prd-rh03/redhat-appstudio-tekton-catalog-build-definitions-pull-secret.yaml
  components/konflux-ci/production/kflux-prd-rh03/snyk-shared-token.yaml
Labels: lgtm, approved

#7237 Update Kueue dashboard
  components/monitoring/grafana/base/dashboards/kueue/kueue.json
Labels: approved

#7234 Use same resources in stage as prod
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#7245 Promote tekton-kueue to stage
  components/kueue/staging/base/tekton-kueue/kustomization.yaml
Labels: approved

#7274 Update Kyverno updateRequestThreshold in p02
  components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Labels: lgtm, approved

#7039 Fix namespace-lister NetworkPolicy ingress rule
  components/namespace-lister/base/network_policy_allow_from_konfluxui.yaml
Labels: lgtm, approved

#7140 ensure kyverno controllers has Guaranteed Qos in prod
  components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
  components/kyverno/production/kflux-osp-p01/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh03/kyverno-helm-values.yaml
  components/kyverno/production/kflux-rhel-p01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Labels: lgtm, approved

#7282 fix kyverno config for prd-rh01
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#7284 reduce cpu for kyverno on prod rh01
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#7263 update pipelines version in production
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-osp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#7286 Update Konflux-Kite RBAC
  components/konflux-kite/base/rbac.yaml
Labels: lgtm, approved

#7275 development: Recommended lease config for kyverno
  components/kyverno/development/kyverno-helm-values.yaml
Labels: lgtm, approved

#7262 add resource limits and requests for pipelines staging
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#7278 Promote tekton-kueue to stage
  components/kueue/staging/base/tekton-kueue-monitoring/kueue-prometheus-alerts.yaml
  components/kueue/staging/base/tekton-kueue-monitoring/kustomization.yaml
  components/kueue/staging/base/tekton-kueue/kustomization.yaml
Labels: lgtm, approved

#7304 Export cluster RAM metrics for MintMaker
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#7312 add pulp-access-controller component to public prod
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
Labels: lgtm, approved

#7269 Deploy Kite service to staging
  argo-cd-apps/base/member/infra-deployments/konflux-kite/konflux-kite.yaml
  argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  components/konflux-kite/base/deployment.yaml
  components/konflux-kite/base/external-secrets/database-secret.yaml
  components/konflux-kite/base/kustomization.yaml
  components/konflux-kite/base/routes.yaml
  components/konflux-kite/development/kustomization.yaml
  components/konflux-kite/development/postgresql.yaml
  components/konflux-kite/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#7315 Set GIT_SSL_CAINFO env on Pipeline resolvers prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-osp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#6153 Promote hac-dev to internal prod cluster
  components/ui/development/kustomization.yaml
  components/ui/production/kflux-ocp-p01/kustomization.yaml
  components/ui/production/stone-prod-p01/kustomization.yaml
  components/ui/production/stone-prod-p02/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: lgtm, approved

#7306 KFLUXINFRA-1970: Change Max Instances for MPC Platforms
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
  components/multi-platform-controller/production-downstream/kflux-osp-p01/host-config.yaml
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: do-not-merge/hold, approved

#7318 fix: adding rbac needed to run tests
  components/konflux-ci/base/kustomization.yaml
  components/konflux-ci/base/test-runner-cluster-role.yaml
  components/konflux-ci/base/test-runner-rolebinding.yaml
Labels: lgtm, approved

#7321 Disable MintMaker runs on Saturday
  components/mintmaker/base/cronjobs/create-dependency-update-check.yaml
Labels: lgtm, approved

#7325 fix: test permissions issue
  components/build-templates/base/e2e/rolebinding.yaml
  components/konflux-ci/base/kustomization.yaml
  components/konflux-ci/base/test-runner-rolebinding.yaml
Labels: lgtm, approved

#7298 restrict update event for integration's ClusterPolicy
  components/policies/development/integration/bootstrap-namespace/.chainsaw-test/chainsaw-test.yaml
  components/policies/development/integration/bootstrap-namespace/.chainsaw-test/resources/actual-namespace-unlabeled-extra.yaml
  components/policies/development/integration/bootstrap-namespace/bootstrap-namespace.yaml
Labels: lgtm, approved

#7349 Revert "restrict update event for integration's ClusterPolicy"
  components/policies/development/integration/bootstrap-namespace/.chainsaw-test/chainsaw-test.yaml
  components/policies/development/integration/bootstrap-namespace/.chainsaw-test/resources/actual-namespace-unlabeled-extra.yaml
  components/policies/development/integration/bootstrap-namespace/bootstrap-namespace.yaml
Labels: lgtm, approved

#7326 feat: add the konflux-banner-configmap as parts of konflux-public-info
  components/konflux-info/base/rbac.yaml
Labels: lgtm, approved

#7360 KubeArchive: add KubeArchive to public production kustomization
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
Labels: lgtm, approved

#7369 Fix typo on the init-container logic
  components/konflux-ui/staging/base/proxy/proxy.yaml
Labels: lgtm, approved

#7352 restrict update event integration policy
  components/policies/development/integration/bootstrap-namespace/.chainsaw-test/chainsaw-test.yaml
  components/policies/development/integration/bootstrap-namespace/.chainsaw-test/resources/actual-namespace-unlabeled-extra.yaml
  components/policies/development/integration/bootstrap-namespace/bootstrap-namespace.yaml
  components/policies/development/integration/kustomization.yaml
Labels: lgtm, approved

#7363 Upgrade kueue 1.0.1
  components/kueue/development/kueue/operator.yaml
Labels: lgtm, approved

#7366 KFLUXINFRA-2013: Deploy cert-manager partially on production
  argo-cd-apps/base/member/infra-deployments/cert-manager/cert-manager.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  components/cert-manager/production/base/kustomization.yaml
  components/cert-manager/production/base/operator.yaml
  components/cert-manager/production/empty-base/.gitempty
  components/cert-manager/production/kflux-ocp-p01/kustomization.yaml
  components/cert-manager/production/kflux-osp-p01/kustomization.yaml
  components/cert-manager/production/kflux-prd-rh02/kustomization.yaml
  components/cert-manager/production/kflux-prd-rh03/kustomization.yaml
  components/cert-manager/production/stone-prod-p01/kustomization.yaml
Labels: lgtm, approved

#7370 mintmaker: increase memory limit to prevent OOMKilled
  components/mintmaker/production/base/manager_patch.yaml
Labels: lgtm, approved

#7364 KubeArchive: consolidate password encoding
  components/kubearchive/base/migration-job.yaml
  components/kubearchive/production/kflux-prd-rh03/kustomization.yaml
Labels: lgtm, approved

#7373 increase memory for knative-eventing imc-controller
  components/knative-eventing/base/kustomization.yaml
Labels: lgtm, approved

#7371 add ability to view pac repositories
  components/release/base/e2e-release-pipeline-resources-role.yaml
  components/release/base/kustomization.yaml
Labels: lgtm, approved

#7372 staging: Upgrade Kueue operator to stable-v1.0
  components/kueue/staging/base/kueue/operator.yaml
Labels: approved

#7381 KFLUXINFRA-1986: Update Kueue alerting rules
  components/kueue/development/tekton-kueue-monitoring/kueue-prometheus-alerts.yaml
  components/kueue/development/tekton-kueue/kustomization.yaml
  components/kueue/staging/base/tekton-kueue-monitoring/kueue-prometheus-alerts.yaml
  components/kueue/staging/base/tekton-kueue/kustomization.yaml
Labels: approved

#7377 Eventing: increase memory for IMC
  components/knative-eventing/production/base/kustomization.yaml
Labels: lgtm, approved

#7397 Confirm that I know how to update the banner
  components/konflux-info/staging/stone-stg-rh01/banner-content.yaml
Labels: approved

#7403 stage: Patch PAC controller image
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#7404 staging: Patch PAC images
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#7411 feat(SPRE-1697) New metric
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, ok-to-test, approved

#7414 chore(KFLUXSPRT-3661): Add namespace expression konflux-user-support
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#7421 chore(KFLUXSPRT-3661): Forward kube_deployment_spec_replicas for konflux_user_support
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved
