Repository redhat-appstudio/infra-deployments, pull requests merged in 2025-06, with the labels that each got.

#6490 Handle private-network differences in build-service and smee-client
  hack/new-cluster/playbook.yaml
  hack/new-cluster/tasks/components.yaml
  hack/new-cluster/tasks/variables.yaml
  hack/new-cluster/templates/cost-management/cost-management-config-source-patch.yaml
  hack/new-cluster/templates/cost-management/kustomization.yaml
  hack/new-cluster/templates/etcd-shield/kustomization.yaml
  hack/new-cluster/templates/knative-eventing/kustomization.yaml
  hack/new-cluster/templates/private/authentication/kustomization.yaml
  hack/new-cluster/templates/private/build-service/webhook-config.json
  hack/new-cluster/templates/private/smee-client/kustomization.yaml
  hack/new-cluster/templates/private/smee-client/sever-url-patch.yaml
Labels: lgtm, approved

#6493 kyverno cleanup configuration for dev
  components/kyverno/development/kyverno-helm-values.yaml
Labels: lgtm, approved

#6534 bump kyverno UpdateRequest threshold in rh01
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#6536 give more cpu to Kyverno background on rh01
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#6509 feat(SPRE-1489): API server metrics
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, ok-to-test, approved

#6542 refresh pulp access controller
  components/pulp-access-controller/base/kustomization.yaml
Labels: lgtm, approved

#6535 disable `mutate-namespace-enforce-label` policy in staging
  components/namespace-lister/base/kustomization.yaml
Labels: lgtm, approved

#6546 chore: promote project controller to production
  components/project-controller/production/kustomization.yaml
Labels: lgtm, approved

#6489 disable kyverno reports in prod
  components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh03/kyverno-helm-values.yaml
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Labels: lgtm, approved

#6457 feat(PVO11Y-4787): Setup Kanary signal deployment
  argo-cd-apps/base/monitoring-workload-kanary/kustomization.yaml
  argo-cd-apps/base/monitoring-workload-kanary/monitoring-workload-kanary.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/kustomization.yaml
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
  components/monitoring/kanary/README.md
  components/monitoring/kanary/base/external-secrets/kanary-db-credentials.yaml
  components/monitoring/kanary/base/external-secrets/kustomization.yaml
  components/monitoring/kanary/base/kustomization.yaml
  components/monitoring/kanary/base/rbac/kanary-maintainers.yaml
  components/monitoring/kanary/base/rbac/kustomization.yaml
  components/monitoring/kanary/staging/base/kanary-db-credentials-secret-path.yaml
  components/monitoring/kanary/staging/base/kustomization.yaml
  components/monitoring/kanary/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#6553 bump memory for image-controller
  components/image-controller/production/base/manager_resources_patch.yaml
  components/image-controller/staging/base/manager_resources_patch.yaml
Labels: lgtm, approved

#6549 split bootstrap-tenant-namespace-networkpolicies in stg
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-test.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.kyverno-test/kyverno-test.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-networkpolicies-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-ocpconsole-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-ocpingress-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-ocpmonitoring-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-olm-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-samenamespace-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/kustomization.yaml
Labels: lgtm, approved

#6567 exclude kubesaw managed namespace from tenant bootstrapping in stg
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-test.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-namespace-kubesaw.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-ocpconsole-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-ocpingress-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-ocpmonitoring-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-olm-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-samenamespace-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-rbcm-clusterpolicy.yaml
Labels: lgtm, approved

#6571 mintmaker (prod): increase memory allocation for controller
  components/mintmaker/production/base/manager_patch.yaml
Labels: lgtm, approved

#6572 Fix chain signing secret path.
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/resources/tekton-chains-public-key-path.yaml
  components/pipeline-service/production/kflux-rhel-p01/resources/tekton-chains-signing-secret-path.yaml
Labels: lgtm, approved

#6568 chore: grant appstudio-pipelines-runner admin permissions on testplat…
  components/sandbox/toolchain-member-operator/base/rbac/appstudio-pipelines-runner.yaml
Labels: lgtm, ok-to-test, approved

#6576 fix kflux-rhel-p01 OSP index tag
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/resources/override-osp-version.yaml
Labels: lgtm, approved

#6580 kflux-rhel-p01 - disable new tektonpruner
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/resources/kustomization.yaml
  components/pipeline-service/production/kflux-rhel-p01/resources/update-config-for-osp-1-19.yaml
Labels: lgtm, approved

#6579 Set number of OSP buckets to 4
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#6582 Move secrets file to each internal MPC cluster folder
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/aws-account.patch.yaml
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/aws-ssh-key.patch.yaml
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/external-secrets.yaml
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/ibm-account.patch.yaml
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/ibm-ssh-key.patch.yaml
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/kustomization.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p01/external-secrets.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p01/kustomization.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/external-secrets.yaml
Labels: lgtm, approved

#6581 Fix MPC deployment on kflux-rhel-p01 cluster
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/kustomization.yaml
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/manager_resources_patch.yaml
Labels: approved

#6589 chore: update kanary exporter
  components/monitoring/kanary/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#6586 Revert "exclude kubesaw managed namespace from tenant bootstrapping in stg"
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/chainsaw-test.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/.chainsaw-test/resources/actual-namespace-kubesaw.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-ocpconsole-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-ocpingress-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-ocpmonitoring-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-olm-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-np-samenamespace-clusterpolicy.yaml
  components/konflux-rbac/policies/bootstrap-tenant-namespace/bootstrap-tenant-namespace-rbcm-clusterpolicy.yaml
Labels: lgtm, approved

#6593 remove cpu limits for etcd-shield
  components/etcd-shield/base/deployment.yaml
  components/etcd-shield/production/base/deployment.yaml
Labels: lgtm, approved

#6595 kyverno remove cpu limits in prod
  components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh03/kyverno-helm-values.yaml
  components/kyverno/production/kflux-rhel-p01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Labels: lgtm, approved

#6603 PVO11Y-4772 - Export prometheus_ready metric for monitoring the internal prom instances.
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#6510 update dev and staging pipelines deployments to next release
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, ok-to-test, approved

#6606 Remove s390x and ppc VMs from p02
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: lgtm, approved

#6614 Remove the deletion of nvme-storage app from downstream overlays
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
Labels: lgtm, approved

#6620 PVO11Y-4802: Kanary label change and appending label to prometheus whitelist
  components/monitoring/kanary/staging/stone-stage-p01/kustomization.yaml
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#6358 Add kueue component
  argo-cd-apps/base/member/infra-deployments/cert-manager/cert-manager.yaml
  argo-cd-apps/base/member/infra-deployments/cert-manager/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kueue/kueue.yaml
  argo-cd-apps/base/member/infra-deployments/kueue/kustomization.yaml
  argo-cd-apps/base/member/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
  components/cert-manager/development/kustomization.yaml
  components/cert-manager/development/operator.yaml
  components/kueue/development/kueue-external-admission/kustomization.yaml
  components/kueue/development/kueue-external-admission/monitoring.yaml
  components/kueue/development/kueue/kueue.yaml
  components/kueue/development/kueue/kustomization.yaml
  components/kueue/development/kueue/operator.yaml
  components/kueue/development/kustomization.yaml
  components/kueue/development/queue-config/cluster-policy.yaml
  components/kueue/development/queue-config/cluster-queue.yaml
  components/kueue/development/queue-config/kustomization.yaml
  components/kueue/development/queue-config/kyverno-rbac.yaml
  components/kueue/development/tekton-kueue/kustomization.yaml
  components/kueue/development/tekton-kueue/monitoring.yaml
  hack/preview.sh
  hack/sandbox-development-mode.sh
Labels: lgtm, approved

#6625 fix(SPRE-1489): Update API Server metrics
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, ok-to-test, approved

#6628 Configure kflux-rhel-p01 s390x and ppc VMs
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml
Labels: lgtm, approved

#6436 updated the memory resource for tekton resources to prevent OOMKills
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, ok-to-test, approved

#6435 update resource configurations for Tekton components
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, ok-to-test, approved

#6632 Promote new MPC to the public prod clusters
  components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh03/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
Labels: lgtm, approved

#6526 KubeArchive: Job to automate SQL migrations
  components/kubearchive/base/kustomization.yaml
  components/kubearchive/base/migration-job.yaml
Labels: lgtm, approved

#6621 KFLUXINFRA-1737: Add kubearchive apiGroup permissions to konflux-admin
  components/authentication/base/konflux-admins.yaml
Labels: lgtm, approved

#6646 increase QPS and Burst for Kyverno in prod rh01
  components/kyverno/production/stone-prd-rh01/patch_background_controller_qps_burst.yaml
Labels: lgtm, approved

#6641 increase QPS and Burst for Kyverno in stg rh01
  components/kyverno/staging/stone-stg-rh01/kustomization.yaml
  components/kyverno/staging/stone-stg-rh01/patch-background-controller-qps-burst.yaml
Labels: lgtm, approved

#6482 add list RoleBindings to maintainers and contributors in prod
  components/konflux-rbac/production/base/konflux-contributor-user-actions.yaml
  components/konflux-rbac/production/base/konflux-maintainer-user-actions.yaml
Labels: lgtm, approved

#6637 Update OSP to newest nightly (dev and stage)
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#6650 kyverno: increase leader election retry period in dev and stg
  components/kyverno/development/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#6653 fix kyverno admission leader election retry period in dev and stg
  components/kyverno/development/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#6655 disable remove-configmap job in prod
  components/kyverno/production/kflux-ocp-p01/kustomization.yaml
  components/kyverno/production/kflux-ocp-p01/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh02/kustomization.yaml
  components/kyverno/production/kflux-prd-rh02/kyverno-helm-values.yaml
  components/kyverno/production/kflux-prd-rh03/kustomization.yaml
  components/kyverno/production/kflux-prd-rh03/kyverno-helm-values.yaml
  components/kyverno/production/kflux-rhel-p01/kustomization.yaml
  components/kyverno/production/kflux-rhel-p01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prd-rh01/kustomization.yaml
  components/kyverno/production/stone-prd-rh01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p01/kustomization.yaml
  components/kyverno/production/stone-prod-p01/kyverno-helm-values.yaml
  components/kyverno/production/stone-prod-p02/kustomization.yaml
  components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Labels: lgtm, approved

#6659 Fix kflux-rhel-p01 MPC subnet and security group
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml
Labels: lgtm, approved

#6647 Update tekton-kueue
  components/kueue/development/kustomization.yaml
  components/kueue/development/tekton-kueue-monitoring/kustomization.yaml
  components/kueue/development/tekton-kueue-monitoring/monitoring.yaml
  components/kueue/development/tekton-kueue/kustomization.yaml
  components/kueue/development/tekton-kueue/monitoring.yaml
Labels: lgtm, approved

#6665 KFLUXINFRA-1759: Update OCP DPA on stage
  components/backup/staging/stone-stage-p01/dpa-channel-patch.yaml
  components/backup/staging/stone-stage-p01/kustomization.yaml
  components/backup/staging/stone-stg-rh01/dpa-channel-patch.yaml
  components/backup/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#6666 KFLUXINFRA-1763: Add apiGroup permissions to konflux-admin
  components/authentication/base/konflux-admins.yaml
Labels: lgtm, approved

#6639 upgrade crossplane environments
  components/crossplane-control-plane/base/kustomization.yaml
  components/crossplane-control-plane/development/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#6678 Fix the rolebinding for cost-management component
  components/cost-management/base/rbac/cost-management-admin.yaml
Labels: lgtm, ok-to-test, approved

#6680 KFLUXINFRA-1768: Deploy Kueue and CertManager to stone-stg-rh01
  argo-cd-apps/overlays/konflux-public-staging/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  components/cert-manager/staging/base/kustomization.yaml
  components/cert-manager/staging/base/operator.yaml
  components/cert-manager/staging/stone-stg-rh01/kustomization.yaml
  components/kueue/staging/base/kueue-external-admission/kustomization.yaml
  components/kueue/staging/base/kueue-external-admission/monitoring.yaml
  components/kueue/staging/base/kueue/kueue.yaml
  components/kueue/staging/base/kueue/kustomization.yaml
  components/kueue/staging/base/kueue/operator.yaml
  components/kueue/staging/base/kustomization.yaml
  components/kueue/staging/base/queue-config/cluster-policy.yaml
  components/kueue/staging/base/queue-config/cluster-queue.yaml
  components/kueue/staging/base/queue-config/kustomization.yaml
  components/kueue/staging/base/queue-config/kyverno-rbac.yaml
  components/kueue/staging/base/tekton-kueue-monitoring/kustomization.yaml
  components/kueue/staging/base/tekton-kueue-monitoring/monitoring.yaml
  components/kueue/staging/base/tekton-kueue/controller-patch.yaml
  components/kueue/staging/base/tekton-kueue/kustomization.yaml
  components/kueue/staging/base/tekton-kueue/webhook-patch.yaml
  components/kueue/staging/stone-stg-rh01/kustomization.yaml
Labels: approved

#6685 KubeArchive: remove it from UI config
  components/konflux-ui/production/base/proxy/nginx.conf
  components/konflux-ui/production/base/proxy/proxy.yaml
  components/konflux-ui/production/kflux-ocp-p01/kustomization.yaml
  components/konflux-ui/production/kflux-prd-rh02/kustomization.yaml
  components/konflux-ui/production/kflux-prd-rh03/kustomization.yaml
  components/konflux-ui/production/stone-prd-rh01/kustomization.yaml
  components/konflux-ui/production/stone-prod-p01/kustomization.yaml
Labels: lgtm, approved

#6688 KubeArchive: don't configure UI for p01
  components/konflux-ui/staging/base/proxy/nginx.conf
  components/konflux-ui/staging/base/proxy/proxy.yaml
  components/konflux-ui/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#6691 KubeArchive: fix UI proxy config for positive case
  components/konflux-ui/staging/base/proxy/proxy.yaml
Labels: lgtm, approved

#6690 KubeArchive: fix rh01 naming and add its folder
  argo-cd-apps/base/member/infra-deployments/kubearchive/kubearchive.yaml
  components/kubearchive/staging/stone-stg-rh01/database-secret.yaml
  components/kubearchive/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#6681 Add pipeline descriptions and details
  components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
Labels: lgtm, approved

#6707 fix: typo
  components/build-service/base/build-pipeline-config/build-pipeline-config.yaml
Labels: lgtm, approved

#6657 disable kyverno's helm tests manifests in dev, chainsaw and stg
  components/kyverno/chainsaw/kyverno-helm-generator.yaml
  components/kyverno/chainsaw/kyverno-helm-values.yaml
  components/kyverno/development/kyverno-helm-generator.yaml
  components/kyverno/development/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stage-p01/kyverno-helm-generator.yaml
  components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-generator.yaml
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#6689 give konflux admins permission over Kueue's CRs
  components/authentication/base/konflux-admins.yaml
Labels: lgtm, approved

#6694 dev: Remove the operations key from generate rule
  components/kueue/development/queue-config/cluster-policy.yaml
Labels: lgtm, ok-to-test, approved

#6723 complete removal of mutate-namespace-enforce-label policy
  components/namespace-lister/policies/ns-label/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/chainsaw-test.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/actual-namespace-konflux-toolchain.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/actual-namespace-konflux.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/actual-namespace-toolchain.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/actual-namespace-unlabeled.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/expected-namespace-konflux-toolchain.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/expected-namespace-konflux.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/expected-namespace-toolchain.yaml
  components/namespace-lister/policies/ns-label/.chainsaw-test/resources/expected-namespace-unlabeled.yaml
  components/namespace-lister/policies/ns-label/kustomization.yaml
  components/namespace-lister/policies/ns-label/kyverno-background-konflux-ns-label-clusterrole.yaml
  components/namespace-lister/policies/ns-label/namespace-enforce-label-clusterpolicy.yaml
  components/namespace-lister/production/kflux-ocp-p01/kustomization.yaml
  components/namespace-lister/production/kflux-prd-rh02/kustomization.yaml
  components/namespace-lister/production/kflux-prd-rh03/kustomization.yaml
  components/namespace-lister/production/stone-prod-p01/kustomization.yaml
  components/namespace-lister/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#6758 Add required sudo command into config
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#6771 refresh the pulp access controller
  components/pulp-access-controller/production/kustomization.yaml
  components/pulp-access-controller/staging/kustomization.yaml
Labels: lgtm, approved

#6779 Optimize timeouts for Tekton Results Watcher
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#6784 enable policies component
  argo-cd-apps/base/member/infra-deployments/policies/policies.yaml
Labels: lgtm, approved

#6776 Knative Eventing: Upgrade to improve memory usage
  components/knative-eventing/base/kustomization.yaml
Labels: lgtm, approved

#6787 Fix typo in kubearchive.conf for Konflux UI nginx
  components/konflux-ui/staging/base/proxy/proxy.yaml
Labels: lgtm, approved

#6791 Update internal production with latest MPC version from staging
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
Labels: lgtm, approved

#6792 scrape kyverno metrics in dev and stage
  components/kyverno/development/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stage-p01/kyverno-helm-values.yaml
  components/kyverno/staging/stone-stg-rh01/kyverno-helm-values.yaml
Labels: lgtm, approved

#6796 kyverno: defaults for skipBackgroundRequests and allowExistingViolations
  components/policies/staging/base/konflux-rbac/bootstrap-tenant-namespace/bootstrap-tenant-namespace-rbcm-clusterpolicy.yaml
  components/policies/staging/base/konflux-rbac/restrict-binding-system-authenticated/validate-restrict-binding-system-authenticated-clusterpolicy.yaml
  components/policies/staging/base/konflux-rbac/validate-rolebindings/invalid-subjects.yaml
Labels: lgtm, approved

#6797 add OWNERS file for policies component
  components/policies/OWNERS
Labels: lgtm, approved

#6774 KubeArchive: upgrade to v1.1.0
  components/kubearchive/README.md
  components/kubearchive/development/kustomization.yaml
Labels: lgtm, approved

#6805 KubeArchive: migration Job force replacement
  components/kubearchive/base/migration-job.yaml
Labels: lgtm, approved

#6807 Update public production with latest MPC version from staging
  components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh03/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
Labels: lgtm, approved

#6800 Delete prd-m01 related manifests
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml
  argo-cd-apps/base/member/infra-deployments/knative-eventing/knative-eventing.yaml
  argo-cd-apps/base/member/infra-deployments/konflux-info/konflux-info.yaml
  argo-cd-apps/base/member/infra-deployments/pipeline-service/pipeline-service.yaml
  components/backup/production/stone-prd-m01/backup-s3-credentials-patch.yaml
  components/backup/production/stone-prd-m01/dpa-bucket-patch.yaml
  components/backup/production/stone-prd-m01/dpa-kmskeyid-patch.yaml
  components/backup/production/stone-prd-m01/kustomization.yaml
  components/knative-eventing/production/stone-prd-m01/kustomization.yaml
  components/monitoring/prometheus/production/stone-prd-m01/cluster-id-label.yaml
  components/monitoring/prometheus/production/stone-prd-m01/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/resources/tekton-chains-public-key-path.yaml
  components/pipeline-service/production/stone-prd-m01/resources/tekton-chains-signing-secret-path.yaml
  components/pipeline-service/production/stone-prd-m01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/stone-prd-m01/resources/tekton-results-s3-secret-path.yaml
  components/sandbox/toolchain-host-operator/production/stone-prd-host1/space-provisioner-configs.yaml
  components/sandbox/user-management/production/kubesaw-admins.yaml
  components/sprayproxy/production/change-backends.yaml
Labels: lgtm, approved

#6809 Knative Eventing: update production version
  components/knative-eventing/production/base/kustomization.yaml
Labels: lgtm, approved

#6813 feat(RELEASE-1596): enable emptyDir for push-artifacts-to-cdn
  components/release/development/release_service_config.yaml
Labels: lgtm, approved

#6814 Update Pipelines Production to be in line with staging and devopment
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/resources/kustomization.yaml
  components/pipeline-service/production/kflux-rhel-p01/resources/override-osp-version.yaml
  components/pipeline-service/production/kflux-rhel-p01/resources/update-config-for-osp-1-19.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#6815 Deploy MPC rbac in production
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh03/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
Labels: lgtm, approved

#6808 KubeArchive: changing commonAnnotations
  argo-cd-apps/base/member/infra-deployments/kubearchive/kubearchive.yaml
  components/kubearchive/development/kustomization.yaml
  components/kubearchive/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#6794 KubeArchive: ignoreDifferences in ClusterRoleBinding
  argo-cd-apps/base/member/infra-deployments/kubearchive/kubearchive.yaml
Labels: lgtm, approved

#6825 Promote konflux-ui to prod
  components/konflux-ui/production/base/kustomization.yaml
Labels: lgtm, approved

#6828 Update production repository validator
  components/repository-validator/production/kustomization.yaml
Labels: lgtm, approved

#6781 Promote release-service from staging to production
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#6812 enable multi-repo Github App token scoping
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stage-p01/resources/update-tekton-config-pac.yaml
Labels: lgtm, approved

#6789 feat(KFLUXVNGD-330): deploying smee sidecar in staging
  components/smee-client/OWNERS
  components/smee-client/staging/deployment.yaml
  components/smee-client/staging/kustomization.yaml
  components/smee-client/staging/sever-url-patch.yaml
Labels: lgtm, approved

#6835 fix: allow insecure connection on smee sidecar
  components/smee-client/staging/deployment.yaml
Labels: lgtm, approved

#6843 fix: rename one of the smee servers containers
  components/smee/staging/deployment.yaml
Labels: lgtm, approved

#6844 fix: correct memory request format in Smee deployment configuration
  components/smee/staging/deployment.yaml
Labels: lgtm, approved

#6845 Update the Tekton Results watcher timeouts
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/resources/kustomization.yaml
  components/pipeline-service/production/stone-prod-p02/resources/update-results-timeouts.yaml
Labels: lgtm, approved

#6833 Enable multi-repo Github App token scoping in pipelines production
  components/pipeline-service/production/base/update-tekton-config-pac.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-ocp-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/resources/update-tekton-config-pac.yaml
Labels: lgtm, approved

#6849 Add KubeArchive route to stone-stg-rh01
  components/kubearchive/staging/stone-stg-rh01/kubearchive-routes.yaml
  components/kubearchive/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#6854 stage: Update tekton-kueue resource req/lim
  components/kueue/staging/base/tekton-kueue/webhook-patch.yaml
Labels: lgtm, approved

#6858 chore: update gosmee image in staging
  components/smee-client/staging/deployment.yaml
  components/smee/staging/deployment.yaml
Labels: lgtm, approved

#6857 Update store deadline and pruner time values
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#6862 fix appstudio pipelines runner cr conflict prod
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/scc-rbac.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/resources/scc-rbac.yaml
Labels: lgtm, approved

#6872 Update stg-rh01 PPC static VM IP Address
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#6875 etcd-shield: use in-memory IPC in staging
  components/etcd-shield/base/deployment.yaml
  components/etcd-shield/base/kustomization.yaml
Labels: lgtm, approved

#6859 KFLUXINFRA-1734: Add a dashboard for Kueue
  components/monitoring/grafana/base/dashboards/kueue/dashboard.yaml
  components/monitoring/grafana/base/dashboards/kueue/kueue.json
  components/monitoring/grafana/base/dashboards/kueue/kustomization.yaml
  components/monitoring/grafana/base/dashboards/kustomization.yaml
Labels: do-not-merge/hold, approved

#6871 Enable kubearchive access from nginx in prod if configured
  components/konflux-ui/production/base/proxy/proxy.yaml
Labels: lgtm, approved

#6886 Upgrade OADP operator on all clusters
  components/backup/base/all-clusters/oadp/install-oadp.yaml
  components/backup/staging/stone-stage-p01/dpa-channel-patch.yaml
  components/backup/staging/stone-stage-p01/kustomization.yaml
  components/backup/staging/stone-stg-rh01/dpa-channel-patch.yaml
  components/backup/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#6883 disable cost-management policy in development
  components/policies/development/kustomization.yaml
Labels: lgtm, approved

#6893 complete kubearchive prod policies migration
  components/kubearchive/policies/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
  components/kubearchive/policies/.chainsaw-test/chainsaw-test.yaml
  components/kubearchive/policies/.chainsaw-test/resources/actual-kubeconfig-archive.yaml
  components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-konfluxcidev.yaml
  components/kubearchive/policies/.chainsaw-test/resources/actual-namespace-unlabeled.yaml
  components/kubearchive/policies/.chainsaw-test/resources/expected-kubearchiveconfig.yaml
  components/kubearchive/policies/.chainsaw-test/resources/kubearchive-crd.yaml
  components/kubearchive/policies/.kyverno-test/kyverno-test.yaml
  components/kubearchive/policies/bootstrap-namespace.yaml
  components/kubearchive/policies/kustomization.yaml
  components/kubearchive/policies/kyverno_rbac.yaml
  components/kubearchive/policies/resources/expected-kubearchiveconfig-konflux.yaml
  components/kubearchive/policies/resources/labeled-namespace-konflux.yaml
  components/kubearchive/production/base/kustomization.yaml
Labels: lgtm, approved

#6915 chore: move smee server sidecar to file based probe
  components/smee/staging/deployment.yaml
Labels: lgtm, do-not-merge/hold, approved

#6922 fix: increase smee sidecar memory
  components/smee-client/staging/deployment.yaml
  components/smee/staging/deployment.yaml
Labels: lgtm, approved

#6903 Fix Tekton Results grafana dashboard rates
  components/monitoring/grafana/base/dashboards/pipeline-service/grafana-config.yaml
Labels: lgtm, approved

#6926 Increase statefulsets quota
  components/sandbox/tiers/production/appstudio/kustomization.yaml
  components/sandbox/tiers/production/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-clusterresources-487279487-487279487.yaml
  components/sandbox/tiers/production/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/production/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-607699003-487279487.yaml
  components/sandbox/tiers/production/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/production/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-1081386182-487279487.yaml
  components/sandbox/tiers/src/appstudio/cluster.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-clusterresources-487279487-487279487.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-clusterresources-607699003-487279487.yaml
  components/sandbox/tiers/staging/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-clusterresources-1081386182-487279487.yaml
Labels: lgtm, approved

#6925 Grant test-platform-ci admins permission to troubleshoot testplatformclusters Claim and XR
  components/authentication/base/group-sync/kustomization.yaml
  components/authentication/base/group-sync/test-platform-ci-admins-rover-group.yaml
  components/authentication/base/kustomization.yaml
  components/authentication/base/test-platform-ci-admins-can-view.yaml
  components/authentication/k-components/ldap-url-patch/kustomization.yaml
Labels: lgtm, ok-to-test, approved

#6928 chore: update references to ec config repo
  components/enterprise-contract/ecp.yaml
Labels: lgtm, approved

#6931 Grant test-platform-ci admins permission to view crossplane objects
  components/authentication/base/test-platform-ci-admins-can-view.yaml
Labels: lgtm, ok-to-test, approved

#6930 Allow ansible-automation-platform-azure-billing-operator
  components/repository-validator/production/kustomization.yaml
Labels: lgtm, approved
