Repository redhat-appstudio/infra-deployments, pull requests merged in 2025-08, with the labels that each got.

#7385 KubeArchive: add vacuum to prevent missing messages
  components/kubearchive/development/kustomization.yaml
  components/kubearchive/development/vacuum.yaml
Labels: lgtm, approved

#7422 remove host operator subscription from stage-p01
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/kustomization.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/patch_resources.yaml
Labels: lgtm, approved

#7429 feat(SPRE-1702): Test Recording Rules
  components/monitoring/prometheus/staging/stone-stg-rh01/kustomization.yaml
  components/monitoring/prometheus/staging/stone-stg-rh01/prometheus_rule_test.yaml
Labels: lgtm, approved

#7433 feat(SPRE-1702): Rollback recording rules
  components/monitoring/prometheus/staging/stone-stg-rh01/kustomization.yaml
  components/monitoring/prometheus/staging/stone-stg-rh01/prometheus_rule_test.yaml
Labels: lgtm, approved

#7447 SRVKP-8255: Patch PAC images on stage
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#7446 feat(kite): use specific SHA for tag
  components/konflux-kite/base/kustomization.yaml
Labels: lgtm, approved

#7442 KONFLUX-8860: Swapping PPC Nodes for RHEL Environment
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/external-secrets.yaml
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml
Labels: lgtm, approved

#7441 KFLUXINFRA-1956: Deploy Kueue on rh02 and rh03
  argo-cd-apps/base/member/infra-deployments/kueue/kueue.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  components/kueue/production/base/kueue/kueue.yaml
  components/kueue/production/base/kueue/kustomization.yaml
  components/kueue/production/base/kueue/operator.yaml
  components/kueue/production/base/kustomization.yaml
  components/kueue/production/base/queue-config/kustomization.yaml
  components/kueue/production/base/queue-config/mintmaker-local-queue.yaml
  components/kueue/production/base/queue-config/workload-priority-class.yaml
  components/kueue/production/base/tekton-kueue-monitoring/kueue-prometheus-alerts.yaml
  components/kueue/production/base/tekton-kueue-monitoring/kustomization.yaml
  components/kueue/production/base/tekton-kueue-monitoring/monitoring.yaml
  components/kueue/production/base/tekton-kueue/config.yaml
  components/kueue/production/base/tekton-kueue/controller-patch.yaml
  components/kueue/production/base/tekton-kueue/kustomization.yaml
  components/kueue/production/base/tekton-kueue/webhook-patch.yaml
  components/kueue/production/empty-base/.git-empty
  components/kueue/production/kflux-prd-rh02/kustomization.yaml
  components/kueue/production/kflux-prd-rh02/queue-config/cluster-queue.yaml
  components/kueue/production/kflux-prd-rh02/queue-config/kustomization.yaml
  components/kueue/production/kflux-prd-rh03/kustomization.yaml
  components/kueue/production/kflux-prd-rh03/queue-config/cluster-queue.yaml
  components/kueue/production/kflux-prd-rh03/queue-config/kustomization.yaml
  hack/kueue-vm-quotas/generate-queue-config.sh
Labels: approved

#7465 Update cluster queue resource for rh03
  components/kueue/production/kflux-prd-rh03/queue-config/cluster-queue.yaml
Labels: approved

#7420 member-operator: split config for each cluster
  argo-cd-apps/base/toolchain-member/toolchain-member-operator.yaml
  components/sandbox/toolchain-member-operator/production/base/kustomization.yaml
  components/sandbox/toolchain-member-operator/production/base/patch_resources.yaml
  components/sandbox/toolchain-member-operator/production/base/sandbox-sre-member.yaml
  components/sandbox/toolchain-member-operator/production/kflux-ocp-p01/kustomization.yaml
  components/sandbox/toolchain-member-operator/production/kflux-osp-p01/kustomization.yaml
  components/sandbox/toolchain-member-operator/production/kflux-prd-es01/kustomization.yaml
  components/sandbox/toolchain-member-operator/production/kflux-prd-rh02/kustomization.yaml
  components/sandbox/toolchain-member-operator/production/kflux-prd-rh03/kustomization.yaml
  components/sandbox/toolchain-member-operator/production/kflux-rhel-p01/kustomization.yaml
  components/sandbox/toolchain-member-operator/production/stone-prd-rh01/kustomization.yaml
  components/sandbox/toolchain-member-operator/production/stone-prod-p01/kustomization.yaml
  components/sandbox/toolchain-member-operator/production/stone-prod-p02/kustomization.yaml
  components/sandbox/toolchain-member-operator/staging/base/kustomization.yaml
  components/sandbox/toolchain-member-operator/staging/base/patch_resources.yaml
  components/sandbox/toolchain-member-operator/staging/kflux-stg-es01/kustomization.yaml
  components/sandbox/toolchain-member-operator/staging/stone-stage-p01/kustomization.yaml
  components/sandbox/toolchain-member-operator/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#7470 SRVKP-8255: Patch PAC images on stage
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#7472 SRVKP-8255: Run one PAC watcher replica
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#7473 SRVKP-8255: Patch PAC images on stage
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: approved

#7428 improve the banner readme
  components/konflux-info/README.md
  components/konflux-info/banner-schema.json
Labels: lgtm, approved

#7431 remove host-operator config from stage-p01
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/kustomization.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/network-policy.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/ns.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/space-provisioner-configs.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stage-p01/toolchainconfig.yaml
Labels: lgtm, approved

#7484 Mintmaker redis memory usage added
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#7483 chore(): update internal-service OWNERS for new members
  components/internal-services/OWNERS
Labels: lgtm, approved

#7491 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#7493 KFLUXINFRA-1958: Deploy Kueue on additional clusters
  argo-cd-apps/base/member/infra-deployments/kueue/kueue.yaml
  components/kueue/production/kflux-ocp-p01/kustomization.yaml
  components/kueue/production/kflux-ocp-p01/queue-config/cluster-queue.yaml
  components/kueue/production/kflux-ocp-p01/queue-config/kustomization.yaml
  components/kueue/production/kflux-osp-p01/kustomization.yaml
  components/kueue/production/kflux-osp-p01/queue-config/cluster-queue.yaml
  components/kueue/production/kflux-osp-p01/queue-config/kustomization.yaml
  components/kueue/production/kflux-rhel-p01/kustomization.yaml
  components/kueue/production/kflux-rhel-p01/queue-config/cluster-queue.yaml
  components/kueue/production/kflux-rhel-p01/queue-config/kustomization.yaml
  components/kueue/production/stone-prod-p01/kustomization.yaml
  components/kueue/production/stone-prod-p01/queue-config/cluster-queue.yaml
  components/kueue/production/stone-prod-p01/queue-config/kustomization.yaml
  hack/kueue-vm-quotas/__pycache__/update-kueue-vm-quotas.cpython-313.pyc
  hack/kueue-vm-quotas/generate-queue-config.sh
Labels: lgtm, approved

#7501 Changing GPU Based AMI ID for OpenStack Environment
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
Labels: lgtm, approved

#7380 KubeArchive: install kflux-rhel-p01
  argo-cd-apps/base/member/infra-deployments/kubearchive/kubearchive.yaml
  components/konflux-ui/production/kflux-rhel-p01/kustomization.yaml
  components/kubearchive/production/kflux-rhel-p01/kustomization.yaml
  components/policies/production/kflux-rhel-p01/kustomization.yaml
Labels: lgtm, approved

#7496 mintmaker: re-enable renovate runs on Saturday
  components/mintmaker/base/cronjobs/create-dependency-update-check.yaml
Labels: lgtm, approved

#7488 stone-stage-p01: remove member operator resources
  components/sandbox/toolchain-member-operator/staging/stone-stage-p01/kustomization.yaml
  components/sandbox/toolchain-member-operator/staging/stone-stage-p01/ns.yaml
Labels: lgtm, approved

#7434 stone-stg-host: remove host-operator subscription
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/kustomization.yaml
  components/sandbox/toolchain-host-operator/staging/stone-stg-host/patch_resources.yaml
Labels: lgtm, approved

#7511 Add more owners to Kite service
  components/konflux-kite/OWNERS
Labels: lgtm, approved

#7409 KFLUXINFRA-2015: Enable newer arm64 instance types (m7g+)
  components/multi-platform-controller/production/kflux-prd-rh03/host-config.yaml
Labels: lgtm, approved

#7342 KubeArchive: install on stone-stage-p01
  argo-cd-apps/base/member/infra-deployments/kubearchive/kubearchive.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  components/konflux-ui/staging/stone-stage-p01/kubearchive.conf
  components/konflux-ui/staging/stone-stage-p01/kustomization.yaml
  components/kubearchive/staging/stone-stage-p01/database-secret.yaml
  components/kubearchive/staging/stone-stage-p01/kubearchive-routes.yaml
  components/kubearchive/staging/stone-stage-p01/kustomization.yaml
  components/policies/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#7523 Make queue generation script output deterministic
  components/kueue/production/kflux-ocp-p01/queue-config/cluster-queue.yaml
  components/kueue/production/kflux-osp-p01/queue-config/cluster-queue.yaml
  components/kueue/production/kflux-prd-rh02/queue-config/cluster-queue.yaml
  components/kueue/production/kflux-prd-rh03/queue-config/cluster-queue.yaml
  components/kueue/production/kflux-rhel-p01/queue-config/cluster-queue.yaml
  components/kueue/production/stone-prd-rh01/queue-config/cluster-queue.yaml
  components/kueue/production/stone-prod-p01/queue-config/cluster-queue.yaml
  components/kueue/production/stone-prod-p02/queue-config/cluster-queue.yaml
  components/kueue/staging/stone-stage-p01/queue-config/cluster-queue.yaml
  components/kueue/staging/stone-stg-rh01/queue-config/cluster-queue.yaml
  hack/kueue-vm-quotas/update-kueue-vm-quotas.py
Labels: lgtm, approved

#7517 Remove member operator subscription on RH01
  components/sandbox/toolchain-member-operator/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#7533 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#7548 KubeArchive: fix trace sending to konflux-otel
  components/kubearchive/staging/stone-stg-rh01/otel-collector-config.yaml
Labels: lgtm, approved

#7549 KubeArchive: add logging namespace to allowed for vault
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: lgtm, approved

#7554 Fix race condition when generating charts
  argo-cd-apps/base/member/infra-deployments/vector-kubearchive-log-collector/vector-kubearchive-log-collector.yaml
  components/vector-kubearchive-log-collector/base/kustomization.yaml
  components/vector-kubearchive-log-collector/development/kustomization.yaml
  components/vector-kubearchive-log-collector/development/vector-helm-generator.yaml
  components/vector-kubearchive-log-collector/development/vector-helm-values.yaml
  components/vector-kubearchive-log-collector/staging/base/kustomization.yaml
  components/vector-kubearchive-log-collector/staging/stone-stg-rh01/.gitignore
  components/vector-kubearchive-log-collector/staging/stone-stg-rh01/kustomization.yaml
  components/vector-kubearchive-log-collector/staging/stone-stg-rh01/vector-helm-generator.yaml
  components/vector-kubearchive-log-collector/staging/stone-stg-rh01/vector-helm-values.yaml
Labels: lgtm, approved

#7557 KFLUXINFRA-1986: Update Kueue dashboard
  components/monitoring/grafana/base/dashboards/kueue/kueue.json
Labels: approved

#7564 Give platform prometheus permission to scrape tekton-kueue
  components/kueue/development/tekton-kueue-monitoring/monitoring.yaml
  components/kueue/production/base/tekton-kueue-monitoring/monitoring.yaml
  components/kueue/staging/base/tekton-kueue-monitoring/monitoring.yaml
Labels: approved

#7576 mintmaker: set GOMEMLIMIT to avoid controller OOMKilled crashes
  components/mintmaker/production/base/manager_patch.yaml
Labels: lgtm, approved

#7568 Make kubearchive admins of the product-kubearchive-logging component
  components/vector-kubearchive-log-collector/base/kustomization.yaml
  components/vector-kubearchive-log-collector/base/rbac.yaml
Labels: lgtm, approved

#7553 Recording Rule uwm stage
  components/monitoring/prometheus/staging/base/kustomization.yaml
  components/monitoring/prometheus/staging/stone-stg-rh01/kustomization.yaml
  components/monitoring/prometheus/staging/stone-stg-rh01/prometheusrule-uwm.yaml
Labels: lgtm, approved

#7509 o11y: Split MonitoringStack by environment
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
  components/monitoring/prometheus/development/monitoringstack/cluster-type-patch.yaml
  components/monitoring/prometheus/development/monitoringstack/kustomization.yaml
  components/monitoring/prometheus/production/base/monitoringstack/endpoints-params.yaml
  components/monitoring/prometheus/production/base/monitoringstack/kustomization.yaml
  components/monitoring/prometheus/production/base/monitoringstack/writeRelabelConfigs.yaml
  components/monitoring/prometheus/staging/base/monitoringstack/endpoints-params.yaml
  components/monitoring/prometheus/staging/base/monitoringstack/kustomization.yaml
  components/monitoring/prometheus/staging/base/monitoringstack/writeRelabelConfigs.yaml
Labels: lgtm, approved

#7508 PVO11Y-4876: Enable prometheus exporter/pipeline for Konflux opentelemetry in staging
  components/tracing/otel-collector/staging/otel-collector-helm-values.yaml
Labels: lgtm, ok-to-test, approved

#7563 KFLUXINFRA-2067: Push Kueue metrics to RHOBS
  components/monitoring/prometheus/production/base/monitoringstack/endpoints-params.yaml
  components/monitoring/prometheus/production/base/monitoringstack/writeRelabelConfigs.yaml
  components/monitoring/prometheus/staging/base/monitoringstack/endpoints-params.yaml
  components/monitoring/prometheus/staging/base/monitoringstack/writeRelabelConfigs.yaml
Labels: lgtm, approved

#7542 Remove member operator subscription on stg es-01
  components/sandbox/toolchain-member-operator/staging/kflux-stg-es01/kustomization.yaml
Labels: lgtm, approved, ¯\_(ツ)_/¯

#7601 Make argo ignore the secret updates
  components/kubearchive/staging/base/external-secret.yaml
Labels: lgtm, approved

#7602 Get rid of toolchain member operator on staging
  components/sandbox/toolchain-member-operator/staging/base/kustomization.yaml
  components/sandbox/toolchain-member-operator/staging/base/ns.yaml
  components/sandbox/toolchain-member-operator/staging/base/patch_resources.yaml
  components/sandbox/toolchain-member-operator/staging/kflux-stg-es01/kustomization.yaml
  components/sandbox/toolchain-member-operator/staging/stone-stage-p01/kustomization.yaml
  components/sandbox/toolchain-member-operator/staging/stone-stg-rh01/kustomization.yaml
  components/sandbox/toolchain-member-operator/staging/stone-stg-rh01/ns.yaml
Labels: lgtm, approved

#7606 Enable konflux-admins to manage OCP projects
  components/authentication/base/konflux-admins.yaml
Labels: lgtm, approved

#7610 Update PAC on staging
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#7609 mintmaker: enable profiling in staging
  components/mintmaker/staging/base/manager_patch.yaml
Labels: lgtm, approved

#7612 mintmaker: Fix YAML type error in mintmaker manager patch
  components/mintmaker/staging/base/manager_patch.yaml
Labels: lgtm, approved

#7615 Update PAC image on rh02 and rh03 & Enable queuing for all pipelineruns on rh02 and rh03
  components/kueue/production/kflux-prd-rh02/kustomization.yaml
  components/kueue/production/kflux-prd-rh03/kustomization.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/kustomization.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/override-pac-images.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/kustomization.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/override-pac-images.yaml
Labels: lgtm, approved

#7622 mintmaker: enable profiling in stone-prod-p02
  components/mintmaker/production/stone-prod-p02/kustomization.yaml
  components/mintmaker/production/stone-prod-p02/manager_patch.yaml
Labels: lgtm, approved

#7619 Override pac images to v0.37.0 in production
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-osp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/kustomization.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/override-missing-operator-proxy-image.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/override-pac-images.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/kustomization.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/override-pac-images.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/override-pac-images.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#7626 Delete the original secret
  components/kubearchive/staging/base/kustomization.yaml
Labels: lgtm, approved

#7620 update pipelines index image in development and staging
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#7640 KFLUXINFRA-2066: Enable Kueue of all PLRs in p02
  components/kueue/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#7624 KubeArchive: upgrade staging to v1.6.0
  components/kubearchive/development/kustomization.yaml
  components/kubearchive/development/release-vacuum.yaml
  components/kubearchive/development/vacuum.yaml
Labels: lgtm, approved

#7643 KFLUXINFRA-2066: Enable Kueue of all PLRs in rhel, osp, p01
  components/kueue/production/kflux-osp-p01/kustomization.yaml
  components/kueue/production/kflux-rhel-p01/kustomization.yaml
  components/kueue/production/stone-prod-p01/kustomization.yaml
Labels: lgtm, approved

#7647 Add some more AWS quotas for AMD(160) and ARM(160) on p02
  components/kueue/production/stone-prod-p02/queue-config/cluster-queue.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: lgtm, approved

#7656 Update Kueue dashboard
  components/monitoring/grafana/base/dashboards/kueue/kueue.json
Labels: lgtm, approved

#7660 Upgrade MCE operator to 2.9 in prod
  components/cluster-as-a-service/base/multicluster-engine.yaml
  components/cluster-as-a-service/production/add-hypershift-params.yaml
Labels: lgtm, approved

#7633 feat(update): Update kite SHA tag
  components/konflux-kite/base/kustomization.yaml
Labels: lgtm, approved

#7661 Promoting component mintmaker from stage to prod
  components/mintmaker/production/base/kustomization.yaml
Labels: lgtm, approved

#7666 Align prod-p02 kyverno config with prd-rh01 one
  components/kyverno/production/stone-prod-p02/kyverno-helm-values.yaml
Labels: lgtm, approved

#7714 Modified owners
  components/mintmaker/OWNERS
Labels: lgtm, approved

#7715 feat(/SPRE-1819) Latency metric api server
  components/monitoring/prometheus/production/base/monitoringstack/endpoints-params.yaml
  components/monitoring/prometheus/staging/base/monitoringstack/endpoints-params.yaml
Labels: lgtm, approved

#7708 Refactor nginx config in prod
  components/konflux-ui/production/base/proxy/auth.conf
  components/konflux-ui/production/base/proxy/kubearchive.conf
  components/konflux-ui/production/base/proxy/kustomization.yaml
  components/konflux-ui/production/base/proxy/nginx.conf
  components/konflux-ui/production/base/proxy/proxy.yaml
  components/konflux-ui/production/base/proxy/tekton-results-workspaces.conf
  components/konflux-ui/production/base/proxy/tekton-results.conf
  components/konflux-ui/production/kflux-ocp-p01/kustomization.yaml
  components/konflux-ui/production/kflux-osp-p01/kubearchive.conf
  components/konflux-ui/production/kflux-osp-p01/kustomization.yaml
  components/konflux-ui/production/kflux-prd-rh02/kubearchive.conf
  components/konflux-ui/production/kflux-prd-rh02/kustomization.yaml
  components/konflux-ui/production/kflux-prd-rh03/kustomization.yaml
  components/konflux-ui/production/kflux-rhel-p01/kustomization.yaml
  components/konflux-ui/production/stone-prd-rh01/kubearchive.conf
  components/konflux-ui/production/stone-prd-rh01/kustomization.yaml
  components/konflux-ui/production/stone-prod-p01/kubearchive.conf
  components/konflux-ui/production/stone-prod-p01/kustomization.yaml
  components/konflux-ui/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#7727 rhel: remove member-operator subscription
  components/sandbox/toolchain-member-operator/production/kflux-rhel-p01/kustomization.yaml
Labels: lgtm, approved

#7737 fix name of ClusterPolicy in stg
  components/policies/staging/base/konflux-rbac/restrict-binding-system-authenticated-releng/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
  components/policies/staging/base/konflux-rbac/restrict-binding-system-authenticated-releng/kyverno_rbac.yaml
  components/policies/staging/base/konflux-rbac/restrict-binding-system-authenticated-releng/validate-restrict-binding-system-authenticated-releng-clusterpolicy.yaml
Labels: lgtm, approved

#7725 Set memory request and limits to same values for ESO
  components/external-secrets-operator/base/operator-config.yaml
Labels: lgtm, approved

#7735 Disable member-operator on osp-p01
  components/sandbox/toolchain-member-operator/production/kflux-osp-p01/kustomization.yaml
Labels: lgtm, approved

#7731 feat(SPRE-1818): Include uwm recording rules
  components/monitoring/prometheus/base/monitoringstack/kustomization.yaml
  components/monitoring/prometheus/base/monitoringstack/prometheusrule-uwm.yaml
  components/monitoring/prometheus/staging/base/monitoringstack/kustomization.yaml
  components/monitoring/prometheus/staging/base/monitoringstack/prometheusrule-uwm.yaml
  components/monitoring/prometheus/staging/stone-stg-rh01/kustomization.yaml
  components/monitoring/prometheus/staging/stone-stg-rh01/prometheusrule-uwm.yaml
Labels: lgtm, approved

#7742 Eventing: add klog verbose flag on the image
  components/knative-eventing/base/kustomization.yaml
Labels: lgtm, approved

#7749 feat(SPRE-1818): Include uwm recording rules in prod
  components/monitoring/prometheus/production/base/monitoringstack/kustomization.yaml
  components/monitoring/prometheus/production/base/monitoringstack/prometheusrule-uwm.yaml
Labels: lgtm, approved

#7758 Align MPC approvers/reviewers to reflect actual state
  components/multi-platform-controller/OWNERS
Labels: lgtm, approved

#7739 KFLUXINFRA-2048 Part I - release to private production clusters
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
Labels: lgtm, approved

#7762 Organising Stage Metrics
  components/monitoring/prometheus/staging/base/monitoringstack/endpoints-params.yaml
Labels: lgtm, approved

#7763 KubeArchive: make ApiServerSource monitor all the namespaces
  components/kubearchive/development/kubearchive.yaml
  components/kubearchive/development/kustomization.yaml
Labels: lgtm, approved

#7767 Increase quota for linux extra fast on rh01
  components/kueue/production/stone-prd-rh01/queue-config/cluster-queue.yaml
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#7768 Fix incorrect namespace in KubeArchive ClusterRoleBinding subject
  components/kubearchive/development/kustomization.yaml
Labels: lgtm, approved

#7770 feat(SPRE-1675): Include apiserver etcd cpu and memory metrics prod
  components/monitoring/prometheus/production/base/monitoringstack/endpoints-params.yaml
Labels: lgtm, approved

#7782 deleted 'linux-test-arm64' platform from stone-stg-rh01
  components/kueue/staging/stone-stg-rh01/kustomization.yaml
  components/kueue/staging/stone-stg-rh01/queue-config/cluster-queue.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#7783 Removing duplicates from stage stack file
  components/monitoring/prometheus/staging/base/monitoringstack/endpoints-params.yaml
Labels: lgtm, approved

#7786 feat(SPRE-1626) Adding namespace release-service
  components/monitoring/prometheus/staging/base/monitoringstack/endpoints-params.yaml
Labels: lgtm, approved

#7789 kflux-osp-p01: remove member operator installation
  components/sandbox/toolchain-member-operator/production/kflux-osp-p01/kustomization.yaml
  components/sandbox/toolchain-member-operator/production/kflux-osp-p01/ns.yaml
Labels: lgtm, approved

#7787 Replicating stage changes in prod
  components/monitoring/prometheus/production/base/monitoringstack/endpoints-params.yaml
Labels: lgtm, approved

#7794 Add MPC VM to test new s390x base image
  components/kueue/production/kflux-rhel-p01/queue-config/cluster-queue.yaml
  components/multi-platform-controller/production-downstream/kflux-rhel-p01/host-config.yaml
Labels: lgtm, approved

#7797 Update project-controller
  components/project-controller/production/kustomization.yaml
Labels: lgtm, approved

#7795 Update OSP to version 5.0.5-646 (prod)
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-osp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/pentest-p01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#7355 KONFLUX-134: Cancel in-progress PipelineRuns for updated pull requests (prod)
  components/pipeline-service/production/base/update-tekton-config-pac.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-ocp-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/kflux-osp-p01/deploy.yaml
  components/pipeline-service/production/kflux-osp-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/resources/update-tekton-config-pac.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  hack/new-cluster/templates/pipeline-service/deploy.yaml
  hack/new-cluster/templates/pipeline-service/resources/update-tekton-config-pac.yaml
Labels: lgtm, approved

#7801 add missing roles to clusters with removed kubesaw
  components/konflux-rbac/production/base/konflux-integration-runner.yaml
  components/konflux-rbac/production/base/kustomization.yaml
  components/konflux-rbac/production/kflux-prd-rh03/kustomization.yaml
  components/konflux-rbac/production/stone-prd-rh01/kustomization.yaml
  components/konflux-rbac/production/stone-prod-p01/kustomization.yaml
  components/konflux-rbac/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#7802 override pac images to v0.37.0 in staging
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-osp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#7803 override pac images to v0.37.0 in prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-osp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/pentest-p01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#7808 remove appstudio-pipelines-runner from new cluster templates
  hack/new-cluster/templates/pipeline-service/resources/scc-rbac.yaml
Labels: lgtm, approved

#7791 Stop alerts on pentest cluster by disabling metrics export
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml
Labels: lgtm, approved

#7811 Disable kubearchive from UI in pentest cluster
  argo-cd-apps/base/member/infra-deployments/kubearchive/kubearchive.yaml
  components/konflux-ui/production/pentest-p01/kubearchive.conf
  components/konflux-ui/production/pentest-p01/kustomization.yaml
Labels: lgtm, approved

#7632 add custom-console-url-namespace in prod
  components/pipeline-service/production/base/update-tekton-config-pac.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-ocp-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/kflux-osp-p01/deploy.yaml
  components/pipeline-service/production/kflux-osp-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/kflux-prd-rh03/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh03/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/kflux-rhel-p01/deploy.yaml
  components/pipeline-service/production/kflux-rhel-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/resources/update-tekton-config-pac.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/resources/update-tekton-config-pac.yaml
Labels: lgtm, approved

#7600 add ClusterPolicy to deny reserved virtual domain
  components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/chainsaw-assert-clusterpolicy.yaml
  components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/chainsaw-test.yaml
  components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/resources/namespace-no-labels.yaml
  components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/resources/namespace-with-virtual-annotation.yaml
  components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/resources/namespace-with-virtual-label.yaml
  components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/resources/tenant-namespace-with-virtual-annotation.yaml
  components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/resources/tenant-namespace-with-virtual-label.yaml
  components/policies/development/namespace-lister/deny-virtual-domain/.chainsaw-test/resources/tenant-namespace.yaml
  components/policies/development/namespace-lister/deny-virtual-domain/deny-virtual-domain.yaml
  components/policies/development/namespace-lister/deny-virtual-domain/kustomization.yaml
  components/policies/development/namespace-lister/kustomization.yaml
  components/policies/staging/base/kustomization.yaml
  components/policies/staging/base/namespace-lister/kustomization.yaml
Labels: lgtm, approved

#7759 Deploy updated kanary supported clusters to prod
  components/monitoring/kanary/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#7821 Stop alerts on pentest cluster by disabling metrics export v2
  components/monitoring/prometheus/production/pentest-p01/cluster-id-label.yaml
  components/monitoring/prometheus/production/pentest-p01/kustomization.yaml
Labels: lgtm, approved

#7824 use Group/Version/Kind in deny-virtual-domain
  components/policies/development/namespace-lister/deny-virtual-domain/deny-virtual-domain.yaml
Labels: lgtm, approved

#7796 Increase registry pull QPS to avoid 'pull QPS exceeded' errors
  argo-cd-apps/base/all-clusters/infra-deployments/kubelet-config/kubelet.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/kubelet-config/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  configs/kubelet-config/base/kubelet-patch.yaml
  configs/kubelet-config/base/kustomization.yaml
  configs/kubelet-config/production/kustomization.yaml
  configs/kubelet-config/staging/kustomization.yaml
Labels: lgtm, approved

#7828 bump otel collector version
  components/tracing/otel-collector/development/otel-collector-helm-values.yaml
  components/tracing/otel-collector/staging/otel-collector-helm-values.yaml
Labels: lgtm, approved

#7838 promote ui to production
  components/konflux-ui/production/base/kustomization.yaml
Labels: lgtm, approved

#7827 KubeArchive: install watchers solution on prd-rh03
  components/kubearchive/production/kflux-prd-rh03/kubearchive.yaml
  components/kubearchive/production/kflux-prd-rh03/kustomization.yaml
Labels: lgtm, approved

#7848 release-service prod update
  components/release/production/kustomization.yaml
Labels: lgtm, approved

#7858 staging: use exclusion lists for resources
  components/backup/staging/stone-stage-p01/backup-tenants-patch.yaml
  components/backup/staging/stone-stage-p01/kustomization.yaml
  components/backup/staging/stone-stg-rh01/backup-tenants-patch.yaml
  components/backup/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#7874 fix ingester credentials error
  components/vector-kubearchive-log-collector/staging/stone-stg-rh01/loki-helm-values.yaml
  components/vector-kubearchive-log-collector/staging/stone-stg-rh01/rbac.yaml
Labels: lgtm, approved

#7872 Reverting changes that were made as part of KFLUXINFRA-2177
  components/backup/staging/stone-stg-rh01/dpa-resource-modifier-patch.yaml
  components/backup/staging/stone-stg-rh01/image-repository-resource-modifier.yaml
  components/backup/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#7875 Add o11y team members
  OWNERS
Labels: lgtm, approved

#7877 Reenable pentest monitoring
  argo-cd-apps/base/all-clusters/infra-deployments/monitoring-workload-prometheus/monitoring-workload-prometheus.yaml
  components/monitoring/prometheus/production/pentest-p01/cluster-id-label.yaml
  components/monitoring/prometheus/production/pentest-p01/kustomization.yaml
Labels: lgtm, approved

#7880 Allow up to 250 VMs of each AWS type
  components/kueue/production/stone-prod-p02/queue-config/cluster-queue.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: lgtm, approved

#7879 Add stone-prod-p02 PPC maintenance to banner
  components/konflux-info/production/stone-prod-p02/banner-content.yaml
Labels: lgtm, approved

#7773 KFLUXINFRA-2161: Control AWS IP requests using Kueue
  components/kueue/development/queue-config/cluster-queue.yaml
  components/kueue/development/tekton-kueue/config.yaml
  hack/test-tekton-kueue-config.py
Labels: lgtm, approved

#7891 Update MPC stone-prod-p02 host config
  components/multi-platform-controller/production-downstream/stone-prod-p02/external-secrets.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: lgtm, approved
