Repository redhat-appstudio/infra-deployments, pull requests merged in 2025-02, with the labels that each got.

#5398 switch pipelines and remote resolver controllers on prod m01 to state…
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/resources/osp-perf-statefulSets.yaml
Labels: lgtm, approved

#5436 [Staging] Change Tekton Vector collection to in-memory and ack enabled
  components/vector-tekton-logs-collector/development/vector-helm-values.yaml
  components/vector-tekton-logs-collector/staging/vector-helm-values.yaml
Labels: lgtm, approved

#5450 Remove gnaponie from MintMaker
  components/mintmaker/OWNERS
Labels: lgtm, approved

#5437 Replace ec-release-policy tag with floating tag
  components/enterprise-contract/ecp.yaml
Labels: lgtm, approved

#5453 Deploy new MPC version to downstream
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
Labels: lgtm, approved

#5455 KFLUXINFRA-1100: Add PPC64 dynamic for prod-rh02
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
Labels: approved

#5456 Ibm multi prod rh02 re-enable static nodes for ppc
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
Labels: approved

#5457 KFLUXINFRA-1100: Added dynamic ppc hosts for prod-rh02
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
Labels: lgtm, do-not-merge/hold, approved

#5458 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#5454 [Prod] Change Tekton Vector collection to in-memory and ack enabled
  components/vector-tekton-logs-collector/production/vector-helm-values.yaml
Labels: lgtm, approved

#5327 kyverno: rollout to all staging clusters
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
Labels: lgtm, approved

#5463 Promote MintMaker changes from stage to prod
  components/mintmaker/production/base/kustomization.yaml
Labels: lgtm, approved

#5464 Add the MPC image tags into preview template
  hack/preview-template.env
Labels: lgtm, approved

#5419 chore: udpate hac-dev to latest
  components/ui/production/kflux-ocp-p01/kustomization.yaml
  components/ui/production/stone-prod-p01/kustomization.yaml
  components/ui/production/stone-prod-p02/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: lgtm, approved

#5441 update sandbox host-operator's ServiceMonitor
  components/sandbox/toolchain-host-operator/base/monitoring/kustomization.yaml
  components/sandbox/toolchain-host-operator/base/monitoring/monitor.yaml
  components/sandbox/toolchain-host-operator/base/monitoring/prometheus-network-policy.yaml
  components/sandbox/toolchain-host-operator/base/monitoring/rbac.yaml
  components/sandbox/toolchain-host-operator/base/monitoring/sandbox-registration-service-proxy.yaml
  components/sandbox/toolchain-host-operator/base/monitoring/serviceaccount.yaml
Labels: lgtm, approved

#5469 update KubeSaw member-operator's ServiceMonitor
  components/sandbox/toolchain-member-operator/base/kustomization.yaml
  components/sandbox/toolchain-member-operator/base/monitoring/kustomization.yaml
  components/sandbox/toolchain-member-operator/base/monitoring/monitor.yaml
  components/sandbox/toolchain-member-operator/base/monitoring/prometheus-network-policy.yaml
  components/sandbox/toolchain-member-operator/base/monitoring/rbac.yaml
  components/sandbox/toolchain-member-operator/base/monitoring/serviceaccount.yaml
Labels: lgtm, approved

#5477 konflux-ci: Cachi2 repo change
  components/konflux-ci/base/repository.yaml
Labels: lgtm, approved

#5171 mintmaker: add staging to production promotion pipeline
  .tekton/mintmaker-prod-overlay-update.yaml
Labels: lgtm, approved

#5480 Promote mintmaker from staging to production
  components/mintmaker/production/base/kustomization.yaml
Labels: lgtm, approved

#5482 release new version of namespace-lister
  components/namespace-lister/base/deployment.yaml
  components/namespace-lister/base/kustomization.yaml
  components/namespace-lister/base/metrics/kustomization.yaml
  components/namespace-lister/base/metrics/monitor.yaml
  components/namespace-lister/base/metrics/network_policy.yaml
  components/namespace-lister/base/metrics/service.yaml
Labels: lgtm, approved

#5483 PVO11Y-4624 Increase COO resource limits
  components/monitoring/prometheus/base/observability-operator/observability-operator.yaml
Labels: lgtm, approved

#5481 Implementing cronJob permission changes
  components/konflux-rbac/production/base/konflux-admin-user-actions.yaml
  components/konflux-rbac/production/base/konflux-contributor-user-actions.yaml
  components/konflux-rbac/production/base/konflux-maintainer-user-actions.yaml
  components/konflux-rbac/staging/base/konflux-admin-user-actions.yaml
  components/konflux-rbac/staging/base/konflux-contributor-user-actions.yaml
  components/konflux-rbac/staging/base/konflux-maintainer-user-actions.yaml
  components/sandbox/tiers/production/appstudio/kustomization.yaml
  components/sandbox/tiers/production/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-admin-2267910203-2267910203.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-contributor-2153673317-2153673317.yaml
  components/sandbox/tiers/production/appstudio/tiertemplate-appstudio-maintainer-1446367252-1446367252.yaml
  components/sandbox/tiers/production/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/production/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-admin-2128555184-2267910203.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-contributor-2128555184-2153673317.yaml
  components/sandbox/tiers/production/appstudiolarge/tiertemplate-appstudiolarge-maintainer-2128555184-1446367252.yaml
  components/sandbox/tiers/production/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/production/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-admin-2094191734-2267910203.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-2094191734-2153673317.yaml
  components/sandbox/tiers/production/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-2094191734-1446367252.yaml
  components/sandbox/tiers/src/appstudio/spacerole_admin.yaml
  components/sandbox/tiers/src/appstudio/spacerole_contributor.yaml
  components/sandbox/tiers/src/appstudio/spacerole_maintainer.yaml
  components/sandbox/tiers/staging/appstudio/kustomization.yaml
  components/sandbox/tiers/staging/appstudio/nstemplatetier-appstudio.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-admin-2267910203-2267910203.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-contributor-2153673317-2153673317.yaml
  components/sandbox/tiers/staging/appstudio/tiertemplate-appstudio-maintainer-1446367252-1446367252.yaml
  components/sandbox/tiers/staging/appstudiolarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudiolarge/nstemplatetier-appstudiolarge.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-admin-2128555184-2267910203.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-contributor-2128555184-2153673317.yaml
  components/sandbox/tiers/staging/appstudiolarge/tiertemplate-appstudiolarge-maintainer-2128555184-1446367252.yaml
  components/sandbox/tiers/staging/appstudioxlarge/kustomization.yaml
  components/sandbox/tiers/staging/appstudioxlarge/nstemplatetier-appstudioxlarge.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-admin-2094191734-2267910203.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-contributor-2094191734-2153673317.yaml
  components/sandbox/tiers/staging/appstudioxlarge/tiertemplate-appstudioxlarge-maintainer-2094191734-1446367252.yaml
Labels: lgtm, approved

#5479 feat(stoneintg-1111): begin archiving snapshots with kubearchive
  components/integration/staging/stone-stage-rh01/kubearchive-config-patch.yaml
  components/integration/staging/stone-stage-rh01/kustomization.yaml
  components/kubearchive/base/kubearchive-config.yaml
  components/kubearchive/base/kustomization.yaml
  components/release/staging/kubearchive-config-patch.yaml
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#5497 [prod] switch pipelines and remote resolver controllers to statefulSets
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/kustomization.yaml
  components/pipeline-service/production/kflux-prd-rh02/resources/osp-perf-resolvers.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-m01/resources/osp-perf-resolvers.yaml
  components/pipeline-service/production/stone-prd-m01/resources/osp-perf-statefulSets.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/osp-perf-resolvers.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/resources/kustomization.yaml
  components/pipeline-service/production/stone-prod-p01/resources/osp-perf-resolvers.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#5499 Update Tekton Results to 0.13.3-2 staging
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5501 Update Tekton Results to 0.13.3-2 production
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#5500 Add read perms of kac resources
  components/kubearchive/base/kubearchive-maintainer.yaml
  components/kubearchive/base/rbac.yaml
Labels: lgtm, approved

#5506 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#5507 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#5512 Rename tektoncd-results downstream fork
  components/konflux-ci/base/repository.yaml
Labels: lgtm, approved

#5484 Fix MPC dev deployment & not use kube-rbac proxy
  components/multi-platform-controller/base/common/monitoring.yaml
  components/multi-platform-controller/base/kustomization.yaml
  components/multi-platform-controller/development/host-config.yaml
  components/multi-platform-controller/development/kustomization.yaml
  components/multi-platform-controller/development/logs-in-console-format-cmd-arg-patch.yaml
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
  components/multi-platform-controller/production-downstream/base/role-temp.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/role-temp.yaml
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/role-temp.yaml
  hack/preview.sh
Labels: lgtm, approved

#5519 KONFLUX-5876 Fix incorrect apiVersion
  components/monitoring/logging/staging/base/configure-clusterlogging.yaml
Labels: lgtm, approved

#5521 KONFLUX-5876 Correct the name of ClusterLogging
  components/monitoring/logging/staging/base/configure-clusterlogging.yaml
Labels: lgtm, approved

#5515 KubeArchive: increase operator memory limit
  components/kubearchive/base/kustomization.yaml
Labels: lgtm, approved

#5523 chore: konflux-admin can patch release status
  components/authentication/base/konflux-admins.yaml
Labels: lgtm, approved

#5525 Allow namespace admins to list and watch pods
  components/konflux-rbac/production/base/konflux-admin-user-actions.yaml
  components/konflux-rbac/staging/base/konflux-admin-user-actions.yaml
Labels: lgtm, approved

#5522 Add amd64 and arm64 options with larger disk on p02
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: lgtm, approved

#5520 Scale up Results API pods
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5529 namespace-lister: unify metrics and api service
  components/namespace-lister/base/metrics/kustomization.yaml
  components/namespace-lister/base/metrics/monitor.yaml
  components/namespace-lister/base/metrics/service.yaml
  components/namespace-lister/base/service.yaml
Labels: lgtm, approved

#5530 [OCP] New c4xlarge VM flavor with higher disk space
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5490 Update postgres dev version
  components/kubearchive/development/postgresql.yaml
Labels: lgtm, approved

#5533 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#5536 Scale up Results API pods prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#5531 Update prod with recent MPC changes
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
  components/multi-platform-controller/production-downstream/base/role-temp.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/kustomization.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/role-temp.yaml
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/role-temp.yaml
Labels: lgtm, approved

#5537 KONFLUX-5876 Apply tolerations to both stage and prod
  components/monitoring/logging/base/configure-logging/configure-logforwarder.yaml
  components/monitoring/logging/staging/base/kustomization.yaml
  components/monitoring/logging/staging/base/patches/configure-clusterlogging-collector.yaml
Labels: lgtm, approved

#5486 Add per-platform instance tags
  components/multi-platform-controller/staging-downstream/host-config.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#5538 fixup MPC image tag for internal prod
  components/multi-platform-controller/production-downstream/base/kustomization.yaml
Labels: lgtm, approved

#5544 Fix Results API service namespace
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5546 Use secrets from appsre[s/p]11ue1 cluster
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/stone-prd-m01/resources/tekton-results-s3-secret-path.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/production/stone-prd-rh01/resources/tekton-results-s3-secret-path.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/tekton-results-database-secret-path.yaml
  components/pipeline-service/staging/stone-stg-rh01/resources/tekton-results-s3-secret-path.yaml
Labels: lgtm, approved

#5550 mintmaker update
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5551 Add 200Gb IBM machines (requested by istio)
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: lgtm, approved

#5549 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#5554 Fix Results API service namespace prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#5528 Change base YAML file for debugging.
  components/kubearchive/base/kustomization.yaml
Labels: lgtm, approved

#5508 fix(RELEASE-1441): allow rsc in development
  components/monitoring/grafana/base/dashboards/release/kustomization.yaml
  components/release/development/kustomization.yaml
  components/release/development/release_service_config.yaml
  components/release/production/release_service_config.yaml
  components/release/staging/kustomization.yaml
  components/release/staging/release_service_config.yaml
Labels: lgtm, approved

#5555 Promote release-service from development to staging
  components/release/staging/kustomization.yaml
Labels: lgtm, approved

#5548 Increase memory requests/limits of smee-client
  components/smee-client/base/deployment.yaml
Labels: lgtm, approved

#5556 Add more debugging for KubeArchive.
  components/kubearchive/base/kustomization.yaml
Labels: lgtm, approved

#5496 bump namespace lister
  components/namespace-lister/base/kustomization.yaml
Labels: lgtm, approved

#5568 Revert memory settings for MPC on RH01 to default (10Gb)
  components/multi-platform-controller/production/stone-prd-rh01/kustomization.yaml
  components/multi-platform-controller/production/stone-prd-rh01/manager_resources_patch.yaml
Labels: lgtm, approved

#5465 add OWNERS for ui
  components/konflux-ui/OWNERS
  components/ui/OWNERS
Labels: lgtm, approved

#5561 use correct label selector for metrics
  components/namespace-lister/base/metrics/monitor.yaml
Labels: lgtm, approved

#5557 Over-provision ephemeral cluster control planes
  components/cluster-as-a-service/base/clustertemplates.yaml
  components/cluster-as-a-service/base/kustomization.yaml
  components/cluster-as-a-service/base/priorityclass.yaml
Labels: lgtm, approved

#5573 Temporarily decrease max instances for testing
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#5574 Remover operator memory limit.
  components/kubearchive/base/kustomization.yaml
Labels: lgtm, approved

#5572 Split Tekton Results API load
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5576 Revert decrease on external & decrease on internal
  components/multi-platform-controller/staging-downstream/host-config.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#5582 Fix split Results API service staging
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5580 Provide access for admins to manage SAs
  components/konflux-rbac/production/base/konflux-admin-user-actions.yaml
  components/konflux-rbac/staging/base/konflux-admin-user-actions.yaml
Labels: lgtm, approved

#5583 Fix Results API cert after service split
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5584 Revert max instances decrease on internal
  components/multi-platform-controller/staging-downstream/host-config.yaml
Labels: lgtm, approved

#5579 Remove patch for memory limit.
  components/kubearchive/base/kustomization.yaml
Labels: lgtm, approved

#5578 Remove finalizer workaround for cluster templates
  components/cluster-as-a-service/base/clustertemplates.yaml
Labels: lgtm, approved

#5586 Grant admin access to kubearchive team
  components/kubearchive/base/rbac.yaml
Labels: lgtm, approved

#5589 Split Tekton Results API service prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#5577 give konflux-core team ownership over konflux-ui
  components/konflux-ui/OWNERS
Labels: lgtm, approved

#5585 Add per-platform instance tags to production
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p01/host-config.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#5592 Fix Results API cert after service split - development
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
Labels: lgtm, approved

#5595 Read Results API service metrics from api-for-watcher
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5597 Refactor results api labels and service monitor
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, ok-to-test, approved

#5601 Promote integration-service from staging to production
  components/integration/production/base/kustomization.yaml
Labels: lgtm, approved

#5603 Pull Results API metrics from both Services
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#5605 [KONFLUX-5918] Declare resources grafana operator
  components/monitoring/grafana/staging/kustomization.yaml
Labels: lgtm, approved

#5607 deploy custom MintMaker image to stage
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5608 Fix typo in MintMaker stage deployment
  components/mintmaker/staging/base/kustomization.yaml
Labels: lgtm, approved

#5599 Add Cost management operator to staging environment - PVO11Y-4610
  argo-cd-apps/base/all-clusters/infra-deployments/cost-management/costmanagement-metrics-operator.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/cost-management/kustomization.yaml
  argo-cd-apps/base/all-clusters/infra-deployments/kustomization.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  components/cost-management/base/costmanagement-metrics-config.yaml
  components/cost-management/base/costmanagement-metrics-operator.yaml
  components/cost-management/base/kustomization.yaml
  components/cost-management/staging/cost-management-config-source-patch.yaml
  components/cost-management/staging/kustomization.yaml
Labels: lgtm, approved

#5606 [KONFLUX-5918] Deploy Grafana operator resource limits
  components/monitoring/grafana/base/grafana-operator.yaml
  components/monitoring/grafana/staging/kustomization.yaml
Labels: lgtm, approved

#5581 deploy namespace-lister to stone-stage-p01
  argo-cd-apps/base/member/infra-deployments/namespace-lister/namespace-lister.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  components/namespace-lister/staging/stone-stg-p01/kustomization.yaml
Labels: lgtm, approved

#5598 add namespace-lister grafana dashboard
  components/monitoring/grafana/base/dashboards/kustomization.yaml
  components/monitoring/grafana/base/dashboards/namespace-lister/dashboard.yaml
  components/monitoring/grafana/base/dashboards/namespace-lister/kustomization.yaml
  components/monitoring/grafana/base/dashboards/namespace-lister/namespace-lister-metrics.json
Labels: lgtm, approved

#5470 konflux-ui: deploy to internal staging
  argo-cd-apps/base/member/infra-deployments/konflux-ui/konflux-ui.yaml
  argo-cd-apps/overlays/staging-downstream/delete-applications.yaml
  components/konflux-ui/staging/stone-stg-p01/add-service-certs-patch.yaml
  components/konflux-ui/staging/stone-stg-p01/dex-config.yaml
  components/konflux-ui/staging/stone-stg-p01/kustomization.yaml
  components/konflux-ui/staging/stone-stg-p01/oauth2-proxy-args-patch.yaml
  components/konflux-ui/staging/stone-stg-p01/remove-run-as-user-proxy-patch.yaml
  components/konflux-ui/staging/stone-stg-p01/set-hostname.yaml
  components/konflux-ui/staging/stone-stg-p01/set-redirect-uri.yaml
  components/konflux-ui/staging/stone-stg-p01/set-replicas-patch.yaml
Labels: lgtm, approved

#5609 Update environment to staging
  argo-cd-apps/base/all-clusters/infra-deployments/cost-management/costmanagement-metrics-operator.yaml
  components/cost-management/staging/kustomization.yaml
Labels: lgtm, approved

#5613 KFLUXSPRT-1907: Adding New ARM Instance Type for Multi-Platform Build
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: lgtm, approved

#5617 Update cost-management source patches to stage clusters
  argo-cd-apps/base/all-clusters/infra-deployments/cost-management/costmanagement-metrics-operator.yaml
  components/cost-management/staging/kflux-stg-es01/cost-management-config-source-patch.yaml
  components/cost-management/staging/kflux-stg-es01/kustomization.yaml
  components/cost-management/staging/stone-stg-host/cost-management-config-source-patch.yaml
  components/cost-management/staging/stone-stg-host/kustomization.yaml
  components/cost-management/staging/stone-stg-p01/cost-management-config-source-patch.yaml
  components/cost-management/staging/stone-stg-p01/kustomization.yaml
  components/cost-management/staging/stone-stg-rh01/cost-management-config-source-patch.yaml
  components/cost-management/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#5610 Removing workspaces application set
  argo-cd-apps/base/host/kustomization.yaml
  argo-cd-apps/base/host/workspaces/kustomization.yaml
  argo-cd-apps/base/host/workspaces/workspaces.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/delete-applications.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
Labels: lgtm, approved

#5357 deploy namespace-lister to production rh02
  argo-cd-apps/base/member/infra-deployments/namespace-lister/namespace-lister.yaml
  argo-cd-apps/overlays/konflux-public-production/delete-applications.yaml
  components/namespace-lister/empty-base/kustomization.yaml
  components/namespace-lister/production/base/deployment.yaml
  components/namespace-lister/production/base/kustomization.yaml
  components/namespace-lister/production/base/metrics/kustomization.yaml
  components/namespace-lister/production/base/metrics/monitor.yaml
  components/namespace-lister/production/base/metrics/network_policy.yaml
  components/namespace-lister/production/base/metrics/rbac.yaml
  components/namespace-lister/production/base/metrics/service-account.yaml
  components/namespace-lister/production/base/namespace.yaml
  components/namespace-lister/production/base/network_policy.yaml
  components/namespace-lister/production/base/patches/with-header-auth-email.yaml
  components/namespace-lister/production/base/patches/with_cachenamespacelabelselector.yaml
  components/namespace-lister/production/base/patches/with_header_auth_user.yaml
  components/namespace-lister/production/base/rbac.yaml
  components/namespace-lister/production/base/service.yaml
  components/namespace-lister/production/kflux-prd-rh02/kustomization.yaml
Labels: lgtm, approved

#5596 Remote write hypershift metrics to RHOBS
  components/monitoring/prometheus/base/monitoringstack/monitoringstack.yaml
Labels: lgtm, approved

#5587 Temporarily disable sync of kubearchive application
  argo-cd-apps/overlays/konflux-public-staging/delete-sync-policy.yaml
  argo-cd-apps/overlays/konflux-public-staging/kustomization.yaml
Labels: lgtm, approved

#5527 kyverno's development overlay
  argo-cd-apps/base/member/infra-deployments/kyverno/kyverno.yaml
  argo-cd-apps/overlays/development/delete-applications.yaml
  argo-cd-apps/overlays/development/kustomization.yaml
  components/kyverno/development/.gitignore
  components/kyverno/development/job_resources.yaml
  components/kyverno/development/kustomization.yaml
  components/kyverno/development/kyverno-helm-generator.yaml
  components/kyverno/development/kyverno-helm-values.yaml
  components/kyverno/staging/.gitignore
  components/kyverno/staging/job_resources.yaml
  components/kyverno/staging/kustomization.yaml
  components/kyverno/staging/kyverno-helm-generator.yaml
  components/kyverno/staging/kyverno-helm-values.yaml
  components/kyverno/staging/kyverno-values.yaml
  hack/deploy-argocd.sh
Labels: lgtm, approved

#5612 Add cost-management operator to production clusters
  argo-cd-apps/base/all-clusters/infra-deployments/cost-management/costmanagement-metrics-operator.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
  components/cost-management/production/kflux-ocp-p01/cost-management-config-source-patch.yaml
  components/cost-management/production/kflux-ocp-p01/kustomization.yaml
  components/cost-management/production/kflux-prd-es01/cost-management-config-source-patch.yaml
  components/cost-management/production/kflux-prd-es01/kustomization.yaml
  components/cost-management/production/stone-prd-host1/cost-management-config-source-patch.yaml
  components/cost-management/production/stone-prd-host1/kustomization.yaml
  components/cost-management/production/stone-prd-rh01/cost-management-config-source-patch.yaml
  components/cost-management/production/stone-prd-rh01/kustomization.yaml
  components/cost-management/production/stone-prd-rh02/cost-management-config-source-patch.yaml
  components/cost-management/production/stone-prd-rh02/kustomization.yaml
  components/cost-management/production/stone-prod-p01/cost-management-config-source-patch.yaml
  components/cost-management/production/stone-prod-p01/kustomization.yaml
  components/cost-management/production/stone-prod-p02/cost-management-config-source-patch.yaml
  components/cost-management/production/stone-prod-p02/kustomization.yaml
  components/cost-management/staging/stone-stage-p01/cost-management-config-source-patch.yaml
  components/cost-management/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#5622 Update Tekton Results to v0.14.0-1 staging
  components/pipeline-service/development/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/staging/stone-stage-p01/deploy.yaml
  components/pipeline-service/staging/stone-stg-rh01/deploy.yaml
Labels: lgtm, approved

#5624 KONFLUX-6962: Adding a New ARM Build Instance for all the Overlays
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p01/host-config.yaml
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
  components/multi-platform-controller/production/kflux-prd-rh02/host-config.yaml
  components/multi-platform-controller/staging-downstream/host-config.yaml
  components/multi-platform-controller/staging/host-config.yaml
Labels: lgtm, approved

#5628 Update Tekton Results to v0.14.0-1 prod
  components/pipeline-service/production/base/main-pipeline-service-configuration.yaml
  components/pipeline-service/production/kflux-ocp-p01/deploy.yaml
  components/pipeline-service/production/kflux-prd-rh02/deploy.yaml
  components/pipeline-service/production/stone-prd-m01/deploy.yaml
  components/pipeline-service/production/stone-prd-rh01/deploy.yaml
  components/pipeline-service/production/stone-prod-p01/deploy.yaml
  components/pipeline-service/production/stone-prod-p02/deploy.yaml
Labels: lgtm, approved

#5630 [KFLUXSPRT-1933] d320 VM flavors
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5618 Fix namespace-lister & UI applications on stone-stage-p01
  argo-cd-apps/base/member/infra-deployments/konflux-ui/konflux-ui.yaml
  argo-cd-apps/base/member/infra-deployments/namespace-lister/namespace-lister.yaml
  components/konflux-ui/staging/stone-stage-p01/add-service-certs-patch.yaml
  components/konflux-ui/staging/stone-stage-p01/dex-config.yaml
  components/konflux-ui/staging/stone-stage-p01/kustomization.yaml
  components/konflux-ui/staging/stone-stage-p01/oauth2-proxy-args-patch.yaml
  components/konflux-ui/staging/stone-stage-p01/remove-run-as-user-proxy-patch.yaml
  components/konflux-ui/staging/stone-stage-p01/set-hostname.yaml
  components/konflux-ui/staging/stone-stage-p01/set-redirect-uri.yaml
  components/konflux-ui/staging/stone-stage-p01/set-replicas-patch.yaml
  components/namespace-lister/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#5620 add namespace-lister to stone-prod-p02
  argo-cd-apps/base/member/infra-deployments/namespace-lister/namespace-lister.yaml
  components/namespace-lister/production/stone-prod-p02/kustomization.yaml
Labels: lgtm, approved

#5635 ns-lister: apply prod overlay patch for prod deployments
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
Labels: lgtm, approved

#5637 KFLUXINFRA-1252: Moving prod-rh01-ppc to dynamic
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: approved

#5638 KFLUXINFRA-1252: Clearing up static nodes
  components/multi-platform-controller/production/stone-prd-rh01/host-config.yaml
Labels: approved

#5639 Promote hac-dev to prod
  components/ui/development/kustomization.yaml
  components/ui/production/kflux-ocp-p01/kustomization.yaml
  components/ui/production/stone-prod-p01/kustomization.yaml
  components/ui/production/stone-prod-p02/kustomization.yaml
  components/ui/staging/kustomization.yaml
Labels: lgtm, approved

#5640 deploy ns-lister to stone-prd-rh01
  argo-cd-apps/base/member/infra-deployments/namespace-lister/namespace-lister.yaml
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  components/namespace-lister/production/stone-prd-rh01/kustomization.yaml
Labels: lgtm, approved

#5643 [OCP] add missing instance-tags
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5646 deploy konflux-ui to stone-prd-rh01
  argo-cd-apps/base/member/infra-deployments/konflux-ui/konflux-ui.yaml
  components/konflux-ui/production/stone-prd-rh01/add-service-certs-patch.yaml
  components/konflux-ui/production/stone-prd-rh01/configure-oauth-proxy-secret.yaml
  components/konflux-ui/production/stone-prd-rh01/dex-config.yaml
  components/konflux-ui/production/stone-prd-rh01/kustomization.yaml
  components/konflux-ui/production/stone-prd-rh01/oauth2-proxy-args-patch.yaml
  components/konflux-ui/production/stone-prd-rh01/remove-run-as-user-proxy-patch.yaml
  components/konflux-ui/production/stone-prd-rh01/set-hostname.yaml
  components/konflux-ui/production/stone-prd-rh01/set-redirect-uri.yaml
  components/konflux-ui/production/stone-prd-rh01/set-replicas-patch.yaml
Labels: lgtm, approved

#5651 bump namespace-lister to latest version in staging
  components/namespace-lister/base/kustomization.yaml
Labels: lgtm, approved

#5636 adding workspace member application set to prod overlay
  argo-cd-apps/overlays/konflux-public-production/kustomization.yaml
  argo-cd-apps/overlays/production-downstream/kustomization.yaml
Labels: lgtm, approved

#5658 [OCP] update IBM tags
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5659 Add cost-management staging external secret
  components/cost-management/base/external-service-account-secret.yaml
  components/cost-management/staging/cost-mangement-external-secret-patch.yaml
  components/cost-management/staging/kflux-stg-es01/cost-management-config-source-patch.yaml
  components/cost-management/staging/kustomization.yaml
  components/cost-management/staging/stone-stage-p01/cost-management-config-source-patch.yaml
  components/cost-management/staging/stone-stg-host/cost-management-config-source-patch.yaml
  components/cost-management/staging/stone-stg-rh01/cost-management-config-source-patch.yaml
Labels: lgtm, approved

#5663 Add cost-management prod external secret
  components/cost-management/base/kustomization.yaml
  components/cost-management/production/cost-mangement-external-secret-patch.yaml
  components/cost-management/production/kflux-ocp-p01/cost-management-config-source-patch.yaml
  components/cost-management/production/kflux-prd-es01/cost-management-config-source-patch.yaml
  components/cost-management/production/kustomization.yaml
  components/cost-management/production/stone-prd-host1/cost-management-config-source-patch.yaml
  components/cost-management/production/stone-prd-rh01/cost-management-config-source-patch.yaml
  components/cost-management/production/stone-prd-rh02/cost-management-config-source-patch.yaml
  components/cost-management/production/stone-prod-p01/cost-management-config-source-patch.yaml
  components/cost-management/production/stone-prod-p02/cost-management-config-source-patch.yaml
Labels: lgtm, approved

#5667 KFLUXSPRT-1634: Optimized CPU and RAM for the ppc nodes in prod-p02
  components/multi-platform-controller/production-downstream/stone-prod-p02/host-config.yaml
Labels: lgtm, approved

#5666 PVO11Y-4655 - Update COO channel to stable
  components/monitoring/prometheus/base/observability-operator/observability-operator.yaml
Labels: lgtm, approved

#5661 deploy ns-lister to stone-prod-p01
  argo-cd-apps/base/member/infra-deployments/namespace-lister/namespace-lister.yaml
  components/namespace-lister/production/stone-prod-p01/kustomization.yaml
Labels: lgtm, approved

#5674 chore: update owners in release service
  components/release/OWNERS
Labels: lgtm, approved

#5664 Update to reflect secrets in stage and prod for cost-management
  components/cost-management/production/base/cost-mangement-external-secret-patch.yaml
  components/cost-management/production/base/kustomization.yaml
  components/cost-management/production/kflux-ocp-p01/kustomization.yaml
  components/cost-management/production/kflux-prd-es01/kustomization.yaml
  components/cost-management/production/stone-prd-host1/kustomization.yaml
  components/cost-management/production/stone-prd-rh01/kustomization.yaml
  components/cost-management/production/stone-prd-rh02/kustomization.yaml
  components/cost-management/production/stone-prod-p01/kustomization.yaml
  components/cost-management/production/stone-prod-p02/kustomization.yaml
  components/cost-management/staging/base/cost-mangement-external-secret-patch.yaml
  components/cost-management/staging/base/kustomization.yaml
  components/cost-management/staging/kflux-stg-es01/kustomization.yaml
  components/cost-management/staging/stone-stage-p01/kustomization.yaml
  components/cost-management/staging/stone-stg-host/kustomization.yaml
  components/cost-management/staging/stone-stg-rh01/kustomization.yaml
Labels: lgtm, approved

#5673 Deploy tenants RBAC to all the clusters
  argo-cd-apps/base/member/infra-deployments/konflux-rbac/konflux-rbac.yaml
  components/konflux-rbac/production/kflux-ocp-p01/kustomization.yaml
  components/konflux-rbac/production/stone-prd-rh01/kustomization.yaml
  components/konflux-rbac/production/stone-prod-p01/kustomization.yaml
  components/konflux-rbac/production/stone-prod-p02/kustomization.yaml
  components/konflux-rbac/staging/stone-stage-p01/kustomization.yaml
Labels: lgtm, approved

#5679 bump namespace lister to latest version in staging
  components/namespace-lister/base/kustomization.yaml
Labels: lgtm, approved

#5681 PVO11Y-4650 - Add costmanagement-metrics-operator ns to cluster-secret-store
  components/cluster-secret-store/base/appsre-stonesoup-vault-secret-store.yaml
Labels: lgtm, approved

#5683 Allow MPC sample multi-arch repo on staging
  components/repository-validator/staging/kustomization.yaml
Labels: lgtm, approved

#5682 Revert "[OCP] update IBM tags"
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5686 [OCP] linux-d250-largecpu variants
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5689 temporarily increase log verbosity for namespace-lister in staging
  components/namespace-lister/base/deployment.yaml
Labels: lgtm, approved

#5693 Revert "temporarily increase log verbosity for namespace-lister in staging (#5689)"
  components/namespace-lister/base/deployment.yaml
Labels: lgtm, approved

#5692 [ocp] increase default linux-large max-instances to 30
  components/multi-platform-controller/production-downstream/kflux-ocp-p01/host-config.yaml
Labels: lgtm, approved

#5695 bump namespace-lister in staging
  components/namespace-lister/base/kustomization.yaml
Labels: lgtm, approved

#5694 Add role and rolebindings to manage cost-management operator
  components/cost-management/base/kustomization.yaml
  components/cost-management/base/rbac/cost-management-admin.yaml
  components/cost-management/base/rbac/kustomization.yaml
Labels: lgtm, approved
